"""A part that fits is never handed on with its skirt or brim off the bed.

Measured 2026-09-30 on a prusa_mk4 (bed 250 x 210 x 220): a 200 x 245 x 215
part, turned to 245 x 200 to fit and centred with 2.5 mm each side, sliced
with PrusaSlicer's one-loop skirt at X -3.7 .. 253.7.  The part fits; the
check before a print refused the file anyway -- rightly, extrusion off the
plate is never sent (incident #0) -- and told the person to "rescale or
split" a part that fits.  A brim chosen for a warp-prone material lands
there too, 5-8 mm wide.

Pinned here, through the slice step every door shares, with a slicer that
draws what the profile it is handed asks for, the way PrusaSlicer does
(skirt and brim under one ``;TYPE:Skirt/Brim`` label): a skirt past the edge
is dropped and the part sliced once more; a brim Kiln asked for is never
narrowed or dropped -- the slice is refused with its width and the room
there is; anything still past the edge is refused with its own name; and the
check before a print keeps refusing such a file while naming what prints
past the edge instead of "rescale or split".  No CAD kernel, no slicer.
"""

from __future__ import annotations

import zipfile
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from kiln.printers import bed_fit
from kiln.slicer import SliceResult
from kiln.slicer_orca import ini_to_settings

trimesh = pytest.importorskip("trimesh")

_MK4 = "prusa_mk4"
#: The turned part's own toolpaths on the 250 x 210 bed, as PrusaSlicer printed them.
_PART = (2.7, 5.2, 247.3, 204.8)
#: PrusaSlicer's default skirt distance, plus the line it is drawn with.
_SKIRT_OUT = 6.38
_LINE = 0.45


def _loop(rect: tuple[float, float, float, float]) -> str:
    """One closed loop, with a point mid-way along each side as a slicer's
    has: a brim loop is told from a skirt by how near its points come to the
    part, and a loop of corners alone stands a diagonal off."""
    x0, y0, x1, y1 = (round(v, 3) for v in rect)
    xm, ym = round((x0 + x1) / 2, 3), round((y0 + y1) / 2, 3)
    corners = [(xm, y0), (x1, y0), (x1, ym), (x1, y1), (xm, y1), (x0, y1), (x0, ym), (x0, y0)]
    return f"G1 X{x0} Y{y0} F6000\n" + "".join(f"G1 X{x} Y{y} E0.1\n" for x, y in corners)


def _out(rect: tuple[float, float, float, float], by: float) -> tuple[float, float, float, float]:
    return (rect[0] - by, rect[1] - by, rect[2] + by, rect[3] + by)


def _gcode(
    path: Path,
    *,
    part: tuple[float, float, float, float] = _PART,
    skirts: int = 1,
    brim: float = 0.0,
    tower: tuple[float, float, float, float] | None = None,
    labelled: bool = True,
) -> str:
    """A first layer the way PrusaSlicer writes one: its brim loops hugging
    the part, its skirt the skirt distance past the brim, both under the one
    ``Skirt/Brim`` label."""
    label = (lambda name: f";TYPE:{name}\n") if labelled else (lambda _name: "")
    body = "; generated by PrusaSlicer 2.9.4\nG90\nM83\n" + label("Custom") + "G28\nG1 Z0.2 F600\n;LAYER_CHANGE\n;Z:0.2\n"
    if skirts or brim:
        body += label("Skirt/Brim") + ";WIDTH:0.42\n"
        loops = int(brim // _LINE)
        for k in range(1, loops + 1):
            body += _loop(_out(part, k * _LINE))
        if skirts:
            body += _loop(_out(part, loops * _LINE + _SKIRT_OUT))
    body += label("External perimeter") + _loop(part)
    if tower is not None:
        body += label("Wipe tower") + _loop(tower)
    path.write_text(body)
    return str(path)


class _Slicer:
    """Draws what the profile it is handed asks for: ``brim_width``, and a
    skirt unless ``skirts = 0``.  Every call is kept, profile and file."""

    def __init__(self, tmp_path: Path, **drawn) -> None:
        self.tmp_path = tmp_path
        self.drawn = drawn
        self.profiles: list[dict[str, str]] = []
        self.files: list[str] = []

    def __call__(self, path: str, *, profile: str | None = None, **_kw) -> SliceResult:
        asked = ini_to_settings(profile) if profile else {}
        self.profiles.append(asked)
        out = _gcode(
            self.tmp_path / f"slice{len(self.files) + 1}.gcode",
            skirts=int(float(asked.get("skirts", "1"))),
            brim=float(asked.get("brim_width", "0")),
            **self.drawn,
        )
        self.files.append(out)
        return SliceResult(success=True, output_path=out, slicer="PrusaSlicer", message=f"Sliced {Path(path).name}")


def _profile(tmp_path: Path, **settings: str) -> str:
    path = tmp_path / "profile.ini"
    path.write_text("layer_height = 0.2\n" + "".join(f"{k} = {v}\n" for k, v in settings.items()))
    return str(path)


def _part_stl(tmp_path: Path) -> str:
    """The turned part, on the MK4 bed where the slice gate leaves it."""
    size = (_PART[2] - _PART[0], _PART[3] - _PART[1], 215.0)
    box = trimesh.creation.box(extents=size)
    box.apply_translation([_PART[0] + size[0] / 2, _PART[1] + size[1] / 2, size[2] / 2])
    path = tmp_path / "part.stl"
    box.export(str(path))
    return str(path)


@pytest.fixture(autouse=True)
def _no_temperature_block(monkeypatch):
    monkeypatch.setattr("kiln.plugins.slicer_tools._material_temp_block", lambda *_a, **_k: None)


def _sliced(tmp_path: Path, slicer: _Slicer, profile: str | None, *, auto_center: bool | None = True):
    from kiln.plugins.slicer_tools import _placed_slice

    return _placed_slice(
        _part_stl(tmp_path), effective_printer_id=_MK4, printer_name=None, placement=None,
        profile_path=profile, auto_center=auto_center, slicer=slicer, plate_gate=False,
    )


class TestTheSharedSliceStep:
    def test_a_skirt_past_the_edge_is_dropped_and_the_file_prints_on_the_bed(self, tmp_path: Path) -> None:
        slicer = _Slicer(tmp_path)
        result, err, info = _sliced(tmp_path, slicer, _profile(tmp_path))
        assert err is None, err
        assert len(slicer.files) == 2, "one more slice, and only one"
        assert slicer.profiles[1].get("skirts") == "0"
        assert result.output_path == slicer.files[1]
        assert bed_fit.validate_gcode_for_printer(result.output_path, _MK4)["ok"]
        note = info["bed_fit"]["skirt_dropped"]
        assert "skirt would have printed 3.7 mm past the edge of the bed" in note and "without one" in note
        assert note in result.message
        assert "prints_past_bed" not in info["bed_fit"]

    def test_the_brim_kiln_asked_for_is_refused_never_narrowed(self, tmp_path: Path) -> None:
        slicer = _Slicer(tmp_path)
        result, err, _info = _sliced(tmp_path, slicer, _profile(tmp_path, brim_width="8", brim_type="outer_only"))
        assert result is None and err is not None
        assert err["error"]["code"] == "BRIM_PAST_BED"
        message = err["error"]["message"]
        assert "8 mm brim" in message and "2.7 mm from the nearest edge" in message
        assert "brim_width=2" in message, "the width that fits, asked for explicitly"
        assert "No spot on this 250 x 210 mm bed" in message, "no placement leaves 8 mm all round a 245 mm part"
        assert len(slicer.files) == 1, "Kiln does not re-slice a brim away"
        assert err["past_the_bed"]["brim_width_mm"] == 8.0 and err["past_the_bed"]["room_mm"] == 2.7

    def test_a_brim_that_fits_stays_and_only_the_skirt_goes(self, tmp_path: Path) -> None:
        """The width the refusal names is one that prints: 2 mm fits beside
        the part, and only its skirt (6 mm past the brim) left the bed."""
        slicer = _Slicer(tmp_path)
        result, err, info = _sliced(tmp_path, slicer, _profile(tmp_path, brim_width="2"))
        assert err is None, err
        assert len(slicer.files) == 2
        assert slicer.profiles[1].get("brim_width") == "2" and slicer.profiles[1].get("skirts") == "0"
        assert bed_fit.validate_gcode_for_printer(result.output_path, _MK4)["ok"]
        assert "kept the 2 mm brim" in info["bed_fit"]["skirt_dropped"]

    def test_a_brim_turned_off_by_its_type_is_not_a_brim(self, tmp_path: Path) -> None:
        """A profile saved from the slicer keeps its last width beside ``no_brim``."""
        slicer = _Slicer(tmp_path)
        _result, err, _info = _sliced(tmp_path, slicer, _profile(tmp_path, brim_width="8", brim_type="no_brim"))
        assert err is None or err["error"]["code"] != "BRIM_PAST_BED"

    def test_what_is_still_past_the_edge_without_the_skirt_is_refused_by_name(self, tmp_path: Path) -> None:
        slicer = _Slicer(tmp_path, tower=(230.0, 150.0, 262.0, 182.0))
        result, err, _info = _sliced(tmp_path, slicer, _profile(tmp_path))
        assert result is None and err["error"]["code"] == "PRINTS_PAST_BED"
        message = err["error"]["message"]
        assert message.startswith("Kiln sliced it again without a skirt and won't hand it on")
        assert "the prime tower" in message and "wipe_tower_x" in message
        assert "skirts=0" not in message, "the skirt is already gone"
        assert len(slicer.files) == 2, "one bounded retry"

    def test_with_no_skirt_to_drop_it_is_refused_without_another_slice(self, tmp_path: Path) -> None:
        slicer = _Slicer(tmp_path, tower=(230.0, 150.0, 262.0, 182.0))
        _result, err, _info = _sliced(tmp_path, slicer, _profile(tmp_path, skirts="0"))
        assert err["error"]["code"] == "PRINTS_PAST_BED" and "the prime tower" in err["error"]["message"]
        assert len(slicer.files) == 1

    def test_a_door_with_no_bed_fit_gate_gets_it_too(self, tmp_path: Path) -> None:
        """The CLI and the pipelines carry no bed-fit block; the slice's own
        message, which every door shows, says the skirt went."""
        slicer = _Slicer(tmp_path)
        result, err, info = _sliced(tmp_path, slicer, _profile(tmp_path), auto_center=None)
        assert err is None and info["bed_fit"] is None
        assert len(slicer.files) == 2
        assert "skirt would have printed 3.7 mm past the edge" in result.message

    def test_a_part_that_itself_prints_past_the_edge_is_not_put_on_its_skirt(self, tmp_path: Path) -> None:
        """No retry, no skirt sentence: the bed-fit block names the part."""
        slicer = _Slicer(tmp_path, part=(-4.0, 5.2, 240.6, 204.8))
        result, err, info = _sliced(tmp_path, slicer, _profile(tmp_path))
        assert err is None and len(slicer.files) == 1
        assert "The part itself prints" in info["bed_fit"]["prints_past_bed"]
        assert "skirts=0" not in info["bed_fit"]["prints_past_bed"]

    def test_an_unknown_bed_slices_once_and_says_nothing(self, tmp_path: Path) -> None:
        from kiln.plugins.slicer_tools import _placed_slice

        slicer = _Slicer(tmp_path)
        _result, err, info = _placed_slice(
            _part_stl(tmp_path), effective_printer_id=None, printer_name=None, placement=None,
            profile_path=_profile(tmp_path), slicer=slicer, plate_gate=False,
        )
        assert err is None and len(slicer.files) == 1


def _plate_3mf(gcode: str, path: Path) -> str:
    with zipfile.ZipFile(path, "w") as zf:
        zf.writestr("Metadata/plate_1.gcode", Path(gcode).read_text())
    return str(path)


class TestTheCheckBeforeAPrint:
    """Not loosened by a millimetre: the file is refused with the same code,
    and the words name what prints past the edge."""

    def test_a_skirt_past_the_edge_is_named_not_rescale_or_split(self, tmp_path: Path) -> None:
        verdict = bed_fit.validate_gcode_for_printer(_gcode(tmp_path / "job.gcode"), _MK4)
        assert verdict["ok"] is False and verdict["error_code"] == "EXCEEDS_BED"
        message = verdict["error_message"]
        assert "3.7 mm past the edge of the bed" in message and "the part itself fits" in message
        assert "the skirt" in message and "skirts=0" in message
        assert "rescale" not in message.lower() and "split" not in message
        assert verdict["part_fits_the_bed"] is True and verdict["printed_past_the_bed"] == ["skirt"]

    def test_a_brim_past_the_edge_names_the_brim(self, tmp_path: Path) -> None:
        verdict = bed_fit.validate_gcode_for_printer(_gcode(tmp_path / "job.gcode", skirts=0, brim=5.0), _MK4)
        assert verdict["ok"] is False and "the brim" in verdict["error_message"]
        assert "brim_width" in verdict["error_message"]

    def test_the_same_file_in_a_printers_3mf_reads_the_same(self, tmp_path: Path) -> None:
        archive = _plate_3mf(_gcode(tmp_path / "job.gcode"), tmp_path / "job.gcode.3mf")
        for verdict in (
            bed_fit.validate_3mf_for_printer(archive, _MK4),
            bed_fit.verify_3mf_is_safe_to_print(archive, _MK4),
        ):
            assert verdict["ok"] is False and verdict["error_code"] == "EXCEEDS_BED"
            assert "the skirt" in verdict["error_message"] and "rescale" not in verdict["error_message"].lower()

    def test_every_gate_before_a_print_still_blocks_it(self, tmp_path: Path) -> None:
        from kiln.printers.print_gate import _fit_verdict

        blocked, code, message, _detail = _fit_verdict(_gcode(tmp_path / "job.gcode"), _MK4)
        assert blocked is True and code == "EXCEEDS_BED" and "the skirt" in message

    def test_the_upload_door_does_not_tell_a_part_that_fits_to_recentre(self, tmp_path: Path, monkeypatch) -> None:
        import kiln.server as srv

        gcode = _gcode(tmp_path / "job.gcode")
        adapter = MagicMock()
        monkeypatch.setenv("KILN_HOME", str(tmp_path / "home"))
        monkeypatch.setattr(srv, "_check_auth", lambda *_a, **_k: None)
        monkeypatch.setattr(srv, "_check_rate_limit", lambda *_a, **_k: None)
        monkeypatch.setattr(srv, "_resolve_control_target", lambda *_a, **_k: (adapter, "mk4"))
        monkeypatch.setattr(srv, "_resolve_printer_model_live", lambda *_a, **_k: _MK4)
        monkeypatch.setattr(srv, "_PRINTER_MODEL", _MK4)
        with patch.object(srv, "_audit", MagicMock()):
            result = srv.upload_file(gcode)
        error = result["error"]
        assert result["success"] is False and error["code"] == "EXCEEDS_BED"
        assert "the skirt" in error["message"]
        assert "auto_center" not in error["message"] and "center_model_on_bed" not in error["message"]
        adapter.upload_file.assert_not_called()

    def test_a_part_too_big_for_the_bed_keeps_its_own_answer(self, tmp_path: Path) -> None:
        verdict = bed_fit.validate_gcode_for_printer(
            _gcode(tmp_path / "job.gcode", part=(0.5, 5.2, 260.0, 204.8), skirts=0), _MK4,
        )
        assert verdict["error_code"] == "EXCEEDS_BED" and "Rescale with rescale_model()" in verdict["error_message"]
        assert "part_fits_the_bed" not in verdict

    def test_a_file_with_no_labels_keeps_the_checks_own_words(self, tmp_path: Path) -> None:
        verdict = bed_fit.validate_gcode_for_printer(_gcode(tmp_path / "job.gcode", labelled=False), _MK4)
        assert verdict["error_code"] == "EXCEEDS_BED" and "part_fits_the_bed" not in verdict


class TestTheSliceTimeNote:
    """The remedy in the slice result follows the cause."""

    def _report(self, tmp_path: Path, gcode: str) -> dict:
        from kiln.plugins.slicer_tools import _report_the_sliced_footprint

        fit = {"ok": True, "error_code": None, "build_volume": (250.0, 210.0, 220.0), "bbox": {
            "x_min": 2.5, "x_max": 247.5, "y_min": 5.0, "y_max": 205.0, "z_min": 0.0, "z_max": 215.0}}
        _report_the_sliced_footprint({"bed_fit": fit}, gcode)
        return fit

    def test_a_tower_past_the_edge_is_not_told_to_drop_a_skirt(self, tmp_path: Path) -> None:
        fit = self._report(tmp_path, _gcode(tmp_path / "job.gcode", skirts=0, tower=(230.0, 150.0, 262.0, 182.0)))
        assert "the prime tower" in fit["prints_past_bed"] and "skirts=0" not in fit["prints_past_bed"]

    def test_a_file_with_no_labels_names_both_and_claims_neither(self, tmp_path: Path) -> None:
        fit = self._report(tmp_path, _gcode(tmp_path / "job.gcode", labelled=False))
        assert "labels none of its features" in fit["prints_past_bed"]


class TestTheRetryDoor:
    """A retry is where a diagnosis adds an 8 mm brim to a part that already
    failed; it slices through the same step, so that brim is refused before
    anything reaches the printer."""

    def test_a_diagnosed_brim_that_does_not_fit_is_refused_before_upload(self, tmp_path: Path, monkeypatch) -> None:
        from kiln.plugins.smart_print_tools import plugin

        tools: dict = {}

        class _Mcp:
            def tool(self, **_kwargs):
                def decorator(fn):
                    tools[fn.__name__] = fn
                    return fn

                return decorator

        plugin.register(_Mcp())
        monkeypatch.setenv("KILN_SKIP_PREVIEW_GATE", "1")
        monkeypatch.setenv("KILN_HOME", str(tmp_path / "home"))
        adapter = MagicMock(spec=["get_state", "upload_file", "start_print"])
        diagnosis = MagicMock()
        diagnosis.to_dict.return_value = {"failure_category": "adhesion", "slicer_overrides": {"brim_width": "8"}}
        slicer = _Slicer(tmp_path)
        with patch("kiln.server._check_auth", return_value=None), \
                patch("kiln.server._resolve_adapter", return_value=adapter), \
                patch("kiln.printability.diagnose_from_signals", return_value=diagnosis), \
                patch("kiln.printability.analyze_printability", side_effect=ValueError("not read here")), \
                patch("kiln.slicer.slice_file", side_effect=slicer):
            result = tools["retry_print_with_fix"](
                model_path=_part_stl(tmp_path), printer_id=_MK4, material="ABS", skip_validation=True,
            )
        assert result.get("success") is False, result
        assert result["error"]["code"] == "BRIM_PAST_BED" and "8 mm brim" in result["error"]["message"]
        adapter.upload_file.assert_not_called()
        adapter.start_print.assert_not_called()
