"""Tests for kiln.file_metadata — the filament figures a file's header carries."""

from __future__ import annotations

import pytest

from kiln.file_metadata import _extract_gcode_metadata_from_lines


class TestFilamentUsedFromHeader:
    def test_two_filaments_are_summed_in_mm(self):
        # OrcaSlicer lists one value per extruder; the plate uses the sum.
        meta = _extract_gcode_metadata_from_lines(
            ["; generated by OrcaSlicer 2.3.2", "; filament used [mm] = 11040.26, 584.30", "G28"]
        )
        assert meta.extra["filament_used"] == pytest.approx(11624.56)
        assert meta.extra["filament_used_unit"] == "mm"

    def test_cura_metres_become_mm(self):
        meta = _extract_gcode_metadata_from_lines([";Filament used: 4.523m"])
        assert meta.extra["filament_used"] == pytest.approx(4523.0)
        assert meta.extra["filament_used_unit"] == "mm"

    def test_grams_alone_are_kept_as_grams(self):
        meta = _extract_gcode_metadata_from_lines(["; total filament weight [g] : 3.66"])
        assert meta.extra["filament_used"] == pytest.approx(3.66)
        assert meta.extra["filament_used_unit"] == "g"

    def test_no_header_means_no_key(self):
        meta = _extract_gcode_metadata_from_lines(["G28", "G1 X10 Y10 E.5"])
        assert "filament_used" not in meta.extra


def _orca_shaped_file(moves: int = 5000) -> str:
    """An OrcaSlicer file's shape: a short header, the print, then the
    totals and the whole settings block at the end."""
    head = "; generated by OrcaSlicer 2.3.2 on 2026-09-23 at 16:58:36\n; total layer number: 225\n; HEADER_BLOCK_END\n"
    body = "".join(f"G1 X{i % 200}.5 Y{i % 150}.25 E.048\n" for i in range(moves))
    foot = (
        "; filament used [mm] = 11040.26, 584.30\n"
        "; filament used [g] = 32.93, 1.74\n"
        "; estimated printing time (normal mode) = 1h 50m 32s\n"
        "; CONFIG_BLOCK_START\n"
        + "".join(f"; some_setting_{i} = {i}\n" for i in range(150))
        + "; filament_type = PLA;PLA\n; layer_height = 0.2\n; nozzle_diameter = 0.4\n"
        "; printer_model = bambu_a1_h679b\n; CONFIG_BLOCK_END\n"
    )
    return head + body + foot


class TestTheWindowReachesTheEnd:
    """OrcaSlicer and PrusaSlicer write their totals and settings at the
    END of the file; a reader of the first 300 lines saw only the
    slicer's name on every one of their files."""

    def test_orca_totals_at_the_tail_are_read(self, tmp_path):
        from kiln.file_metadata import extract_metadata

        path = tmp_path / "jar.gcode"
        path.write_text(_orca_shaped_file())
        meta = extract_metadata(str(path))
        assert meta.extra["filament_used"] == pytest.approx(11624.56)
        assert meta.estimated_time_seconds == 1 * 3600 + 50 * 60 + 32
        # Two PLA filaments are one material, not one called "PLA;PLA".
        assert meta.material_hint == "PLA"
        assert meta.extra["printer_model"] == "bambu_a1_h679b"
        assert meta.extra["layer_height"] == pytest.approx(0.2)
        assert meta.slicer_hint.startswith("OrcaSlicer 2.3.2")

    def test_a_value_at_the_top_still_wins_over_the_same_key_at_the_end(self, tmp_path):
        from kiln.file_metadata import extract_metadata

        path = tmp_path / "both.gcode"
        path.write_text("; layer_height = 0.16\n" + _orca_shaped_file())
        assert extract_metadata(str(path)).extra["layer_height"] == pytest.approx(0.16)


def _cura_shaped_file(moves: int = 5000) -> str:
    """Cura's shape, the slicer that writes UFP: everything read at the top."""
    head = (
        ";FLAVOR:Marlin\n;TIME:6632\n;Filament used: 4.523m\n;Layer height: 0.2\n"
        ";Generated with Cura_SteamEngine 5.7.0\n;LAYER_COUNT:150\n;LAYER:0\n"
    )
    return head + "".join(f"G1 X{i % 200} Y{i % 150} E.05\n" for i in range(moves))


class TestPackagesAreReadOnlyAtTheTop:
    """A UFP's G-code is a zipped member: reaching its end means unpacking
    all of it, so only its top is read, bounded in bytes."""

    def _ufp(self, tmp_path, text: str):
        import zipfile

        path = tmp_path / "part.ufp"
        with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            zf.writestr("3D/model.gcode", text)
        return str(path)

    def test_curas_header_is_read(self, tmp_path):
        from kiln.file_metadata import extract_metadata

        meta = extract_metadata(self._ufp(tmp_path, _cura_shaped_file()))
        assert meta.file_type == "ufp"
        assert meta.extra["filament_used"] == pytest.approx(4523.0)
        assert meta.estimated_time_seconds == 6632
        assert meta.layer_count == 150
        assert meta.slicer_hint.startswith("Cura_SteamEngine 5.7.0")

    def test_a_member_is_never_unpacked_past_the_budget(self, tmp_path, monkeypatch):
        import zipfile

        from kiln.file_metadata import extract_metadata
        from kiln.gcode_metadata import _HEADER_BYTES

        # 3 MB on one line, then 2.6 MB of moves: a few KB zipped.  Reading
        # its end means unpacking all of it, and so does walking its lines.
        text = (
            ";Generated with Cura_SteamEngine 5.7.0\n;TIME:6632\n"
            + ";" + "x" * 3_000_000 + "\n" + "G1 X1 Y1 E.1\n" * 200_000 + "; filament used [mm] = 999\n"
        )
        path = self._ufp(tmp_path, text)
        reached: list[int] = []
        real_open = zipfile.ZipFile.open

        def watched_open(zf, name, *args, **kwargs):
            return _Watched(real_open(zf, name, *args, **kwargs), reached)

        monkeypatch.setattr(zipfile.ZipFile, "open", watched_open)
        meta = extract_metadata(path)
        assert meta.slicer_hint.startswith("Cura_SteamEngine")
        assert meta.estimated_time_seconds == 6632
        assert "filament_used" not in meta.extra
        assert reached and max(reached) <= _HEADER_BYTES + 1


def _project_file(tmp_path, members: dict[str, str], *, application: str = "BambuStudio-01.10.02.67") -> str:
    """A slicer's saved project: the model, then *members* in the order
    given, which is the order the archive lists them in."""
    import zipfile

    model = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">\n'
        f' <metadata name="Application">{application}</metadata>\n'
        " <resources/>\n <build/>\n</model>\n"
    )
    path = tmp_path / "part.3mf"
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("3D/3dmodel.model", model)
        for name, text in members.items():
            zf.writestr(name, text)
    return str(path)


def _json_settings(**changed) -> str:
    """Bambu Studio's and OrcaSlicer's project settings: one JSON object,
    every value a string or a list of strings, one entry per extruder or
    filament in the lists."""
    import json

    settings = {
        "accel_to_decel_enable": "0",
        "filament_colour": ["#DDE5ED", "#000000"],
        "filament_settings_id": ["Bambu PLA Basic @BBL A1", "Bambu PLA Basic @BBL A1"],
        "filament_type": ["PLA", "PLA"],
        "from": "project",
        "initial_layer_print_height": "0.28",
        "layer_height": "0.2",
        "name": "project_settings",
        "nozzle_diameter": ["0.4"],
        "printable_area": ["0x0", "256x0", "256x256", "0x256"],
        "printable_height": "256",
        "printer_model": "Bambu Lab A1",
        "printer_settings_id": "Bambu Lab A1 0.4 nozzle",
        "version": "01.10.02.67",
    }
    settings.update(changed)
    return json.dumps(dict(sorted(settings.items())), indent=4)


#: What Bambu Studio writes beside the settings: XML, under the same suffix.
_SLICE_INFO_XML = (
    '<?xml version="1.0" encoding="UTF-8"?>\n<config>\n  <plate>\n'
    '    <metadata key="printer_model_id" value="N2S"/>\n'
    '    <metadata key="nozzle_diameters" value="0.4"/>\n  </plate>\n</config>\n'
)


def _commented_settings(*, filament_type: str = "PLA", nozzle_diameter: str = "0.4", printer_model: str = "MK4S") -> str:
    """PrusaSlicer's project settings: its name, a blank line, then every
    setting as ``; key = value`` in key order — a few hundred of them, so
    the printer's name sits past the two-hundredth line."""
    before = "".join(f"; a_setting_{i:03d} = {i}\n" for i in range(150))
    between = "".join(f"; m_setting_{i:03d} = {i}\n" for i in range(70))
    return (
        "; generated by PrusaSlicer 2.9.4 on 2026-09-30 at 21:31:58 UTC\n\n"
        + before
        + "; bed_shape = 0x0,250x0,250x210,0x210\n"
        + f"; filament_type = {filament_type}\n"
        + "; first_layer_height = 0.25\n"
        + "; layer_height = 0.3\n"
        + between
        + f"; nozzle_diameter = {nozzle_diameter}\n"
        + f"; printer_model = {printer_model}\n"
        + "; printer_technology = FFF\n"
    )


class TestAProjectFileIsReadInTheFormatItsSlicerWrote:
    """A saved project carries the printer, nozzle, layer height and
    material it was set up for.  Bambu Studio and OrcaSlicer write them as
    JSON, PrusaSlicer as commented lines; a reader of bare ``key = value``
    lines returned the slicer's name and nothing else for all three."""

    def test_json_settings_give_the_printer_nozzle_layer_and_material(self, tmp_path):
        from kiln.file_metadata import extract_metadata

        path = _project_file(tmp_path, {"Metadata/project_settings.config": _json_settings()})
        meta = extract_metadata(path)
        assert meta.file_type == "3mf"
        assert meta.extra["printer_model"] == "Bambu Lab A1"
        assert meta.extra["nozzle_diameter"] == pytest.approx(0.4)
        # The layer height, not the first layer's, which names it too.
        assert meta.extra["layer_height"] == pytest.approx(0.2)
        # Two PLA filaments are one material.
        assert meta.material_hint == "PLA"

    def test_json_filaments_of_two_kinds_are_both_named(self, tmp_path):
        from kiln.file_metadata import extract_metadata

        settings = _json_settings(filament_type=["PLA", "PETG", "PLA"])
        meta = extract_metadata(_project_file(tmp_path, {"Metadata/project_settings.config": settings}))
        assert meta.material_hint == "PLA + PETG"

    def test_a_blank_printer_name_is_not_reported_as_one(self, tmp_path):
        # A project saved with no printer preset chosen names its printer "".
        from kiln.file_metadata import extract_metadata

        settings = _json_settings(printer_model="")
        meta = extract_metadata(_project_file(tmp_path, {"Metadata/project_settings.config": settings}))
        assert "printer_model" not in meta.extra
        assert meta.extra["nozzle_diameter"] == pytest.approx(0.4)

    def test_the_project_outranks_one_objects_overrides_wherever_the_archive_lists_them(self, tmp_path):
        # Bambu Studio saves a changed preset beside the project's settings;
        # it holds one object's layer height, not the project's.
        from kiln.file_metadata import extract_metadata

        path = _project_file(
            tmp_path,
            {
                "Metadata/process_settings_1.config": '{\n    "from": "project",\n    "layer_height": "0.12"\n}',
                "Metadata/slice_info.config": _SLICE_INFO_XML,
                "Metadata/project_settings.config": _json_settings(),
            },
        )
        assert extract_metadata(path).extra["layer_height"] == pytest.approx(0.2)

    def test_commented_settings_are_read_to_their_last_line(self, tmp_path):
        from kiln.file_metadata import extract_metadata

        text = _commented_settings()
        assert text.splitlines().index("; printer_model = MK4S") > 200
        meta = extract_metadata(
            _project_file(tmp_path, {"Metadata/Slic3r_PE.config": text}, application="PrusaSlicer-2.9.4")
        )
        assert meta.extra["printer_model"] == "MK4S"
        assert meta.extra["nozzle_diameter"] == pytest.approx(0.4)
        assert meta.extra["layer_height"] == pytest.approx(0.3)
        assert meta.material_hint == "PLA"

    def test_commented_settings_for_five_extruders_give_one_nozzle_and_each_material_once(self, tmp_path):
        from kiln.file_metadata import extract_metadata

        text = _commented_settings(
            filament_type="PLA;PLA;PETG;PLA;PLA", nozzle_diameter="0.4,0.4,0.4,0.4,0.4", printer_model="XL5"
        )
        meta = extract_metadata(_project_file(tmp_path, {"Metadata/Slic3r_PE.config": text}))
        assert meta.extra["nozzle_diameter"] == pytest.approx(0.4)
        assert meta.material_hint == "PLA + PETG"
        assert meta.extra["printer_model"] == "XL5"

    def test_bare_key_value_settings_are_still_read(self, tmp_path):
        from kiln.file_metadata import extract_metadata

        text = "# a profile\nlayer_height = 0.16\nnozzle_diameter = 0.6\nprinter_model = ender3\nfilament_type = PETG\n"
        meta = extract_metadata(_project_file(tmp_path, {"Metadata/Slic3r_PE.config": text}))
        assert meta.extra == {"layer_height": pytest.approx(0.16), "nozzle_diameter": pytest.approx(0.6), "printer_model": "ender3"}
        assert meta.material_hint == "PETG"

    def test_settings_that_do_not_parse_cost_nothing_else(self, tmp_path):
        from kiln.file_metadata import extract_metadata

        cut_short = _json_settings()[:120]
        meta = extract_metadata(_project_file(tmp_path, {"Metadata/project_settings.config": cut_short}))
        assert meta.file_type == "3mf"
        assert meta.slicer_hint == "BambuStudio-01.10.02.67"
        assert meta.extra == {}

    def test_a_settings_member_past_the_budget_is_left_unread(self, tmp_path, monkeypatch):
        import kiln.file_metadata as file_metadata

        monkeypatch.setattr(file_metadata, "_SETTINGS_MEMBER_BYTES", 1024, raising=False)
        text = "layer_height = 0.16\n" + "; padding = x\n" * 400
        meta = file_metadata.extract_metadata(_project_file(tmp_path, {"Metadata/Slic3r_PE.config": text}))
        assert meta.file_type == "3mf"
        assert meta.slicer_hint == "BambuStudio-01.10.02.67"
        assert "layer_height" not in meta.extra

    def test_the_tool_reports_what_the_project_was_set_up_for(self, tmp_path):
        from kiln.server import extract_file_metadata

        result = extract_file_metadata(_project_file(tmp_path, {"Metadata/project_settings.config": _json_settings()}))
        assert result["success"] is True
        metadata = result["metadata"]
        assert metadata["material_hint"] == "PLA"
        assert metadata["extra"] == {
            "layer_height": pytest.approx(0.2),
            "nozzle_diameter": pytest.approx(0.4),
            "printer_model": "Bambu Lab A1",
        }


class _Watched:
    """A package member that records how far into it anything has read,
    however it reads: whole reads, lines, iteration or a seek."""

    def __init__(self, fh, reached: list[int]):
        self._fh = fh
        self._reached = reached

    def _note(self, result):
        self._reached.append(self._fh.tell())
        return result

    def read(self, n=-1):
        return self._note(self._fh.read(n))

    def readline(self, limit=-1):
        return self._note(self._fh.readline(limit))

    def seek(self, *args):
        return self._note(self._fh.seek(*args))

    def tell(self):
        return self._fh.tell()

    def __iter__(self):
        return self

    def __next__(self):
        line = self.readline()
        if not line:
            raise StopIteration
        return line

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self._fh.close()

