"""Where the clumping probe taps, for everyone, with no paid package installed.

A Bambu that probes for a nozzle blob drives the toolhead to one corner of
the bed and taps there.  A part parked in that corner stops the detection
from working, and printing in spiral vase or by-object skips the probe
altogether.  Both facts are published by the printer's maker, like a build
volume, so they live in Kiln's public printer catalogue and the warning
works offline on any install -- the curated research behind them stays in
Kiln Pro (https://kiln3d.com).

Measured 2026-09-15: the warning existed only inside the paid package, so
the people it was written for never saw it.
"""

from __future__ import annotations

from unittest import mock
from unittest.mock import MagicMock, patch

import pytest

from kiln.nozzle_clumping_detection import (
    file_facts,
    part_overlaps_probe_area,
    preflight_entry_for_file,
    probe_facts_for,
)
from kiln.printers.base import NozzleClumpingDetection, PrinterStatus

A1_AREA = {"x_min": 226.0, "y_min": 224.0, "x_max": 256.0, "y_max": 256.0}


def _on() -> NozzleClumpingDetection:
    return NozzleClumpingDetection(
        enabled=True, source="bambu_mqtt_home_flag", supported=True, mode="on",
    )


class TestTheCatalogueCarriesTheFact:
    def test_the_a1_and_the_a1_mini_state_their_probe_corner(self) -> None:
        assert probe_facts_for("bambu_a1")["detection_area_mm"] == A1_AREA
        assert probe_facts_for("bambu_a1_mini")["detection_area_mm"] == {
            "x_min": 156.0, "y_min": 152.0, "x_max": 180.0, "y_max": 180.0,
        }

    def test_both_name_the_modes_that_skip_the_probe(self) -> None:
        for model in ("bambu_a1", "bambu_a1_mini"):
            assert probe_facts_for(model)["defeated_by"] == ["spiral vase", "print by object"]

    def test_a_model_nobody_measured_states_nothing(self) -> None:
        assert probe_facts_for("bambu_x1c") is None
        assert probe_facts_for("ender3") is None
        assert probe_facts_for("") is None


class TestTheOverlapIsOneHelper:
    @pytest.mark.parametrize(
        "footprint, overlaps",
        [
            ({"x_min": 230, "y_min": 230, "x_max": 250, "y_max": 250}, True),
            ({"x_min": 20, "y_min": 20, "x_max": 120, "y_max": 120}, False),
            ({"x_min": 200, "y_min": 200, "x_max": 226, "y_max": 224}, True),
            ({"x_min": 100, "y_min": 100, "x_max": 225.9, "y_max": 223.9}, False),
        ],
        ids=["inside", "clear", "touching-the-corner", "just-short"],
    )
    def test_it_answers_the_geometry(self, footprint: dict, overlaps: bool) -> None:
        assert part_overlaps_probe_area(footprint, A1_AREA) is overlaps

    def test_a_footprint_it_cannot_read_is_not_an_overlap(self) -> None:
        assert part_overlaps_probe_area({"x_min": "left"}, A1_AREA) is False
        assert part_overlaps_probe_area(None, A1_AREA) is False
        assert part_overlaps_probe_area({"x_min": 1, "y_min": 1, "x_max": 2, "y_max": 2}, None) is False


def _gcode(tmp_path, x: float, y: float, spiral: bool = False, tower: bool = False):
    lines = [
        "; generated by PrusaSlicer 2.9.4",
        ";LAYER_CHANGE",
        ";TYPE:Perimeter",
        f"G1 X{x} Y{y} E1",
        f"G1 X{x + 20} Y{y} E1",
        f"G1 X{x + 20} Y{y + 20} E1",
    ]
    if tower:
        lines += [";TYPE:Wipe tower", "G1 X10 Y10 E1"]
    lines += [
        "; prusaslicer_config = begin",
        f"; spiral_vase = {1 if spiral else 0}",
        "; complete_objects = 0",
        f"; wipe_tower = {1 if tower else 0}",
        "; prusaslicer_config = end",
    ]
    path = tmp_path / f"part_{int(x)}_{int(y)}{'_spiral' if spiral else ''}.gcode"
    path.write_text("\n".join(lines) + "\n")
    return str(path)


class TestThePreFlightWarnsWithoutTheePaidPackage:
    def test_a_part_in_the_corner_is_named(self, tmp_path) -> None:
        facts = file_facts(_gcode(tmp_path, 230, 230, tower=True))
        entry = preflight_entry_for_file(_on(), facts, printer_model="bambu_a1")
        assert any("where the probe taps" in w for w in entry["warnings"])
        assert "226" in " ".join(entry["warnings"])

    def test_a_part_clear_of_it_is_not(self, tmp_path) -> None:
        facts = file_facts(_gcode(tmp_path, 30, 30, tower=True))
        entry = preflight_entry_for_file(_on(), facts, printer_model="bambu_a1")
        assert not any("probe taps" in w for w in entry["warnings"])

    def test_a_mode_that_skips_the_probe_is_named(self, tmp_path) -> None:
        facts = file_facts(_gcode(tmp_path, 30, 30, spiral=True, tower=True))
        entry = preflight_entry_for_file(_on(), facts, printer_model="bambu_a1")
        assert any("spiral vase" in w and "will not run" in w for w in entry["warnings"])

    def test_a_model_without_the_fact_warns_about_neither(self, tmp_path) -> None:
        facts = file_facts(_gcode(tmp_path, 230, 230, spiral=True, tower=True))
        entry = preflight_entry_for_file(_on(), facts, printer_model="bambu_x1c")
        assert entry["warnings"] == []

    def test_a_switch_that_is_off_warns_about_neither(self, tmp_path) -> None:
        off = NozzleClumpingDetection(
            enabled=False, source="bambu_mqtt_home_flag", supported=True, mode="off",
        )
        facts = file_facts(_gcode(tmp_path, 230, 230))
        entry = preflight_entry_for_file(off, facts, printer_model="bambu_a1")
        assert entry["warnings"] == []


def _pf_state():
    state = MagicMock()
    state.connected = True
    state.state = PrinterStatus.IDLE
    state.tool_temp_actual = 25.0
    state.tool_temp_target = 0.0
    state.bed_temp_actual = 25.0
    state.bed_temp_target = 0.0
    return state


class TestTheWholePreFlightDoorWithNoPaidPackage:
    @patch("kiln.server._get_adapter")
    @patch("kiln.server._get_temp_limits", return_value=(280.0, 120.0))
    @patch("kiln.server.get_db")
    @patch("kiln.server._registry")
    def test_the_corner_warning_reaches_a_free_install(
        self, mock_registry, mock_get_db, mock_limits, mock_adapter, tmp_path, monkeypatch,
    ) -> None:
        mock_adapter.return_value.get_state.return_value = _pf_state()
        mock_adapter.return_value.read_nozzle_clumping_detection.return_value = _on()
        mock_registry.count = 1
        mock_registry.list_names.return_value = ["default"]
        monkeypatch.setattr("kiln.server._PRINTER_MODEL", "bambu_a1", raising=False)
        # No kiln-pro on this machine: the curated judgement is unavailable.
        monkeypatch.setattr(
            "kiln._pro_nozzle_bridge.consult_clumping_detection", lambda **kw: None,
        )
        from kiln.server import preflight_check

        result = preflight_check(file_path=_gcode(tmp_path, 230, 230, tower=True))
        check = next(c for c in result["checks"] if c["name"] == "nozzle_clumping_detection")
        assert any("where the probe taps" in w for w in check["warnings"])
        assert "where the probe taps" in check["message"]
        assert result["ready"] is True
