"""The quiet start: a print started beside a part still on the plate.

THE GAP
-------
A part could be sliced beside what the plate still held, checked by the
placement verdict, and then not started: every start door refused onto an
occupied plate, because the file it would start carries the vendor's own
start -- a Z home on the plate, a bed probe, a purge line across it.  The
placed slice could only be printed from the printer's screen.

WHAT THIS PINS
--------------
* the plate record holds MORE than one part, and a fingerprint of them;
* the file's contract (Kiln's quiet-start header) and the start gate that
  lets a file planned for THIS plate through to the live judge, and
  refuses one planned for a plate that has changed;
* the prologue's order -- an absolute lift first, the X/Y home at that
  height, the travel over the new footprint, the waits, the descent;
* the wrap: the contract header, the prologue in place of the vendor's
  start, every colour change and the end block lifted to the floor, and
  the builder refusing its own output if a vendor motion slipped in;
* the live judge, condition by condition, against a machine that answers;
* the adapter template forcing a quiet file's switches off, refusing when
  its gate cannot run, and recording the part beside the others;
* every slicing door handing the plan to the wrap, and every start door
  naming the file to the gate.
"""

from __future__ import annotations

import ast
import os
import re
import sys
import zipfile
from pathlib import Path
from typing import Any
from unittest.mock import patch

import pytest

from kiln.plate_state import (
    PLATE_CHANGED_CODE,
    START_NOT_YET_CODE,
    PlateJob,
    PlateState,
    fingerprint,
    mark_clear,
    mark_occupied,
    mark_occupied_by_start,
    quiet_start_contract_for,
    quiet_start_flags,
    read,
    start_refusal,
)
from kiln.printers import print_gate as pg
from kiln.printers.bambu_3mf import (
    KILN_QUIET_START_MARKER,
    BambuPrintSettings,
    _check_quiet_plan,
    _quiet_start_header,
    _raise_absolute_z_to_floor,
    _resolve_end_gcode,
    _wrap_tool_changes,
    build_bambu_3mf,
)
from kiln.printers.base import PrinterAdapter, PrinterState, PrinterStatus, PrintResult, is_resume_mode_3mf
from kiln.printers.print_gate import (
    QUIET_START_HEADER_END,
    QUIET_START_HEADER_START,
    evaluate_quiet_start,
    read_quiet_start_contract,
    same_bed_machine_id,
)
from kiln.printers.safe_motion import build_quiet_start_preamble

from .test_plate_placement_doors import _Bridge, _cube, _fake_slice, _machine, _slicer_tools, _verdict

SRC = Path(__file__).resolve().parent.parent / "src" / "kiln"
JAR = PlateJob(file="jar_v2.gcode.3mf", footprint_mm=[90, 90, 160, 160], max_z_mm=42.0, printer_id="bambu_a1")
COASTER = PlateJob(file="coaster.gcode.3mf", footprint_mm=[180, 20, 220, 60], max_z_mm=6.0, printer_id="bambu_a1")


@pytest.fixture(autouse=True)
def _isolated(tmp_path, monkeypatch):
    monkeypatch.setenv("KILN_HOME", str(tmp_path / "kiln-home"))
    for name in list(sys.modules):
        if name == "kiln_pro" or name.startswith("kiln_pro."):
            monkeypatch.delitem(sys.modules, name, raising=False)
    monkeypatch.setitem(sys.modules, "kiln_pro", None)
    import kiln.server as srv
    from kiln import monitor_twin

    d = tmp_path / "twin"
    d.mkdir()
    monkeypatch.setattr(monitor_twin, "_TWIN_DIR", d)
    monkeypatch.setattr(monitor_twin, "_SLICES_FILE", d / "slices.json")
    monkeypatch.setattr(monitor_twin, "_ACTIVE_FILE", d / "active.json")
    monkeypatch.setattr(srv, "_check_auth", lambda *_a, **_k: None)
    monkeypatch.setattr(srv, "_pro_api_call", lambda tool, **kw: {"status": "error", "error": "no network in tests"})
    monkeypatch.setattr("kiln.printers.bed_fit.get_build_volume", lambda pid: (256.0, 256.0, 256.0))


def _body(x0: float = 200.0, y0: float = 20.0, size: float = 30.0, layers: int = 3, *, change_at: int | None = None) -> str:
    out = "; generated by PrusaSlicer 2.9.4\nM190 S65\nM104 S220\nG21\nG90\nM83\n"
    for i in range(layers):
        z = round(0.2 * (i + 1), 2)
        out += f";LAYER_CHANGE\n;Z:{z}\nG1 Z{z + 0.2:.2f} F24000\nG1 X{x0} Y{y0}\nG1 Z{z}\n;TYPE:Skirt/Brim\n"
        out += f"G1 X{x0 + size} Y{y0} E1\nG1 X{x0 + size} Y{y0 + size} E1\nG1 X{x0} Y{y0 + size} E1\n"
        if change_at is not None and i == change_at:
            out += "T1\n"
        out += f"G1 X{x0} Y{y0} E1\n"
    return out + "; filament used [g] = 4.26\n"


def _plan(machine: Any, **over: Any) -> dict[str, Any]:
    plan = {
        "mode": "quiet_start", "ok": True, "available": True, "refusals": [],
        "clear_z_mm": 47.0, "lift_floor_mm": 47.0, "travel_to_mm": [215.0, 35.0], "first_layer_z_mm": 0.2,
        "approach_mm": 5.0, "z_travel_mm": 256.0, "home_xy_gcode": "G28 X Y", "purge_at_mm": [-48.2, None],
        "flags": {"bed_leveling": False, "flow_cali": False, "vibration_cali": False, "timelapse": False, "layer_inspect": False},
        "switched_off": {"clog_probe": "nozzle_clog_detect=False"},
        "planned_for_machine": same_bed_machine_id(machine),
        "plate_fingerprint": fingerprint(read(machine)),
    }
    plan.update(over)
    return plan


def _quiet_file(tmp_path: Path, machine: Any, *, body: str | None = None, name: str = "part.gcode", **over: Any) -> str:
    """A quiet-start 3MF built by the real wrap, for this machine's plate as it stands."""
    out = str(tmp_path / f"{Path(name).stem}_quiet.gcode.3mf")
    build_bambu_3mf(body or _body(), out, settings=BambuPrintSettings(), quiet_start=_plan(machine, **over), printer_model="bambu_a1")
    return out


def _gcode_of(path: str) -> str:
    with zipfile.ZipFile(path) as zf:
        return zf.read("Metadata/plate_1.gcode").decode("utf-8")


# ---------------------------------------------------------------------------
# The record holds more than one part
# ---------------------------------------------------------------------------


class TestThePlateHoldsMoreThanOnePart:
    def test_a_quiet_start_joins_the_part_to_what_was_there(self):
        m = _machine()
        mark_occupied(m, JAR)
        mark_occupied(m, COASTER, keep_previous=True)
        state = read(m)
        assert [j.file for j in state.jobs] == ["jar_v2.gcode.3mf", "coaster.gcode.3mf"]
        assert state.job == COASTER, "the last part is the job every reader knew"
        assert state.tallest_mm == 42.0
        assert [o["name"] for o in state.occupancy([256, 256])["occupied"]] == ["jar v2", "coaster"], "as a person says them"

    def test_an_ordinary_start_replaces_what_was_there(self):
        m = _machine()
        mark_occupied(m, JAR)
        mark_occupied(m, JAR, keep_previous=True)
        mark_occupied(m, COASTER)
        assert [j.file for j in read(m).jobs] == ["coaster.gcode.3mf"]

    def test_a_print_seen_ending_keeps_every_part(self):
        m = _machine()
        mark_occupied(m, JAR)
        mark_occupied(m, COASTER, keep_previous=True)
        mark_occupied(m, None, source="print_ended")
        assert len(read(m).jobs) == 2

    def test_the_sentence_names_them_all_and_the_tallest(self, monkeypatch):
        m = _machine()
        mark_occupied(m, JAR)
        mark_occupied(m, COASTER, keep_previous=True)
        monkeypatch.setattr(PlateState, "since_clock", lambda self: "18:12")
        assert read(m).holds_sentence() == (
            "The last prints, jar v2 and coaster, are still on the plate (since 18:12, the tallest about 42 mm)."
        )

    def test_the_old_record_shape_still_reads(self):
        state = PlateState.from_dict("m", {"status": "occupied", "source": "kiln_started_print", "since": None, "job": JAR.to_dict()})
        assert state.jobs == (JAR,) and state.job == JAR
        assert PlateState.from_dict("m", {"status": "clear", "source": "human", "since": None, "job": None}).jobs == ()

    def test_the_fingerprint_is_the_parts_not_the_moment(self):
        m = _machine()
        mark_occupied(m, JAR)
        first = fingerprint(read(m))
        assert re.fullmatch(r"[0-9a-f]{16}", first)
        mark_occupied(m, None, source="print_ended")
        assert fingerprint(read(m)) == first, "a print seen ending re-stamps the moment, not the parts"
        mark_occupied(m, COASTER, keep_previous=True)
        assert fingerprint(read(m)) != first
        mark_occupied(m, PlateJob(file="jar_v2.gcode.3mf", footprint_mm=[90, 90, 160, 160], max_z_mm=60.0))
        assert fingerprint(read(m)) != first, "a taller jar is another plate"
        assert read(m).to_dict()["fingerprint"] == fingerprint(read(m))

    def test_beside_from_the_start_door(self, tmp_path):
        m = _machine()
        mark_occupied(m, JAR)
        gcode = tmp_path / "part.gcode"
        gcode.write_text(_body())
        mark_occupied_by_start(m, str(gcode), beside=True)
        assert len(read(m).jobs) == 2 and read(m).job.file == "part.gcode"


# ---------------------------------------------------------------------------
# The contract, and the start gate that reads it
# ---------------------------------------------------------------------------


class TestTheContractAndTheStartGate:
    def test_the_header_is_read_back_from_a_3mf_and_from_gcode(self, tmp_path):
        m = _machine()
        mark_occupied(m, JAR)
        path = _quiet_file(tmp_path, m)
        contract = read_quiet_start_contract(path)
        assert contract is not None
        assert contract["motion_contract"] == "absolute_z_first" and contract["quiet_start_policy_version"] == "1"
        assert contract["planned_for_plate"] == fingerprint(read(m))
        assert contract["planned_for_machine"] == same_bed_machine_id(m)
        assert contract["clear_z_mm"] == "47.00" and contract["lift_floor_mm"] == "47.00"
        assert contract["switched_off"] == "bed_leveling,flow_cali,vibration_cali,timelapse,layer_inspect,nozzle_clog_detect"
        raw = tmp_path / "raw.gcode"
        raw.write_text(_quiet_start_header(_plan(m)) + _body())
        assert read_quiet_start_contract(str(raw)) == contract
        plain = tmp_path / "plain.gcode"
        plain.write_text(_body())
        assert read_quiet_start_contract(str(plain)) is None

    def test_quiet_start_flags_are_every_switch_off(self, tmp_path):
        m = _machine()
        mark_occupied(m, JAR)
        contract = read_quiet_start_contract(_quiet_file(tmp_path, m))
        assert quiet_start_flags(contract) == {
            "bed_leveling": False, "flow_cali": False, "vibration_cali": False, "timelapse": False,
            "layer_inspect": False, "nozzle_clog_detect": False,
        }

    def test_a_file_planned_for_this_plate_passes_the_gate_to_the_live_judge(self, tmp_path):
        m = _machine()
        mark_occupied(m, JAR)
        path = _quiet_file(tmp_path, m)
        assert start_refusal(m, local_path=path) is None
        assert start_refusal(m, file_name=path) is None, "a bare path is read as itself"
        assert start_refusal(m)["error"]["code"] == START_NOT_YET_CODE, "an ordinary start still refuses"

    def test_the_printer_side_name_is_joined_through_the_slice_ledger(self, tmp_path):
        from kiln.monitor_twin import note_sliced, note_wrapped

        m = _machine()
        mark_occupied(m, JAR)
        path = _quiet_file(tmp_path, m)
        note_sliced(str(tmp_path / "part.stl"), str(tmp_path / "part.gcode"))
        note_wrapped(str(tmp_path / "part.gcode"), path)
        assert start_refusal(m, file_name=os.path.basename(path)) is None
        assert quiet_start_contract_for(os.path.basename(path)) is not None
        assert quiet_start_contract_for("never_sliced.gcode.3mf") is None

    def test_a_file_planned_for_a_plate_that_changed_refuses_and_says_so(self, tmp_path, monkeypatch):
        m = _machine()
        mark_occupied(m, JAR)
        path = _quiet_file(tmp_path, m)
        mark_occupied(m, COASTER, keep_previous=True)
        monkeypatch.setattr(PlateState, "since_clock", lambda self: "18:12")
        block = start_refusal(m, local_path=path)
        assert block["error"]["code"] == PLATE_CHANGED_CODE and block["error"]["retryable"] is False
        assert block["error"]["message"] == (
            "The last prints, jar v2 and coaster, are still on the plate (since 18:12, the tallest about 42 mm). "
            "This file was planned for a different plate than the one Kiln has on record now, so it won't start it. "
            "Slice it again beside what is there, or clear the plate and say so."
        )
        assert block["occupancy"]["occupied"][1]["name"] == "coaster"

    def test_a_file_planned_for_another_machine_refuses(self, tmp_path):
        m = _machine()
        mark_occupied(m, JAR)
        path = _quiet_file(tmp_path, m, planned_for_machine="bambu:serial:SOMEONE_ELSE")
        assert start_refusal(m, local_path=path)["error"]["code"] == PLATE_CHANGED_CODE

    def test_a_clear_plate_passes_any_file_and_a_resume_still_passes(self, tmp_path):
        m = _machine()
        mark_clear(m, "human")
        assert start_refusal(m, local_path=str(tmp_path / "nothing.3mf")) is None
        mark_occupied(m, JAR)
        assert start_refusal(m, resume=True) is None

    def test_the_quiet_name_is_never_read_as_a_resume(self):
        assert not is_resume_mode_3mf("part_quiet.gcode.3mf")
        assert not pg._is_resume_print("part_quiet.gcode.3mf", {})


# ---------------------------------------------------------------------------
# The prologue
# ---------------------------------------------------------------------------


class TestThePreamble:
    def test_the_order_is_the_safety(self):
        lines = [line.split(";", 1)[0].strip() for line in build_quiet_start_preamble(
            hotend_temp=220, bed_temp=65, clear_z_mm=47.0, travel_to_mm=(215.0, 35.0), first_layer_z_mm=0.2,
        )]
        codes = [line for line in lines if line]
        assert codes == [
            "M140 S65", "M104 S220", "G21", "G90", "M83",
            "G1 Z47.00 F600", "G28 X Y", "G1 X215.00 Y35.00 F6000",
            "M190 S65", "M109 S220",
            "G1 Z5.20 F600",
            "G92 E0", "G1 E5 F60", "G92 E0", "G4 P500",
        ]
        assert codes.index("G90") < codes.index("G1 Z47.00 F600") < codes.index("G28 X Y") < codes.index("G1 X215.00 Y35.00 F6000")
        assert codes.index("M190 S65") > codes.index("G1 X215.00 Y35.00 F6000"), "the waits happen over the new footprint"
        assert not any(c.startswith(("G28 Z", "G29", "G380", "G91")) for c in codes)

    def test_with_a_chute_on_record_the_heat_and_the_prime_happen_off_the_plate(self):
        lines = [line.split(";", 1)[0].strip() for line in build_quiet_start_preamble(
            hotend_temp=220, bed_temp=65, clear_z_mm=47.0, travel_to_mm=(215.0, 35.0), first_layer_z_mm=0.2,
            purge_at_mm=(-48.2, None),
        )]
        codes = [line for line in lines if line]
        assert codes == [
            "M140 S65", "M104 S220", "G21", "G90", "M83",
            "G1 Z47.00 F600", "G28 X Y",
            "G1 X-48.20 F6000",
            "M190 S65", "M109 S220",
            "G92 E0", "G1 E5 F60", "G92 E0", "G4 P500",
            "G1 X215.00 Y35.00 F6000",
            "G1 Z5.20 F600",
        ], "home, then the chute at the clear height, the waits and the prime there, then over the part, then down"
        both = build_quiet_start_preamble(
            hotend_temp=220, bed_temp=65, clear_z_mm=47.0, travel_to_mm=(215.0, 35.0), first_layer_z_mm=0.2,
            purge_at_mm=(60.0, 265.0),
        )
        assert any(line.startswith("G1 X60.00 Y265.00 F6000") for line in both), "a chute behind the plate names both axes"
        assert build_quiet_start_preamble(
            hotend_temp=220, bed_temp=65, clear_z_mm=47.0, travel_to_mm=(215.0, 35.0), first_layer_z_mm=0.2,
            purge_at_mm=(None, None),
        ) == build_quiet_start_preamble(
            hotend_temp=220, bed_temp=65, clear_z_mm=47.0, travel_to_mm=(215.0, 35.0), first_layer_z_mm=0.2,
        ), "a chute with no axis is no chute"

    def test_a_printer_spells_its_own_home_and_the_prime_carries_its_sentinel(self):
        lines = build_quiet_start_preamble(
            hotend_temp=200, bed_temp=60, clear_z_mm=12.5, travel_to_mm=(10.0, 10.0), first_layer_z_mm=0.3,
            approach_mm=3.0, home_xy_gcode="G28 X0 Y0", prime_mm=4.0,
        )
        assert any(line.startswith("G28 X0 Y0") for line in lines)
        assert any(line.startswith("G1 Z3.30 ") for line in lines)
        assert "; --- Extruder prime on quiet start ---" in lines
        assert any(line.startswith("G1 E4 F60") for line in lines)


# ---------------------------------------------------------------------------
# The wrap
# ---------------------------------------------------------------------------


class TestTheWrap:
    def test_the_file_opens_with_the_contract_and_the_absolute_lift_and_nothing_of_the_vendors(self, tmp_path):
        m = _machine()
        mark_occupied(m, JAR)
        path = _quiet_file(tmp_path, m)
        assert path.endswith("_quiet.gcode.3mf")
        gcode = _gcode_of(path)
        lines = gcode.split("\n")
        head = lines.index(QUIET_START_HEADER_START)
        end = lines.index(QUIET_START_HEADER_END)
        assert 0 < head < end
        motions = [line for line in lines[end:] if re.match(r"^G[01]\b.*[XYZ]-?\d", line.split(";", 1)[0])]
        assert motions[0].startswith("G1 Z47.00 F600"), "the first motion is the absolute lift"
        assert motions[1].startswith("G1 X-48.20 F6000"), "then the chute, before anything heats over the plate"
        assert lines.index("M109 S220  ; wait for the hotend") < lines.index("G1 X215.00 Y35.00 F6000  ; over the new part's own footprint, still clear")
        assert "M620 M" not in gcode and "G29" not in gcode and "G380" not in gcode and "M73 P0 R" not in gcode.split(";LAYER_CHANGE")[0]
        homes = [line for line in lines if line.split(";", 1)[0].strip().startswith("G28")]
        assert homes and all(line.split(";", 1)[0].strip() == "G28 X Y" for line in homes)
        with zipfile.ZipFile(path) as zf:
            names = zf.namelist()
        assert KILN_QUIET_START_MARKER in names and "Metadata/plate_1.gcode" in names

    def test_a_colour_change_lifts_to_the_floor_goes_to_the_cutter_and_comes_back_before_it_descends(self, tmp_path):
        m = _machine()
        mark_occupied(m, JAR)
        body = _body(layers=4, change_at=1)
        path = str(tmp_path / "two_quiet.gcode.3mf")
        build_bambu_3mf(
            body, path, settings=BambuPrintSettings(num_filaments=2, filament_colors=["#FFFFFF", "#FF0000"]),
            quiet_start=_plan(m), printer_model="bambu_a1",
        )
        lines = [line.split(";", 1)[0].strip() for line in _gcode_of(path).split("\n")]
        i = lines.index("M620 S1A")
        assert lines[i - 1] == "G1 Z47.00 F600", "lifted to the floor before the block"
        j = lines.index("M621 S1A")
        assert lines[j + 1] == "G1 X200.000 Y50.000 F6000", "back over the part at the floor"
        assert lines[j + 2] == "G1 Z0.40 F600", "then down to the layer it left"
        assert "G1 X-48.20 F3000" in lines[i:j], "the A1's own chute, spelled by the one shared helper"

    def test_the_end_block_never_dips_below_the_floor(self, tmp_path):
        m = _machine()
        mark_occupied(m, JAR)
        gcode = _gcode_of(_quiet_file(tmp_path, m))
        end = gcode.split("; filament used [g]")[1]
        zs = [float(mm.group(1)) for mm in re.finditer(r"^\s*G1 Z(\d+\.?\d*)", end, re.MULTILINE)]
        assert zs and min(zs) >= 47.0, zs
        assert any(line.strip().startswith("G1 X0 Y128") for line in end.split("\n")), "the vendor's path is kept"
        assert "G1 X-48 Y180 F3600" in end, "and its park"

    def test_a_floor_without_the_plan_writes_no_file_and_says_to_clear_the_plate(self, tmp_path):
        """A floor means a part is on the plate.  Without the plan, a file
        with the vendor's start would home Z onto that part from the
        printer's own screen -- so Kiln writes nothing and says what to do.
        It names no tier: the wrap cannot tell a plan the caller's tier
        withheld from one no tier would give (a printer Kiln has not seen
        start quietly, a lift its travel cannot reach), and the verdict's
        own start sentence on the same response says which."""
        from kiln.plate_state import PRINT_AROUND_SENTENCE

        out = str(tmp_path / "floor.gcode.3mf")
        with pytest.raises(ValueError) as caught:
            build_bambu_3mf(
                _body(layers=4, change_at=1), out,
                settings=BambuPrintSettings(num_filaments=2, filament_colors=["#FFFFFF", "#FF0000"]),
                lift_floor_mm=30.0, printer_model="bambu_a1",
            )
        assert str(caught.value) == PRINT_AROUND_SENTENCE == (
            "Kiln won't write a printer file while the plate still holds the last print: clear the plate and say so "
            "to print again."
        )
        assert not os.path.exists(out)
        from kiln.plugins.slicer_tools import _auto_wrap_bambu_3mf

        gcode = tmp_path / "part.gcode"
        gcode.write_text(_body())
        threemf, warning = _auto_wrap_bambu_3mf(str(gcode), "bambu_a1", None, lift_floor_mm=30.0)
        assert threemf is None and PRINT_AROUND_SENTENCE in str(warning)
        assert not list(tmp_path.glob("*.3mf"))

    def test_raising_absolute_z_leaves_relative_stretches_and_xy_lines_alone(self):
        text = "G90\nG1 Z5.5 F900\nG1 X0 Y128 F18000\nG91\nG1 Z2 F600\nG90\nG1 Z165 F600\nG1 Z163\nG1 X-48 Y180 F3600\nG0 Z1 ; comment\n"
        out = _raise_absolute_z_to_floor(text, 47.0).split("\n")
        assert out[1] == "G1 Z47.00 F900" and out[2] == "G1 X0 Y128 F18000"
        assert out[4] == "G1 Z2 F600", "a relative Z is a distance"
        assert out[6] == "G1 Z165 F600" and out[7] == "G1 Z163"
        assert out[9] == "G0 Z47.00 ; comment"

    def test_the_end_template_keeps_its_first_lift_rule_and_adds_the_floor(self):
        template = "G1 Z65.5 F900 ; lower z a little\nG1 X0 Y128 F18000\n    G1 Z165 F600\n    G1 Z163\nG1 X-48 Y180 F3600\n"
        plain = _resolve_end_gcode(template, max_z=10.0, printer_model="bambu_a1")
        assert plain.startswith("G1 Z15.0 F900")
        floored = _resolve_end_gcode(template, max_z=10.0, printer_model="bambu_a1", lift_floor_mm=200.0)
        assert floored.split("\n")[0] == "G1 Z200.00 F900 ; lower z a little"
        assert "    G1 Z200.00 F600" in floored and "    G1 Z200.00" in floored

    def test_the_tool_change_wrapper_tracks_the_layer_it_left(self):
        body = ";LAYER_CHANGE\n;Z:0.6\nG1 Z0.8 F24000\nG1 X10 Y20\nG1 Z0.6\nG1 X30 Y20 E1\nT1\nG1 X10 Y20 E1\n"
        out = _wrap_tool_changes(body, printer_model="bambu_a1", hotend_temp=220, filament_type="PLA", lift_floor_mm=2.0).split("\n")
        i = out.index("M620 S1A   ; AMS switch to filament 1")
        assert out[i - 1].startswith("G1 Z3.60 F600"), "never less than the vendor's own 3 mm above the layer"
        j = next(k for k, line in enumerate(out) if line.startswith("M621 S1A"))
        assert out[j + 1].startswith("G1 X30.000 Y20.000 F6000") and out[j + 2].startswith("G1 Z0.60 F600")
        assert not any("Kiln:" in line for line in _wrap_tool_changes(body, printer_model="bambu_a1", hotend_temp=220, filament_type="PLA").split("\n"))

    def test_a_plan_missing_a_number_or_contradicting_itself_is_refused_before_a_line_is_written(self, tmp_path):
        m = _machine()
        mark_occupied(m, JAR)
        out = str(tmp_path / "bad.gcode.3mf")
        with pytest.raises(ValueError, match="missing clear_z_mm"):
            build_bambu_3mf(_body(), out, quiet_start={k: v for k, v in _plan(m).items() if k != "clear_z_mm"}, printer_model="bambu_a1")
        with pytest.raises(ValueError, match="cannot be above lift_floor_mm"):
            build_bambu_3mf(_body(), out, quiet_start=_plan(m, clear_z_mm=60.0, lift_floor_mm=47.0), printer_model="bambu_a1")
        with pytest.raises(ValueError, match="two different prologues"):
            build_bambu_3mf(_body(), out, quiet_start=_plan(m), resume_mode=True, printer_model="bambu_a1")
        with pytest.raises(ValueError, match="travel_to_mm"):
            _check_quiet_plan(_plan(m, travel_to_mm=[1.0]))
        assert not os.path.exists(out)

    def test_the_builder_refuses_its_own_output_when_a_vendor_motion_slips_in(self, tmp_path, monkeypatch):
        import kiln.printers.bambu_3mf as b3

        m = _machine()
        mark_occupied(m, JAR)
        real = b3.build_quiet_start_preamble if hasattr(b3, "build_quiet_start_preamble") else None
        assert real is None, "the preamble is imported inside the build, so it cannot be swapped at module level by accident"
        monkeypatch.setattr(
            "kiln.printers.safe_motion.build_quiet_start_preamble",
            lambda **kw: ["G90", "G28", "G1 Z47.00 F600"],
        )
        with pytest.raises(ValueError, match="homing line other than"):
            build_bambu_3mf(_body(), str(tmp_path / "x.3mf"), quiet_start=_plan(m), printer_model="bambu_a1")
        monkeypatch.setattr(
            "kiln.printers.safe_motion.build_quiet_start_preamble",
            lambda **kw: ["G90", "G1 X10 Y10 F6000", "G1 Z47.00 F600"],
        )
        with pytest.raises(ValueError, match="first motion is"):
            build_bambu_3mf(_body(), str(tmp_path / "y.3mf"), quiet_start=_plan(m), printer_model="bambu_a1")

    def test_the_upload_step_never_falls_back_to_a_raw_file_with_a_plan(self, tmp_path):
        from kiln.printers.upload_prep import prepare_upload_for_adapter

        gcode = tmp_path / "part.gcode"
        gcode.write_text(_body())
        captured: dict[str, Any] = {}

        class _Wraps:
            name = "bambu"

            def wrap_gcode_as_3mf(self, path, **kw):
                captured.update(kw)
                raise RuntimeError("thumbnail renderer down")

        with pytest.raises(RuntimeError, match="thumbnail renderer down"):
            prepare_upload_for_adapter(_Wraps(), str(gcode), quiet_start={"x": 1}, lift_floor_mm=47.0)
        assert captured["quiet_start"] == {"x": 1} and captured["lift_floor_mm"] == 47.0
        assert prepare_upload_for_adapter(_Wraps(), str(gcode)) == (str(gcode), False), "an ordinary wrap still falls back"

        class _Raw:
            name = "octoprint"

        with pytest.raises(ValueError, match="starts raw G-code"):
            prepare_upload_for_adapter(_Raw(), str(gcode), quiet_start={"x": 1})


# ---------------------------------------------------------------------------
# The live judge
# ---------------------------------------------------------------------------


class _QuietAdapter(PrinterAdapter):
    """Registry-shaped, with a serial (the plate record's key): answers the
    judge's questions from attributes a test sets and records every start."""

    printer_id = "bambu_a1"
    serial = "01P00A000000001"

    def __init__(self) -> None:
        self._kiln_registered_name = "bench-a1"
        self._printer_model = "bambu_a1"
        self.homed: set[str] | None = {"x", "y", "z"}
        self.state = PrinterStatus.IDLE
        self.impl_calls: list[tuple[str, dict[str, Any]]] = []

    @property
    def name(self) -> str:
        return "bambu"

    def get_state(self) -> PrinterState:
        return PrinterState(connected=True, state=self.state)

    def homed_axes_now(self) -> set[str] | None:
        return None if self.homed is None else set(self.homed)

    def homed_axes_field(self) -> str | None:
        return "print.home_flag[bits 0-2]"

    def _start_print_impl(self, file_name: str, **kwargs: Any) -> PrintResult:
        self.impl_calls.append((file_name, dict(kwargs)))
        return PrintResult(success=True, message="IMPL")


_QuietAdapter.__abstractmethods__ = frozenset()


class _Unlatched:
    def __init__(self) -> None:
        self.status: dict[str, Any] = {"latched": False, "critical_interlocks_pending": []}

    def get_latch_status(self, printer_id: str) -> dict[str, Any]:
        return dict(self.status)


@pytest.fixture
def latch(monkeypatch):
    coord = _Unlatched()
    monkeypatch.setattr("kiln.emergency.get_emergency_coordinator", lambda: coord)
    return coord


QUIET_KWARGS = {
    "bed_leveling": False, "flow_cali": False, "vibration_cali": False, "timelapse": False,
    "layer_inspect": False, "nozzle_clog_detect": False,
}


class TestTheLiveJudge:
    def _planned(self, tmp_path, adapter) -> str:
        mark_occupied(adapter, JAR)
        return _quiet_file(tmp_path, adapter)

    def test_a_file_planned_for_this_plate_on_a_homed_idle_machine_is_accepted(self, tmp_path, latch):
        adapter = _QuietAdapter()
        path = self._planned(tmp_path, adapter)
        verdict = evaluate_quiet_start(adapter, path, QUIET_KWARGS)
        assert verdict["accepted"] and not verdict["blocked"] and verdict["code"] == "QUIET_START_ACCEPTED"
        assert verdict["homed_evidence"]["axes"] == ["x", "y", "z"] and verdict["kind"] == "quiet_start"
        assert "x,y,z homed and idle" in verdict["reason"]

    @pytest.mark.parametrize(("break_it", "code", "condition"), [
        (lambda a, p: None, "QUIET_START_WRONG_MACHINE", "machine"),
        (lambda a, p: mark_occupied(a, COASTER, keep_previous=True), "QUIET_START_PLATE_CHANGED", "plate"),
        (lambda a, p: mark_clear(a, "human"), "QUIET_START_PLATE_NOT_OCCUPIED", "plate"),
        (lambda a, p: setattr(a, "state", PrinterStatus.PRINTING), "QUIET_START_PRINTER_BUSY", "printer_state"),
        (lambda a, p: setattr(a, "state", PrinterStatus.PAUSED), "QUIET_START_PRINTER_BUSY", "printer_state"),
        (lambda a, p: setattr(a, "homed", None), "QUIET_START_HOMED_UNKNOWN", "homed_axes"),
        (lambda a, p: setattr(a, "homed", {"x", "y"}), "QUIET_START_NOT_HOMED", "homed_axes"),
    ])
    def test_each_condition_refuses_with_its_own_code(self, tmp_path, latch, break_it, code, condition):
        adapter = _QuietAdapter()
        if code == "QUIET_START_WRONG_MACHINE":
            mark_occupied(adapter, JAR)
            path = _quiet_file(tmp_path, adapter, planned_for_machine="bambu:serial:SOMEONE_ELSE")
        else:
            path = self._planned(tmp_path, adapter)
        break_it(adapter, path)
        verdict = evaluate_quiet_start(adapter, path, QUIET_KWARGS)
        assert verdict["blocked"] and verdict["code"] == code and verdict["condition"] == condition, verdict["reason"]
        assert verdict["reason"]

    def test_the_latch_and_a_switch_left_on_refuse(self, tmp_path, latch):
        adapter = _QuietAdapter()
        path = self._planned(tmp_path, adapter)
        latch.status = {"latched": True, "critical_interlocks_pending": ["door"]}
        verdict = evaluate_quiet_start(adapter, path, QUIET_KWARGS)
        assert verdict["code"] == "QUIET_START_EMERGENCY_LATCHED" and "door" in verdict["reason"]
        latch.status = {"latched": False, "critical_interlocks_pending": []}
        left_on = evaluate_quiet_start(adapter, path, {**QUIET_KWARGS, "bed_leveling": True})
        assert left_on["code"] == "QUIET_START_SWITCH_ON" and "bed_leveling" in left_on["reason"]
        unsaid = evaluate_quiet_start(adapter, path, {})
        assert unsaid["code"] == "QUIET_START_SWITCH_ON", "an absent flag is judged as the adapter would send it"
        assert "bed_leveling" in unsaid["reason"] and "nozzle_clog_detect" in unsaid["reason"]

    def test_a_torn_or_foreign_contract_is_named(self, tmp_path, latch):
        adapter = _QuietAdapter()
        mark_occupied(adapter, JAR)
        torn = tmp_path / "torn.gcode"
        torn.write_text(f"{QUIET_START_HEADER_START}\n; motion_contract: absolute_z_first\n{QUIET_START_HEADER_END}\n" + _body())
        verdict = evaluate_quiet_start(adapter, str(torn), QUIET_KWARGS)
        assert verdict["code"] == "QUIET_START_NO_CONTRACT" and "missing" in verdict["reason"]
        other = tmp_path / "other.gcode"
        other.write_text(_quiet_start_header(_plan(adapter)).replace("absolute_z_first", "relative_lift") + _body())
        assert evaluate_quiet_start(adapter, str(other), QUIET_KWARGS)["code"] == "QUIET_START_NO_CONTRACT"
        plain = tmp_path / "plain.gcode"
        plain.write_text(_body())
        assert evaluate_quiet_start(adapter, str(plain), QUIET_KWARGS)["code"] == "QUIET_START_NO_CONTRACT"

    def test_the_adapter_gate_judges_a_quiet_file_and_returns_the_verdict(self, tmp_path, latch):
        adapter = _QuietAdapter()
        path = self._planned(tmp_path, adapter)
        assert pg.run_adapter_gate(adapter, path, dict(QUIET_KWARGS)) is None
        adapter.homed = {"x", "y"}
        blocked = pg.run_adapter_gate(adapter, path, dict(QUIET_KWARGS))
        assert blocked["blocked"] and blocked["code"] == "QUIET_START_NOT_HOMED" and blocked["quiet_start"]["kind"] == "quiet_start"


class TestTheStartTemplate:
    def test_a_quiet_file_starts_with_every_switch_off_whatever_the_door_sent(self, tmp_path, latch, monkeypatch):
        monkeypatch.setenv("KILN_SKIP_PREVIEW_GATE", "1")
        adapter = _QuietAdapter()
        mark_occupied(adapter, JAR)
        path = _quiet_file(tmp_path, adapter)
        result = adapter.start_print(path, bed_leveling=True, timelapse=True)
        assert result.success, result.message
        (name, kwargs), = adapter.impl_calls
        assert name == path
        assert {k: kwargs[k] for k in QUIET_KWARGS} == QUIET_KWARGS, "the file's contract decides its switches"
        assert [j.file for j in read(adapter).jobs] == ["jar_v2.gcode.3mf", os.path.basename(path)], "recorded beside the jar"

    def test_the_printer_side_name_reaches_the_contract_through_the_local_copy(self, tmp_path, latch, monkeypatch):
        monkeypatch.setenv("KILN_SKIP_PREVIEW_GATE", "1")
        adapter = _QuietAdapter()
        mark_occupied(adapter, JAR)
        path = _quiet_file(tmp_path, adapter)
        result = adapter.start_print(os.path.basename(path), local_file_path=path)
        assert result.success, result.message
        assert adapter.impl_calls[0][1]["bed_leveling"] is False

    def test_a_gate_that_cannot_run_refuses_a_quiet_file_and_still_allows_an_ordinary_one(self, tmp_path, latch, monkeypatch):
        monkeypatch.setenv("KILN_SKIP_PREVIEW_GATE", "1")
        adapter = _QuietAdapter()
        mark_occupied(adapter, JAR)
        path = _quiet_file(tmp_path, adapter)

        def _boom(*a, **k):
            raise RuntimeError("gate down")

        monkeypatch.setattr(pg, "run_adapter_gate", _boom)
        refused = adapter.start_print(path)
        assert not refused.success and "safety gate" in refused.message and adapter.impl_calls == []
        mark_clear(adapter, "human")
        plain = tmp_path / "plain.gcode"
        plain.write_text(_body())
        assert adapter.start_print(str(plain)).success, "an ordinary file keeps the old rule: a gate fault never blocks"

    def test_a_quiet_file_for_a_changed_plate_is_refused_by_the_template_itself(self, tmp_path, latch, monkeypatch):
        monkeypatch.setenv("KILN_SKIP_PREVIEW_GATE", "1")
        adapter = _QuietAdapter()
        mark_occupied(adapter, JAR)
        path = _quiet_file(tmp_path, adapter)
        mark_occupied(adapter, COASTER, keep_previous=True)
        refused = adapter.start_print(path)
        assert not refused.success and "record has changed since" in refused.message and adapter.impl_calls == []


# ---------------------------------------------------------------------------
# The doors
# ---------------------------------------------------------------------------


def _plan_verdict(machine: Any, *, available: bool = True) -> dict[str, Any]:
    verdict = _verdict(ok=True, at=(200.0, 20.0))
    plan = {k: v for k, v in _plan(machine).items() if k != "planned_for_machine"}
    if not available:
        plan = {"mode": "quiet_start", "ok": False, "available": False, "tier_required": "pro", "lift_floor_mm": 47.0,
                "refusals": [{"code": "QUIET_START_TIER", "sentence": "starting it beside jar v2 the quiet way is a Kiln Pro feature"}],
                "plate_fingerprint": plan["plate_fingerprint"]}
    verdict["start"] = plan
    return verdict


@pytest.fixture
def machine(monkeypatch):
    import kiln.server as srv

    m = _machine()
    monkeypatch.setattr(srv, "_resolve_adapter", lambda *_a, **_k: m)
    return m


class TestTheDoors:
    def test_the_placed_slice_carries_the_plan_bound_to_this_machine(self, tmp_path, machine, monkeypatch):
        from kiln.plugins.slicer_tools import _placed_slice

        mark_occupied(machine, JAR)
        monkeypatch.setattr("kiln._pro_placement_bridge.ask", _Bridge((_verdict(ok=True), None), (_plan_verdict(machine), None)))
        slicer, _gcode = _fake_slice(tmp_path)
        result, err, info = _placed_slice(
            _cube(tmp_path / "part.stl"), effective_printer_id="bambu_a1", printer_name=None, placement=[200.0, 20.0],
            adapter=machine, slicer=slicer,
        )
        assert err is None and result is not None
        plan = info["quiet_start"]
        assert plan is not None and plan["planned_for_machine"] == same_bed_machine_id(machine)
        assert plan["plate_fingerprint"] == fingerprint(read(machine)) and plan["clear_z_mm"] == 47.0
        assert info["lift_floor_mm"] == 47.0

    def test_a_withheld_plan_leaves_the_floor_and_no_plan(self, tmp_path, machine, monkeypatch):
        from kiln.plugins.slicer_tools import _attach_placement, _placed_slice

        mark_occupied(machine, JAR)
        monkeypatch.setattr("kiln._pro_placement_bridge.ask", _Bridge((_verdict(ok=True), None), (_plan_verdict(machine, available=False), None)))
        slicer, _gcode = _fake_slice(tmp_path)
        _result, err, info = _placed_slice(
            _cube(tmp_path / "part.stl"), effective_printer_id="bambu_a1", printer_name=None, placement=[200.0, 20.0],
            adapter=machine, slicer=slicer,
        )
        assert err is None and info["quiet_start"] is None and info["lift_floor_mm"] == 47.0
        resp: dict[str, Any] = {}
        _attach_placement(resp, info["placement"])
        assert resp["start"] == {
            "allowed": False, "mode": "quiet_start",
            "why": "starting it beside jar v2 the quiet way is a Kiln Pro feature.",
        }

    def test_the_success_response_says_the_file_starts_the_quiet_way(self, tmp_path, machine, monkeypatch):
        from kiln.plugins.slicer_tools import _attach_placement, _placed_slice

        mark_occupied(machine, JAR)
        monkeypatch.setattr("kiln._pro_placement_bridge.ask", _Bridge((_verdict(ok=True), None), (_plan_verdict(machine), None)))
        slicer, _gcode = _fake_slice(tmp_path)
        _result, _err, info = _placed_slice(
            _cube(tmp_path / "part.stl"), effective_printer_id="bambu_a1", printer_name=None, placement=[200.0, 20.0],
            adapter=machine, slicer=slicer,
        )
        resp: dict[str, Any] = {}
        _attach_placement(resp, info["placement"])
        assert resp["start"]["allowed"] is True and resp["start"]["mode"] == "quiet_start"
        assert resp["start"]["why"].startswith("This file starts the quiet way: no Z home, no probe and no purge line")
        assert "47 mm clear" in resp["start"]["why"]
        assert resp["approval_carries"] is False

    def test_slice_and_print_hands_the_plan_to_the_wrap(self, tmp_path, machine, monkeypatch):
        mark_occupied(machine, JAR)
        monkeypatch.setattr("kiln._pro_placement_bridge.ask", _Bridge((_verdict(ok=True), None), (_plan_verdict(machine), None)))
        slicer, _gcode = _fake_slice(tmp_path)
        monkeypatch.setattr("kiln.slicer.slice_file", slicer)
        seen: dict[str, Any] = {}

        def _capture(adapter, gcode_path, **kw):
            seen.update(kw)
            raise RuntimeError("stop here")

        with patch("kiln.printers.upload_prep.prepare_upload_for_adapter", side_effect=_capture):
            resp = _slicer_tools()["slice_and_print"](
                input_path=_cube(tmp_path / "part.stl"), printer_id="bambu_a1", placement=[200.0, 20.0], skip_validation=True,
            )
        assert seen["quiet_start"]["clear_z_mm"] == 47.0 and seen["quiet_start"]["planned_for_machine"] == same_bed_machine_id(machine)
        assert seen["lift_floor_mm"] == 47.0
        assert resp.get("success") is not True, "stopped at the wrap on purpose"

    def test_slice_and_print_still_refuses_the_start_without_a_plan(self, tmp_path, machine, monkeypatch):
        mark_occupied(machine, JAR)
        monkeypatch.setattr("kiln._pro_placement_bridge.ask", _Bridge((_verdict(ok=True), None), (_plan_verdict(machine, available=False), None)))
        slicer, _gcode = _fake_slice(tmp_path)
        monkeypatch.setattr("kiln.slicer.slice_file", slicer)
        with patch("kiln.printers.upload_prep.prepare_upload_for_adapter", side_effect=RuntimeError("must not wrap")):
            resp = _slicer_tools()["slice_and_print"](
                input_path=_cube(tmp_path / "part.stl"), printer_id="bambu_a1", placement=[200.0, 20.0], skip_validation=True,
            )
        assert resp["success"] is False and resp["error"]["code"] == START_NOT_YET_CODE
        assert resp["start"]["allowed"] is False and "Kiln Pro" in resp["start"]["why"]

    def test_a_plan_that_refuses_on_its_own_is_said_as_itself_and_never_sold(self, tmp_path, machine, monkeypatch):
        """A caller on the plan's own tier whose plan refuses by itself --
        here a lift the machine's travel cannot reach -- is told why, and
        nothing on the slice result tells them to buy the tier they are on:
        not the wrap's refusal, not the start line."""
        import json

        mark_occupied(machine, JAR)
        verdict = _plan_verdict(machine)
        why = "to print beside jar v2 the head has to lift 257 mm clear of it, and the Bambu Lab A1 only has 256 mm of travel"
        verdict["start"] = {**verdict["start"], "ok": False, "refusals": [{"code": "PLACEMENT_LIFT_EXCEEDS_TRAVEL", "sentence": why}]}
        verdict["record"]["quiet_start"] = False
        monkeypatch.setattr("kiln._pro_placement_bridge.ask", _Bridge((_verdict(ok=True), None), (verdict, None)))
        slicer, _gcode = _fake_slice(tmp_path)
        monkeypatch.setattr("kiln.slicer.slice_file", slicer)
        resp = _slicer_tools()["slice_model"](
            input_path=_cube(tmp_path / "part.stl"), printer_id="bambu_a1", placement=[200.0, 20.0],
        )
        assert resp["start"] == {"allowed": False, "mode": "quiet_start", "why": why + "."}
        assert any("Kiln won't write a printer file while the plate still holds the last print" in w for w in resp.get("warnings", []))
        text = json.dumps(resp)
        assert "Kiln Pro" not in text and "kiln3d.com" not in text

    @pytest.mark.parametrize("refusal, said, sold", [
        # Below the plan's tier, on a plan that would stand: the tier is the one thing in the way.
        ({"code": "QUIET_START_TIER",
          "sentence": "the plate still holds jar v2; clear it and say so to print again, or print around it on "
                      "Kiln Pro (https://kiln3d.com/pricing)"},
         "Kiln won't upload this file. The plate still holds jar v2; clear it and say so to print again, or print "
         "around it on Kiln Pro (https://kiln3d.com/pricing).",
         True),
        # A plan that refuses on its own, on every tier: its own reason, no tier.
        ({"code": "PLACEMENT_LIFT_EXCEEDS_TRAVEL",
          "sentence": "to print beside jar v2 the head has to lift 257 mm clear of it, and the Bambu Lab A1 only "
                      "has 256 mm of travel"},
         "Kiln won't upload this file. To print beside jar v2 the head has to lift 257 mm clear of it, and the "
         "Bambu Lab A1 only has 256 mm of travel. Clear the plate and say so, then slice and print the ordinary way.",
         False),
    ])
    def test_kiln_slice_print_after_says_why_the_file_has_no_quiet_start(self, tmp_path, monkeypatch, refusal, said, sold):
        """The CLI door that writes the printer file itself.  When the wrap
        refuses for want of a plan, the error carries the verdict's own
        start sentence -- the tier where the verdict names it, the plan's
        own reason where it does not -- as every slice result does."""
        import json

        from click.testing import CliRunner

        from kiln.cli.main import cli
        from kiln.printers.bambu import BambuAdapter

        monkeypatch.setenv("KILN_SKIP_PREVIEW_GATE", "1")
        a1 = BambuAdapter(host="192.168.1.50", access_code="12345678", serial="01P00A000000001", timeout=2,
                          printer_model="bambu_a1")
        mark_occupied(a1, JAR)
        verdict = _verdict(ok=True, at=(200.0, 20.0))
        verdict["start"] = {"mode": "quiet_start", "ok": False, "available": False, "lift_floor_mm": 47.0,
                            "refusals": [refusal], "plate_fingerprint": fingerprint(read(a1))}
        if sold:
            verdict["start"]["tier_required"] = "pro"
        monkeypatch.setattr("kiln._pro_placement_bridge.ask", _Bridge((_verdict(ok=True), None), (verdict, None)))
        monkeypatch.setattr("kiln.cli.main._get_adapter_from_ctx", lambda ctx: a1)
        slicer, _gcode = _fake_slice(tmp_path)
        monkeypatch.setattr("kiln.slicer.slice_file", slicer)
        res = CliRunner().invoke(cli, [
            "slice", _cube(tmp_path / "part.stl"), "--printer-id", "bambu_a1", "--placement", "[200, 20]",
            "--print-after", "--json",
        ])
        assert res.exit_code == 1, res.output
        error = json.loads(res.output)["error"]
        assert error["code"] == "QUIET_START_WRAP_FAILED", error
        assert error["message"] == said, "the reason once, and one thing to do"
        assert ("kiln3d.com/pricing" in error["message"]) is sold, error["message"]
        assert error["message"].count("say so") == 1, "one thing to do, said once"

    def test_every_wrap_call_site_hands_the_plan_on(self):
        """Every call that wraps a placed slice into a 3MF names the plan and
        the floor; a door that wraps without them would write the vendor's
        start onto the occupied plate."""
        files = {
            "plugins/slicer_tools.py": ("_auto_wrap_bambu_3mf", "prepare_upload_for_adapter"),
            "pipelines.py": ("prepare_upload_for_adapter",),
            "plugins/smart_print_tools.py": ("wrap_gcode_as_3mf",),
            "plugins/generation_ai_tools.py": ("prepare_upload_for_adapter",),
            "cli/main.py": ("wrap_gcode_as_3mf",),
        }
        missing: list[str] = []
        for rel, names in files.items():
            tree = ast.parse((SRC / rel).read_text(encoding="utf-8"))
            for node in ast.walk(tree):
                if not isinstance(node, ast.Call):
                    continue
                fn = node.func
                called = fn.attr if isinstance(fn, ast.Attribute) else (fn.id if isinstance(fn, ast.Name) else "")
                if called not in names:
                    continue
                kws = {k.arg for k in node.keywords}
                if "quiet_start" not in kws and not (rel == "cli/main.py" and any(k.arg is None for k in node.keywords)):
                    missing.append(f"{rel}:{node.lineno} {called}(...)")
        assert not missing, f"wrap calls without the plan: {missing}"

    def test_every_start_gate_call_names_the_file_or_stands_behind_a_plan(self):
        """Every ``start_refusal(`` call outside the record itself either hands
        the gate the file (``file_name=`` / ``local_path=``), says it is a
        resume, or is the pre-wrap check a door skips when it holds a plan."""
        offenders: list[str] = []
        for path in SRC.rglob("*.py"):
            if path.name == "plate_state.py":
                continue
            for i, line in enumerate(path.read_text(encoding="utf-8").split("\n"), 1):
                if "start_refusal(" not in line or "def " in line or line.strip().startswith("#"):
                    continue
                ok = ("file_name=" in line or "local_path=" in line or "resume=" in line or "quiet_plan is None" in line
                      or "_cli_start_refusal(" in line and "file_name=" in line)
                if not ok:
                    offenders.append(f"{path.relative_to(SRC)}:{i}: {line.strip()}")
        assert not offenders, "\n".join(offenders)

    def test_the_bridge_sends_every_part_and_the_fingerprint(self, machine):
        from kiln import _pro_placement_bridge as bridge

        mark_occupied(machine, JAR)
        mark_occupied(machine, COASTER, keep_previous=True)
        req = bridge.request_for(machine, "bambu_a1", placement="auto", part=None)
        assert [j["file"] for j in req["plate"]["jobs"]] == ["jar_v2.gcode.3mf", "coaster.gcode.3mf"]
        assert req["plate"]["job"]["file"] == "coaster.gcode.3mf", "the last part, the shape the wire always carried"
        assert req["plate"]["fingerprint"] == fingerprint(read(machine))
        assert all(j["gcode"] is None for j in req["plate"]["jobs"]), "nothing in the ledger, so the record's boxes"


class TestWhereItFitsIsThePaidHalf:
    """Below the plan's tier the refusal still says room exists, and never
    where: a spot a person cannot print at is a list read out through glass.
    It names the plan's tier only where the verdict says a print could start
    there on it (``record.quiet_start``).  The refusal itself is the floor
    and is free."""

    def test_the_count_is_named_when_the_places_are_withheld(self):
        from kiln.plugins.slicer_tools import _spots_clause

        stands = {"record": {"printer_id": "bambu_a1", "quiet_start": True}}
        assert _spots_clause({"spots": [], "spots_found": 3, **stands}) == (
            " 3 spots beside it would fit; printing around what is on the plate is a kiln-pro feature "
            "(https://kiln3d.com/pricing)."
        )
        assert " 1 spot beside it would fit;" in _spots_clause({"spots": [], "spots_found": 1, **stands}), "singular reads right"
        assert _spots_clause({"spots": [], "spots_found": 0, **stands}) == "", "no room, nothing to sell"
        assert _spots_clause({"spots": [], "spots_found": None, **stands}) == ""
        assert _spots_clause(None) == "" and _spots_clause({}) == ""

    @pytest.mark.parametrize("record", [
        {"printer_id": "anker_m5", "measured": False, "source": "vendor_profile", "quiet_start": False},
        {"printer_id": "anker_m5", "measured": False, "source": "vendor_profile"},   # a service older than the field
        None,
    ])
    def test_no_tier_is_named_beside_the_count_where_no_tier_would_start_the_print(self, record):
        from kiln.plugins.slicer_tools import _spots_clause

        assert _spots_clause({"spots": [], "spots_found": 3, "record": record}) == " 3 spots beside it would fit."
        assert _spots_clause({"spots": [], "spots_found": 1, "record": record}) == " 1 spot beside it would fit."

    def test_the_places_are_named_when_they_are_this_accounts_to_use(self):
        from kiln.plugins.slicer_tools import _spots_clause

        paid = {"spots": [{"at_mm": [40.0, 40.0], "clearance_mm": 12.0}, {"at_mm": [40.0, 200.0]}], "spots_found": 2}
        assert _spots_clause(paid) == " Spots with room: [40, 40] (12 mm clear), [40, 200]."
        assert "kiln3d.com" not in _spots_clause(paid), "no nudge when there is nothing to unlock"

    def test_a_bare_list_still_reads_as_the_places(self):
        from kiln.plugins.slicer_tools import _spots_clause

        assert _spots_clause([{"at_mm": [10.0, 20.0]}]) == " Spots with room: [10, 20]."

    def test_the_door_says_the_count_on_an_occupied_plate(self, tmp_path, machine, monkeypatch):
        from kiln.plugins.slicer_tools import _apply_plate_placement

        mark_occupied(machine, JAR)
        withheld = _verdict(ok=False, spots=[])
        withheld["spots_found"] = 3
        withheld["record"]["quiet_start"] = True
        monkeypatch.setattr("kiln._pro_placement_bridge.ask", _Bridge((withheld, None)))
        _placed, err, _info = _apply_plate_placement(
            _cube(tmp_path / "part.stl"), effective_printer_id="bambu_a1", printer_name=None,
            placement=None, adapter=machine,
        )
        message = err["error"]["message"]
        assert "3 spots beside it would fit" in message and "kiln3d.com/pricing" in message
        assert "[" not in message.split("would fit")[1], "no coordinates once the places are withheld"

    @pytest.mark.parametrize("placement", [None, [100.0, 100.0]])
    def test_the_door_names_no_tier_where_no_tier_would_start_the_print(self, tmp_path, machine, monkeypatch, placement):
        """A printer whose quiet start Kiln has not seen run: room beside the
        part is still room, said plainly -- never "no spot is safe", which
        would be false, and never a tier, which would sell a start that
        paying does not buy."""
        from kiln.plugins.slicer_tools import _apply_plate_placement

        mark_occupied(machine, JAR)
        withheld = _verdict(ok=False, spots=[])
        withheld["spots_found"] = 3
        withheld["record"]["quiet_start"] = False
        monkeypatch.setattr("kiln._pro_placement_bridge.ask", _Bridge((withheld, None)))
        _placed, err, _info = _apply_plate_placement(
            _cube(tmp_path / "part.stl"), effective_printer_id="bambu_a1", printer_name=None,
            placement=placement, adapter=machine,
        )
        message = err["error"]["message"]
        assert message.endswith(" 3 spots beside it would fit."), message
        assert "No spot on the plate is safe" not in message, "room exists; only a start beside it does not"
        assert "kiln3d.com" not in message and "kiln-pro" not in message
        assert err["tier_note"] == "The clearance verdict is free on every tier."

    def test_the_tier_note_names_the_tier_only_where_it_would_start_the_print(self, machine):
        from kiln.plugins.slicer_tools import _placement_refusal

        mark_occupied(machine, JAR)
        state = read(machine)
        stands, refuses, older = (_verdict(ok=False, spots=[]) for _ in range(3))
        stands["record"]["quiet_start"] = True
        refuses["record"]["quiet_start"] = False
        note = _placement_refusal("x", "PLACEMENT_REFUSED", state=state, bed=None, verdict=stands)["tier_note"]
        assert "kiln3d.com/pricing" in note
        for verdict in (refuses, older, None):
            note = _placement_refusal("x", "PLACEMENT_REFUSED", state=state, bed=None, verdict=verdict)["tier_note"]
            assert note == "The clearance verdict is free on every tier.", verdict


# ---------------------------------------------------------------------------
# The AMS block goes to THIS machine's chute, or Kiln does not write the file
# ---------------------------------------------------------------------------


_TWO_COLOUR_BODY = ";LAYER_CHANGE\n;Z:0.4\nG1 Z0.4 F24000\nG1 X30 Y20 E1\nT1\nG1 X10 Y20 E1\n"


class TestTheAmsBlockGoesToThisMachinesChute:
    def test_the_a1s_block_goes_to_the_a1s_own_chute(self):
        from kiln.printers.bambu_3mf import flush_station_for

        assert flush_station_for("bambu_a1") == (-48.2, None), "the position that was run and watched"
        out = _wrap_tool_changes(_TWO_COLOUR_BODY, printer_model="bambu_a1").split("\n")
        i = out.index("M620 S1A   ; AMS switch to filament 1")
        j = next(k for k, line in enumerate(out) if line.startswith("M621 S1A"))
        travels = [line.strip() for line in out[i:j] if line.strip().startswith("G1 X")]
        assert travels == ["G1 X-48.20 F3000"], "one travel, to the A1's chute, before the flush"
        assert out.index("    M620.1 E F299.339 T250") > i + travels.index("G1 X-48.20 F3000")

    @pytest.mark.parametrize(
        "printer_model",
        ["bambu_x1c", "bambu_x1e", "bambu_p1s", "bambu_p1p", "bambu_p2s", "bambu_h2s", "bambu_h2d", "bambu_h2d_pro"],
    )
    def test_a_model_with_no_chute_on_record_is_refused_never_sent_to_the_a1s(self, printer_model):
        """X-48.2 is 48 mm past the leftmost point any of these machines'
        own sequences ever command.  Kiln will not write it."""
        with pytest.raises(ValueError) as caught:
            _wrap_tool_changes(_TWO_COLOUR_BODY, printer_model=printer_model)
        said = str(caught.value)
        assert printer_model in said and "no waste chute on record" in said
        assert "bambu_a1" in said, "the refusal names what it CAN do"
        assert "-48.2" not in said, "a refusal never leaks another machine's position as a suggestion"

    @pytest.mark.parametrize("printer_model", [None, "", "bambu_never_heard_of_it"])
    def test_a_printer_nobody_declared_keeps_the_a1_default_its_other_routines_take(self, printer_model):
        """An undeclared or unknown printer has always been treated as an A1
        -- its warm-up and end sequence are the A1's -- and people print
        multi-colour on that path.  Only a model Kiln KNOWS is not an A1 is
        refused its chute."""
        from kiln.printers.bambu_3mf import flush_station_for

        assert flush_station_for(printer_model) == (-48.2, None)
        out = _wrap_tool_changes(_TWO_COLOUR_BODY, printer_model=printer_model).split("\n")
        assert "    G1 X-48.20 F3000" in out

    def test_a_single_colour_print_is_untouched_on_every_model(self):
        """The refusal is about the AMS block, not about the machine: a file
        that never changes tool has no chute to go to and builds fine."""
        body = ";LAYER_CHANGE\n;Z:0.4\nG1 X30 Y20 E1\n"
        for printer_model in (None, "bambu_x1c", "bambu_h2d"):
            assert _wrap_tool_changes(body, printer_model=printer_model) == body

    def test_the_whole_file_refuses_rather_than_carrying_the_wrong_chute(self, tmp_path):
        from kiln.printers.bambu_3mf import BambuPrintSettings, build_bambu_3mf

        out = str(tmp_path / "two.gcode.3mf")
        with pytest.raises(ValueError, match="no waste chute on record"):
            build_bambu_3mf(
                _body(layers=4, change_at=1), out,
                settings=BambuPrintSettings(num_filaments=2, filament_colors=["#FFFFFF", "#FF0000"]),
                printer_model="bambu_x1c",
            )
        assert not Path(out).exists(), "no half-written file is left behind"

    def test_one_helper_spells_the_chute_for_every_door(self):
        """The quiet start and the AMS block send the head to the same place
        the same way — a chute off the left edge on one machine and behind
        the plate on another is one figure, written once."""
        from kiln.printers.safe_motion import chute_move

        assert chute_move((-48.2, None), feedrate=3000) == "G1 X-48.20 F3000"
        assert chute_move((60.0, 265.0)) == "G1 X60.00 Y265.00 F6000"
        assert chute_move(None) is None and chute_move((None, None)) is None


class TestTheEndSequenceSaysWhoseItIs:
    def test_a_model_with_no_end_capture_carries_the_a1s_and_says_so(self, tmp_path):
        """Every printer in the catalogue now has an end of its own, so the
        fallback is for a model Kiln has never heard of: it gets the A1's, a
        deliberate, long-standing fallback.  What was missing is that the
        start said so and the end did not -- the end block is the one that
        wipes, parks and rolls the bed with a finished part on it."""
        from kiln.printers.bambu_3mf import _MODEL_END_GCODE_FILES, BambuPrintSettings, build_bambu_3mf

        assert "bambu_never_heard_of_it" not in _MODEL_END_GCODE_FILES
        result = build_bambu_3mf(
            _body(), str(tmp_path / "unknown.gcode.3mf"),
            settings=BambuPrintSettings(), printer_model="bambu_never_heard_of_it",
        )
        assert result.end_gcode_model == "bambu_a1" and result.requested_model == "bambu_never_heard_of_it"
        said = result.end_gcode_warning
        assert said and "bambu_a1 end sequence" in said and "bambu_never_heard_of_it" in said
        assert result.to_dict()["end_gcode_model"] == "bambu_a1"
        assert "end_gcode_warning" in result.to_dict()

    def test_a_model_with_its_own_end_capture_says_nothing(self, tmp_path):
        from kiln.printers.bambu_3mf import BambuPrintSettings, build_bambu_3mf

        result = build_bambu_3mf(
            _body(), str(tmp_path / "x1c.gcode.3mf"),
            settings=BambuPrintSettings(), printer_model="bambu_x1c",
        )
        assert result.end_gcode_model == "bambu_x1c" and result.end_gcode_warning is None
        assert "end_gcode_warning" not in result.to_dict()
