"""The doors that put slicer-added geometry on the stage.

Every payload-producing door goes through ``attach_stage_plate``; that is
the one place plate and placement are decided, so it is where the skirt,
brim, prime tower and supports are laid around the part too.  Three things
have to hold or the extras lie:

* they land in the SAME coordinate frame as the part — built against the
  centred bbox and moved by the same centring offset, so a skirt can never
  wrap empty plate beside the model it was sliced around;
* the slice belongs to THIS mesh — joined through the machine's own slice
  ledger by exact path, never by stem, never on the hosted server whose
  ledger is nobody's;
* with no slice, nothing changes — the model-only payload is byte-identical
  to one built before extras existed, so every stage that predates the
  block renders exactly as it did.
"""

from __future__ import annotations

import base64
import copy
import json
import os
import time

import numpy as np
import pytest

from kiln import local_stage, monitor_twin, stage_link, stage_plate
from kiln import slicer_geometry as sg


def _box(path, extents=(40.0, 30.0, 10.0), origin_corner=True):
    trimesh = pytest.importorskip("trimesh")
    mesh = trimesh.creation.box(extents=extents)
    if origin_corner:
        mesh.apply_translation([extents[0] / 2, extents[1] / 2, extents[2] / 2])
    mesh.export(str(path))
    return str(path)


def _loop(x0, y0, x1, y1, z):
    return (
        f"G1 X{x0} Y{y0} Z{z} F6000\nG1 X{x1} Y{y0} E0.1\nG1 X{x1} Y{y1} E0.1\n"
        f"G1 X{x0} Y{y1} E0.1\nG1 X{x0} Y{y0} E0.1\n"
    )


def _gcode_for_box(path, *, tower=True):
    """The 40 x 30 box sliced at bed (100..140, 100..130): skirt 2 mm out,
    a 10 mm prime tower 20 mm to the right."""
    lines = ["; generated by OrcaSlicer 2.3.2 on 2026-09-03", "G90", "M83"]
    for i in range(2):
        z = 0.2 * (i + 1)
        lines += [";LAYER_CHANGE", f";Z:{z}"]
        if i == 0:
            lines += [";TYPE:Skirt", _loop(98, 98, 142, 132, z)]
        lines += [";TYPE:Outer wall", _loop(100, 100, 140, 130, z)]
        if tower:
            lines += [";TYPE:Prime tower", _loop(160, 100, 170, 110, z)]
    path.write_text("\n".join(lines) + "\n")
    return str(path)


def _positions(payload):
    return np.frombuffer(base64.b64decode(payload["positions"]), dtype="<f4").reshape(-1, 3)


def _segments(feature):
    return np.frombuffer(base64.b64decode(feature["segments"]), dtype="<f4").reshape(-1, 6)


@pytest.fixture()
def twin_dir(tmp_path, monkeypatch):
    d = tmp_path / "monitor_twin"
    monkeypatch.setattr(monitor_twin, "_TWIN_DIR", d)
    monkeypatch.setattr(monitor_twin, "_SLICES_FILE", d / "slices.json")
    monkeypatch.setattr(monitor_twin, "_ACTIVE_FILE", d / "active.json")
    return d


@pytest.fixture()
def no_printer(monkeypatch):
    monkeypatch.setattr("kiln.printer_model_resolver.resolve_printer_model", lambda: None)


# ===========================================================================
# 1. Same frame as the part
# ===========================================================================


class TestSameFrameAsThePart:
    def test_extras_are_laid_around_the_centred_part(self, tmp_path, no_printer):
        """The part arrives corner-at-origin, the slice put it at the bed
        centre; after the door, both are centred on the stage and the
        skirt wraps the part, the tower stands 20 mm to its right."""
        from kiln.mesh_payload import mesh_to_viewer_payload

        mesh = _box(tmp_path / "part.stl")
        gcode = _gcode_for_box(tmp_path / "part.gcode")
        payload = stage_plate.attach_stage_plate(
            mesh_to_viewer_payload(mesh), gcode_path=gcode,
        )
        # The part is centred on the plate (mesh x -20..20, y -15..15).
        assert payload["bbox"]["min"][:2] == pytest.approx([-20.0, -15.0])
        assert payload["bbox"]["max"][:2] == pytest.approx([20.0, 15.0])
        block = payload["slicer"]
        assert block["available"] and block["frame"] == "viewer"
        by_class = {f["class"]: f for f in block["features"]}
        skirt = _segments(by_class["skirt"])
        # Viewer frame: x is mesh x; z is -mesh y.  The skirt is 2 mm out.
        assert skirt[:, [0, 3]].min() == pytest.approx(-22.0, abs=1e-3)
        assert skirt[:, [0, 3]].max() == pytest.approx(22.0, abs=1e-3)
        assert skirt[:, [2, 5]].min() == pytest.approx(-17.0, abs=1e-3)
        assert skirt[:, [2, 5]].max() == pytest.approx(17.0, abs=1e-3)
        # ...and it lies on the part's floor (viewer y = mesh z).
        assert skirt[:, [1, 4]].min() == pytest.approx(0.2, abs=1e-3)
        tower = _segments(by_class["prime_tower"])
        assert tower[:, [0, 3]].min() == pytest.approx(40.0, abs=1e-3)
        assert tower[:, [0, 3]].max() == pytest.approx(50.0, abs=1e-3)
        # The part's own vertices agree — the tower is beside the part's
        # +x face, not beside where the file's corner used to be.
        pos = _positions(payload)
        assert pos[:, 0].max() == pytest.approx(20.0, abs=1e-3)
        assert by_class["skirt"]["bounds"]["min"][0] == pytest.approx(-22.0, abs=1e-3)

    def test_a_late_centring_moves_the_extras_with_the_part(self, tmp_path):
        """A block attached to an off-centre payload rides the same slide
        stand_on_plate gives the vertices — pinned by comparing deltas."""
        from kiln.mesh_payload import mesh_to_viewer_payload

        mesh = _box(tmp_path / "part.stl")
        gcode = _gcode_for_box(tmp_path / "part.gcode")
        payload = mesh_to_viewer_payload(mesh)          # corner at the origin
        sg.attach_to_payload(payload, gcode)            # aligned to THAT bbox
        before_pos = _positions(payload).copy()
        before = {f["class"]: _segments(f).copy() for f in payload["slicer"]["features"]}
        stage_plate.stand_on_plate(payload)
        delta = _positions(payload)[0] - before_pos[0]
        assert delta[0] == pytest.approx(-20.0) and delta[2] == pytest.approx(15.0)
        for f in payload["slicer"]["features"]:
            a, b = before[f["class"]], _segments(f)
            assert np.allclose(b[:, [0, 3]] - a[:, [0, 3]], delta[0], atol=1e-4)
            assert np.allclose(b[:, [2, 5]] - a[:, [2, 5]], delta[2], atol=1e-4)
            assert np.allclose(b[:, [1, 4]], a[:, [1, 4]])
        assert payload["slicer"]["features"][0]["bounds"]["min"][0] == pytest.approx(-22.0, abs=1e-3)

    def test_a_downgraded_payload_carries_no_extras(self, tmp_path):
        gcode = _gcode_for_box(tmp_path / "part.gcode")
        payload = {"kind": "kiln.mesh.v1", "downgraded": True,
                   "bbox": {"min": [0, 0, 0], "max": [40, 30, 10]}}
        sg.attach_to_payload(payload, gcode)
        assert "slicer" not in payload


# ===========================================================================
# 2. Nothing changes without a slice
# ===========================================================================


class TestModelOnlyIsUnchanged:
    def test_no_slice_means_a_byte_identical_payload(self, tmp_path, twin_dir, no_printer):
        from kiln.mesh_payload import mesh_to_viewer_payload

        mesh = _box(tmp_path / "part.stl")
        a = stage_plate.attach_stage_plate(mesh_to_viewer_payload(mesh))
        b = stage_plate.attach_stage_plate(mesh_to_viewer_payload(mesh), mesh_path=mesh)
        assert "slicer" not in b
        assert json.dumps(a, sort_keys=True) == json.dumps(b, sort_keys=True)

    def test_none_and_junk_pass_through(self):
        assert stage_plate.attach_slicer_geometry(None) is None
        assert sg.attach_to_payload({"kind": "kiln.mesh.v1"}, None) == {"kind": "kiln.mesh.v1"}


# ===========================================================================
# 3. Which slice belongs to which mesh
# ===========================================================================


class TestTheLedgerJoin:
    def test_the_slice_ledger_answers_by_exact_path(self, tmp_path, twin_dir):
        mesh = _box(tmp_path / "part.stl")
        gcode = _gcode_for_box(tmp_path / "part.gcode")
        monitor_twin.note_sliced(mesh, gcode)
        assert monitor_twin.sliced_output_for(mesh) == os.path.abspath(gcode)

    def test_a_stem_match_is_not_a_join(self, tmp_path, twin_dir):
        (tmp_path / "elsewhere").mkdir()
        other = _box(tmp_path / "elsewhere" / "part.stl")  # same stem, other file
        mesh = _box(tmp_path / "part.stl")
        gcode = _gcode_for_box(tmp_path / "part.gcode")
        monitor_twin.note_sliced(other, gcode)
        assert monitor_twin.sliced_output_for(mesh) is None

    def test_the_newest_surviving_slice_wins(self, tmp_path, twin_dir):
        mesh = _box(tmp_path / "part.stl")
        old = _gcode_for_box(tmp_path / "old.gcode")
        new = _gcode_for_box(tmp_path / "new.gcode")
        monitor_twin.note_sliced(mesh, old)
        monitor_twin.note_sliced(mesh, new)
        assert monitor_twin.sliced_output_for(mesh) == os.path.abspath(new)
        os.unlink(new)
        assert monitor_twin.sliced_output_for(mesh) == os.path.abspath(old)

    def test_a_slice_older_than_the_mesh_is_not_a_slice_of_it(self, tmp_path, twin_dir):
        """A file edited in place after slicing keeps its path and loses
        its G-code — the extras of the previous shape must not dress it."""
        mesh = _box(tmp_path / "part.stl")
        gcode = _gcode_for_box(tmp_path / "part.gcode")
        monitor_twin.note_sliced(mesh, gcode)
        stale = time.time() - 120
        os.utime(gcode, (stale, stale))
        assert monitor_twin.sliced_output_for(mesh) is None

    def test_the_retained_twin_copy_answers_too(self, tmp_path, twin_dir):
        """``note_print_started`` copies the pair under the twin dir; the
        copy is the mesh the print monitor hands the stage."""
        mesh = _box(tmp_path / "part.stl")
        gcode = _gcode_for_box(tmp_path / "part.gcode")
        monitor_twin.note_sliced(mesh, gcode)
        monitor_twin.note_print_started("bambu", "part.gcode")
        rec = monitor_twin.active_twin("bambu")
        assert rec["mesh"] and rec["gcode"]
        assert monitor_twin.sliced_output_for(rec["mesh"]) == rec["gcode"]

    def test_the_plate_door_reaches_the_ledger(self, tmp_path, twin_dir, no_printer):
        from kiln.mesh_payload import mesh_to_viewer_payload

        mesh = _box(tmp_path / "part.stl")
        gcode = _gcode_for_box(tmp_path / "part.gcode")
        monitor_twin.note_sliced(mesh, gcode)
        payload = stage_plate.attach_stage_plate(mesh_to_viewer_payload(mesh), mesh_path=mesh)
        assert payload["slicer"]["available"]
        assert [f["class"] for f in payload["slicer"]["features"]] == ["skirt", "prime_tower"]

    def test_an_explicit_gcode_outranks_the_ledger(self, tmp_path, twin_dir, no_printer):
        from kiln.mesh_payload import mesh_to_viewer_payload

        mesh = _box(tmp_path / "part.stl")
        ledger = _gcode_for_box(tmp_path / "ledger.gcode")
        held = _gcode_for_box(tmp_path / "held.gcode", tower=False)
        monitor_twin.note_sliced(mesh, ledger)
        payload = stage_plate.attach_stage_plate(
            mesh_to_viewer_payload(mesh), mesh_path=mesh, gcode_path=held,
        )
        assert [f["class"] for f in payload["slicer"]["features"]] == ["skirt"]
        assert payload["slicer"]["source"]["filename"] == "held.gcode"

    def test_the_hosted_process_never_reads_the_shared_ledger(
        self, tmp_path, twin_dir, monkeypatch,
    ):
        """One ~/.kiln, every customer: a hosted caller's mesh must never
        be dressed in another tenant's skirt."""
        from kiln.mesh_payload import mesh_to_viewer_payload

        mesh = _box(tmp_path / "part.stl")
        gcode = _gcode_for_box(tmp_path / "part.gcode")
        monitor_twin.note_sliced(mesh, gcode)
        monkeypatch.setenv("KILN_HOSTED_MULTITENANT", "1")
        monkeypatch.setattr(
            monitor_twin, "sliced_output_for",
            lambda *a, **k: pytest.fail("hosted resolution read the shared ledger"),
        )
        payload = stage_plate.attach_stage_plate(mesh_to_viewer_payload(mesh), mesh_path=mesh)
        assert "slicer" not in payload
        # An explicit slice the hosted door HOLDS (the print twin) still counts.
        payload = stage_plate.attach_stage_plate(
            mesh_to_viewer_payload(mesh), mesh_path=mesh, gcode_path=gcode,
        )
        assert payload["slicer"]["available"]

    def test_a_slice_of_something_else_rides_as_an_honest_refusal(
        self, tmp_path, twin_dir, no_printer,
    ):
        from kiln.mesh_payload import mesh_to_viewer_payload

        mesh = _box(tmp_path / "big.stl", extents=(400.0, 300.0, 10.0))
        gcode = _gcode_for_box(tmp_path / "big.gcode")
        monitor_twin.note_sliced(mesh, gcode)
        payload = stage_plate.attach_stage_plate(mesh_to_viewer_payload(mesh), mesh_path=mesh)
        assert payload["slicer"]["available"] is False
        assert "does not match" in payload["slicer"]["reason"]


# ===========================================================================
# 4. The local stage and the 30-minute link go through the same door
# ===========================================================================


class TestEveryDoor:
    def test_the_local_stage_payload_carries_the_slice(self, tmp_path, twin_dir, no_printer):
        mesh = _box(tmp_path / "part.stl")
        gcode = _gcode_for_box(tmp_path / "part.gcode")
        monitor_twin.note_sliced(mesh, gcode)
        payload = local_stage._payload_for_mesh(mesh)
        assert payload["slicer"]["available"]
        assert payload["slicer"]["frame"] == "viewer"

    def test_the_sidecar_is_the_mesh_frame_block(self, tmp_path, twin_dir):
        mesh = _box(tmp_path / "part.stl")
        gcode = _gcode_for_box(tmp_path / "part.gcode")
        monitor_twin.note_sliced(mesh, gcode)
        raw = sg.sidecar_for_mesh(mesh)
        block = sg.load_sidecar(raw)
        assert block["available"] and block["frame"] == "mesh"
        # Aligned to the FILE's bbox (corner at the origin), not a centred one.
        assert block["model_footprint"] == {"min": [0.0, 0.0], "max": [40.0, 30.0]}
        skirt = next(f for f in block["features"] if f["class"] == "skirt")
        assert skirt["bounds"]["min"][:2] == pytest.approx([-2.0, -2.0])

    def test_no_slice_means_no_sidecar(self, tmp_path, twin_dir):
        mesh = _box(tmp_path / "part.stl")
        assert sg.sidecar_for_mesh(mesh) is None

    def test_the_link_upload_carries_the_sidecar(self, tmp_path, twin_dir, monkeypatch):
        mesh = _box(tmp_path / "part.stl")
        gcode = _gcode_for_box(tmp_path / "part.gcode")
        monitor_twin.note_sliced(mesh, gcode)
        monkeypatch.setattr(stage_link, "_stage_printer_id", lambda: None)
        monkeypatch.setattr(
            "kiln.auth_session.resolve_api_bearer",
            lambda *a, **k: type("B", (), {"token": "bearer-abc", "state": "license"})(),
        )
        seen: list[dict] = []

        class _Resp:
            status_code = 200

            def json(self):
                return {"viewer_url": "https://app.kiln3d.com/view#v=tok",
                        "viewer_expires_at": time.time() + 1800}

        def _post(url, **kw):
            files = kw.get("files") or {}
            seen.append({k: (v[0], v[1] if isinstance(v[1], bytes) else b"<stream>")
                         for k, v in files.items()})
            return _Resp()

        import httpx

        monkeypatch.setattr(httpx, "post", _post)
        monkeypatch.setattr(stage_link, "_cache", {})
        link = stage_link.stage_link_for(mesh)
        assert link and link["viewer_url"].endswith("#v=tok")
        assert "slicer" in seen[-1], "the sidecar did not ride the upload"
        name, raw = seen[-1]["slicer"]
        assert name == "slicer.json"
        assert sg.load_sidecar(raw)["available"]

    def test_a_re_slice_is_a_new_link_not_a_stale_tower(self, tmp_path, twin_dir, monkeypatch):
        """The sidecar is part of the link's identity: the cache must not
        serve a link still wearing the previous slice's extras."""
        mesh = _box(tmp_path / "part.stl")
        first = _gcode_for_box(tmp_path / "first.gcode")
        monitor_twin.note_sliced(mesh, first)
        monkeypatch.setattr(stage_link, "_stage_printer_id", lambda: None)
        monkeypatch.setattr(
            "kiln.auth_session.resolve_api_bearer",
            lambda *a, **k: type("B", (), {"token": "bearer-abc", "state": "license"})(),
        )
        calls = []

        class _Resp:
            status_code = 200

            def json(self):
                return {"viewer_url": f"https://app.kiln3d.com/view#v={len(calls)}",
                        "viewer_expires_at": time.time() + 1800}

        def _post(url, **kw):
            calls.append(kw)
            return _Resp()

        import httpx

        monkeypatch.setattr(httpx, "post", _post)
        monkeypatch.setattr(stage_link, "_cache", {})
        one = stage_link.stage_link_for(mesh)
        again = stage_link.stage_link_for(mesh)
        assert again["cached"] and again["viewer_url"] == one["viewer_url"]
        second = _gcode_for_box(tmp_path / "second.gcode", tower=False)
        monitor_twin.note_sliced(mesh, second)
        fresh = stage_link.stage_link_for(mesh)
        assert not fresh["cached"]
        assert fresh["viewer_url"] != one["viewer_url"]
        assert len(calls) == 2


# ===========================================================================
# 5. The contract is documented where the other blocks are
# ===========================================================================


def test_the_payload_contract_names_the_block():
    from kiln import mesh_payload

    assert '"slicer": {...}' in mesh_payload.__doc__
    assert "THE SLICER BLOCK" in mesh_payload.__doc__


def test_attach_never_raises_on_a_broken_payload(tmp_path):
    gcode = _gcode_for_box(tmp_path / "part.gcode")
    junk = {"kind": "kiln.mesh.v1", "bbox": {"min": "nope"}}
    assert sg.attach_to_payload(copy.deepcopy(junk), gcode) == junk
    assert stage_plate.attach_slicer_geometry(copy.deepcopy(junk), gcode_path=gcode) == junk


# ===========================================================================
# 6. The hosted door — a sidecar block lands where the slice would have
# ===========================================================================


class TestSidecarOnTheHostedDoor:
    """The hosted server never sees the slice, only the MESH-frame block
    the owner's install built from it.  Stamped onto a payload that has
    since been centred, it must land exactly where the G-code route
    would have put it."""

    def test_a_mesh_frame_sidecar_lands_where_the_gcode_would(self, tmp_path, no_printer):
        from kiln.mesh_payload import mesh_to_viewer_payload

        mesh = _box(tmp_path / "part.stl")
        gcode = _gcode_for_box(tmp_path / "part.gcode")
        # The G-code route: the truth to match.
        direct = stage_plate.attach_stage_plate(mesh_to_viewer_payload(mesh), gcode_path=gcode)
        # The hosted route: a sidecar built against the FILE bbox, attached
        # to a payload the plate door already centred.
        block = sg.load_sidecar(sg.sidecar_for_mesh(mesh, gcode))
        hosted = stage_plate.attach_stage_plate(mesh_to_viewer_payload(mesh))
        sg.attach_block_to_payload(hosted, block)
        assert hosted["slicer"]["frame"] == "viewer"
        for a, b in zip(direct["slicer"]["features"], hosted["slicer"]["features"], strict=True):
            assert a["class"] == b["class"]
            assert np.allclose(_segments(a), _segments(b), atol=1e-3)
            assert a["bounds"] == pytest.approx(b["bounds"], abs=1e-3)
        # The sidecar itself is untouched — the caller may reuse it.
        assert block["frame"] == "mesh"

    def test_an_unavailable_sidecar_rides_as_is(self):
        payload = {"kind": "kiln.mesh.v1", "bbox": {"min": [0, 0, 0], "max": [1, 1, 1]}}
        sg.attach_block_to_payload(payload, sg.unavailable_block("no slice"))
        assert payload["slicer"]["available"] is False
        assert payload["slicer"]["reason"] == "no slice"

    def test_junk_attaches_nothing(self):
        payload = {"kind": "kiln.mesh.v1", "bbox": {"min": [0, 0, 0], "max": [1, 1, 1]}}
        sg.attach_block_to_payload(payload, {"kind": "something.else"})
        sg.attach_block_to_payload(payload, None)
        assert "slicer" not in payload
