"""The slice result reports ONE footprint: the G-code's.

2026-09-23: ``slice_model`` reported the mesh's placement under ``bed_fit``
(measured before the slicer ran) beside the G-code's under
``safety_verification`` — two footprints for one file, 60 mm apart,
because OrcaSlicer's arrange had turned the plate.  The bed-fit block now
describes what will print, and says when the slicer moved the part.
"""

from __future__ import annotations

import pytest

from kiln.plugins.slicer_tools import _report_the_sliced_footprint


def _loop(x0, y0, x1, y1, z):
    return (
        f"G1 X{x0} Y{y0} Z{z} F6000\nG1 X{x1} Y{y0} E0.1\nG1 X{x1} Y{y1} E0.1\n"
        f"G1 X{x0} Y{y1} E0.1\nG1 X{x0} Y{y0} E0.1\n"
    )


def _gcode(path, *, part=(100, 100, 140, 130), tower=(160, 100, 170, 110)):
    """A 40 x 30 part with a 10 mm prime tower to its right."""
    lines = ["; generated by OrcaSlicer 2.3.2", "G90", "M83", "G28", ";LAYER_CHANGE", ";Z:0.2"]
    lines += [";TYPE:Outer wall", _loop(*part, 0.2), ";TYPE:Prime tower", _loop(*tower, 0.2)]
    path.write_text("\n".join(lines) + "\n")
    return str(path)


def _mesh_fit(x0, y0, x1, y1):
    return {"ok": True, "error_code": None, "bbox": {"x_min": x0, "x_max": x1, "y_min": y0, "y_max": y1, "z_min": 0.0, "z_max": 20.0}}


class TestOneFootprint:
    def test_the_block_reports_the_gcode_with_the_tower(self, tmp_path):
        info = {"bed_fit": _mesh_fit(100, 100, 140, 130)}
        _report_the_sliced_footprint(info, _gcode(tmp_path / "job.gcode"))
        fit = info["bed_fit"]
        assert fit["bbox_source"] == "gcode"
        assert (fit["bbox"]["x_min"], fit["bbox"]["x_max"]) == (100.0, 170.0)
        assert (fit["bbox"]["y_min"], fit["bbox"]["y_max"]) == (100.0, 130.0)
        # The part printed where the mesh was: no move to report.
        assert "slicer_moved_the_part" not in fit and "input_bbox" not in fit

    def test_a_part_the_slicer_moved_is_said_so(self, tmp_path):
        """The mesh was measured 60 mm left of where the slicer printed it."""
        info = {"bed_fit": _mesh_fit(40, 100, 80, 130)}
        _report_the_sliced_footprint(info, _gcode(tmp_path / "job.gcode"))
        fit = info["bed_fit"]
        assert fit["slicer_moved_the_part"] is True
        assert fit["input_bbox"]["x_min"] == 40 and fit["bbox"]["x_min"] == 100.0
        assert fit["part_footprint"] == {"x_min": 100.0, "y_min": 100.0, "x_max": 140.0, "y_max": 130.0}

    def test_a_part_the_slicer_turned_is_said_so(self, tmp_path):
        """The jar-and-lid case: same centre, width and depth swapped."""
        info = {"bed_fit": _mesh_fit(105, 95, 135, 135)}   # 30 wide, 40 deep, centred like the part
        _report_the_sliced_footprint(info, _gcode(tmp_path / "job.gcode"))
        assert info["bed_fit"]["slicer_moved_the_part"] is True

    def test_no_gcode_leaves_the_gate_block_as_written(self, tmp_path):
        info = {"bed_fit": _mesh_fit(100, 100, 140, 130)}
        _report_the_sliced_footprint(info, str(tmp_path / "missing.gcode"))
        assert info["bed_fit"] == _mesh_fit(100, 100, 140, 130)
        info = {"bed_fit": None}
        _report_the_sliced_footprint(info, _gcode(tmp_path / "job.gcode"))
        assert info["bed_fit"] is None

    def test_the_placed_slice_reports_the_gcode_footprint(self, tmp_path, monkeypatch):
        """Through the door every slice tool shares."""
        from kiln.plugins.slicer_tools import _placed_slice
        from kiln.slicer import SliceResult

        trimesh = pytest.importorskip("trimesh")
        box = trimesh.creation.box(extents=(40.0, 30.0, 20.0))
        box.apply_translation([120.0, 115.0, 10.0])
        stl = str(tmp_path / "part.stl")
        box.export(stl)
        gcode = _gcode(tmp_path / "job.gcode")
        monkeypatch.setattr("kiln.plugins.slicer_tools._material_temp_block", lambda *_a, **_k: None)

        def fake_slicer(path, **_k):
            return SliceResult(success=True, output_path=gcode, slicer="orcaslicer")

        _result, err, info = _placed_slice(
            stl, effective_printer_id="bambu_a1", printer_name=None, placement=None,
            auto_center=True, slicer=fake_slicer, plate_gate=False,
        )
        assert err is None
        fit = info["bed_fit"]
        assert fit["bbox_source"] == "gcode" and fit["bbox"]["x_max"] == 170.0
        assert "slicer_moved_the_part" not in fit

    def test_an_unlabelled_file_never_claims_a_move(self, tmp_path):
        """Without feature labels the tower counts as part; a move flag from
        that would be the same lie the stage refuses to tell."""
        g = tmp_path / "old.gcode"
        g.write_text("G90\nM83\nG28\n;LAYER_CHANGE\n" + _loop(100, 100, 140, 130, 0.2) + _loop(160, 100, 170, 110, 0.2))
        info = {"bed_fit": _mesh_fit(100, 100, 140, 130)}
        _report_the_sliced_footprint(info, str(g))
        fit = info["bed_fit"]
        assert fit["bbox_source"] == "gcode" and fit["bbox"]["x_max"] == 170.0
        assert "slicer_moved_the_part" not in fit
