"""The volumetric flow limit, and the one time correction that follows it.

Investigated 2026-08-27 after a multicolor slice reported ~10h.  The
suspected cause — Kiln's Orca presets carrying no machine speed or
acceleration limits — did NOT reproduce: adding the whole stock A1 set
(machine_max_acceleration_*, machine_max_speed_*, machine_max_jerk_*,
and the process acceleration keys) moved the estimate by 2.3%, from
9h52m to 9h38m.

The real cause was a key neither side names: ``filament_max_volumetric
_speed``.  PrusaSlicer defaults it to 0 — unlimited, honour the
profile's speeds — and Orca defaults it to about 2 mm³/s, which clamps
every extruding move.  Measured on the same model and profile: Orca
estimated 5h27m with the key absent against PrusaSlicer's 2h19m, with
extrusion moves at 20-30 mm/s where the profile asks 200-250.  That is
not an estimate bug — the G-code really did print at a fraction of the
intended speed.  Stating the key brought the same slice to 1h52m, and
the multicolor case from 9h52m to 4h37m.

Once Orca's number was honest, a second bug surfaced: the Bambu wrap
halved every estimate through a factor calibrated on PrusaSlicer's
motion model.  Applied to Orca — Bambu's own fork, which already models
the input shaping the factor compensates for — it reported prints as
taking half as long as they do.
"""

from __future__ import annotations

import json
import os
import re
import struct
import subprocess
import tempfile
from pathlib import Path

import pytest

from kiln.printers.bambu_3mf import (
    _gcode_is_bambu_dialect,
    _reset_cache,
    build_bambu_3mf,
)
from kiln.slicer_orca import (
    ini_to_settings,
    settings_to_orca_presets,
    write_orca_presets,
)
from kiln.slicer_profiles import resolve_slicer_profile

_ORCA = "/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer"

_SETTINGS = {
    "nozzle_diameter": "0.4",
    "layer_height": "0.2",
    "bed_shape": "0x0,256x0,256x256,0x256",
    "temperature": "220",
    "use_relative_e_distances": "1",
}


def _installed(path: str) -> bool:
    return os.path.isfile(path) and os.access(path, os.X_OK)


def _seconds(text: str) -> int:
    total = 0
    for value, unit in re.findall(r"(\d+)([dhms])", text):
        total += int(value) * {"d": 86400, "h": 3600, "m": 60, "s": 1}[unit]
    return total


# ---------------------------------------------------------------------------
# The preset key
# ---------------------------------------------------------------------------


class TestVolumetricSpeedIsStated:
    def test_absent_from_profile_becomes_explicit_zero(self):
        """Zero is PrusaSlicer's own default for these same profiles, so
        stating it makes the two slicers agree rather than inventing a
        material figure Kiln does not have."""
        p = settings_to_orca_presets(_SETTINGS, name="t")
        assert p.filament["filament_max_volumetric_speed"] == ["0"]

    def test_a_profile_value_is_translated(self):
        p = settings_to_orca_presets(
            dict(_SETTINGS, filament_max_volumetric_speed="12"), name="t",
        )
        assert p.filament["filament_max_volumetric_speed"] == ["12"]

    def test_every_multicolor_slot_carries_it(self):
        """Orca cross-checks the per-filament vectors; a slot without the
        limit is a slot back at the 2 mm³/s default."""
        p = settings_to_orca_presets(
            _SETTINGS, name="t",
            filament_colors=["#FF0000", "#00FF00", "#0000FF"],
        )
        assert len(p.filaments) == 3
        for slot in p.filaments:
            assert slot["filament_max_volumetric_speed"] == ["0"]

    def test_it_reaches_the_written_file(self, tmp_path):
        w = write_orca_presets(_SETTINGS, str(tmp_path), name="t")
        body = json.loads(Path(w.filament_path).read_text())
        assert body["filament_max_volumetric_speed"] == ["0"]

    def test_a_real_bundled_profile_carries_it(self):
        settings = ini_to_settings(resolve_slicer_profile("bambu_a1"))
        p = settings_to_orca_presets(settings, name="t")
        assert p.filament["filament_max_volumetric_speed"] == ["0"]


# ---------------------------------------------------------------------------
# The time correction that must not double-apply
# ---------------------------------------------------------------------------


class TestBambuDialectDetection:
    @pytest.mark.parametrize(
        "header",
        [
            "; generated by OrcaSlicer 2.3.2 on 2026-08-27",
            "; generated by BambuStudio 02.06.00.51",
            "; HEADER_BLOCK_START\n; generated by OrcaSlicer 2.3.2",
        ],
    )
    def test_bambu_family_recognised(self, header):
        assert _gcode_is_bambu_dialect(header) is True

    @pytest.mark.parametrize(
        "header",
        [
            "; generated by PrusaSlicer 2.9.4",
            "; generated by SuperSlicer",
            "",
        ],
    )
    def test_everything_else_is_not(self, header):
        assert _gcode_is_bambu_dialect(header) is False

    def test_only_the_head_is_read(self):
        """A body can mention any slicer in a comment; the generator
        stamp is a header line."""
        body = "; generated by PrusaSlicer 2.9.4\n" + ("G1 X1\n" * 2000)
        body += "; sliced again in OrcaSlicer by hand\n"
        assert _gcode_is_bambu_dialect(body) is False


class TestTimeCorrectionAppliesToPrusaOnly:
    _BODY = "\n".join(
        [";BEFORE_LAYER_CHANGE", ";Z:0.2", ";LAYER_CHANGE",
         "G1 Z0.2 F600", "G1 X10 Y10 E0.5"] * 3
    ) + "\n; estimated printing time (normal mode) = 2h 0m 0s\n"

    def _est(self, tmp_path, header: str) -> int:
        _reset_cache()
        try:
            result = build_bambu_3mf(
                header + self._BODY, str(tmp_path / "o.3mf"),
            )
        finally:
            _reset_cache()
        return result.est_print_time_sec

    def test_prusa_estimate_is_still_halved(self, tmp_path):
        """The correction's original job is untouched."""
        est = self._est(tmp_path, "; generated by PrusaSlicer 2.9.4\n")
        assert est < 7200 * 0.75

    def test_orca_estimate_is_left_alone(self, tmp_path):
        """Orca models the input shaping this factor compensates for —
        halving it reports a print as half as long as it is."""
        est = self._est(tmp_path, "; generated by OrcaSlicer 2.3.2\n")
        assert est >= 7200

    def test_unknown_generator_keeps_historical_behaviour(self, tmp_path):
        est = self._est(tmp_path, "; generated by something else\n")
        assert est < 7200 * 0.75


# ---------------------------------------------------------------------------
# The real slicer, because the whole claim is about a subprocess
# ---------------------------------------------------------------------------


def _cube_stl(path: Path, size: float = 30.0) -> str:
    lo, hi = 0.0, size
    v = [
        (lo, lo, 0), (hi, lo, 0), (hi, hi, 0), (lo, hi, 0),
        (lo, lo, size), (hi, lo, size), (hi, hi, size), (lo, hi, size),
    ]
    faces = [
        (0, 3, 2), (0, 2, 1), (4, 5, 6), (4, 6, 7), (0, 1, 5), (0, 5, 4),
        (1, 2, 6), (1, 6, 5), (2, 3, 7), (2, 7, 6), (3, 0, 4), (3, 4, 7),
    ]
    with open(path, "wb") as fh:
        fh.write(b"\0" * 80)
        fh.write(struct.pack("<I", len(faces)))
        for a, b, c in faces:
            fh.write(struct.pack("<3f", 0, 0, 0))
            for i in (a, b, c):
                fh.write(struct.pack("<3f", *v[i]))
            fh.write(struct.pack("<H", 0))
    return str(path)


@pytest.mark.skipif(not _installed(_ORCA), reason="OrcaSlicer not installed")
class TestRealSlicerHonoursTheProfileSpeeds:
    """Slices the same cube twice — as Kiln emits presets, and with the
    flow key stripped back out — and compares what Orca says it costs.

    An A/B in the suite rather than a fixed number: the absolute
    estimate moves with Orca's version and the bundled profile, but
    removing the key must always make the same print markedly slower.
    Measured 2026-08-27 with OrcaSlicer 2.3.2: 47m57s as emitted against
    1h19m02s stripped, a factor of 1.65 (2.14 on the multicolor model
    that started this).  The assertion sits well under that.
    """

    @staticmethod
    def _estimate(model: str, work: str, strip_key: bool) -> int:
        settings = ini_to_settings(resolve_slicer_profile("bambu_a1"))
        presets = write_orca_presets(settings, work, name="probe")
        if strip_key:
            body = json.loads(Path(presets.filament_path).read_text())
            body.pop("filament_max_volumetric_speed", None)
            Path(presets.filament_path).write_text(json.dumps(body))
        subprocess.run(
            [
                _ORCA, "--slice", "0", "--outputdir", work,
                "--load-settings",
                f"{presets.machine_path};{presets.process_path}",
                "--load-filaments", ";".join(presets.filament_paths),
                model,
            ],
            capture_output=True, text=True, timeout=900,
        )
        produced = [f for f in os.listdir(work) if f.endswith(".gcode")]
        assert produced, "OrcaSlicer wrote no G-code"
        text = Path(work, produced[0]).read_text(errors="replace")
        match = re.search(
            r"^; estimated printing time \(normal mode\) = (.+)$",
            text, re.MULTILINE,
        )
        assert match, "no time estimate in the G-code"
        return _seconds(match.group(1))

    def test_stating_the_flow_limit_makes_the_print_faster(self, tmp_path):
        model = _cube_stl(tmp_path / "cube.stl")
        with tempfile.TemporaryDirectory() as a, tempfile.TemporaryDirectory() as b:
            emitted = self._estimate(model, a, strip_key=False)
            stripped = self._estimate(model, b, strip_key=True)
        assert stripped > emitted * 1.25, (
            f"stripping filament_max_volumetric_speed changed the estimate "
            f"from {emitted}s to {stripped}s — the clamp is not being lifted"
        )
