"""Slicer-added geometry — what prints that the model never contained.

The stage draws the model; the printer prints the model plus a skirt, a
brim, a prime tower, supports.  Measured 2026-09-03 on a Bambu Lab A1: a
three-colour jar's first layer carried a 157 mm skirt loop and a 30 mm prime
tower that had never appeared on any stage.  This file pins the engine that
reads them out of the slice:

* every slicer dialect Kiln drives lands in the right class by keyword —
  PrusaSlicer, SuperSlicer, OrcaSlicer, Bambu Studio, Cura, Simplify3D —
  and an unknown label is the PART, never an extra;
* a segment is an extrusion while moving.  A ``G1 E0.8`` unretract at a
  travel destination is not a toolpath: on the jar those alone pushed the
  "outer wall" footprint 35 mm into the tower and would have mis-aligned
  everything;
* the join to the mesh is the model's own footprint, and it is CHECKED —
  a slice of a different or rescaled part is refused with a reason rather
  than drawn around the wrong object;
* the budget samples layers, never silently drops a class, and says so;
* the viewer-frame rotation and the plate-centring shift are the same
  rules the payload's positions follow.
"""

from __future__ import annotations

import base64
import math

import numpy as np
import pytest

from kiln import slicer_geometry as sg


def _segments(feature: dict) -> np.ndarray:
    return np.frombuffer(base64.b64decode(feature["segments"]), dtype="<f4").reshape(-1, 6)


def _square_loop(x0: float, y0: float, x1: float, y1: float, z: float, e_step: float = 0.1) -> str:
    """One closed rectangular extrusion loop, relative E."""
    return (
        f"G1 X{x0} Y{y0} Z{z} F6000\n"
        f"G1 X{x1} Y{y0} E{e_step}\n"
        f"G1 X{x1} Y{y1} E{e_step}\n"
        f"G1 X{x0} Y{y1} E{e_step}\n"
        f"G1 X{x0} Y{y0} E{e_step}\n"
    )


def _orca_job(
    *, layers: int = 3, tower: bool = True, support: bool = False, skirt: bool = True,
) -> str:
    """A tiny OrcaSlicer-flavoured file: a 40 x 30 part placed at bed
    (100..140, 100..130), a skirt 2 mm out on layer 1, a 10 mm tower to
    the right on every layer, optional supports."""
    out = ["; generated by OrcaSlicer 2.3.2 on 2026-09-03 at 12:37:11", "G90", "M83", "G28"]
    for i in range(layers):
        z = 0.2 * (i + 1)
        out.append(";LAYER_CHANGE")
        out.append(f";Z:{z}")
        if i == 0 and skirt:
            out.append(";TYPE:Skirt")
            out.append(_square_loop(98, 98, 142, 132, z))
        # The unretract-at-destination pattern every slicer emits before a
        # feature change: a travel, then E-only, still under the OLD type.
        out.append(";TYPE:Outer wall")
        out.append(_square_loop(100, 100, 140, 130, z))
        out.append(";TYPE:Inner wall")
        out.append(_square_loop(101, 101, 139, 129, z))
        if tower:
            out.append("G1 E-.8 F1800")
            out.append(f"G1 X160 Y100 Z{z + 0.2}")   # travel to the tower...
            out.append(f"G1 Z{z}")
            out.append("G1 E.8 F1800")                # ...unretract, type still 'Inner wall'
            out.append(";TYPE:Prime tower")
            out.append(_square_loop(160, 100, 170, 110, z))
            out.append("G1 X165 Y105 E0.05")          # a purge stroke inside it
        if support:
            out.append(";TYPE:Support")
            out.append(_square_loop(120, 140, 130, 150, z))
    return "\n".join(out) + "\n"


# ===========================================================================
# 1. Classification — every dialect, by keyword
# ===========================================================================


class TestClassification:
    @pytest.mark.parametrize(
        ("label", "cls"),
        [
            # PrusaSlicer / SuperSlicer
            ("Skirt/Brim", "skirt"),
            ("Skirt", "skirt"),
            ("Brim", "brim"),
            ("Wipe tower", "prime_tower"),
            ("Support material", "support"),
            ("Support material interface", "support_interface"),
            # OrcaSlicer / Bambu Studio
            ("Prime tower", "prime_tower"),
            ("Support", "support"),
            ("Support interface", "support_interface"),
            ("Support transition", "support"),
            # Cura
            ("SKIRT", "skirt"),
            ("PRIME-TOWER", "prime_tower"),
            ("SUPPORT", "support"),
            ("SUPPORT-INTERFACE", "support_interface"),
            # Simplify3D
            ("skirt", "skirt"),
            ("prime pillar", "prime_tower"),
            ("raft", "raft"),
            ("ooze shield", "shield"),
            ("support", "support"),
        ],
    )
    def test_every_slicer_dialect_lands_in_its_class(self, label, cls):
        assert sg.classify_feature(label) == cls

    @pytest.mark.parametrize(
        "label",
        ["External perimeter", "Outer wall", "WALL-OUTER", "Sparse infill",
         "Top solid infill", "Bridge infill", "outer perimeter", "Ironing",
         "Something Nobody Has Seen"],
    )
    def test_part_features_and_unknown_labels_are_the_model(self, label):
        """The conservative reading: hiding real part geometry under an
        extras toggle would be worse than showing an extra as part."""
        assert sg.classify_feature(label) == "model"

    def test_the_contact_layer_is_its_own_class_and_plain_support_is_not(self):
        """The interface — the layer that touches the part, where it will
        scar — is drawn apart from the lattice under it, on every slicer's
        spelling.  A support with no such word stays a support."""
        assert sg.classify_feature("Support interface") == "support_interface"
        assert sg.classify_feature("Support material interface") == "support_interface"
        assert sg.classify_feature("SUPPORT-INTERFACE") == "support_interface"
        assert sg.classify_feature("Support transition") == "support"
        assert sg.classify_feature("Support material") == "support"
        assert "support_interface" in sg.EXTRA_CLASSES
        assert sg.SCAFFOLD_CLASSES == ("support", "support_interface", "raft", "shield")

    def test_start_gcode_blocks_are_neither(self):
        """A purge line at the bed edge is the printer's start G-code,
        not a slicer feature — it must not widen the model footprint."""
        assert sg.classify_feature("Custom") == "ignore"

    def test_no_label_at_all_reads_as_model(self):
        assert sg.classify_feature(None) == "model"
        assert sg.classify_feature("") == "model"


# ===========================================================================
# 2. Parsing — segments are extrusions while moving
# ===========================================================================


class TestParsing:
    def test_reads_orca_labels_skirt_and_tower(self, tmp_path):
        g = tmp_path / "job.gcode"
        g.write_text(_orca_job(layers=2))
        parsed = sg.parse_slicer_features(g)
        assert parsed.slicer == "OrcaSlicer 2.3.2"
        assert parsed.labelled
        assert set(parsed.buckets) == {"skirt", "prime_tower"}
        assert parsed.buckets["skirt"].count == 4
        assert parsed.buckets["skirt"].z_min == parsed.buckets["skirt"].z_max == pytest.approx(0.2)
        # 4 loop sides + 1 purge stroke, on both layers
        assert parsed.buckets["prime_tower"].count == 10
        assert len(set(parsed.buckets["prime_tower"].layers)) == 2

    def test_the_unretract_at_a_travel_destination_is_not_a_toolpath(self, tmp_path):
        """The regression, named: ``G1 E.8`` at (160, 100) under 'Inner
        wall' used to drag the model footprint into the tower."""
        g = tmp_path / "job.gcode"
        g.write_text(_orca_job(layers=1))
        parsed = sg.parse_slicer_features(g)
        x0, y0, x1, y1 = parsed.model_footprint
        assert (x0, y0, x1, y1) == pytest.approx((100.0, 100.0, 140.0, 130.0))

    def test_travels_and_z_only_moves_never_become_segments(self, tmp_path):
        g = tmp_path / "job.gcode"
        g.write_text(
            "G90\nM83\n;LAYER_CHANGE\n;TYPE:Skirt\n"
            "G1 X10 Y10 Z0.2 F3000\n"   # travel
            "G1 Z0.6\n"                  # lift
            "G1 E-0.8\n"                 # retract in place
            "G1 X20 Y10 E0.1\n"          # the one real segment
        )
        parsed = sg.parse_slicer_features(g)
        assert parsed.buckets["skirt"].count == 1

    def test_absolute_extrusion_and_g92_resets(self, tmp_path):
        """Cura-style M82 with periodic G92 E0 — the delta is what counts."""
        g = tmp_path / "cura.gcode"
        g.write_text(
            ";Generated with Cura_SteamEngine 5.8.0\nG90\nM82\n;LAYER:0\n;TYPE:SKIRT\n"
            "G1 X0 Y0 Z0.2\nG1 X10 Y0 E1.0\nG92 E0\nG1 X10 Y10 E1.0\n"
            "G1 X10 Y10 E0.2\n"          # unretract, no motion — not a segment
            ";TYPE:WALL-OUTER\nG1 X20 Y20 E2\n"
        )
        parsed = sg.parse_slicer_features(g)
        assert parsed.slicer.startswith("Cura_SteamEngine")
        assert parsed.buckets["skirt"].count == 2
        assert parsed.model_footprint == pytest.approx((10.0, 10.0, 20.0, 20.0))

    def test_simplify3d_feature_comments(self, tmp_path):
        g = tmp_path / "s3d.gcode"
        g.write_text(
            "; G-Code generated by Simplify3D(R) Version 5.1.2\nG90\nM82\n"
            "; layer 1, Z = 0.200\n; feature skirt\nG1 X0 Y0 Z0.2\nG1 X5 Y0 E0.5\n"
            "; feature prime pillar\nG1 X30 Y30\nG1 X35 Y30 E1.0\n"
            "; feature outer perimeter\nG1 X10 Y10\nG1 X20 Y10 E1.5\n"
        )
        parsed = sg.parse_slicer_features(g)
        assert set(parsed.buckets) == {"skirt", "prime_tower"}
        assert parsed.labels == {
            "skirt": "skirt", "prime pillar": "prime_tower", "outer perimeter": "model",
        }

    def test_prusa_wipe_tower_and_support_material(self, tmp_path):
        g = tmp_path / "prusa.gcode"
        g.write_text(
            "; generated by PrusaSlicer 2.9.4 on 2026-09-03 at 21:50:01 UTC\nG90\nM83\n"
            ";LAYER_CHANGE\n;Z:0.2\n;TYPE:Skirt/Brim\nG1 X0 Y0 Z0.2\nG1 X5 Y0 E0.5\n"
            ";TYPE:Wipe tower\nG1 X40 Y40\nG1 X45 Y40 E0.5\n"
            ";TYPE:Support material\nG1 X10 Y30\nG1 X12 Y30 E0.1\n"
            ";TYPE:External perimeter\nG1 X10 Y10\nG1 X20 Y10 E1\nG1 X20 Y20 E1\n"
        )
        parsed = sg.parse_slicer_features(g)
        assert parsed.slicer == "PrusaSlicer 2.9.4"
        assert set(parsed.buckets) == {"skirt", "prime_tower", "support"}
        assert parsed.buckets["skirt"].label == "Skirt/Brim", "the joint label is kept as written"

    def test_arcs_are_expanded_to_chords(self, tmp_path):
        """A skirt fitted with G2/G3 stays a loop, not a chord across it."""
        g = tmp_path / "arc.gcode"
        g.write_text(
            "G90\nM83\n;LAYER_CHANGE\n;TYPE:Skirt\n"
            "G1 X10 Y0 Z0.2\n"
            "G3 X0 Y10 I-10 J0 E1.0\n"   # quarter circle, CCW, radius 10
        )
        parsed = sg.parse_slicer_features(g)
        seg = np.asarray(parsed.buckets["skirt"].segments).reshape(-1, 6)
        assert len(seg) >= 8
        radii = np.hypot(seg[:, 0], seg[:, 1])
        assert np.allclose(radii, 10.0, atol=1e-6)
        assert seg[0, :2] == pytest.approx((10.0, 0.0))
        assert seg[-1, 3:5] == pytest.approx((0.0, 10.0))

    def test_layers_are_inferred_from_z_when_a_file_has_no_markers(self, tmp_path):
        g = tmp_path / "bare.gcode"
        g.write_text(
            "G90\nM83\n;TYPE:Support\n"
            "G1 X0 Y0 Z0.2\nG1 X5 Y0 E0.1\n"
            "G1 X0 Y0 Z0.4\nG1 X5 Y0 E0.1\n"
            "G1 X0 Y0 Z0.6\nG1 X5 Y0 E0.1\n"
        )
        parsed = sg.parse_slicer_features(g)
        assert len(set(parsed.buckets["support"].layers)) == 3

    def test_prusaslicers_before_and_after_markers_do_not_double_count_layers(self, tmp_path):
        """PrusaSlicer brackets each change with ;BEFORE_LAYER_CHANGE and
        ;AFTER_LAYER_CHANGE around the ;LAYER_CHANGE itself — one layer."""
        g = tmp_path / "prusa.gcode"
        g.write_text(
            "G90\nM83\n"
            ";LAYER_CHANGE\n;Z:0.2\n;BEFORE_LAYER_CHANGE\nG1 Z0.2\n;AFTER_LAYER_CHANGE\n;0.2\n"
            ";TYPE:Support material\nG1 X0 Y0\nG1 X5 Y0 E0.1\n"
            ";LAYER_CHANGE\n;Z:0.4\n;BEFORE_LAYER_CHANGE\nG1 Z0.4\n;AFTER_LAYER_CHANGE\n;0.4\n"
            ";TYPE:Support material\nG1 X0 Y0\nG1 X5 Y0 E0.1\n"
        )
        parsed = sg.parse_slicer_features(g)
        assert sorted(set(parsed.buckets["support"].layers)) == [1, 2]

    def test_a_missing_file_raises(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            sg.parse_slicer_features(tmp_path / "nope.gcode")


# ===========================================================================
# 2b. Filaments and tools — the colour a segment really prints in
# ===========================================================================


def _u16(b64: str) -> np.ndarray:
    return np.frombuffer(base64.b64decode(b64), dtype="<u2")


def _u8(b64: str) -> np.ndarray:
    return np.frombuffer(base64.b64decode(b64), dtype="u1")


class TestFilamentsAndTools:
    def test_the_slicers_filament_colours_are_read_from_the_config_block(self, tmp_path):
        """Orca / Bambu / Prusa write ``filament_colour`` at the END of the
        file, one entry per tool — so the whole file is scanned."""
        g = tmp_path / "job.gcode"
        g.write_text(_orca_job(layers=1) + "; CONFIG_BLOCK_START\n; filament_colour = #FFFFFF;#C81E1E;#161616\n")
        parsed = sg.parse_slicer_features(g)
        assert parsed.filament_colors == ["#FFFFFF", "#C81E1E", "#161616"]
        block = sg.slicer_features_block(g, (0.0, 0.0, 0.0), (40.0, 30.0, 10.0))
        assert block["filaments"] == ["#FFFFFF", "#C81E1E", "#161616"]

    def test_a_file_that_names_no_colours_names_none(self, tmp_path):
        g = tmp_path / "job.gcode"
        g.write_text(_orca_job(layers=1))
        assert sg.parse_slicer_features(g).filament_colors == []

    def test_a_colour_list_with_junk_is_dropped_whole_never_guessed(self, tmp_path):
        g = tmp_path / "job.gcode"
        g.write_text(_orca_job(layers=1) + "; filament_colour = #FFFFFF;;#161616\n")
        assert sg.parse_slicer_features(g).filament_colors == []
        g.write_text(_orca_job(layers=1) + "; filament_colour = white;red\n")
        assert sg.parse_slicer_features(g).filament_colors == []

    def test_every_segment_carries_the_tool_that_laid_it(self, tmp_path):
        g = tmp_path / "job.gcode"
        g.write_text(
            "; generated by OrcaSlicer 2.3.2\nG90\nM83\n;LAYER_CHANGE\n;Z:0.2\n"
            ";TYPE:Skirt\n" + _square_loop(98, 98, 142, 132, 0.2) +
            ";TYPE:Outer wall\n" + _square_loop(100, 100, 140, 130, 0.2) +
            "T1\n;TYPE:Prime tower\n" + _square_loop(160, 100, 170, 110, 0.2) +
            "T2\nG1 X165 Y105 E0.05\n"
        )
        block = sg.slicer_features_block(g, (0.0, 0.0, 0.0), (40.0, 30.0, 10.0))
        by = {f["class"]: f for f in block["features"]}
        assert _u8(by["skirt"]["tool_index"]).tolist() == [0, 0, 0, 0]
        tower = by["prime_tower"]
        assert _u8(tower["tool_index"]).tolist() == [1, 1, 1, 1, 2]
        assert len(_u16(tower["layer_index"])) == tower["count"]
        assert _u16(tower["layer_index"]).tolist() == [1] * 5

    def test_each_class_carries_the_width_the_slicer_drew_it_at(self, tmp_path):
        """``;WIDTH:`` precedes the paths it applies to; a class reports the
        width most of its segments were laid at, and a file with none
        reports the common default rather than nothing."""
        g = tmp_path / "job.gcode"
        g.write_text(
            "; generated by OrcaSlicer 2.3.2\nG90\nM83\n;LAYER_CHANGE\n;Z:0.2\n"
            ";TYPE:Skirt\n;WIDTH:0.5\n" + _square_loop(98, 98, 142, 132, 0.2) +
            ";TYPE:Outer wall\n;WIDTH:0.42\n" + _square_loop(100, 100, 140, 130, 0.2) +
            ";TYPE:Prime tower\n;WIDTH:0.6\n" + _square_loop(160, 100, 170, 110, 0.2) +
            ";WIDTH:0.5\nG1 X165 Y105 E0.05\n"
        )
        block = sg.slicer_features_block(g, (0.0, 0.0, 0.0), (40.0, 30.0, 10.0))
        by = {f["class"]: f for f in block["features"]}
        assert by["skirt"]["line_width_mm"] == 0.5
        assert by["prime_tower"]["line_width_mm"] == 0.6   # 4 segments at 0.6, 1 at 0.5
        bare = tmp_path / "bare.gcode"
        bare.write_text(_orca_job(layers=1))
        block = sg.slicer_features_block(bare, (0.0, 0.0, 0.0), (40.0, 30.0, 10.0))
        assert all(f["line_width_mm"] == sg.DEFAULT_LINE_WIDTH_MM for f in block["features"])

    def test_prusaslicers_joint_label_is_kept_as_written(self, tmp_path):
        """One label for both loops — calling it "Skirt" would hide the brim."""
        g = tmp_path / "prusa.gcode"
        g.write_text(
            "; generated by PrusaSlicer 2.9.4\nG90\nM83\n;LAYER_CHANGE\n;Z:0.2\n"
            ";TYPE:Skirt/Brim\n" + _square_loop(98, 98, 142, 132, 0.2) +
            ";TYPE:External perimeter\n" + _square_loop(100, 100, 140, 130, 0.2)
        )
        block = sg.slicer_features_block(g, (0.0, 0.0, 0.0), (40.0, 30.0, 10.0))
        assert block["features"][0]["class"] == "skirt"
        assert block["features"][0]["label"] == "Skirt/Brim"

    def test_layer_index_survives_the_budget_sampling(self, tmp_path):
        g = tmp_path / "tall.gcode"
        g.write_text(_orca_job(layers=40))
        tight = sg.slicer_features_block(
            g, (0.0, 0.0, 0.0), (40.0, 30.0, 10.0), max_segments=60,
        )
        for f in tight["features"]:
            assert len(_u16(f["layer_index"])) == f["count"]
            assert len(_u8(f["tool_index"])) == f["count"]
            assert len(set(_u16(f["layer_index"]).tolist())) == f["layers"]


# ===========================================================================
# 3. Alignment — the model's own footprint, checked before believed
# ===========================================================================


class TestAlignment:
    def test_footprint_centre_maps_to_the_mesh_centre_and_floor(self, tmp_path):
        g = tmp_path / "job.gcode"
        g.write_text(_orca_job(layers=1))
        parsed = sg.parse_slicer_features(g)
        # The same 40 x 30 part, in ITS file at the origin corner, floating 5 up.
        offset, reason = sg.align_to_mesh(parsed, (0.0, 0.0, 5.0), (40.0, 30.0, 25.0))
        assert reason is None
        assert offset == pytest.approx((-100.0, -100.0, 5.0))

    def test_a_slice_of_a_different_part_is_refused_with_a_reason(self, tmp_path):
        g = tmp_path / "job.gcode"
        g.write_text(_orca_job(layers=1))
        parsed = sg.parse_slicer_features(g)
        offset, reason = sg.align_to_mesh(parsed, (0.0, 0.0, 0.0), (80.0, 60.0, 20.0))
        assert offset is None
        assert "does not match" in reason
        assert "40.0 × 30.0" in reason and "80.0 × 60.0" in reason

    def test_half_a_line_width_of_shrink_is_within_tolerance(self, tmp_path):
        """An extrusion centreline sits inside the surface; the toolpath
        box is always a hair smaller than the mesh.  Measured on the jar:
        114.5 mm mesh, 113.9 mm footprint."""
        g = tmp_path / "job.gcode"
        g.write_text(_orca_job(layers=1))
        parsed = sg.parse_slicer_features(g)
        offset, reason = sg.align_to_mesh(parsed, (0.0, 0.0, 0.0), (40.45, 30.45, 20.0))
        assert reason is None and offset is not None

    def test_an_unlabelled_file_is_refused_rather_than_guessed(self, tmp_path):
        g = tmp_path / "old.gcode"
        g.write_text("G90\nM83\nG1 X0 Y0 Z0.2\nG1 X10 Y0 E1\nG1 X10 Y10 E1\n")
        parsed = sg.parse_slicer_features(g)
        offset, reason = sg.align_to_mesh(parsed, (0.0, 0.0, 0.0), (10.0, 10.0, 1.0))
        assert offset is None
        assert "no feature labels" in reason

    def test_a_file_with_only_extras_has_no_footprint_to_align(self, tmp_path):
        g = tmp_path / "skirt_only.gcode"
        g.write_text("G90\nM83\n;TYPE:Skirt\nG1 X0 Y0 Z0.2\nG1 X10 Y0 E1\n")
        parsed = sg.parse_slicer_features(g)
        offset, reason = sg.align_to_mesh(parsed, (0.0, 0.0, 0.0), (10.0, 10.0, 1.0))
        assert offset is None
        assert "no model toolpaths" in reason


# ===========================================================================
# 4. The block
# ===========================================================================


class TestBlock:
    def test_features_land_in_the_mesh_frame_beside_the_part(self, tmp_path):
        g = tmp_path / "job.gcode"
        g.write_text(_orca_job(layers=2, support=True))
        block = sg.slicer_features_block(g, (0.0, 0.0, 0.0), (40.0, 30.0, 10.0))
        assert block["kind"] == sg.FEATURE_KIND
        assert block["available"] is True
        assert block["frame"] == "mesh"
        assert block["offset_mm"] == pytest.approx([-100.0, -100.0, 0.0])
        classes = [f["class"] for f in block["features"]]
        assert classes == ["skirt", "prime_tower", "support"], "plate first, then beside and under"
        skirt = next(f for f in block["features"] if f["class"] == "skirt")
        assert skirt["bounds"]["min"][:2] == pytest.approx([-2.0, -2.0])
        assert skirt["bounds"]["max"][:2] == pytest.approx([42.0, 32.0])
        assert skirt["label"] == "Skirt" and skirt["layers"] == 1
        tower = next(f for f in block["features"] if f["class"] == "prime_tower")
        assert tower["bounds"]["min"][:2] == pytest.approx([60.0, 0.0])
        assert tower["bounds"]["max"][:2] == pytest.approx([70.0, 10.0])
        assert tower["layers"] == 2
        assert block["model_footprint"] == {"min": [0.0, 0.0], "max": [40.0, 30.0]}
        assert block["source"]["filename"] == "job.gcode"
        assert "/" not in block["source"]["filename"]
        assert block["source"]["labels"]["Prime tower"] == "prime_tower"
        assert block["segments_total"] == sum(f["count"] for f in block["features"])
        assert block["sampled_layer_stride"] == 1
        assert block["truncated"] is False

    def test_segments_decode_to_the_declared_count(self, tmp_path):
        g = tmp_path / "job.gcode"
        g.write_text(_orca_job(layers=1))
        block = sg.slicer_features_block(g, (0.0, 0.0, 0.0), (40.0, 30.0, 10.0))
        for f in block["features"]:
            assert len(_segments(f)) == f["count"]

    def test_a_single_colour_job_carries_its_skirt_only(self, tmp_path):
        g = tmp_path / "one.gcode"
        g.write_text(_orca_job(layers=2, tower=False))
        block = sg.slicer_features_block(g, (0.0, 0.0, 0.0), (40.0, 30.0, 10.0))
        assert [f["class"] for f in block["features"]] == ["skirt"]

    def test_a_mismatched_slice_is_an_honest_unavailable_block(self, tmp_path):
        g = tmp_path / "job.gcode"
        g.write_text(_orca_job(layers=1))
        block = sg.slicer_features_block(g, (0.0, 0.0, 0.0), (400.0, 300.0, 10.0))
        assert block["available"] is False
        assert "does not match" in block["reason"]
        assert block["source"]["filename"] == "job.gcode"
        assert "features" not in block

    def test_a_vanished_file_is_unavailable_not_an_exception(self, tmp_path):
        block = sg.slicer_features_block(tmp_path / "gone.gcode", (0, 0, 0), (1, 1, 1))
        assert block["available"] is False
        assert "no longer on disk" in block["reason"]

    def test_the_budget_samples_layers_and_says_so(self, tmp_path):
        g = tmp_path / "tall.gcode"
        g.write_text(_orca_job(layers=40, skirt=True))
        full = sg.slicer_features_block(g, (0.0, 0.0, 0.0), (40.0, 30.0, 10.0))
        tight = sg.slicer_features_block(
            g, (0.0, 0.0, 0.0), (40.0, 30.0, 10.0), max_segments=60,
        )
        assert full["sampled_layer_stride"] == 1
        assert tight["sampled_layer_stride"] > 1
        assert tight["segments_total"] <= 60 < full["segments_total"]
        # The plate story always survives: the skirt is on layer one.
        assert [f["class"] for f in tight["features"]] == ["skirt", "prime_tower"]
        tower = next(f for f in tight["features"] if f["class"] == "prime_tower")
        assert tower["layers"] < 40
        assert tower["z_min"] == pytest.approx(0.2), "the first layer is never sampled away"


# ===========================================================================
# 5. Frames — the payload's own rotation and shift
# ===========================================================================


class TestFrames:
    def _block(self, tmp_path):
        g = tmp_path / "job.gcode"
        g.write_text(_orca_job(layers=1))
        return sg.slicer_features_block(g, (0.0, 0.0, 0.0), (40.0, 30.0, 10.0))

    def test_viewer_frame_is_the_payload_rotation(self, tmp_path):
        """``(x, y, z)_mesh → (x, z, -y)_viewer`` — the rule mesh_payload
        bakes into positions, applied to every segment and its bounds."""
        mesh = self._block(tmp_path)
        viewer = sg.to_viewer_frame(mesh)
        assert viewer["frame"] == "viewer"
        assert mesh["frame"] == "mesh", "conversion returns a copy"
        for fm, fv in zip(mesh["features"], viewer["features"], strict=True):
            a, b = _segments(fm), _segments(fv)
            assert np.allclose(b[:, 0], a[:, 0])
            assert np.allclose(b[:, 1], a[:, 2])
            assert np.allclose(b[:, 2], -a[:, 1])
            assert np.allclose(b[:, 3], a[:, 3])
            assert np.allclose(b[:, 4], a[:, 5])
            assert np.allclose(b[:, 5], -a[:, 4])
            lo, hi = fm["bounds"]["min"], fm["bounds"]["max"]
            assert fv["bounds"]["min"] == pytest.approx([lo[0], lo[2], -hi[1]])
            assert fv["bounds"]["max"] == pytest.approx([hi[0], hi[2], -lo[1]])
        # The footprint names the plate axes and stays in mesh XY.
        assert viewer["model_footprint"] == mesh["model_footprint"]

    def test_converting_twice_is_a_no_op(self, tmp_path):
        viewer = sg.to_viewer_frame(self._block(tmp_path))
        assert sg.to_viewer_frame(viewer) is viewer

    def test_shift_moves_mesh_frame_geometry_and_its_bounds(self, tmp_path):
        block = self._block(tmp_path)
        before = {f["class"]: _segments(f).copy() for f in block["features"]}
        sg.shift_block(block, 7.0, -3.0)
        for f in block["features"]:
            a = before[f["class"]]
            b = _segments(f)
            assert np.allclose(b[:, [0, 3]], a[:, [0, 3]] + 7.0)
            assert np.allclose(b[:, [1, 4]], a[:, [1, 4]] - 3.0)
            assert np.allclose(b[:, [2, 5]], a[:, [2, 5]])
        skirt = next(f for f in block["features"] if f["class"] == "skirt")
        assert skirt["bounds"]["min"][:2] == pytest.approx([5.0, -5.0])
        assert block["model_footprint"]["min"] == pytest.approx([7.0, -3.0])
        assert block["offset_mm"][:2] == pytest.approx([-93.0, -103.0])

    def test_shift_in_the_viewer_frame_moves_z_the_way_positions_move(self, tmp_path):
        """Mesh +y is viewer −z — the exact line stand_on_plate applies."""
        block = sg.to_viewer_frame(self._block(tmp_path))
        before = {f["class"]: _segments(f).copy() for f in block["features"]}
        sg.shift_block(block, 7.0, -3.0)
        for f in block["features"]:
            a = before[f["class"]]
            b = _segments(f)
            assert np.allclose(b[:, [0, 3]], a[:, [0, 3]] + 7.0)
            assert np.allclose(b[:, [1, 4]], a[:, [1, 4]])
            assert np.allclose(b[:, [2, 5]], a[:, [2, 5]] + 3.0)

    def test_an_unavailable_block_passes_through_both(self):
        block = sg.unavailable_block("nothing here")
        assert sg.to_viewer_frame(block) is block
        assert sg.shift_block(block, 1.0, 1.0) is block


# ===========================================================================
# 6. Sidecar round trip
# ===========================================================================


class TestSidecar:
    def test_load_accepts_only_the_contract(self):
        assert sg.load_sidecar(b"not json") is None
        assert sg.load_sidecar(b'{"kind": "something.else"}') is None
        assert sg.load_sidecar(None) is None
        ok = sg.load_sidecar(b'{"kind": "kiln.slicer_features.v1", "available": false}')
        assert ok == {"kind": sg.FEATURE_KIND, "available": False}

    def test_arc_helper_degrades_an_r_form_arc_to_its_chord(self):
        pts = sg._arc_points(0, 0, 0, 10, 0, 0, None, None, 5.0, clockwise=True)
        assert pts == [(0, 0, 0), (10, 0, 0)]

    def test_arc_helper_walks_a_full_circle(self):
        pts = sg._arc_points(10, 0, 0, 10, 0, 0, -10.0, 0.0, None, clockwise=False)
        assert len(pts) > 30
        assert all(math.isclose(math.hypot(x, y), 10.0, abs_tol=1e-9) for x, y, _ in pts)


class TestRaftAndCost:
    def _raft_job(self) -> str:
        """Two raft layers labelled as every slicer labels them — Support —
        under a part whose first layer stands at 0.8 mm, then a support
        column beside the part from that layer up."""
        out = ["; generated by OrcaSlicer 2.3.2", "G90", "M83", "G28"]
        for z in (0.2, 0.4):
            out += [";LAYER_CHANGE", f";Z:{z}", ";TYPE:Support", ";WIDTH:0.5", _square_loop(95, 95, 145, 135, z)]
        out += [";LAYER_CHANGE", ";Z:0.4", ";TYPE:Support interface", ";WIDTH:0.5", _square_loop(96, 96, 144, 134, 0.4)]
        for z in (0.8, 1.0):
            out += [";LAYER_CHANGE", f";Z:{z}", ";TYPE:Outer wall", ";WIDTH:0.42", _square_loop(100, 100, 140, 130, z)]
            out += [";TYPE:Support", ";WIDTH:0.42", _square_loop(150, 100, 156, 106, z)]
        return "\n".join(out) + "\n"

    def test_support_under_the_parts_first_layer_is_the_raft(self, tmp_path):
        """Orca, Bambu Studio and PrusaSlicer label raft layers as support;
        the height says what the label cannot.  Support at the part's own
        first layer and above stays support."""
        g = tmp_path / "raft.gcode"
        g.write_text(self._raft_job())
        parsed = sg.parse_slicer_features(g)
        assert parsed.model_z_min == pytest.approx(0.8)
        assert set(parsed.buckets) == {"raft", "support"}
        raft, support = parsed.buckets["raft"], parsed.buckets["support"]
        assert raft.count == 12                      # 3 loops × 4 sides, both classes under the floor
        assert raft.z_max == pytest.approx(0.4)
        assert raft.label == "Raft"
        assert support.count == 8                    # 2 loops × 4 sides beside the part
        assert support.z_min == pytest.approx(0.8)
        block = sg.slicer_features_block(g, (100, 100, 0), (140, 130, 1))
        assert [f["class"] for f in block["features"]] == ["raft", "support"]

    def test_a_job_without_a_raft_moves_nothing(self, tmp_path):
        g = tmp_path / "job.gcode"
        g.write_text(_orca_job(layers=3, support=True))
        parsed = sg.parse_slicer_features(g)
        assert "raft" not in parsed.buckets
        assert "support" in parsed.buckets

    def test_every_entry_says_what_it_costs(self, tmp_path):
        """Path length and a grams estimate at the file's own width and
        layer height, the way the slicer's legend gives them — a person
        deciding whether to keep supports wants the number."""
        g = tmp_path / "raft.gcode"
        g.write_text(self._raft_job())
        block = sg.slicer_features_block(g, (100, 100, 0), (140, 130, 1))
        by = {f["class"]: f for f in block["features"]}
        # raft: two 50×40 loops (180 mm each) + one 48×38 loop (172 mm)
        assert by["raft"]["length_mm"] == pytest.approx(532, abs=0.5)
        # at 0.5 mm wide, 0.2 mm layers, 1.24 g/cm³: 532 × 0.5 × 0.2 × 1.24 / 1000
        assert by["raft"]["filament_g_est"] == pytest.approx(0.066, abs=0.005)
        assert by["support"]["length_mm"] == pytest.approx(48, abs=0.5)
        assert by["support"]["filament_g_est"] > 0
