"""Hardware stops: the plan in the job file, told to the person while the print runs.

kiln-pro writes one plan line into a job that takes a nut, a magnet or a
bearing during a pause; this half reads it back when the print starts and
answers every door that reads the printer.  Pinned here: where the line goes
and that it reads back, each moment a print passes through (a stop ahead, a
stop close, the stop itself, a stop gone past, the finished print), the resume
that waits for the person's word, and the doors that carry all of it --
the start template and gate that file the plan, printer_status, the monitor
report, the wait tool, the watcher, resume_print and the CLI.
"""

from __future__ import annotations

import time
import zipfile
from unittest.mock import patch

import pytest

from kiln import hardware_stops as hs
from kiln.printers.base import (
    HardwareStopRefusal,
    JobProgress,
    JobResult,
    PrinterAdapter,
    PrinterState,
    PrinterStatus,
    PrintResult,
)

PLAN = {
    "v": 1,
    "firmware": "bambu",
    "stop_word": "M400 U1",
    "layers": 50,
    "total_min": 40.0,
    "stops": [
        {"n": 1, "before_layer": 29, "z": 5.8, "insert": "2x M3 nut in S1, S2", "minutes_in": 24,
         "steps": ["Clear any loose strands or support from the cavity.", "Put in: 2x M3 nut in S1, S2.",
                   "Check each piece is level with or below the top of the print; press nothing hard."],
         "magnets": False},
        {"n": 2, "before_layer": 41, "z": 8.2, "insert": "4x 6x3 magnet in S3, S4, S5, S6", "minutes_in": 33,
         "steps": ["Put in: 4x 6x3 magnet in S3, S4, S5, S6."], "magnets": True},
    ],
    "after_print": [
        {"item": "4x M3 heat-set insert", "spoken": "the 4 M3 heat-set inserts", "kind": "heat_set_insert",
         "seats": ["S7", "S8", "S9", "S10"], "safety": ["The insert iron burns on contact."],
         "where": ["S7: 4.0 mm round pocket open at the top"],
         "when": "After the print, once the part is cool and any supports are off.",
         "next_calls": [{"tool": "recommend_heat_set_insert", "arguments": {"thread": "M3"}}]},
    ],
    "safety": ["A paused printer is a hot, unattended machine. Stay with it while it waits."],
}

JOB = "bracket-hardware-stops.gcode"


class _Machine(PrinterAdapter):
    """A printer whose state each test sets, and which counts the resumes it is sent."""

    _RESUME_VERIFY_TIMEOUT = 0.0
    _RESUME_VERIFY_INTERVAL = 0.0

    def __init__(self) -> None:
        self.status = PrinterStatus.PRINTING
        self.layer: int | None = None
        self.completion: float | None = None
        self.left_s: int | None = None
        self.file = JOB
        self.ended: JobResult | None = None
        self.resumed = 0

    @property
    def name(self) -> str:
        return "bench"

    def get_state(self) -> PrinterState:
        return PrinterState(connected=True, state=self.status)

    def get_job(self) -> JobProgress:
        return JobProgress(file_name=self.file, completion=self.completion, print_time_left_seconds=self.left_s,
                           current_layer=self.layer, ended_as=self.ended)

    def _resume_print_impl(self) -> PrintResult:
        self.resumed += 1
        self.status = PrinterStatus.PRINTING
        return PrintResult(success=True, message="Print resumed.")

    def _start_print_impl(self, file_name, **kwargs) -> PrintResult:
        return PrintResult(success=True, message="Started.")


_Machine.__abstractmethods__ = frozenset()


def _job_file(tmp_path, plan=PLAN, name=JOB) -> str:
    lines = ["; generated by PrusaSlicer 2.9.4", "", "G28", "G1 Z0.2 F600", "G1 X10 Y10 E1"]
    lines.insert(hs.plan_line_index(lines), hs.plan_line(plan))
    path = tmp_path / name
    path.write_text("\n".join(lines) + "\n")
    return str(path)


@pytest.fixture()
def machine(tmp_path):
    """A printer that has just started a job carrying PLAN."""
    m = _Machine()
    hs.note_print_started(m, _job_file(tmp_path))
    return m


def _at(m, status, layer=None, *, announce=False, **fields):
    m.status, m.layer = status, layer
    for key, value in fields.items():
        setattr(m, key, value)
    return hs.observe(m, m.get_state(), m.get_job(), now=fields.get("now"), announce=announce)


def _see(m, *, now, status=PrinterStatus.PRINTING, layer=None, announce=False):
    m.status, m.layer = status, layer
    return hs.observe(m, m.get_state(), m.get_job(), now=now, announce=announce)


# --- the line in the file ----------------------------------------------------


class TestThePlanLine:
    def test_it_goes_below_the_slicers_opening_and_never_inside_a_thumbnail(self):
        bambu = ["; HEADER_BLOCK_START", "; BambuStudio 02.05.00.66", "; HEADER_BLOCK_END", "", "G28"]
        prusa = ["; generated by PrusaSlicer 2.9.4", "", "; thumbnail begin 16x16 492", "; iVBOR"]
        assert hs.plan_line_index(bambu) == 3
        assert hs.plan_line_index(prusa) == 1
        assert hs.plan_line_index(["; thumbnail begin 16x16 492", "; iVBOR", "; thumbnail end"]) == 0
        assert hs.plan_line_index(["G28"]) == 0 and hs.plan_line_index([]) == 0

    def test_it_reads_back_from_a_plain_file_and_from_a_sliced_3mf(self, tmp_path):
        plain = _job_file(tmp_path)
        assert hs.read_plan(plain)["stops"][1]["insert"] == "4x 6x3 magnet in S3, S4, S5, S6"
        archive = tmp_path / "bracket.gcode.3mf"
        with zipfile.ZipFile(archive, "w") as zf:
            zf.writestr("Metadata/plate_1.gcode", open(plain).read())
        carried = hs.read_plan(str(archive))
        assert [s["before_layer"] for s in carried["stops"]] == [29, 41]
        assert carried["after_print"][0]["seats"] == ["S7", "S8", "S9", "S10"]

    @pytest.mark.parametrize("bad", [
        {**PLAN, "v": 2},
        {"v": 1, "stops": [], "after_print": []},
        {"v": 1, "stops": [{"n": 1, "before_layer": 0, "insert": "nut"}]},
    ])
    def test_a_plan_the_reader_cannot_use_is_refused_when_written(self, bad):
        with pytest.raises(ValueError):
            hs.plan_line(bad)

    def test_a_line_of_another_version_is_ignored(self, tmp_path):
        path = tmp_path / "later.gcode"
        path.write_text('; kiln_hardware_plan = {"v":2,"stops":[]}\nG28\n')
        assert hs.read_plan(str(path)) is None


# --- while the print runs ----------------------------------------------------


class TestDuringThePrint:
    def test_a_distant_stop_is_planned_with_the_printers_own_minutes(self, machine):
        # 20 % done with 32 min left: a 40-minute print, stop at 60 % -> 16 min away.
        note = _at(machine, PrinterStatus.PRINTING, 10, completion=20.0, left_s=32 * 60)
        assert note["stage"] == "planned" and note["minutes_to_stop"] == pytest.approx(16.0)
        assert note["before_layer"] == 29

    def test_a_close_stop_is_said_once(self, machine):
        first = _at(machine, PrinterStatus.PRINTING, 25, completion=50.0, left_s=20 * 60, announce=True)
        assert first["stage"] == "coming_up" and first["new"] is True
        assert "In about 4 minutes the printer stops before layer 29 so you can put in 2x M3 nut" in first["say"]
        again = _at(machine, PrinterStatus.PRINTING, 26, completion=52.0, left_s=19 * 60, announce=True)
        assert again["stage"] == "coming_up" and again["new"] is False

    def test_a_status_read_shows_a_moment_without_using_it_up(self, machine):
        """Found in a dress rehearsal: a status poll took the warning, and the
        wait the person was relying on never passed it on."""
        assert _at(machine, PrinterStatus.PRINTING, 25)["new"] is True  # a status read
        assert _at(machine, PrinterStatus.PRINTING, 25)["new"] is True  # and another
        assert _at(machine, PrinterStatus.PRINTING, 26, announce=True)["new"] is True  # the wait hands it over
        assert _at(machine, PrinterStatus.PRINTING, 26)["new"] is False

    def test_without_a_time_it_warns_by_layers(self, machine):
        note = _at(machine, PrinterStatus.PRINTING, 25)
        assert note["stage"] == "coming_up" and note["say"].startswith("In 4 layers")

    def test_a_magnet_stop_asks_for_tweezers(self, machine):
        _see(machine, now=0, status=PrinterStatus.PAUSED, layer=29)  # stop 1 reached and resumed from
        note = _see(machine, now=600, layer=38)
        assert note["stage"] == "coming_up" and note["stop"] == 2 and "non-magnetic tweezers" in note["say"]

    def test_at_the_stop_it_says_what_goes_in_and_waits_for_the_person(self, machine):
        note = _at(machine, PrinterStatus.PAUSED, 29)
        assert note["stage"] == "now" and note["new"] is True and note["certain"] is True
        assert note["say"].startswith("Now is the time to put in 2x M3 nut in S1, S2.")
        assert note["steps"] == PLAN["stops"][0]["steps"]
        assert "hardware_confirmed=true" in note["resume"] and "on its own" in note["resume"]
        assert note["safety"] == PLAN["safety"]
        assert _at(machine, PrinterStatus.PAUSED, 29, announce=True)["new"] is True
        assert _at(machine, PrinterStatus.PAUSED, 29)["new"] is False

    def test_a_printer_counting_from_zero_is_still_at_the_stop(self, machine):
        assert _at(machine, PrinterStatus.PAUSED, 28)["stage"] == "now"

    def test_a_pause_that_is_not_a_stop_says_so(self, machine):
        note = _at(machine, PrinterStatus.PAUSED, 12)
        assert note["stage"] == "paused_elsewhere" and "Nothing goes in yet" in note["say"]

    def test_a_stop_gone_past_while_watched_is_missed(self, machine):
        for t, layer in ((0, 27), (10, 28), (20, 29)):
            _see(machine, now=t, layer=layer)
        note = _see(machine, now=30, layer=30)
        assert note["stage"] == "missed" and note["new"] is True
        assert "went past layer 29 without stopping" in note["say"] and "(M400 U1)" in note["say"]
        assert _see(machine, now=35, layer=30)["stage"] == "missed"  # a status read does not use it up
        assert _see(machine, now=38, layer=31, announce=True)["stage"] == "missed"  # the wait hands it over
        assert _see(machine, now=40, layer=31)["stage"] == "planned"  # said once; stop 2 is next

    def test_a_stop_gone_past_between_far_apart_readings_is_unseen(self, machine):
        _see(machine, now=0, layer=27)
        note = _see(machine, now=300, layer=31)
        assert note["stage"] == "passed_unseen" and "cannot tell whether it stopped" in note["say"]

    def test_after_a_restart_kiln_does_not_claim_it_watched(self, machine):
        _see(machine, now=0, layer=27)
        hs.forget_process_state()
        assert _see(machine, now=10, layer=30)["stage"] == "passed_unseen"

    def test_a_stop_the_person_resumed_from_is_not_missed(self, machine):
        assert _see(machine, now=0, status=PrinterStatus.PAUSED, layer=29)["stage"] == "now"
        assert _see(machine, now=200, layer=30)["stage"] == "planned"

    def test_another_job_on_the_machine_hears_nothing(self, machine):
        machine.file = "someone-elses-calibration-cube.gcode"
        assert _at(machine, PrinterStatus.PAUSED, 29) is None

    def test_the_finished_print_names_what_goes_in_afterwards(self, machine):
        done = _at(machine, PrinterStatus.IDLE, ended=JobResult.COMPLETED, now=1000.0, announce=True)
        assert done["stage"] == "after_print" and done["new"] is True
        assert done["say"] == ("The print has finished. Now press in the 4 M3 heat-set inserts, one in each of S7, "
                               "S8, S9 and S10. After the print, once the part is cool and any supports are off.")
        assert done["after_print"][0]["next_calls"][0]["tool"] == "recommend_heat_set_insert"
        assert done["safety"] == ["The insert iron burns on contact."]
        assert _at(machine, PrinterStatus.IDLE, now=2000.0)["new"] is False
        assert _at(machine, PrinterStatus.IDLE, now=1000.0 + 25 * 3600) is None

    def test_a_cancelled_print_says_nothing_afterwards(self, machine):
        assert _at(machine, PrinterStatus.IDLE, ended=JobResult.CANCELLED) is None

    def test_a_start_without_a_plan_clears_the_last_one(self, machine, tmp_path):
        plain = tmp_path / "cube.gcode"
        plain.write_text("; generated by PrusaSlicer 2.9.4\nG28\n")
        hs.note_print_started(machine, str(plain))
        assert hs.has_plan(machine) is False


# --- resuming ----------------------------------------------------------------


class TestResume:
    def test_a_resume_at_the_stop_waits_for_the_persons_word(self, machine):
        machine.status, machine.layer = PrinterStatus.PAUSED, 29
        refused = machine.resume_print()
        assert isinstance(refused, HardwareStopRefusal) and refused.success is False
        assert refused.code == hs.NOT_CONFIRMED and refused.hardware["stage"] == "now"
        assert "2x M3 nut" in refused.message and machine.resumed == 0
        assert refused.to_dict()["hardware"]["before_layer"] == 29

        assert machine.resume_print(hardware_confirmed=True).success is True
        assert machine.resumed == 1
        assert hs._read_store()[hs.machine_key(machine)]["stops"]["1"]["confirmed_at"]

    def test_force_does_not_stand_in_for_the_persons_word(self, machine):
        machine.status, machine.layer = PrinterStatus.PAUSED, 29
        assert machine.resume_print(force=True).success is False and machine.resumed == 0

    def test_without_a_layer_counter_every_pause_asks_and_the_word_moves_on(self, machine):
        machine.status = PrinterStatus.PAUSED
        first = machine.resume_print()
        assert first.hardware["stop"] == 1 and first.hardware["certain"] is False
        assert first.message.startswith("The printer has paused. If this is the planned stop")
        assert machine.resume_print(hardware_confirmed=True).success is True
        machine.status = PrinterStatus.PAUSED
        assert machine.resume_print().hardware["stop"] == 2

    def test_a_pause_that_is_not_a_stop_resumes_as_usual(self, machine):
        machine.status, machine.layer = PrinterStatus.PAUSED, 12
        assert machine.resume_print().success is True and machine.resumed == 1

    def test_an_ordinary_print_resumes_as_before(self):
        plain = _Machine()
        plain.status = PrinterStatus.PAUSED
        assert plain.resume_print().success is True


# --- the doors ---------------------------------------------------------------


class TestTheDoors:
    def test_the_start_template_files_the_plan(self, tmp_path, monkeypatch):
        import kiln.printers.base as base

        monkeypatch.setattr("kiln.printers.print_gate.run_adapter_gate", lambda *a, **k: None)
        monkeypatch.setattr(base, "_PRINT_STARTED_HOOKS", ())
        m = _Machine()
        assert m.start_print(_job_file(tmp_path)).success
        assert hs.has_plan(m)
        m.status, m.layer = PrinterStatus.PAUSED, 29
        assert hs.observe(m, m.get_state(), m.get_job())["stage"] == "now"

    def test_the_gate_reads_the_plan_from_the_copy_it_judges(self, tmp_path, monkeypatch):
        from kiln.printers.print_gate import run_adapter_gate

        seen = []
        monkeypatch.setattr(hs, "stage", lambda adapter, file_name, path: seen.append((file_name, path)))
        path = _job_file(tmp_path)
        run_adapter_gate(_Machine(), path, {})
        assert seen == [(path, path)]

    def test_printer_status_carries_the_block(self, machine):
        from kiln.server import printer_status

        machine.status, machine.layer = PrinterStatus.PAUSED, 29
        with patch("kiln.server._get_adapter", return_value=machine):
            lite = printer_status(detail="lite")
        assert lite["hardware"]["stage"] == "now" and lite["hardware"]["insert"] == "2x M3 nut in S1, S2"

    def test_the_monitor_report_says_what_goes_in(self, machine):
        from kiln.server import monitor_print

        machine.status, machine.layer = PrinterStatus.PAUSED, 29
        with patch("kiln.server._get_adapter", return_value=machine):
            report = monitor_print(include_snapshot=False)
        assert "- Hardware: Now is the time to put in 2x M3 nut in S1, S2." in report
        assert "  2. Put in: 2x M3 nut in S1, S2." in report

    def test_resume_print_refuses_then_resumes_on_the_persons_word(self, machine, monkeypatch):
        import kiln.server as server

        monkeypatch.setattr(server, "_check_rate_limit", lambda name: None)
        machine.status, machine.layer = PrinterStatus.PAUSED, 29
        with patch("kiln.server._get_adapter", return_value=machine):
            refused = server.resume_print()
            assert refused["success"] is False and refused["code"] == hs.NOT_CONFIRMED
            assert refused["hardware"]["stage"] == "now" and machine.resumed == 0
            assert server.resume_print(hardware_confirmed=True)["success"] is True
        assert machine.resumed == 1

    def test_the_wait_tool_comes_back_at_the_stop(self, machine):
        from kiln.server import await_print_completion

        machine.status, machine.layer = PrinterStatus.PAUSED, 29
        with patch("kiln.server._get_adapter", return_value=machine):
            result = await_print_completion(timeout=5, poll_interval=0)
        assert result["outcome"] == "hardware_stop" and result["hardware"]["stage"] == "now"

    def test_the_wait_tool_names_the_after_print_step(self, machine):
        from kiln.server import await_print_completion

        machine.status, machine.ended = PrinterStatus.IDLE, JobResult.COMPLETED
        with patch("kiln.server._get_adapter", return_value=machine):
            result = await_print_completion(timeout=5, poll_interval=0)
        assert result["outcome"] == "completed" and result["hardware"]["stage"] == "after_print"

    def test_the_watcher_hands_the_stop_back_instead_of_inviting_a_resume(self, machine):
        from kiln.plugins.monitoring_tools import _PrintWatcher

        machine.status, machine.layer = PrinterStatus.PAUSED, 29
        watcher = _PrintWatcher("w1", machine, "bench", poll_interval=0)
        watcher._start_time = time.time()
        watcher._run()
        assert watcher._result["outcome"] == "hardware_stop"
        assert watcher._result["message"].startswith("Now is the time to put in")
        assert "Call resume_print" not in watcher._result["message"]

    def test_the_watcher_says_a_close_stop_once(self, machine):
        from kiln.plugins.monitoring_tools import _PrintWatcher

        machine.status, machine.layer = PrinterStatus.PRINTING, 26
        watcher = _PrintWatcher("w2", machine, "bench", poll_interval=0)
        watcher._start_time = time.time()
        watcher._run()
        assert watcher._result["outcome"] == "hardware_stop"
        assert watcher._result["hardware"]["stage"] == "coming_up"

    def test_the_cli_carries_the_persons_word(self):
        from click.testing import CliRunner

        from kiln.cli.main import cli

        with patch("kiln.cli.main._get_adapter_from_ctx") as get, \
                patch("kiln.cli.main._emergency_latch_status", return_value=None):
            get.return_value.resume_print.return_value = PrintResult(success=True, message="Print resumed.")
            result = CliRunner().invoke(cli, ["resume", "--hardware-in", "--json"])
        assert result.exit_code == 0, result.output
        get.return_value.resume_print.assert_called_once_with(force=False, hardware_confirmed=True)
