"""A same-bed retry starts only when the MACHINE says it is still homed.

The pre-print gate refuses any file that moves before it homes (incident
#0).  kiln-pro's same-bed retry is the one file class that must not home:
the failed part is still on the bed beside the retry, and a G28 or a bed
probe would hit it.  So the gate takes that file on a contract, and checks
the contract against the printer, live, in this order:

  (a) the file carries Kiln's same-bed safe-startup header, whole;
  (b) the machine being started is the machine it was baked for;
  (c) no emergency latch on that machine;
  (d) the machine is not printing or paused;
  (e) the firmware, asked NOW, reports X, Y and Z homed.

Every other file keeps the old rule, unchanged.  A backend that cannot
answer (e) refuses with the measurement sentence -- a cached reading is a
guess, and a guess does not start a print next to a part on the bed.
"""

from __future__ import annotations

import logging
from typing import Any
from unittest import mock

import pytest

from kiln.printers import print_gate as pg
from kiln.printers.base import (
    PrinterAdapter,
    PrinterError,
    PrinterState,
    PrinterStatus,
    PrintResult,
)

# --- A same-bed retry artifact, exactly as kiln-pro bakes it -------------

_BODY = (
    ";LAYER_CHANGE\n;Z:0.2\n"
    "G1 Z.4 F24000\nG1 X114.658 Y114.939\nG1 Z.2\n"
    ";TYPE:Skirt/Brim\nG1 F3000\nG1 X116.4 Y113.37 E.06961\n"
)

_ORDINARY_NO_HOMING = (
    "; generated by PrusaSlicer 2.9.4\n"
    "M190 S65\nM104 S220\nM109 S220\nG21\nG90\nM83\nM107\n" + _BODY
)

MACHINE = "bench-a1"


def _header(
    *,
    machine: str | None = MACHINE,
    policy_id: str | None = "same-bed-safe-prologue-v2:bambu",
    policy_version: str | None = "same-bed-safe-prologue-v2",
    contract: str | None = "no_xyz_motion",
) -> str:
    lines = [
        "; --- Kiln same-bed retry safe startup ---",
        "; source_gcode: benchy.gcode",
        "; baked_xy_offset_mm: X70.000 Y70.000",
        "; no homing, bed-scan, or extrusion-line motion is emitted by this header",
        "; printer_profile: bambu",
    ]
    if policy_id is not None:
        lines.append(f"; safe_startup_policy_id: {policy_id}")
    if policy_version is not None:
        lines.append(f"; safe_startup_policy_version: {policy_version}")
    if contract is not None:
        lines.append(f"; safe_startup_motion_contract: {contract}")
    if machine is not None:
        lines.append(f"; baked_for_machine: {machine}")
    lines += [
        "; prohibited_startup_actions: xy_motion,z_motion,homing",
        "G21 ; Kiln same-bed retry units: mm",
        "G90 ; Kiln same-bed retry absolute XY",
        "M140 S60 ; preserved bed target",
        "; --- End Kiln same-bed retry safe startup ---",
    ]
    return "\n".join(lines) + "\n"


@pytest.fixture
def retry_file(tmp_path):
    def _write(name: str = "benchy_same_bed_retry.gcode", **header_kw: Any) -> str:
        path = tmp_path / name
        path.write_text(_header(**header_kw) + _BODY)
        return str(path)

    return _write


# --- A real adapter running the real start template ----------------------


class _RetryAdapter(PrinterAdapter):
    """Registry-shaped: named by its owner, no serial, answers the gate's
    questions from attributes a test sets, records every start."""

    printer_id = "bambu_a1"

    def __init__(self, registered_name: str | None = MACHINE) -> None:
        if registered_name is not None:
            self._kiln_registered_name = registered_name
        self.homed: set[str] | None = {"x", "y", "z"}
        self.homed_field: str | None = "toolhead.homed_axes"
        self.homed_reads = 0
        self.state = PrinterStatus.IDLE
        self.impl_calls: list[str] = []

    @property
    def name(self) -> str:
        return "stub"

    def get_state(self) -> PrinterState:
        return PrinterState(connected=True, state=self.state)

    def homed_axes_now(self) -> set[str] | None:
        self.homed_reads += 1
        return None if self.homed is None else set(self.homed)

    def homed_axes_field(self) -> str | None:
        return self.homed_field

    def _start_print_impl(self, file_name: str, **kwargs: Any) -> PrintResult:
        self.impl_calls.append(file_name)
        return PrintResult(success=True, message="IMPL")


_RetryAdapter.__abstractmethods__ = frozenset()


class _Unlatched:
    def __init__(self) -> None:
        self.asked: list[str] = []
        self.status: dict[str, Any] = {"latched": False, "critical_interlocks_pending": []}

    def get_latch_status(self, printer_id: str) -> dict[str, Any]:
        self.asked.append(printer_id)
        return dict(self.status)


@pytest.fixture
def latch(monkeypatch):
    """The emergency coordinator, unlatched unless a test says otherwise."""
    coord = _Unlatched()
    monkeypatch.setattr("kiln.emergency.get_emergency_coordinator", lambda: coord)
    return coord


@pytest.fixture(autouse=True)
def _isolated(latch, monkeypatch):
    pg._oversize_grants.clear()
    monkeypatch.delenv("KILN_SKIP_PREVIEW_GATE", raising=False)
    yield
    pg._oversize_grants.clear()


# --- Every other file keeps the old rule ---------------------------------


def test_an_ordinary_no_homing_file_is_refused_exactly_as_before(tmp_path):
    path = tmp_path / "raw.gcode"
    path.write_text(_ORDINARY_NO_HOMING)
    adapter = _RetryAdapter()  # homed, idle, unlatched -- none of it matters
    blocked = pg.run_adapter_gate(adapter, str(path), {})
    assert blocked is not None and blocked["code"] == "NO_HOMING_SEQUENCE"
    assert "G28" in blocked["reason"]
    assert adapter.homed_reads == 0, "an ordinary file never asks the machine"
    result = adapter.start_print(str(path))
    assert result.success is False and adapter.impl_calls == []


def test_a_homed_file_never_consults_the_contract(tmp_path):
    path = tmp_path / "homed.gcode"
    path.write_text("G28\n" + _ORDINARY_NO_HOMING)
    adapter = _RetryAdapter()
    assert pg.run_adapter_gate(adapter, str(path), {}) is None
    assert adapter.homed_reads == 0


# --- All five hold: accepted, with the evidence written down --------------


def test_all_conditions_true_is_accepted_and_the_evidence_is_recorded(retry_file, caplog):
    adapter = _RetryAdapter()
    path = retry_file()
    with caplog.at_level(logging.INFO, logger="kiln.printers.print_gate"):
        verdict = pg.evaluate_same_bed_retry(adapter, path)
        assert pg.run_adapter_gate(adapter, path, {}) is None
    assert verdict["blocked"] is False and verdict["accepted"] is True
    evidence = verdict["homed_evidence"]
    assert evidence["axes"] == ["x", "y", "z"]
    assert evidence["field"] == "toolhead.homed_axes"
    assert evidence["read_at"].endswith("+00:00")  # an ISO-8601 UTC timestamp
    assert verdict["machine"] == MACHINE
    assert verdict["contract"]["safe_startup_policy_version"] == "same-bed-safe-prologue-v2"
    audit = [r.getMessage() for r in caplog.records if "same-bed retry" in r.getMessage()]
    assert audit, "no audit line"
    assert all(s in audit[-1] for s in ("accepted", MACHINE, "x,y,z", "toolhead.homed_axes", evidence["read_at"]))

    result = adapter.start_print(path)
    assert result.success is True and adapter.impl_calls == [path]


# --- Each condition refuses on its own, naming itself and the remedy ------


@pytest.mark.parametrize(
    "missing, named",
    [
        ({"policy_id": None}, "safe_startup_policy_id"),
        ({"policy_version": None}, "safe_startup_policy_version"),
        ({"contract": "xyz_motion"}, "safe_startup_motion_contract"),
        ({"machine": None}, "baked_for_machine"),
    ],
)
def test_a_contract_with_a_line_missing_or_wrong_is_refused(retry_file, missing, named):
    adapter = _RetryAdapter()
    verdict = pg.evaluate_same_bed_retry(adapter, retry_file(**missing))
    assert verdict["blocked"] is True
    assert verdict["code"] == "SAME_BED_RETRY_NO_CONTRACT"
    assert named in verdict["reason"]
    assert "reslice" in verdict["reason"].lower()
    assert adapter.homed_reads == 0


def test_baked_for_another_machine_is_refused(retry_file):
    adapter = _RetryAdapter()
    verdict = pg.evaluate_same_bed_retry(adapter, retry_file(machine="other-a1"))
    assert verdict["blocked"] is True
    assert verdict["code"] == "SAME_BED_RETRY_WRONG_MACHINE"
    assert "other-a1" in verdict["reason"] and MACHINE in verdict["reason"]
    assert adapter.homed_reads == 0
    assert adapter.start_print(retry_file(machine="other-a1")).success is False


def test_a_machine_kiln_cannot_identify_is_refused(retry_file):
    adapter = _RetryAdapter(registered_name=None)  # no serial, no host, no name
    assert pg.same_bed_machine_id(adapter) == ""
    verdict = pg.evaluate_same_bed_retry(adapter, retry_file())
    assert verdict["blocked"] is True and verdict["code"] == "SAME_BED_RETRY_WRONG_MACHINE"


def test_an_emergency_latch_is_refused(retry_file, latch):
    latch.status = {"latched": True, "critical_interlocks_pending": ["door"]}
    adapter = _RetryAdapter()
    verdict = pg.evaluate_same_bed_retry(adapter, retry_file())
    assert verdict["blocked"] is True
    assert verdict["code"] == "SAME_BED_RETRY_EMERGENCY_LATCHED"
    assert "clear_emergency_stop" in verdict["reason"] and "door" in verdict["reason"]
    assert latch.asked == [MACHINE]
    assert adapter.homed_reads == 0


@pytest.mark.parametrize("state", [PrinterStatus.PRINTING, PrinterStatus.PAUSED])
def test_a_printing_or_paused_machine_is_refused(retry_file, state):
    adapter = _RetryAdapter()
    adapter.state = state
    verdict = pg.evaluate_same_bed_retry(adapter, retry_file())
    assert verdict["blocked"] is True
    assert verdict["code"] == "SAME_BED_RETRY_PRINTER_BUSY"
    assert state.value in verdict["reason"]
    assert adapter.homed_reads == 0


def test_a_state_that_cannot_be_read_is_refused(retry_file, monkeypatch):
    adapter = _RetryAdapter()

    def boom():
        raise PrinterError("socket closed")

    monkeypatch.setattr(adapter, "get_state", boom)
    verdict = pg.evaluate_same_bed_retry(adapter, retry_file())
    assert verdict["blocked"] is True and verdict["code"] == "SAME_BED_RETRY_STATE_READ_FAILED"
    assert "socket closed" in verdict["reason"]


def test_a_machine_missing_an_axis_is_refused_with_the_axes_it_reported(retry_file):
    adapter = _RetryAdapter()
    adapter.homed = {"x", "y"}
    verdict = pg.evaluate_same_bed_retry(adapter, retry_file())
    assert verdict["blocked"] is True
    assert verdict["code"] == "SAME_BED_RETRY_NOT_HOMED"
    assert "z" in verdict["reason"]
    assert verdict["homed_evidence"]["axes"] == ["x", "y"]
    assert verdict["homed_evidence"]["field"] == "toolhead.homed_axes"
    assert adapter.homed_reads == 1


def test_a_backend_that_cannot_say_refuses_with_the_measurement_sentence(retry_file):
    adapter = _RetryAdapter()
    adapter.homed = None
    adapter.homed_field = None
    verdict = pg.evaluate_same_bed_retry(adapter, retry_file())
    assert verdict["blocked"] is True
    assert verdict["code"] == "SAME_BED_RETRY_HOMED_UNKNOWN"
    assert pg.HOMED_UNKNOWN_SENTENCE in verdict["reason"]
    assert verdict["homed_evidence"]["axes"] is None
    assert adapter.start_print(retry_file()).success is False
    assert adapter.impl_calls == []


def test_a_homed_read_that_fails_is_a_retry_not_a_measurement_gap(retry_file, monkeypatch):
    adapter = _RetryAdapter()

    def boom():
        raise PrinterError("timed out")

    monkeypatch.setattr(adapter, "homed_axes_now", boom)
    verdict = pg.evaluate_same_bed_retry(adapter, retry_file())
    assert verdict["blocked"] is True and verdict["code"] == "SAME_BED_RETRY_HOMED_READ_FAILED"
    assert "timed out" in verdict["reason"]
    assert pg.HOMED_UNKNOWN_SENTENCE not in verdict["reason"]


def test_conditions_are_checked_in_order_and_the_first_failure_is_named(retry_file, latch):
    latch.status = {"latched": True, "critical_interlocks_pending": []}
    adapter = _RetryAdapter()
    adapter.state = PrinterStatus.PRINTING
    adapter.homed = None
    # (a) holds, (b) fails, (c) (d) (e) would all fail too: (b) is the answer.
    verdict = pg.evaluate_same_bed_retry(adapter, retry_file(machine="other-a1"))
    assert verdict["code"] == "SAME_BED_RETRY_WRONG_MACHINE"
    assert latch.asked == [] and adapter.homed_reads == 0
    # (b) holds, (c) fails: the latch is named, the state and the axes are never read.
    verdict = pg.evaluate_same_bed_retry(adapter, retry_file())
    assert verdict["code"] == "SAME_BED_RETRY_EMERGENCY_LATCHED"
    assert adapter.homed_reads == 0
    # (c) holds, (d) fails: still no homed read.
    latch.status = {"latched": False, "critical_interlocks_pending": []}
    verdict = pg.evaluate_same_bed_retry(adapter, retry_file())
    assert verdict["code"] == "SAME_BED_RETRY_PRINTER_BUSY"
    assert adapter.homed_reads == 0


def test_a_refusal_is_logged_with_the_evidence(retry_file, caplog):
    adapter = _RetryAdapter()
    adapter.homed = {"x"}
    with caplog.at_level(logging.INFO, logger="kiln.printers.print_gate"):
        blocked = pg.run_adapter_gate(adapter, retry_file(), {})
    assert blocked is not None and blocked["code"] == "SAME_BED_RETRY_NOT_HOMED"
    assert blocked["homed_evidence"]["axes"] == ["x"]
    audit = [r.getMessage() for r in caplog.records if "same-bed retry" in r.getMessage()]
    assert audit and "refused" in audit[-1] and "axes=x " in audit[-1] + " "


def test_the_contract_does_not_rescue_a_material_the_hotend_cannot_reach(retry_file):
    class _Ender(_RetryAdapter):
        printer_id = "ender3"

    _Ender.__abstractmethods__ = frozenset()
    adapter = _Ender()
    blocked = pg.run_adapter_gate(adapter, retry_file(), {"material": "polycarbonate"})
    assert blocked is not None and blocked["code"] == "MATERIAL_EXCEEDS_HOTEND"


def test_resume_exemption_is_untouched(retry_file):
    adapter = _RetryAdapter()
    adapter.homed = None
    assert pg.run_adapter_gate(adapter, retry_file(), {"resume_from_paused": True}) is None
    assert adapter.homed_reads == 0


# --- Which machine the file is bound to ----------------------------------


def test_machine_id_prefers_the_hardware_fingerprint_over_the_registered_name():
    adapter = _RetryAdapter("bench-a1")
    assert pg.same_bed_machine_id(adapter) == "bench-a1"
    adapter.serial = "01P00A000000001"
    fingerprint = pg.same_bed_machine_id(adapter)
    assert fingerprint == "stub:serial:01p00a000000001"
    # The same machine registered twice ("default" and its config name) is
    # still one machine to the contract.
    twin = _RetryAdapter("default")
    twin.serial = "01P00A000000001"
    assert pg.same_bed_machine_id(twin) == fingerprint


# --- The backends: who can answer, and that the answer is live ------------


def _moonraker():
    from kiln.printers.moonraker import MoonrakerAdapter

    return MoonrakerAdapter(host="http://klipper.local:7125", timeout=5, retries=1)


def _fake_response(payload: dict[str, Any]) -> mock.MagicMock:
    resp = mock.MagicMock()
    resp.ok = True
    resp.status_code = 200
    resp.json.return_value = payload
    return resp


def test_moonraker_asks_klipper_over_the_wire_on_every_call():
    adapter = _moonraker()
    answers = iter(["xyz", "xy", ""])
    requests_made: list[tuple[str, str, dict | None]] = []

    def fake_request(method, url, **kw):
        requests_made.append((method, url, kw.get("params")))
        return _fake_response(
            {"result": {"status": {"toolhead": {"homed_axes": next(answers)}}}}
        )

    with mock.patch.object(adapter._session, "request", side_effect=fake_request):
        assert adapter.homed_axes_now() == {"x", "y", "z"}
        assert adapter.homed_axes_now() == {"x", "y"}
        assert adapter.homed_axes_now() == set()
    assert len(requests_made) == 3, "one query per call: a cached answer is a guess"
    for method, url, params in requests_made:
        assert method == "GET" and url.endswith("/printer/objects/query")
        assert params == {"toolhead": "homed_axes"}
    assert adapter.homed_axes_field() == "toolhead.homed_axes"


def test_moonraker_read_failure_raises_rather_than_answering_none():
    import requests

    adapter = _moonraker()
    down = requests.exceptions.ConnectionError("down")
    with (
        mock.patch.object(adapter._session, "request", side_effect=down),
        pytest.raises(PrinterError),
    ):
        adapter.homed_axes_now()


def test_duet_reads_the_object_model_live(monkeypatch):
    from kiln.printers.duet import DuetAdapter

    adapter = DuetAdapter(host="http://duet.local")
    monkeypatch.setattr(adapter, "_generation", lambda: 3)
    reads: list[str] = []

    def fake_model(key):
        reads.append(key)
        return [
            {"letter": "X", "homed": True},
            {"letter": "Y", "homed": True},
            {"letter": "Z", "homed": False},
        ]

    monkeypatch.setattr(adapter, "_model", fake_model)
    assert adapter.homed_axes_now() == {"x", "y"}
    assert adapter.homed_axes_now() == {"x", "y"}
    assert reads == ["move.axes", "move.axes"]
    assert adapter.homed_axes_field() == "move.axes[].homed"

    monkeypatch.setattr(adapter, "_generation", lambda: 2)
    monkeypatch.setattr(
        adapter, "_get_json", lambda path, params=None: {"coords": {"axesHomed": [1, 1, 1]}}
    )
    assert adapter.homed_axes_now() == {"x", "y", "z"}
    assert adapter.homed_axes_field() == "coords.axesHomed"


def test_creality_answers_through_its_klipper_backend(monkeypatch):
    from kiln.printers.creality import CrealityAdapter

    ok = mock.MagicMock()
    ok.ok = True
    ok.status_code = 200
    ok.json.return_value = {"result": {"klippy_state": "ready"}}
    with mock.patch("kiln.printers.creality.requests.get", return_value=ok):
        adapter = CrealityAdapter("http://printer.local", timeout=5, retries=1)
    monkeypatch.setattr(adapter._backend, "homed_axes_now", lambda: {"x", "y", "z"})
    assert adapter.homed_axes_now() == {"x", "y", "z"}
    assert adapter.homed_axes_field() == "toolhead.homed_axes"


def test_the_base_default_cannot_say():
    adapter = _RetryAdapter()
    assert PrinterAdapter.homed_axes_now(adapter) is None
    assert PrinterAdapter.homed_axes_field(adapter) is None


def test_bambu_cannot_say_yet_and_does_not_guess_from_home_flag(retry_file, monkeypatch):
    from kiln.printers.bambu import BambuAdapter

    monkeypatch.setenv("KILN_BAMBU_TLS_PIN_FILE", "/dev/null")
    adapter = BambuAdapter(
        host="192.168.1.5", access_code="12345678", serial="01P00A000000001", timeout=2
    )
    # A push that sets every bit: the homed-axis bits of home_flag are not
    # measured, so no reading of it may be turned into "homed".
    adapter._last_status = {"gcode_state": "IDLE", "home_flag": (1 << 32) - 1}
    assert adapter.homed_axes_now() is None
    assert adapter.homed_axes_field() is None

    adapter._kiln_registered_name = MACHINE
    monkeypatch.setattr(
        adapter, "get_state", lambda: PrinterState(connected=True, state=PrinterStatus.IDLE)
    )
    bound_to = pg.same_bed_machine_id(adapter)
    assert bound_to == "bambu:serial:01p00a000000001"  # the serial outranks the name
    verdict = pg.evaluate_same_bed_retry(adapter, retry_file(machine=bound_to))
    assert verdict["blocked"] is True
    assert verdict["code"] == "SAME_BED_RETRY_HOMED_UNKNOWN"
    assert pg.HOMED_UNKNOWN_SENTENCE in verdict["reason"]
