"""One answer to "what is this print made of", at every door.

Coverage: the one reader of a print file's filament types
(:func:`kiln.gcode.slicer_filament_types`) and its one label; every door
that reports a file's material agreeing with it on real-shaped files; each
filament weighed and priced as its own material, a named material winning;
one material table behind every estimate; pre-flight pricing the file's
own grams; and a source gate that fails when a module reads the slicer's
per-filament settings its own way.
"""

from __future__ import annotations

import ast
import math
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from kiln.cost_estimator import BUILTIN_MATERIALS, CostEstimator, resolve_material
from kiln.gcode import slicer_filament_types, slicer_material_label

_SRC = Path(__file__).resolve().parents[1] / "src" / "kiln"
_AREA_MM2 = math.pi * (1.75 / 2) ** 2


def _grams(length_mm: float, material: str) -> float:
    return length_mm * _AREA_MM2 * BUILTIN_MATERIALS[material].density_g_per_cm3 / 1000.0


def _orca_plate(types: str = "PLA;PETG;PLA", *, grams: bool = True) -> str:
    """An OrcaSlicer three-colour plate's shape: a short header; a prime
    tower whose every tool change notes ``; material : A -> B`` long before
    the settings block; the print; then the totals and settings at the end."""
    lines = [
        "; generated by OrcaSlicer 2.3.2 on 2026-09-23 at 12:38:47",
        "; total layer number: 2",
        "; HEADER_BLOCK_END",
        "M83",
        "T0",
        "G1 X10 Y10 E1000",
        "; CP TOOLCHANGE START",
        "; toolchange #1",
        "; material : PLA -> PETG",
        "T1",
        "G1 X20 Y10 E500",
        "; CP TOOLCHANGE START",
        "; toolchange #2",
        "; material : PETG -> PLA",
        "T2",
        "G1 X30 Y10 E250",
        "; filament used [mm] = 1000.00, 500.00, 250.00",
    ]
    if grams:
        lines.append(
            f"; filament used [g] = {_grams(1000, 'PLA'):.2f}, "
            f"{_grams(500, 'PETG'):.2f}, {_grams(250, 'PLA'):.2f}"
        )
    lines += [
        "; estimated printing time (normal mode) = 1h 0m 0s",
        "; CONFIG_BLOCK_START",
        "; filament_colour = #FFFFFF;#C81E1E;#161616",
        f"; filament_type = {types}",
        "; CONFIG_BLOCK_END",
    ]
    return "\n".join(lines) + "\n"


def _studio_plate() -> str:
    """A Bambu Studio plate's shape: totals and settings at the TOP, four AMS
    slots configured, and only T0 and T2 printed -- so its totals list two
    values and the second is slot 3's."""
    return "\n".join(
        [
            "; HEADER_BLOCK_START",
            "; BambuStudio 02.05.00.66",
            "; model printing time: 14m 49s; total estimated time: 21m 5s",
            "; total layer number: 2",
            "; total filament length [mm] : 1000.00,500.00",
            f"; total filament weight [g] : {_grams(1000, 'PLA'):.2f},{_grams(500, 'PETG'):.2f}",
            "; HEADER_BLOCK_END",
            "; CONFIG_BLOCK_START",
            "; filament_colour = #FFFFFF;#FFFFFF;#C81E1E;#FFFFFF",
            "; filament_type = PLA;PLA;PETG;PLA",
            "; CONFIG_BLOCK_END",
            "M83",
            "T0",
            "G1 X10 Y10 E1000",
            "T2",
            "G1 X20 Y10 E500",
        ]
    ) + "\n"


def _cura_plate() -> str:
    """A Cura plate: time, filament and layer height at the top, no type."""
    return "\n".join(
        [
            ";FLAVOR:Marlin",
            ";TIME:3600",
            ";Filament used: 1m",
            ";Layer height: 0.2",
            ";Generated with Cura_SteamEngine 5.5.0",
            "M83",
            "G1 X10 Y10 E1000",
        ]
    ) + "\n"


def _write(tmp_path: Path, name: str, text: str) -> str:
    path = tmp_path / name
    path.write_text(text)
    return str(path)


class TestTheOneReader:
    def test_one_type_per_slot_in_slot_order(self):
        assert slicer_filament_types(_orca_plate()) == ("PLA", "PETG", "PLA")
        assert slicer_filament_types(_studio_plate()) == ("PLA", "PLA", "PETG", "PLA")

    def test_a_tool_change_note_is_never_the_material(self):
        text = "; material : PLA -> PETG\n; filament_type = ABS\n"
        assert slicer_filament_types(text) == ("ABS",)
        assert slicer_filament_types("; material : PLA -> PETG\n") == ()

    def test_cura_style_material_line_is_one_filament(self):
        assert slicer_filament_types(";MATERIAL:PETG\n") == ("PETG",)

    def test_a_settings_text_line_without_the_comment_mark(self):
        assert slicer_filament_types("filament_type = PLA;PETG\n") == ("PLA", "PETG")

    def test_a_blank_slot_keeps_its_place(self):
        assert slicer_filament_types("; filament_type = PLA;;PETG\n") == ("PLA", "", "PETG")

    def test_a_file_that_names_nothing(self):
        assert slicer_filament_types(_cura_plate()) == ()

    @pytest.mark.parametrize(
        "types, label",
        [
            (("PLA", "PLA"), "PLA"),
            (("PLA", "PETG", "PLA"), "PLA + PETG"),
            (("pla", "", "PETG"), "PLA + PETG"),
            ((), None),
        ],
    )
    def test_the_label_names_each_material_once(self, types, label):
        assert slicer_material_label(types) == label


class TestEveryDoorAgrees:
    """Every door that reports what a file is made of gives the reader's
    answer, on the plates that broke them: an OrcaSlicer prime tower (whose
    tool-change notes were read as the material) and a per-slot list (read
    as one material called ``"PLA;PLA"``)."""

    @pytest.mark.parametrize("plate, label", [(_orca_plate, "PLA + PETG"), (_studio_plate, "PLA + PETG")])
    def test_listings_and_file_details_show_the_label(self, tmp_path, plate, label):
        from kiln.file_metadata import extract_metadata as file_details
        from kiln.gcode_metadata import extract_metadata

        path = _write(tmp_path, "plate.gcode", plate())
        assert extract_metadata(path).material == label
        assert file_details(path).material_hint == label

    def test_the_print_time_tool_lists_the_files_types(self, tmp_path):
        from kiln.slicer import _parse_gcode_estimates

        path = _write(tmp_path, "plate.gcode", _orca_plate())
        assert _parse_gcode_estimates(path)["filament_types"] == ["PLA", "PETG", "PLA"]

    def test_ams_routing_reads_each_slots_type(self, tmp_path):
        from kiln.ams_routing import read_file_filaments

        path = _write(tmp_path, "plate.gcode", _orca_plate())
        assert [f.material for f in read_file_filaments(path).filaments] == ["PLA", "PETG", "PLA"]

    def test_the_cost_tool_names_each_filaments_type(self, tmp_path):
        path = _write(tmp_path, "plate.gcode", _orca_plate())
        est = CostEstimator().estimate_from_file(path)
        assert [f["file_material"] for f in est.filaments] == ["PLA", "PETG", "PLA"]

    def test_the_bambu_wrapper_reads_the_first_slots_type(self):
        from kiln.printers.bambu_3mf import BambuPrintSettings, resolve_settings_from_gcode

        settings = resolve_settings_from_gcode(BambuPrintSettings(), _orca_plate("PETG;PLA;PLA"))
        assert settings.filament_type == "PETG"

    def test_the_bambu_wrapper_states_each_types_own_density(self):
        from kiln.printers.bambu_3mf import _build_gcode_header

        header = _build_gcode_header(total_layers=2, max_z=1.0, est_print_time_sec=60, filament_types=["PLA", "PETG"])
        pla, petg = BUILTIN_MATERIALS["PLA"], BUILTIN_MATERIALS["PETG"]
        assert f"; filament_density: {pla.density_g_per_cm3:g},{petg.density_g_per_cm3:g}\n" in header


class TestEachFilamentIsPricedAsItsOwnMaterial:
    def test_the_files_own_types_price_each_filament(self, tmp_path):
        path = _write(tmp_path, "plate.gcode", _orca_plate())
        est = CostEstimator().estimate_from_file(path)
        assert (est.material, est.material_source) == ("PLA + PETG", "file")
        assert [f["material"] for f in est.filaments] == ["PLA", "PETG", "PLA"]
        pla, petg = BUILTIN_MATERIALS["PLA"], BUILTIN_MATERIALS["PETG"]
        expected = (
            _grams(1000, "PLA") * pla.cost_per_kg_usd
            + _grams(500, "PETG") * petg.cost_per_kg_usd
            + _grams(250, "PLA") * pla.cost_per_kg_usd
        ) / 1000.0
        assert est.filament_cost_usd == pytest.approx(expected, abs=0.001)
        assert est.warnings == []

    def test_a_named_material_prices_every_filament_and_says_what_the_file_was_for(self, tmp_path):
        path = _write(tmp_path, "plate.gcode", _orca_plate())
        est = CostEstimator().estimate_from_file(path, material="ABS")
        assert (est.material, est.material_source) == ("ABS", "named")
        # Weight converts between materials by density: the same filament length.
        assert est.filament_weight_grams == pytest.approx(_grams(1750, "ABS"), abs=0.02)
        assert any("sliced for PLA, PETG" in w and "ABS was named" in w for w in est.warnings)

    def test_kiln_weighs_the_length_at_each_type_when_the_slicer_wrote_no_grams(self, tmp_path):
        path = _write(tmp_path, "plate.gcode", _orca_plate(grams=False))
        est = CostEstimator().estimate_from_file(path)
        assert [f["weight_g"] for f in est.filaments] == pytest.approx(
            [_grams(1000, "PLA"), _grams(500, "PETG"), _grams(250, "PLA")], abs=0.01
        )

    def test_a_used_ams_slot_takes_its_own_type(self, tmp_path):
        path = _write(tmp_path, "plate.gcode", _studio_plate())
        est = CostEstimator().estimate_from_file(path)
        assert [(f["tool"], f["material"]) for f in est.filaments] == [(0, "PLA"), (2, "PETG")]

    def test_a_file_that_names_nothing_is_priced_as_pla_and_says_so(self, tmp_path):
        path = _write(tmp_path, "plate.gcode", _cura_plate())
        est = CostEstimator().estimate_from_file(path)
        assert (est.material, est.material_source) == ("PLA", "default")
        assert any("does not say what filament" in w for w in est.warnings)

    def test_a_type_the_table_lacks_is_named_in_the_warning(self, tmp_path):
        path = _write(tmp_path, "plate.gcode", _orca_plate("WOODFILL;PETG;PLA"))
        est = CostEstimator().estimate_from_file(path)
        assert est.material_source == "default"
        assert est.filaments[0]["material"] == "PLA"
        assert any("WOODFILL" in w for w in est.warnings)


class TestOneTableAtEveryDoor:
    """Every estimate weighs and prices a material from the one table,
    through the one lookup, whatever the spelling."""

    @pytest.mark.parametrize(
        "spelling, row",
        [
            ("petg", "PETG"),
            ("PETG-HF", "PETG"),
            ("PLA Basic", "PLA"),
            ("pla_plus", "PLA+"),
            ("Silk PLA", "SILK-PLA"),
            ("PLA-CF", "CF-PLA"),
            ("PA-CF", "NYLON"),
            ("abs", "ABS"),
        ],
    )
    def test_every_door_lands_on_the_same_row(self, tmp_path, spelling, row):
        from kiln.cli.main import _estimate_print_cost_cli
        from kiln.design_intelligence import resolve_filament
        from kiln.material_inventory import _mm_to_grams
        from kiln.pre_estimate import _get_material_profile
        from kiln.server import _estimate_print_cost
        from kiln.slicer_filament import material_density

        profile = BUILTIN_MATERIALS[row]
        assert resolve_material(spelling) is profile
        assert CostEstimator().get_material(spelling) is profile
        assert material_density(spelling) == (row, profile.density_g_per_cm3)
        assert _estimate_print_cost(3600, 0, material=spelling)["cost_per_kg_usd"] == profile.cost_per_kg_usd
        assert _estimate_print_cost_cli(3600, 0, spelling)["cost_per_kg_usd"] == profile.cost_per_kg_usd
        assert _mm_to_grams(1000, spelling) == pytest.approx(_grams(1000, row))
        assert _get_material_profile(spelling)["cost_per_kg_usd"] == profile.cost_per_kg_usd
        assert resolve_filament(spelling).density_g_per_cm3 == profile.density_g_per_cm3

    def test_the_mesh_estimates_read_the_table(self, tmp_path):
        from kiln.design_reasoning import estimate_weight
        from kiln.generation.validation import estimate_material_cost

        stl = tmp_path / "cube.stl"
        _write_cube_stl(stl)
        petg = BUILTIN_MATERIALS["PETG"]
        cost = estimate_material_cost(str(stl), material="PETG-HF")
        assert (cost["density_g_cm3"], cost["cost_per_kg_usd"]) == (petg.density_g_per_cm3, petg.cost_per_kg_usd)
        assert estimate_weight(str(stl), material="PETG-HF").density_g_cm3 == petg.density_g_per_cm3

    def test_no_door_keeps_its_own_price_or_density_table(self):
        """A density or price written down a second time drifts: the
        pre-flight table priced PLA at $20/kg while the cost tool said $25."""
        assert _material_tables() == [], (
            "A material price or density table outside kiln.cost_estimator; read "
            "the one table through kiln.cost_estimator.resolve_material instead"
        )

    def test_no_module_restates_plas_density(self):
        assert _restated_pla_density() == [], (
            "PLA's density written as a number; read "
            "BUILTIN_MATERIALS[DEFAULT_MATERIAL].density_g_per_cm3 instead"
        )


def _material_tables() -> list[str]:
    """Dicts keyed by materials whose name or shape says density or price."""
    found = []
    for path in sorted(_SRC.rglob("*.py")):
        rel = str(path.relative_to(_SRC))
        if rel == "cost_estimator.py":
            continue
        for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
            if isinstance(node, (ast.Assign, ast.AnnAssign)) and isinstance(node.value, ast.Dict):
                targets = node.targets if isinstance(node, ast.Assign) else [node.target]
                names = " ".join(ast.unparse(t) for t in targets).upper()
                table = node.value
            else:
                continue
            keys = {
                k.value.upper() for k in table.keys if isinstance(k, ast.Constant) and isinstance(k.value, str)
            }
            if not {"PLA", "PETG"} <= keys:
                continue
            nested_keys = {
                k.value
                for v in table.values
                if isinstance(v, ast.Dict)
                for k in v.keys
                if isinstance(k, ast.Constant)
            }
            if any(w in names for w in ("DENS", "COST", "PRICE")) or nested_keys & {"density", "cost_per_kg"}:
                found.append(f"{rel}:{node.lineno}")
    return found


def _restated_pla_density() -> list[str]:
    pla = BUILTIN_MATERIALS["PLA"].density_g_per_cm3
    found = []
    for path in sorted(_SRC.rglob("*.py")):
        rel = str(path.relative_to(_SRC))
        if rel == "cost_estimator.py":
            continue
        for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
            if isinstance(node, ast.Constant) and isinstance(node.value, float) and node.value in (pla, pla / 1000):
                found.append(f"{rel}:{node.lineno}")
    return found


def _write_cube_stl(path: Path, size: float = 20.0) -> None:
    s = size
    v = [(0, 0, 0), (s, 0, 0), (s, s, 0), (0, s, 0), (0, 0, s), (s, 0, s), (s, s, s), (0, s, s)]
    faces = [
        (0, 2, 1), (0, 3, 2), (4, 5, 6), (4, 6, 7), (0, 1, 5), (0, 5, 4),
        (1, 2, 6), (1, 6, 5), (2, 3, 7), (2, 7, 6), (3, 0, 4), (3, 4, 7),
    ]
    out = ["solid cube"]
    for a, b, c in faces:
        out += ["facet normal 0 0 0", "outer loop"]
        out += [f"vertex {x} {y} {z}" for x, y, z in (v[a], v[b], v[c])]
        out += ["endloop", "endfacet"]
    out.append("endsolid cube")
    path.write_text("\n".join(out) + "\n")


def _state():
    from kiln.printers.base import PrinterStatus

    state = MagicMock()
    state.connected = True
    state.state = PrinterStatus.IDLE
    state.tool_temp_actual = state.bed_temp_actual = 25.0
    state.tool_temp_target = state.bed_temp_target = 0.0
    return state


class TestPreflightPricesTheFilesOwnFilament:
    @patch("kiln.server._get_adapter")
    @patch("kiln.server._get_temp_limits", return_value=(280.0, 120.0))
    @patch("kiln.server.get_db")
    @patch("kiln.server._registry")
    def test_the_advisory_weighs_the_file_not_the_clock(self, registry, get_db, _limits, adapter, tmp_path):
        adapter.return_value.get_state.return_value = _state()
        registry.count = 1
        registry.list_names.return_value = ["default"]
        get_db.return_value.get_printer_learning_insights.return_value = {"total_outcomes": 0}

        from kiln.server import preflight_check

        path = _write(tmp_path, "plate.gcode", _orca_plate())
        cost = preflight_check(file_path=path)["estimated_cost"]
        grams = _grams(1000, "PLA") + _grams(500, "PETG") + _grams(250, "PLA")
        assert cost["weight_source"] == "gcode"
        assert cost["estimated_weight_g"] == pytest.approx(grams, abs=0.1)
        assert cost["material"] == "PLA + PETG"


# ---------------------------------------------------------------------------
# The gate: nothing but kiln.gcode reads the slicer's per-filament settings
# ---------------------------------------------------------------------------

#: The per-filament settings a slicer writes as one list per file.
_SETTING_WORDS = ("filament_type", "filament_colo", "filament_density", "filament_diameter")

#: Readers of the colour, density and diameter lists that predate the one
#: reader.  Each moves into kiln.gcode in its own change; the gate fails
#: when one is gone from this list's file so the list only ever shrinks,
#: and fails on any reader not on it.  The file's TYPE has no entry: it is
#: read by kiln.gcode alone.
_NOT_YET_MOVED = {
    ("ams_routing.py", "filament_colo"),
    ("printers/bambu_3mf.py", "filament_colo"),
    ("printers/bambu_3mf.py", "filament_density"),
    ("printers/bambu_3mf.py", "filament_diameter"),
    ("slicer_geometry.py", "filament_colo"),
}


_REGEX_CALLS = {"compile", "match", "search", "fullmatch", "findall", "finditer", "sub", "subn", "split"}


def _pattern_text(node: ast.AST) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.JoinedStr):
        return "".join(v.value for v in node.values if isinstance(v, ast.Constant) and isinstance(v.value, str))
    return None


def _setting_readers() -> set[tuple[str, str]]:
    """Every regex, outside kiln.gcode, that reads a per-filament setting
    line or a material comment: the pattern handed to an ``re`` call."""
    found: set[tuple[str, str]] = set()
    for path in sorted(_SRC.rglob("*.py")):
        rel = str(path.relative_to(_SRC))
        if rel == "gcode.py":
            continue
        for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
            if not (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Attribute)
                and node.func.attr in _REGEX_CALLS
                and node.args
            ):
                continue
            text = _pattern_text(node.args[0])
            if text is None:
                continue
            low = text.lower()
            for word in _SETTING_WORDS:
                if word in low:
                    found.add((rel, word))
            if "material" in low and (";" in text or "[:=]" in text):
                found.add((rel, "material"))
    return found


class TestTheSettingsBlockHasOneReader:
    def test_no_module_reads_a_files_material_its_own_way(self):
        readers = _setting_readers()
        rogue = sorted(r for r in readers if r not in _NOT_YET_MOVED)
        assert rogue == [], (
            "These read a slicer's per-filament settings (or a material comment) "
            "with their own pattern; call kiln.gcode.slicer_filament_types / "
            f"slicer_material_label instead: {rogue}"
        )

    def test_the_not_yet_moved_list_only_shrinks(self):
        gone = sorted(_NOT_YET_MOVED - _setting_readers())
        assert gone == [], f"Moved to the one reader: take these off _NOT_YET_MOVED: {gone}"
