"""Tests for kiln.file_metadata — the filament figures a file's header carries."""

from __future__ import annotations

import pytest

from kiln.file_metadata import _extract_gcode_metadata_from_lines


class TestFilamentUsedFromHeader:
    def test_two_filaments_are_summed_in_mm(self):
        # OrcaSlicer lists one value per extruder; the plate uses the sum.
        meta = _extract_gcode_metadata_from_lines(
            ["; generated by OrcaSlicer 2.3.2", "; filament used [mm] = 11040.26, 584.30", "G28"]
        )
        assert meta.extra["filament_used"] == pytest.approx(11624.56)
        assert meta.extra["filament_used_unit"] == "mm"

    def test_cura_metres_become_mm(self):
        meta = _extract_gcode_metadata_from_lines([";Filament used: 4.523m"])
        assert meta.extra["filament_used"] == pytest.approx(4523.0)
        assert meta.extra["filament_used_unit"] == "mm"

    def test_grams_alone_are_kept_as_grams(self):
        meta = _extract_gcode_metadata_from_lines(["; total filament weight [g] : 3.66"])
        assert meta.extra["filament_used"] == pytest.approx(3.66)
        assert meta.extra["filament_used_unit"] == "g"

    def test_no_header_means_no_key(self):
        meta = _extract_gcode_metadata_from_lines(["G28", "G1 X10 Y10 E.5"])
        assert "filament_used" not in meta.extra


def _orca_shaped_file(moves: int = 5000) -> str:
    """An OrcaSlicer file's shape: a short header, the print, then the
    totals and the whole settings block at the end."""
    head = "; generated by OrcaSlicer 2.3.2 on 2026-09-23 at 16:58:36\n; total layer number: 225\n; HEADER_BLOCK_END\n"
    body = "".join(f"G1 X{i % 200}.5 Y{i % 150}.25 E.048\n" for i in range(moves))
    foot = (
        "; filament used [mm] = 11040.26, 584.30\n"
        "; filament used [g] = 32.93, 1.74\n"
        "; estimated printing time (normal mode) = 1h 50m 32s\n"
        "; CONFIG_BLOCK_START\n"
        + "".join(f"; some_setting_{i} = {i}\n" for i in range(150))
        + "; filament_type = PLA;PLA\n; layer_height = 0.2\n; nozzle_diameter = 0.4\n"
        "; printer_model = bambu_a1_h679b\n; CONFIG_BLOCK_END\n"
    )
    return head + body + foot


class TestTheWindowReachesTheEnd:
    """OrcaSlicer and PrusaSlicer write their totals and settings at the
    END of the file; a reader of the first 300 lines saw only the
    slicer's name on every one of their files."""

    def test_orca_totals_at_the_tail_are_read(self, tmp_path):
        from kiln.file_metadata import extract_metadata

        path = tmp_path / "jar.gcode"
        path.write_text(_orca_shaped_file())
        meta = extract_metadata(str(path))
        assert meta.extra["filament_used"] == pytest.approx(11624.56)
        assert meta.estimated_time_seconds == 1 * 3600 + 50 * 60 + 32
        assert meta.material_hint == "PLA;PLA"
        assert meta.extra["printer_model"] == "bambu_a1_h679b"
        assert meta.extra["layer_height"] == pytest.approx(0.2)
        assert meta.slicer_hint.startswith("OrcaSlicer 2.3.2")

    def test_a_value_at_the_top_still_wins_over_the_same_key_at_the_end(self, tmp_path):
        from kiln.file_metadata import extract_metadata

        path = tmp_path / "both.gcode"
        path.write_text("; layer_height = 0.16\n" + _orca_shaped_file())
        assert extract_metadata(str(path)).extra["layer_height"] == pytest.approx(0.16)


def _cura_shaped_file(moves: int = 5000) -> str:
    """Cura's shape, the slicer that writes UFP: everything read at the top."""
    head = (
        ";FLAVOR:Marlin\n;TIME:6632\n;Filament used: 4.523m\n;Layer height: 0.2\n"
        ";Generated with Cura_SteamEngine 5.7.0\n;LAYER_COUNT:150\n;LAYER:0\n"
    )
    return head + "".join(f"G1 X{i % 200} Y{i % 150} E.05\n" for i in range(moves))


class TestPackagesAreReadOnlyAtTheTop:
    """A UFP's G-code is a zipped member: reaching its end means unpacking
    all of it, so only its top is read, bounded in bytes."""

    def _ufp(self, tmp_path, text: str):
        import zipfile

        path = tmp_path / "part.ufp"
        with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            zf.writestr("3D/model.gcode", text)
        return str(path)

    def test_curas_header_is_read(self, tmp_path):
        from kiln.file_metadata import extract_metadata

        meta = extract_metadata(self._ufp(tmp_path, _cura_shaped_file()))
        assert meta.file_type == "ufp"
        assert meta.extra["filament_used"] == pytest.approx(4523.0)
        assert meta.estimated_time_seconds == 6632
        assert meta.layer_count == 150
        assert meta.slicer_hint.startswith("Cura_SteamEngine 5.7.0")

    def test_a_member_is_never_unpacked_past_the_budget(self, tmp_path, monkeypatch):
        import zipfile

        from kiln.file_metadata import extract_metadata
        from kiln.gcode_metadata import _HEADER_BYTES

        # 3 MB on one line, then 2.6 MB of moves: a few KB zipped.  Reading
        # its end means unpacking all of it, and so does walking its lines.
        text = (
            ";Generated with Cura_SteamEngine 5.7.0\n;TIME:6632\n"
            + ";" + "x" * 3_000_000 + "\n" + "G1 X1 Y1 E.1\n" * 200_000 + "; filament used [mm] = 999\n"
        )
        path = self._ufp(tmp_path, text)
        reached: list[int] = []
        real_open = zipfile.ZipFile.open

        def watched_open(zf, name, *args, **kwargs):
            return _Watched(real_open(zf, name, *args, **kwargs), reached)

        monkeypatch.setattr(zipfile.ZipFile, "open", watched_open)
        meta = extract_metadata(path)
        assert meta.slicer_hint.startswith("Cura_SteamEngine")
        assert meta.estimated_time_seconds == 6632
        assert "filament_used" not in meta.extra
        assert reached and max(reached) <= _HEADER_BYTES + 1


class _Watched:
    """A package member that records how far into it anything has read,
    however it reads: whole reads, lines, iteration or a seek."""

    def __init__(self, fh, reached: list[int]):
        self._fh = fh
        self._reached = reached

    def _note(self, result):
        self._reached.append(self._fh.tell())
        return result

    def read(self, n=-1):
        return self._note(self._fh.read(n))

    def readline(self, limit=-1):
        return self._note(self._fh.readline(limit))

    def seek(self, *args):
        return self._note(self._fh.seek(*args))

    def tell(self):
        return self._fh.tell()

    def __iter__(self):
        return self

    def __next__(self):
        line = self.readline()
        if not line:
            raise StopIteration
        return line

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self._fh.close()

