"""Every door that reports a slicer's print time or layer total reads it
the same way, from the same spellings — kiln.gcode.slicer_print_time and
kiln.gcode.slicer_layer_count.

Coverage: the metadata reader, file details, the cost tool, the print-time
tool, preflight's cost advisory and the merged multi-colour file, each on
the real spellings of Bambu Studio, OrcaSlicer, PrusaSlicer and Cura.
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from kiln.printers.base import PrinterStatus

_MOVES = "".join(f"G1 X{i % 200}.5 Y{i % 150}.25 E.048\n" for i in range(3000))

#: One file per slicer, in its own spelling and its own place in the file:
#: Bambu Studio and Cura at the top, OrcaSlicer and PrusaSlicer at the end.
_FILES: dict[str, tuple[str, int, int | None]] = {
    "bambu_studio": (
        "; HEADER_BLOCK_START\n; BambuStudio 02.02.00.85\n"
        "; model printing time: 14m 49s; total estimated time: 21m 5s\n"
        "; total layer number: 100\n; HEADER_BLOCK_END\n" + _MOVES,
        21 * 60 + 5,
        100,
    ),
    "orcaslicer": (
        "; generated by OrcaSlicer 2.3.2 on 2026-09-23 at 16:58:36\n; total layer number: 225\n"
        + _MOVES
        + "; filament used [mm] = 11040.26, 584.30\n; total layers count = 225\n"
        "; estimated printing time (normal mode) = 1h 50m 32s\n"
        "; estimated first layer printing time (normal mode) = 1s\n",
        1 * 3600 + 50 * 60 + 32,
        225,
    ),
    "prusaslicer": (
        "; generated by PrusaSlicer 2.9.4 on 2026-09-20 at 05:12:44 UTC\n"
        + _MOVES
        + "; estimated printing time (normal mode) = 16m 32s\n"
        "; estimated printing time (silent mode) = 17m 33s\n"
        "; estimated first layer printing time (normal mode) = 29s\n"
        "; interlocking_beam_layer_count = 2\n",
        16 * 60 + 32,
        None,
    ),
    "cura": (
        ";FLAVOR:Marlin\n;TIME:6632\n;Filament used: 4.523m\n;Layer height: 0.2\n"
        ";LAYER_COUNT:150\n;LAYER:0\n" + _MOVES + ";TIME_ELAPSED:6630.5\n",
        6632,
        150,
    ),
}


@pytest.fixture(params=sorted(_FILES))
def sliced(request, tmp_path):
    text, seconds, layers = _FILES[request.param]
    path = tmp_path / f"{request.param}.gcode"
    path.write_text(text)
    return str(path), seconds, layers


class TestEveryDoorReadsTheSameTime:
    def test_the_metadata_reader(self, sliced):
        from kiln.gcode_metadata import extract_metadata

        path, seconds, _ = sliced
        assert extract_metadata(path).estimated_time_seconds == seconds

    def test_file_details(self, sliced):
        from kiln.file_metadata import extract_metadata

        path, seconds, layers = sliced
        meta = extract_metadata(path)
        assert meta.estimated_time_seconds == seconds
        assert meta.layer_count == layers

    def test_the_cost_tool(self, sliced):
        from kiln.cost_estimator import CostEstimator

        path, seconds, _ = sliced
        assert CostEstimator().estimate_from_file(path).estimated_time_seconds == seconds

    def test_the_print_time_tool(self, sliced):
        from kiln.slicer import _parse_gcode_estimates

        path, seconds, layers = sliced
        estimates = _parse_gcode_estimates(path)
        assert estimates["estimated_time_seconds"] == seconds
        assert estimates.get("layer_count") == layers

    def test_the_print_time_tool_gives_words_only_where_the_slicer_wrote_them(self, sliced):
        from kiln.slicer import _parse_gcode_estimates

        path, _, _ = sliced
        words = {"bambu_studio": "21m 5s", "orcaslicer": "1h 50m 32s", "prusaslicer": "16m 32s", "cura": None}
        expected = words[Path(path).stem]
        assert _parse_gcode_estimates(path).get("estimated_time_human") == expected

    @patch("kiln.server._get_adapter")
    @patch("kiln.server._get_temp_limits", return_value=(280.0, 120.0))
    @patch("kiln.server.get_db")
    @patch("kiln.server._registry")
    def test_preflights_cost_advisory(self, mock_registry, mock_get_db, mock_limits, mock_adapter, sliced):
        from kiln.server import preflight_check

        state = MagicMock()
        state.connected = True
        state.state = PrinterStatus.IDLE
        state.tool_temp_actual = state.bed_temp_actual = 25.0
        state.tool_temp_target = state.bed_temp_target = 0.0
        mock_adapter.return_value.get_state.return_value = state

        path, seconds, _ = sliced
        result = preflight_check(file_path=path)
        assert result["estimated_cost"]["total_print_time_hours"] == pytest.approx(round(seconds / 3600, 2))


class TestAMergedFileStatesItsOwnTotals:
    """A file Kiln merges from separately sliced parts states the whole
    print's time, layer total and each tool's filament at its top, in the
    slicers' own spellings.  Each part's footer still rides in the body, so
    without those lines every door took the first part's figures for the
    whole print's."""

    def _part(self, tmp_path: Path, name: str, header: str, footer: str, x0: float) -> str:
        lines = [header, "G90", "M83"]
        for z in (0.2, 0.4):
            lines += [";LAYER_CHANGE", f";Z:{z}", f"G1 Z{z} F3000", f"G1 X{x0} Y5 E.5", f"G1 X{x0 + 10} Y15 E.5"]
        path = tmp_path / name
        path.write_text("\n".join(lines) + "\n" + footer)
        return str(path)

    def _merged(self, tmp_path: Path) -> str:
        from kiln.slicer import merge_multipart_gcode

        orca = self._part(
            tmp_path, "orca.gcode", "; generated by OrcaSlicer 2.3.2",
            "; filament used [mm] = 2.00\n; filament used [g] = 0.01\n"
            "; estimated printing time (normal mode) = 1h 50m 32s\n"
            "; filament_type = PLA\n",
            10.0,
        )
        studio = self._part(
            tmp_path, "studio.gcode",
            "; model printing time: 14m 49s; total estimated time: 21m 5s\n"
            "; total filament length [mm] : 2.00\n; total filament weight [g] : 0.01\n"
            "; filament_type = PETG",
            "", 60.0,
        )
        result = merge_multipart_gcode(
            [
                {"gcode_path": orca, "tool_index": 0, "name": "left"},
                {"gcode_path": studio, "tool_index": 1, "name": "right"},
            ],
            output_path=str(tmp_path / "merged.gcode"),
        )
        assert result["estimated_time_sec"] == 6632 + 1265
        return result["output_path"]

    def test_the_file_states_the_whole_print_at_its_top(self, tmp_path):
        from kiln.gcode import (
            slicer_filament_totals,
            slicer_filament_types,
            slicer_layer_count,
            slicer_print_time,
        )

        text = Path(self._merged(tmp_path)).read_text()
        assert slicer_print_time(text).seconds == 6632 + 1265
        assert slicer_layer_count(text) == 2
        totals = slicer_filament_totals(text)
        assert totals.mm == (2.0, 2.0)
        assert totals.grams == (0.01, 0.01)
        # Each tool's type, from its own part: the left part's settings
        # block rides in the body, the right part's header does not.
        assert slicer_filament_types(text) == ("PLA", "PETG")

    def test_every_door_reads_the_merged_totals(self, tmp_path):
        from kiln.cost_estimator import CostEstimator
        from kiln.file_metadata import extract_metadata as file_details
        from kiln.gcode_metadata import extract_metadata
        from kiln.printers.bambu_3mf import filament_usage_from_gcode
        from kiln.slicer import _parse_gcode_estimates

        path = self._merged(tmp_path)
        seconds = 6632 + 1265
        assert extract_metadata(path).estimated_time_seconds == seconds
        details = file_details(path)
        assert (details.estimated_time_seconds, details.layer_count) == (seconds, 2)
        estimates = _parse_gcode_estimates(path)
        assert (estimates["estimated_time_seconds"], estimates["layer_count"]) == (seconds, 2)
        cost = CostEstimator().estimate_from_file(path)
        assert cost.estimated_time_seconds == seconds
        assert cost.filament_length_meters == pytest.approx(0.004)
        assert cost.filament_source == "slicer_header" and cost.warnings == []
        assert [f["material"] for f in cost.filaments] == ["PLA", "PETG"]
        assert extract_metadata(path).material == "PLA + PETG"
        assert filament_usage_from_gcode(Path(path).read_text()).mm == (2.0, 2.0)

    def test_the_printer_screen_shows_the_merged_time(self, tmp_path):
        import re
        import zipfile

        from kiln.printers import bambu_3mf

        out = str(tmp_path / "merged.gcode.3mf")
        bambu_3mf.build_bambu_3mf(Path(self._merged(tmp_path)).read_text(), out)
        with zipfile.ZipFile(out) as zf:
            info = zf.read("Metadata/slice_info.config").decode()
        prediction = int(re.search(r'<metadata key="prediction" value="(\d+)"', info).group(1))
        # Kiln's start sequence adds a fixed allowance to what the slicers said.
        assert prediction == 6632 + 1265 + bambu_3mf._BAMBU_STARTUP_OVERHEAD_SEC
