"""load_tables.json is DERIVED data — prove it, in the public suite.

The 2026-07-16 physics audit found the previous hand-authored table
exceeded the raw bending capacity of any compact cross-section ~4x
while claiming a 3x safety margin. The table is now generated by
kiln/scripts/generate_load_tables.py from the cantilever bending
formula; these tests keep it that way even when this repo is built
standalone (kiln-pro's physics-truth gate adds the cross-catalogue
check on its side).
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TABLE_PATH = REPO_ROOT / "src" / "kiln" / "data" / "design_knowledge" / "load_tables.json"
GENERATOR_PATH = REPO_ROOT / "scripts" / "generate_load_tables.py"


def _load_generator():
    spec = importlib.util.spec_from_file_location("generate_load_tables", GENERATOR_PATH)
    mod = importlib.util.module_from_spec(spec)
    sys.modules.setdefault("generate_load_tables", mod)
    spec.loader.exec_module(mod)
    return mod


def _table() -> dict:
    return json.loads(TABLE_PATH.read_text(encoding="utf-8"))


def test_table_matches_its_generator_exactly():
    gen = _load_generator()
    rendered = json.dumps(gen.build(), indent=2) + "\n"
    assert TABLE_PATH.read_text(encoding="utf-8") == rendered, (
        "load_tables.json was hand-edited — regenerate it with "
        "kiln/scripts/generate_load_tables.py (and change the generator, "
        "not the JSON, if a value must move)"
    )


def test_every_load_rederives_from_the_bending_formula():
    gen = _load_generator()
    doc = _table()
    for material, entry in doc.items():
        if material.startswith("_"):
            continue
        if entry.get("limit_mode") == "deflection":
            continue  # a different model — re-derived in its own test below
        cap = entry["tensile_capacity_n_per_mm2"]
        # The capacity field itself re-derives from the declared basis.
        expected_cap = round(
            gen.SIGMA_T_MPA[material] * gen.FDM_PRINT_FACTOR / gen.SAFETY_FACTOR, 1
        )
        assert cap == expected_cap, material
        for row in entry["cross_section_vs_load"]:
            length = row["cantilever_length_mm"]
            for cell in row["entries"]:
                area = cell["cross_section_mm2"]
                z_mm3 = area ** 1.5 / 6.0
                exact = cap * z_mm3 / length
                # Stored value is floor-rounded: never above the formula,
                # never more than one rounding step below it.
                assert cell["max_load_n"] <= exact + 1e-9, (material, length, area)
                assert cell["max_load_n"] >= exact - 0.01, (material, length, area)


def test_orientation_pair_is_weak_below_strong_everywhere():
    for material, entry in _table().items():
        if material.startswith("_"):
            continue
        if entry.get("limit_mode") == "deflection":
            continue  # deflection is a stiffness limit; no strength derate applies
        od = entry["layer_orientation_derating"]
        assert od["across_layers"] < od["along_layers"], material
        assert 0.0 < od["across_layers"] <= 0.6, material
        assert od["along_layers"] == 1.0, material


def test_table_monotonic_in_area_and_length():
    for material, entry in _table().items():
        if material.startswith("_"):
            continue
        deflection = entry.get("limit_mode") == "deflection"
        key = "cross_section_vs_deflection_load" if deflection else "cross_section_vs_load"
        load_key = "load_at_deflection_limit_n" if deflection else "max_load_n"
        rows = sorted(entry[key], key=lambda r: r["cantilever_length_mm"])
        for row in rows:
            loads = [c[load_key] for c in row["entries"]]
            assert loads == sorted(loads) and len(set(loads)) == len(loads), (
                material, row["cantilever_length_mm"])
        for r1, r2 in zip(rows, rows[1:]):
            for c1, c2 in zip(r1["entries"], r2["entries"]):
                assert c2[load_key] < c1[load_key], (
                    material, r1["cantilever_length_mm"], r2["cantilever_length_mm"])


def test_every_deflection_load_rederives_from_the_stiffness_formula():
    """The elastomer entries re-derive too — a different model, equally pinned.

    F = E * A^2 / (4 * ratio * L^2), the cantilever deflection equation
    d = F L^3 / (3 E I) solved for the load at an allowable deflection, with
    a square section (I = A^2/12) to match the strength table's basis.
    """
    gen = _load_generator()
    for material, entry in _table().items():
        if material.startswith("_") or entry.get("limit_mode") != "deflection":
            continue
        e_mpa = entry["youngs_modulus_mpa"]
        assert e_mpa == gen.E_MODULUS_MPA[material], material
        ratio = entry["deflection_limit_ratio"]
        for row in entry["cross_section_vs_deflection_load"]:
            length = row["cantilever_length_mm"]
            assert row["allowable_deflection_mm"] == round(length / ratio, 2), material
            for cell in row["entries"]:
                area = cell["cross_section_mm2"]
                exact = e_mpa * (area ** 2) / (4.0 * ratio * (length ** 2))
                stored = cell["load_at_deflection_limit_n"]
                # floor-rounded: never above the formula, never a full step below
                assert stored <= exact + 1e-9, (material, length, area)
                assert stored >= exact - 0.0001, (material, length, area)
