"""One picker of the G-code a sliced 3MF prints, and one bounded reader
of it, at every door that unzips a print file.

Coverage: the print gate, both bed-fit readers, the safe-motion reader,
AMS routing and the cost tool all read a 3MF's plate through
``kiln.gcode_metadata.sliced_gcode_member`` + ``read_member_text``; a
member compressed so it cannot be unpacked in chunks is refused at each
of them rather than inflated; and a source gate that fails when a module
picks the plate its own way again.
"""

from __future__ import annotations

import ast
import zipfile
from pathlib import Path

_SRC = Path(__file__).resolve().parents[1] / "src" / "kiln"
_PLATE = "; generated by OrcaSlicer 2.3.2\nM83\nG1 X10 Y10 Z0.2 E1\nG1 X20 Y20 E1\n; filament used [mm] = 2.00\n"


def _archive(tmp_path: Path, compression: int) -> str:
    path = tmp_path / "plate.gcode.3mf"
    with zipfile.ZipFile(path, "w", compression=compression) as zf:
        zf.writestr("Metadata/plate_1.gcode", _PLATE)
    return str(path)


class TestEveryDoorReadsThroughTheOnePicker:
    def test_the_print_gate_reads_a_deflated_plate_and_refuses_a_bzip2_one(self, tmp_path):
        from kiln.printers.print_gate import _gcode_head as _gcode_lines

        assert _gcode_lines(_archive(tmp_path, zipfile.ZIP_DEFLATED), max_lines=10)[0].startswith("; generated")
        assert _gcode_lines(_archive(tmp_path, zipfile.ZIP_BZIP2), max_lines=10) is None

    def test_safe_motion_reads_a_deflated_plate_and_refuses_a_bzip2_one(self, tmp_path):
        from kiln.printers.safe_motion import _job_gcode_lines

        assert _job_gcode_lines(_archive(tmp_path, zipfile.ZIP_DEFLATED)).read().startswith("; generated")
        assert _job_gcode_lines(_archive(tmp_path, zipfile.ZIP_BZIP2)) is None

    def test_bed_fit_reads_a_deflated_plate_and_refuses_a_bzip2_one(self, tmp_path):
        from kiln.printers.bed_fit import compute_3mf_bbox

        assert compute_3mf_bbox(_archive(tmp_path, zipfile.ZIP_DEFLATED)) is not None
        assert compute_3mf_bbox(_archive(tmp_path, zipfile.ZIP_BZIP2)) is None

    def test_a_member_that_lies_about_its_size_is_refused_within_a_bound(self, tmp_path, monkeypatch):
        import kiln.gcode
        from kiln.printers.print_gate import _gcode_head as _gcode_lines

        monkeypatch.setattr(kiln.gcode, "_MAX_SCAN_BYTES", 32)
        assert _gcode_lines(_archive(tmp_path, zipfile.ZIP_DEFLATED), max_lines=10) is None


#: Modules that name the Bambu plate prefix for a reason other than
#: unpacking a plate's G-code, each with why.
_NOT_PICKERS = {
    "gcode_metadata.py": "the one picker",
    "printers/bambu_3mf.py": "asks whether a plate exists; never unpacks one",
    "nozzle_clumping_detection.py": "lists plate JSON, not G-code",
}


class TestNoModulePicksThePlateItsOwnWay:
    def test_no_private_picker_of_the_plates_gcode(self):
        offenders = []
        for path in sorted(_SRC.rglob("*.py")):
            rel = str(path.relative_to(_SRC))
            if rel in _NOT_PICKERS:
                continue
            for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
                if (
                    isinstance(node, ast.Call)
                    and isinstance(node.func, ast.Attribute)
                    and node.func.attr == "startswith"
                    and node.args
                    and isinstance(node.args[0], ast.Constant)
                    and node.args[0].value == "Metadata/plate_"
                ):
                    offenders.append(f"{rel}:{node.lineno}")
        assert offenders == [], (
            "pick the plate with kiln.gcode_metadata.sliced_gcode_member and read it with "
            f"read_member_text instead: {offenders}"
        )
