"""Tests for the G-code metadata extraction module (kiln.gcode_metadata).

Covers:
    - PrusaSlicer / OrcaSlicer / BambuStudio comment patterns
    - Cura comment patterns
    - Simplify3D comment patterns
    - Time string parsing (all formats)
    - Material name normalisation
    - Temperature fallback from M-commands
    - PrinterFile enrichment
    - Edge cases (empty, binary, no metadata, huge header)
"""

from __future__ import annotations

import pytest

from kiln.gcode_metadata import (
    GCodeMetadata,
    _normalize_material,
    enrich_printer_file,
    extract_metadata,
    extract_metadata_from_content,
)
from kiln.printers.base import PrinterFile

# ===================================================================
# GCodeMetadata dataclass
# ===================================================================

class TestGCodeMetadataDataclass:
    """Verify the metadata dataclass defaults and to_dict behaviour."""

    def test_defaults_are_none(self) -> None:
        meta = GCodeMetadata()
        assert meta.material is None
        assert meta.estimated_time_seconds is None
        assert meta.tool_temp is None
        assert meta.bed_temp is None
        assert meta.slicer is None
        assert meta.layer_height is None
        assert meta.filament_used_mm is None
        assert meta.printer_model is None

    def test_to_dict_omits_none(self) -> None:
        meta = GCodeMetadata(material="PLA", tool_temp=210.0)
        d = meta.to_dict()
        assert d == {"material": "PLA", "tool_temp": 210.0}
        assert "bed_temp" not in d
        assert "slicer" not in d

    def test_to_dict_full(self) -> None:
        meta = GCodeMetadata(
            material="PETG",
            estimated_time_seconds=3600,
            tool_temp=240.0,
            bed_temp=80.0,
            slicer="PrusaSlicer 2.7.0",
            layer_height=0.2,
            filament_used_mm=4523.45,
            printer_model="Ender 3",
        )
        d = meta.to_dict()
        assert len(d) == 8
        assert d["material"] == "PETG"
        assert d["estimated_time_seconds"] == 3600

    def test_independent_instances(self) -> None:
        m1 = GCodeMetadata()
        m2 = GCodeMetadata()
        m1.material = "PLA"
        assert m2.material is None


# ===================================================================
# Material normalisation
# ===================================================================

class TestMaterialExtraction:
    """Test material name normalisation."""

    def test_simple_uppercase(self) -> None:
        assert _normalize_material("PLA") == "PLA"

    def test_lowercase_normalised(self) -> None:
        assert _normalize_material("pla") == "PLA"

    def test_mixed_case(self) -> None:
        assert _normalize_material("Petg") == "PETG"

    def test_whitespace_stripped(self) -> None:
        assert _normalize_material("  ABS  ") == "ABS"

    def test_full_name_alias(self) -> None:
        assert _normalize_material("Polylactic Acid") == "PLA"

    def test_tpu_alias(self) -> None:
        assert _normalize_material("Thermoplastic Polyurethane") == "TPU"

    def test_unknown_material_passthrough(self) -> None:
        assert _normalize_material("Nylon-CF") == "NYLON-CF"


# ===================================================================
# PrusaSlicer / OrcaSlicer / BambuStudio parsing
# ===================================================================

class TestExtractMetadataPrusaSlicer:
    """Test parsing from PrusaSlicer-style G-code headers."""

    def test_full_prusa_header(self) -> None:
        content = (
            "; generated by PrusaSlicer 2.7.0\n"
            "; filament_type = PLA\n"
            "; estimated printing time (normal mode) = 1h 42m 30s\n"
            "; temperature = 210\n"
            "; bed_temperature = 60\n"
            "; layer_height = 0.2\n"
            "; filament used [mm] = 4523.45\n"
            "; printer_model = Original Prusa i3 MK3S\n"
            "G28\n"
            "M104 S210\n"
        )
        meta = extract_metadata_from_content(content)
        assert meta.material == "PLA"
        assert meta.estimated_time_seconds == 6150
        assert meta.tool_temp == 210.0
        assert meta.bed_temp == 60.0
        assert meta.slicer == "PrusaSlicer 2.7.0"
        assert meta.layer_height == pytest.approx(0.2)
        assert meta.filament_used_mm == pytest.approx(4523.45)
        assert meta.printer_model == "Original Prusa i3 MK3S"

    def test_orcaslicer_header(self) -> None:
        content = (
            "; generated by OrcaSlicer 1.8.0\n"
            "; filament_type = PETG\n"
            "; estimated printing time (normal mode) = 3h 15m\n"
            "; nozzle_temperature = 240\n"
            "; bed_temperature = 80\n"
            "; layer_height = 0.15\n"
        )
        meta = extract_metadata_from_content(content)
        assert meta.material == "PETG"
        assert meta.estimated_time_seconds == 11700
        assert meta.tool_temp == 240.0
        assert meta.bed_temp == 80.0
        assert meta.slicer == "OrcaSlicer 1.8.0"
        assert meta.layer_height == pytest.approx(0.15)

    def test_partial_prusa_header(self) -> None:
        content = (
            "; filament_type = ABS\n"
            "; layer_height = 0.3\n"
        )
        meta = extract_metadata_from_content(content)
        assert meta.material == "ABS"
        assert meta.layer_height == pytest.approx(0.3)
        assert meta.estimated_time_seconds is None
        assert meta.tool_temp is None


# ===================================================================
# Cura parsing
# ===================================================================

class TestExtractMetadataCura:
    """Test parsing from Cura-style G-code headers."""

    def test_full_cura_header(self) -> None:
        content = (
            ";Generated with Cura_SteamEngine 5.5.0\n"
            ";MATERIAL:PLA\n"
            ";TIME:6150\n"
            ";Filament used: 4.523m\n"
            ";Layer height: 0.2\n"
            ";MACHINE_TYPE:Ender-3 V2\n"
        )
        meta = extract_metadata_from_content(content)
        assert meta.material == "PLA"
        assert meta.estimated_time_seconds == 6150
        assert meta.filament_used_mm == pytest.approx(4523.0)
        assert meta.layer_height == pytest.approx(0.2)
        assert meta.slicer == "Cura_SteamEngine 5.5.0"
        assert meta.printer_model == "Ender-3 V2"

    def test_two_filaments_are_summed(self) -> None:
        # OrcaSlicer lists one value per extruder; a reader that kept the
        # first lost the second filament of a two-colour plate.
        content = "; filament used [mm] = 11040.26, 584.30\n"
        meta = extract_metadata_from_content(content)
        assert meta.filament_used_mm == pytest.approx(11624.56)

    def test_cura_filament_in_mm(self) -> None:
        content = ";Filament used: 4523.0mm\n"
        meta = extract_metadata_from_content(content)
        assert meta.filament_used_mm == pytest.approx(4523.0)

    def test_cura_filament_in_metres(self) -> None:
        content = ";Filament used: 4.523m\n"
        meta = extract_metadata_from_content(content)
        assert meta.filament_used_mm == pytest.approx(4523.0)


# ===================================================================
# Simplify3D parsing
# ===================================================================

class TestExtractMetadataSimplify3D:
    """Test parsing from Simplify3D-style G-code headers."""

    def test_full_s3d_header(self) -> None:
        content = (
            "; Simplify3D(R) Version 5.0\n"
            "; extruder0Temp,210\n"
            "; platformTemp,60\n"
            "; Build time: 1 hours 42 minutes\n"
            "; Filament length: 4523.4 mm\n"
            "; layerHeight,0.20\n"
        )
        meta = extract_metadata_from_content(content)
        assert meta.tool_temp == 210.0
        assert meta.bed_temp == 60.0
        assert meta.estimated_time_seconds == 6120
        assert meta.filament_used_mm == pytest.approx(4523.4)
        assert meta.layer_height == pytest.approx(0.2)
        assert meta.slicer == "5.0"

    def test_s3d_filament_in_metres(self) -> None:
        content = "; Filament length: 4.523 m\n"
        meta = extract_metadata_from_content(content)
        assert meta.filament_used_mm == pytest.approx(4523.0)


# ===================================================================
# Temperature fallback from M-commands
# ===================================================================

class TestTemperatureFallback:
    """Test M-command fallback when no slicer comments provide temps."""

    def test_m104_fallback(self) -> None:
        content = "G28\nM104 S215\nM140 S65\nG1 X10\n"
        meta = extract_metadata_from_content(content)
        assert meta.tool_temp == 215.0
        assert meta.bed_temp == 65.0

    def test_m109_fallback(self) -> None:
        content = "G28\nM109 S200\n"
        meta = extract_metadata_from_content(content)
        assert meta.tool_temp == 200.0

    def test_m190_fallback(self) -> None:
        content = "G28\nM190 S70\n"
        meta = extract_metadata_from_content(content)
        assert meta.bed_temp == 70.0

    def test_comment_temps_override_mcommands(self) -> None:
        content = (
            "; temperature = 210\n"
            "; bed_temperature = 60\n"
            "M104 S220\n"
            "M140 S70\n"
        )
        meta = extract_metadata_from_content(content)
        # Comment temps take priority
        assert meta.tool_temp == 210.0
        assert meta.bed_temp == 60.0

    def test_m104_s0_ignored(self) -> None:
        """M104 S0 (heater off) should not be used as fallback."""
        content = "M104 S0\nM104 S200\n"
        meta = extract_metadata_from_content(content)
        assert meta.tool_temp == 200.0

    def test_m140_s0_ignored(self) -> None:
        """M140 S0 (bed off) should not be used as fallback."""
        content = "M140 S0\nM140 S60\n"
        meta = extract_metadata_from_content(content)
        assert meta.bed_temp == 60.0

    def test_no_temps_at_all(self) -> None:
        content = "G28\nG1 X10 Y10\n"
        meta = extract_metadata_from_content(content)
        assert meta.tool_temp is None
        assert meta.bed_temp is None


# ===================================================================
# enrich_printer_file
# ===================================================================

class TestEnrichPrinterFile:
    """Test the enrichment function that mutates a PrinterFile."""

    def test_basic_enrichment(self) -> None:
        pf = PrinterFile(name="test.gcode", path="/test.gcode")
        content = (
            "; filament_type = PLA\n"
            "; temperature = 210\n"
            "; bed_temperature = 60\n"
            "; layer_height = 0.2\n"
        )
        enrich_printer_file(pf, file_content=content)
        assert pf.material == "PLA"
        assert pf.tool_temp == 210.0
        assert pf.bed_temp == 60.0
        assert pf.layer_height == pytest.approx(0.2)

    def test_no_content_is_noop(self) -> None:
        pf = PrinterFile(name="test.gcode", path="/test.gcode")
        enrich_printer_file(pf, file_content=None)
        assert pf.material is None
        assert pf.tool_temp is None

    def test_does_not_overwrite_existing(self) -> None:
        pf = PrinterFile(
            name="test.gcode", path="/test.gcode",
            material="PETG", tool_temp=240.0,
        )
        content = "; filament_type = PLA\n; temperature = 210\n"
        enrich_printer_file(pf, file_content=content)
        # Existing values should NOT be overwritten
        assert pf.material == "PETG"
        assert pf.tool_temp == 240.0

    def test_empty_content_is_safe(self) -> None:
        pf = PrinterFile(name="test.gcode", path="/test.gcode")
        enrich_printer_file(pf, file_content="")
        assert pf.material is None

    def test_enrichment_from_mcommands(self) -> None:
        pf = PrinterFile(name="test.gcode", path="/test.gcode")
        content = "G28\nM104 S195\nM140 S55\n"
        enrich_printer_file(pf, file_content=content)
        assert pf.tool_temp == 195.0
        assert pf.bed_temp == 55.0


# ===================================================================
# File-based extraction
# ===================================================================

class TestExtractMetadataFromFile:
    """Test file-based extraction using tmpfile."""

    def test_from_file(self, tmp_path) -> None:
        gcode = tmp_path / "test.gcode"
        gcode.write_text(
            "; filament_type = PETG\n"
            "; estimated printing time (normal mode) = 2h 15m\n"
            "; temperature = 240\n"
            "; bed_temperature = 80\n"
            "G28\n"
        )
        meta = extract_metadata(str(gcode))
        assert meta.material == "PETG"
        assert meta.estimated_time_seconds == 8100
        assert meta.tool_temp == 240.0
        assert meta.bed_temp == 80.0

    def test_nonexistent_file(self) -> None:
        meta = extract_metadata("/nonexistent/path/test.gcode")
        # Should not raise -- returns empty metadata
        assert meta.material is None
        assert meta.estimated_time_seconds is None


# ===================================================================
# Edge cases
# ===================================================================

class TestEdgeCases:
    """Edge cases: empty file, binary file, no metadata, huge header."""

    def test_empty_content(self) -> None:
        meta = extract_metadata_from_content("")
        assert meta.material is None
        assert meta.to_dict() == {}

    def test_no_metadata_in_content(self) -> None:
        content = "G28\nG1 X10 Y10 Z0.2 F1200\nG1 X20 Y20 E1.5\n"
        meta = extract_metadata_from_content(content)
        assert meta.material is None
        assert meta.slicer is None
        assert meta.layer_height is None

    def test_binary_content(self) -> None:
        """Binary content should not crash the parser."""
        content = "\x00\x01\x02\xff\xfe\xfd"
        meta = extract_metadata_from_content(content)
        assert meta.material is None

    def test_only_comments_no_metadata(self) -> None:
        content = (
            "; This is a custom G-code file\n"
            "; Created by hand\n"
            "; No slicer metadata here\n"
        )
        meta = extract_metadata_from_content(content)
        assert meta.material is None
        assert meta.slicer is None

    def test_metadata_beyond_max_lines(self) -> None:
        """Metadata in the MIDDLE of a long file is not picked up.

        The scan reads two windows — the header (Bambu/Orca style) and the
        footer (PrusaSlicer writes its totals at the END, ~350 lines above
        EOF under its config dump; a header-only scan answered "unknown"
        for time and filament on every PrusaSlicer file).  A value outside
        both windows stays invisible.
        """
        lines = ["; unrelated comment\n"] * 1100
        lines.append("; filament_type = PLA\n")
        lines.extend(["; more padding\n"] * 1100)
        content = "".join(lines)
        meta = extract_metadata_from_content(content)
        # PLA sits past the 1000-line header and more than 1000 lines above
        # the end — outside both windows.
        assert meta.material is None

    def test_footer_totals_are_picked_up(self) -> None:
        """The PrusaSlicer shape: totals at the end, under a config dump."""
        lines = ["; header comment\n"] + ["G1 X0 Y0 E1\n"] * 500
        lines.append("; estimated printing time (normal mode) = 8m 42s\n")
        lines.append("; filament used [mm] = 849.94\n")
        lines.extend(["; prusaslicer_config = padding\n"] * 300)
        meta = extract_metadata_from_content("".join(lines))
        assert meta.estimated_time_seconds == 522
        assert meta.filament_used_mm == 849.94

    def test_metadata_within_max_lines(self) -> None:
        lines = ["; unrelated comment\n"] * 150
        lines.append("; filament_type = ABS\n")
        content = "".join(lines)
        meta = extract_metadata_from_content(content)
        assert meta.material == "ABS"

    def test_empty_file_on_disk(self, tmp_path) -> None:
        gcode = tmp_path / "empty.gcode"
        gcode.write_text("")
        meta = extract_metadata(str(gcode))
        assert meta.to_dict() == {}

    def test_mixed_slicer_comments(self) -> None:
        """First match wins when multiple slicer patterns appear."""
        content = (
            "; filament_type = PLA\n"
            ";MATERIAL:PETG\n"
        )
        meta = extract_metadata_from_content(content)
        # PrusaSlicer pattern matches first
        assert meta.material == "PLA"

    def test_case_insensitive_comments(self) -> None:
        content = "; FILAMENT_TYPE = pla\n; TEMPERATURE = 200\n"
        meta = extract_metadata_from_content(content)
        assert meta.material == "PLA"
        assert meta.tool_temp == 200.0


# ===================================================================
# PrinterFile.to_dict with metadata
# ===================================================================

class TestPrinterFileToDict:
    """Verify PrinterFile.to_dict strips None metadata fields."""

    def test_no_metadata(self) -> None:
        pf = PrinterFile(name="test.gcode", path="/test.gcode", size_bytes=1024)
        d = pf.to_dict()
        assert d["name"] == "test.gcode"
        assert d["size_bytes"] == 1024
        assert "material" not in d
        assert "tool_temp" not in d

    def test_with_metadata(self) -> None:
        pf = PrinterFile(
            name="test.gcode", path="/test.gcode",
            material="PLA", tool_temp=210.0,
        )
        d = pf.to_dict()
        assert d["material"] == "PLA"
        assert d["tool_temp"] == 210.0
        assert "bed_temp" not in d  # None, should be stripped

    def test_partial_metadata(self) -> None:
        pf = PrinterFile(
            name="test.gcode", path="/test.gcode",
            material="PETG", estimated_time_seconds=3600,
        )
        d = pf.to_dict()
        assert d["material"] == "PETG"
        assert d["estimated_time_seconds"] == 3600
        assert "slicer" not in d
        assert "layer_height" not in d


class TestTheWindowCoversBambuStudio:
    """Bambu Studio writes its settings block at the top and it runs past
    line 500; a 200-line window read the material and stopped."""

    def _studio_shaped(self) -> str:
        head = "; model printing time: 14m 49s; total estimated time: 21m 5s\n; total filament length [mm] : 1227.58\n; HEADER_BLOCK_END\n; CONFIG_BLOCK_START\n"
        settings = "".join(f"; setting_{i} = {i}\n" for i in range(300))
        late = "; nozzle_diameter = 0.4\n; nozzle_temperature = 220\n; printer_model = Bambu Lab P1S\n; layer_height = 0.2\n; CONFIG_BLOCK_END\n"
        return head + settings + late + "".join(f"G1 X{i} Y{i} E.05\n" for i in range(3000))

    def test_settings_past_line_200_are_read(self, tmp_path) -> None:
        path = tmp_path / "p1s.gcode"
        path.write_text(self._studio_shaped())
        meta = extract_metadata(str(path))
        assert meta.printer_model == "Bambu Lab P1S"
        assert meta.tool_temp == 220.0
        assert meta.layer_height == pytest.approx(0.2)
        assert meta.filament_used_mm == pytest.approx(1227.58)

    def test_head_and_tail_keeps_both_ends(self) -> None:
        from kiln.gcode_metadata import _MAX_FOOTER_LINES, _MAX_HEADER_LINES, head_and_tail

        lines = [str(i) for i in range(5000)]
        window = head_and_tail(lines)
        assert window[:_MAX_HEADER_LINES] == lines[:_MAX_HEADER_LINES]
        assert window[_MAX_HEADER_LINES:] == lines[-_MAX_FOOTER_LINES:]
        assert head_and_tail(lines[:10]) == lines[:10]


def _filler(n: int, width: int) -> bytes:
    """Exactly *n* bytes of whole comment lines, each at most *width* long."""
    count, rest = divmod(n, width)
    if 0 < rest < 2:
        count, rest = count - 1, rest + width
    out = (b";" + b"x" * (width - 2) + b"\n") * count
    return out + (b";" + b"x" * (rest - 2) + b"\n" if rest else b"")


class TestTheWindowEdges:
    """The top is read up to a byte budget and the end from a fixed number
    of bytes before it.  A line cut by either edge is left out, because
    its visible piece can read as a different figure; a line that starts
    or ends exactly on an edge is whole and is read."""

    def _meta(self, tmp_path, data: bytes):
        path = tmp_path / "edge.gcode"
        path.write_bytes(data)
        return extract_metadata(str(path))

    def test_a_whole_line_starting_exactly_at_the_end_window_is_read(self, tmp_path) -> None:
        from kiln.gcode_metadata import _FOOTER_BYTES, _HEADER_BYTES

        time_line = b"; estimated printing time (normal mode) = 1h 50m 32s\n"
        data = _filler(_HEADER_BYTES + 100_000, 4096) + time_line + _filler(_FOOTER_BYTES - len(time_line), 256)
        assert self._meta(tmp_path, data).estimated_time_seconds == 6632

    def test_a_line_cut_by_the_end_window_is_not_read(self, tmp_path) -> None:
        from kiln.gcode_metadata import _FOOTER_BYTES, _HEADER_BYTES

        # The whole line is "; note = abc;TIME:5", which is no time at all;
        # the window starts at its ";TIME:5", which would read as 5 s.
        data = (
            _filler(_HEADER_BYTES + 100_000 - 12, 4096) + b"; note = abc"
            + b";TIME:5\n" + _filler(_FOOTER_BYTES - 8, 256)
        )
        assert self._meta(tmp_path, data).estimated_time_seconds is None

    def test_a_line_cut_by_the_top_budget_is_not_read(self, tmp_path) -> None:
        from kiln.gcode_metadata import _HEADER_BYTES

        # The budget ends after ";TIME:66" of ";TIME:6632123".
        data = _filler(_HEADER_BYTES - 8, 4096) + b";TIME:6632123\n" + _filler(300_000, 4096)
        assert self._meta(tmp_path, data).estimated_time_seconds is None

    def test_a_whole_line_ending_exactly_at_the_top_budget_is_read(self, tmp_path) -> None:
        from kiln.gcode_metadata import _HEADER_BYTES

        data = _filler(_HEADER_BYTES - 10, 4096) + b";TIME:6632\n" + _filler(300_000, 4096)
        assert self._meta(tmp_path, data).estimated_time_seconds == 6632
