"""Wrapping multicolor gcode as a Bambu 3MF without losing the colors.

The second half of the multicolor slicing fix, and the door the print
actually goes through.  ``build_bambu_3mf`` already knew how to declare
several filaments — nothing told it to: every caller left
``num_filaments`` at its default, so a gcode with 186 tool changes was
packaged with ONE filament in ``slice_info.config``, a
``filament_sequence`` of ``[0]``, and none of the M620/M621 AMS load
blocks that make a tool change actually swap material.  The toolpath was
right and everything the printer reads said one color.

The gcode is the authority here — these slicers write
``; filament_colour = a;b;c`` and one ``T`` per change — so the wrapper
reads it rather than each caller being asked to pass it down.
"""

from __future__ import annotations

import re
import zipfile
from pathlib import Path

import pytest

from kiln.printers.bambu_3mf import (
    BambuPrintSettings,
    _declared_filaments_in_gcode,
    _reset_cache,
    build_bambu_3mf,
)


@pytest.fixture(autouse=True)
def _clear_singleton_cache():
    _reset_cache()
    yield
    _reset_cache()


def _layers(n: int = 2, tools: list[int] | None = None) -> str:
    """A PrusaSlicer-shaped body, optionally changing tool each layer."""
    out = ["; generated by PrusaSlicer", "M83", "G28", "M104 S200"]
    for i in range(n):
        out += [
            ";BEFORE_LAYER_CHANGE",
            f";Z:{0.2 * (i + 1):.1f}",
            ";LAYER_CHANGE",
            f"G1 Z{0.2 * (i + 1):.1f} F600",
        ]
        if tools:
            out.append(f"T{tools[i % len(tools)]}")
        out.append(f"G1 X{10 * (i + 1)} Y10 E0.5")
    return "\n".join(out) + "\n"


_MULTICOLOR_GCODE = (
    _layers(4, tools=[0, 1, 2, 0])
    + "; filament_colour = #F2F2F2;#D32F2F;#1A1A1A\n"
    + "; filament_type = PLA;PETG;PLA\n"
    + "; filament used [mm] = 100.0, 50.0, 25.0\n"
)


# ---------------------------------------------------------------------------
# Reading what the gcode declares
# ---------------------------------------------------------------------------


class TestDeclaredFilamentsInGcode:
    def test_reads_count_colors_and_types(self):
        assert _declared_filaments_in_gcode(_MULTICOLOR_GCODE) == (
            3,
            ["#F2F2F2", "#D32F2F", "#1A1A1A"],
            ["PLA", "PETG", "PLA"],
        )

    def test_single_filament_gcode_reads_as_none(self):
        assert _declared_filaments_in_gcode(_layers(2, tools=[0])) is None

    def test_toolless_gcode_reads_as_none(self):
        assert _declared_filaments_in_gcode(_layers(2)) is None

    def test_count_is_highest_tool_not_distinct_count(self):
        """A print using T0 and T2 needs THREE trays declared, or T2 maps
        to nothing on the printer."""
        count, _colors, _types = _declared_filaments_in_gcode(
            _layers(2, tools=[0, 2])
        )
        assert count == 3

    def test_heater_targeting_is_not_a_tool_change(self):
        """``M104 T0 S200`` sets a heater; it must not read as a tool."""
        body = _layers(2) + "M104 T0 S200\nM109 T1 S220\n"
        assert _declared_filaments_in_gcode(body) is None

    def test_short_color_declaration_is_padded_not_dropped(self):
        """The consumer drops a color list shorter than the slot count —
        which would throw away the real colors the gcode DID state."""
        body = (
            _layers(3, tools=[0, 1, 2])
            + "; filament_colour = #AA0000;#00BB00\n"
        )
        count, colors, _types = _declared_filaments_in_gcode(body)
        assert count == 3
        assert colors[:2] == ["#AA0000", "#00BB00"]
        assert len(colors) == 3

    def test_undeclared_colors_stay_empty(self):
        _count, colors, types = _declared_filaments_in_gcode(
            _layers(2, tools=[0, 1])
        )
        assert colors == []
        assert types == []


# ---------------------------------------------------------------------------
# What the printer ends up reading
# ---------------------------------------------------------------------------


def _wrap(tmp_path: Path, body: str, **kw) -> zipfile.ZipFile:
    out = tmp_path / "out.3mf"
    build_bambu_3mf(body, str(out), **kw)
    return zipfile.ZipFile(out)


class TestMulticolorWrap:
    def test_slice_info_declares_every_filament(self, tmp_path):
        zf = _wrap(tmp_path, _MULTICOLOR_GCODE)
        info = zf.read("Metadata/slice_info.config").decode()
        entries = re.findall(r'<filament id="(\d+)"[^>]*color="([^"]+)"', info)
        assert entries == [
            ("1", "#F2F2F2"), ("2", "#D32F2F"), ("3", "#1A1A1A"),
        ]

    def test_filament_sequence_covers_every_slot(self, tmp_path):
        zf = _wrap(tmp_path, _MULTICOLOR_GCODE)
        seq = zf.read("Metadata/filament_sequence.json").decode()
        assert '"filament_sequence": [0, 1, 2]' in seq

    def test_tool_changes_get_ams_blocks(self, tmp_path):
        """Without M620/M621 around each T, the printer changes tool and
        keeps extruding the filament already loaded."""
        zf = _wrap(tmp_path, _MULTICOLOR_GCODE)
        body = zf.read("Metadata/plate_1.gcode").decode(errors="replace")
        assert body.count("M620") >= 3
        assert body.count("M621") >= 3

    def test_declared_types_survive(self, tmp_path):
        zf = _wrap(tmp_path, _MULTICOLOR_GCODE)
        info = zf.read("Metadata/slice_info.config").decode()
        assert 'type="PETG"' in info

    def test_explicit_settings_win_over_the_gcode(self, tmp_path):
        """A caller that already knows its filaments is not overridden."""
        zf = _wrap(
            tmp_path,
            _MULTICOLOR_GCODE,
            settings=BambuPrintSettings(
                num_filaments=2, filament_colors=["#123456", "#654321"],
            ),
        )
        info = zf.read("Metadata/slice_info.config").decode()
        colors = re.findall(r'<filament id="\d+"[^>]*color="([^"]+)"', info)
        assert colors == ["#123456", "#654321"]


class TestSingleFilamentUnchanged:
    """The regression guard: an ordinary one-color wrap is untouched."""

    def test_single_filament_declares_one(self, tmp_path):
        zf = _wrap(tmp_path, _layers(3, tools=[0]))
        info = zf.read("Metadata/slice_info.config").decode()
        assert len(re.findall(r"<filament id=", info)) == 1
        seq = zf.read("Metadata/filament_sequence.json").decode()
        assert '"filament_sequence": [0]' in seq

    def test_toolless_gcode_declares_one(self, tmp_path):
        zf = _wrap(tmp_path, _layers(3))
        info = zf.read("Metadata/slice_info.config").decode()
        assert len(re.findall(r"<filament id=", info)) == 1

    def test_single_filament_gets_no_extra_ams_blocks(self, tmp_path):
        """Bambu's own start/end gcode carries a couple of M620s (initial
        load, return-to-AMS), so the honest measure is the DIFFERENCE: a
        one-tool body must add none beyond what a toolless body has, and
        a three-tool body must add several."""

        def m620s(body: str) -> int:
            zf = _wrap(tmp_path, body)
            return zf.read("Metadata/plate_1.gcode").decode(
                errors="replace"
            ).count("M620")

        baseline = m620s(_layers(3))
        assert m620s(_layers(3, tools=[0])) == baseline
        assert m620s(_MULTICOLOR_GCODE) > baseline
