"""A file that leaves Kiln for ANY printer carries its preview and its weight.

The Bambu half of this rule is held by ``test_bambu_thumbnail_invariant``:
a ``.gcode.3mf`` without the tile family its screen draws never leaves.
Every other family gets the slicer's raw G-code as-is, and what their
surfaces read was established from the surfaces themselves:

* **Klipper / Moonraker** (Mainsail, Fluidd, and Kiln's Creality adapter,
  which is Moonraker-backed): ``moonraker/components/file_manager/metadata.py``
  matches ``(thumbnail(?:_[A-Za-z0-9]+)?) begin([;/\\+=\\w\\s]+?); \\1 end``
  and refuses a block whose declared size is not the length of its base64;
  weight comes from ``total filament used [g]`` and ``filament used [g]``.
  Mainsail's own slicer page asks for ``32x32/PNG,400x300/PNG``.
* **OctoPrint**: the Slicer Thumbnails plugin matches
  ``^; thumbnail(?:_JPG)* begin \\d+[x ]\\d+ \\d+`` and stops reading at the
  first ``G1`` with an ``E`` word, so the block must precede the first
  extrusion.  Filament figures come from OctoPrint's own pass over the E
  moves (``octoprint/util/gcodeInterpreter.py``), not from a comment.
* **PrusaLink**: ``prusa3d/gcode-metadata`` matches
  ``; thumbnail_?(QOI|JPG|) begin (dim) (size)`` — plain PNG included —
  ignores anything under 50x50, and reads ``filament used [g]``.
* **Duet / RepRapFirmware**: ``FileInfoParser.cpp`` looks for
  ``; thumbnail begin 32x32 2140`` (PNG) and ``ilament used`` in mm.
* **Elegoo** (SDCP): what the Centauri Carbon's own screen reads could not
  be established from a source Kiln can cite, so a preview is written
  best-effort and its absence is never a refusal.
* **Serial / Marlin**: ``SerialPrinterAdapter.upload_file`` drops every
  comment line on the way to the SD card, so neither a preview nor a
  weight survives the trip.  Nothing is refused for their absence.

The format written is PrusaSlicer's own, pinned here against its emitter
(``src/libslic3r/GCode/Thumbnails.hpp``, 2.9.4)::

    output("\\n;\\n; %s begin %dx%d %d\\n")   # tag, width, height, len(base64)
    ...                                     # "; " + up to 78 base64 chars
    output("; %s end\\n;\\n")

Measured on this machine, 2026-09-19: PrusaSlicer 2.9.4 accepts
``--thumbnails`` on the command line, writes the setting into its config
block, and emits no thumbnail block at all — so the picture has to be put
in afterwards.  The same slice wrote ``; total filament used [g] = 0.00``
and no ``; filament used [g]`` line, because Kiln's profiles describe a
printer and name no filament density.
"""

from __future__ import annotations

import base64
import io
import re
import struct
from pathlib import Path
from unittest import mock

import pytest

from kiln.printers import gcode_complete
from kiln.printers.base import (
    JobProgress,
    PrinterAdapter,
    PrinterCapabilities,
    PrinterError,
    PrinterState,
    PrintResult,
    UploadResult,
)

# ---------------------------------------------------------------------------
# A slice shaped like the one Kiln's own profile produces
# ---------------------------------------------------------------------------

_HEADER = (
    "; generated by PrusaSlicer 2.9.4 on 2026-09-19 at 03:47:35 UTC\n"
    "\n"
    "; external perimeters extrusion width = 0.45mm\n"
    "M104 S200 ; set temperature\n"
    "M190 S60\n"
    "G28 ; home all axes\n"
)

#: What PrusaSlicer wrote for a Kiln slice, verbatim from the measured run:
#: a length, no per-extruder grams line at all, and a zero total.
_FOOTER = (
    "M104 S0 ; turn off temperature\n"
    "M84     ; disable motors\n"
    "; filament used [mm] = 1493.99\n"
    "; filament used [cm3] = 3.59\n"
    "; total filament used [g] = 0.00\n"
    "; estimated printing time (normal mode) = 13m 54s\n"
    "\n"
    "; prusaslicer_config = begin\n"
    "; filament_density = 0\n"
    "; filament_diameter = 1.75\n"
    "; filament_type = PLA\n"
    "; prusaslicer_config = end\n"
)


def _moves(count: int = 40) -> str:
    out = ["M83\n"]
    for i in range(count):
        out.append(f"G1 X{10 + i} Y{10 + i} E1.2 F1800\n")
    return "".join(out)


def raw_gcode(tmp_path: Path, name: str = "part.gcode") -> str:
    """The file Kiln hands a non-Bambu printer today: no picture, no weight."""
    p = tmp_path / name
    p.write_text(_HEADER + _moves() + _FOOTER, encoding="utf-8")
    return str(p)


def png_bytes(width: int, height: int, rgb=(200, 60, 60)) -> bytes:
    from PIL import Image

    buf = io.BytesIO()
    Image.new("RGB", (width, height), rgb).save(buf, format="PNG")
    return buf.getvalue()


@pytest.fixture
def preview() -> bytes:
    """A picture of the plate, at the largest size any surface asks for."""
    return png_bytes(400, 300)


def complete(path: str, family: str | None = None, **kw) -> str:
    kw.setdefault("preview_png", png_bytes(400, 300))
    return gcode_complete.complete_gcode_for_printer(path, family, **kw)


def _png_size(data: bytes):
    return struct.unpack(">II", data[16:24]) if data[:8] == b"\x89PNG\r\n\x1a\n" else None


def _moves_of(text: str) -> list[str]:
    """Every line that is not a comment and not blank — what the printer
    actually executes.  A blank line is part of the block shape PrusaSlicer's
    own emitter writes (``"\\n;\\n; thumbnail begin ..."``)."""
    return [
        ln for ln in text.splitlines()
        if ln.strip() and not ln.lstrip().startswith(";")
    ]


# ---------------------------------------------------------------------------
# The block format, pinned against the two readers that judge it
# ---------------------------------------------------------------------------


class TestThumbnailBlockFormat:
    def test_the_block_is_prusaslicers_own_shape(self, tmp_path, preview):
        path = raw_gcode(tmp_path)
        complete(path, "moonraker", preview_png=preview)
        text = Path(path).read_text(encoding="utf-8")

        begins = re.findall(r"^; thumbnail begin (\d+)x(\d+) (\d+)$", text, re.MULTILINE)
        assert [(w, h) for w, h, _ in begins] == [("400", "300"), ("32", "32")], begins
        assert text.count("; thumbnail end") == 2

    def test_moonrakers_own_regex_reads_it(self, tmp_path, preview):
        """The pattern copied verbatim from Moonraker's metadata.py, and the
        size check it applies: a declared length that is not the base64's
        own length is dropped with ``Thumbnail Size Mismatch``."""
        path = raw_gcode(tmp_path)
        complete(path, "moonraker", preview_png=preview)
        text = Path(path).read_text(encoding="utf-8")

        pattern = r"(thumbnail(?:_[A-Za-z0-9]+)?) begin([;/\+=\w\s]+?); \1 end"
        found = []
        for match in re.finditer(pattern, text):
            lines = re.split(r"\r?\n", match.group(2).replace("; ", ""))
            info = [int(n) for n in re.findall(r"\d+", lines[0])]
            data = "".join(lines[1:-1])
            assert len(info) == 3, lines[0]
            assert len(data) == info[2], "Moonraker would report a size mismatch"
            decoded = base64.b64decode(data.encode())
            assert _png_size(decoded) == (info[0], info[1])
            found.append((info[0], info[1]))
        assert found == [(400, 300), (32, 32)], found

    def test_moonraker_gets_the_32x32_it_makes_its_own_miniature_from(
        self, tmp_path, preview,
    ):
        path = raw_gcode(tmp_path)
        complete(path, "moonraker", preview_png=preview)
        assert (32, 32) in gcode_complete.gcode_thumbnails(
            Path(path).read_text(encoding="utf-8")
        )

    def test_no_base64_row_is_longer_than_the_emitter_writes(self, tmp_path, preview):
        path = raw_gcode(tmp_path)
        complete(path, "moonraker", preview_png=preview)
        for line in Path(path).read_text(encoding="utf-8").splitlines():
            if line.startswith("; ") and not line.startswith("; thumbnail"):
                assert len(line) <= 2 + 78, line[:40]

    def test_the_picture_precedes_the_first_extrusion(self, tmp_path, preview):
        """OctoPrint's reader stops at the first ``G1`` carrying an ``E``."""
        path = raw_gcode(tmp_path)
        complete(path, "octoprint", preview_png=preview)
        lines = Path(path).read_text(encoding="utf-8").splitlines()
        first_extrusion = next(
            i for i, ln in enumerate(lines)
            if ln.startswith("G1") and re.search(r"\bE[-\d.]", ln)
        )
        last_block_line = max(i for i, ln in enumerate(lines) if "thumbnail end" in ln)
        assert last_block_line < first_extrusion

    def test_octoprints_own_regex_reads_it(self, tmp_path, preview):
        path = raw_gcode(tmp_path)
        complete(path, "octoprint", preview_png=preview)
        text = Path(path).read_text(encoding="utf-8")
        regex = (
            r"(?:^; thumbnail(?:_JPG)* begin \d+[x ]\d+ \d+)(?:\n|\r\n?)"
            r"((?:.+(?:\n|\r\n?))+?)(?:^; thumbnail(?:_JPG)* end)"
        )
        assert re.findall(regex, text, re.MULTILINE)

    def test_prusalink_ignores_nothing_it_was_given(self, tmp_path, preview):
        """gcode-metadata drops any thumbnail under 50x50 and picks the one
        closest to 640x480; 400x300 shares that aspect ratio."""
        path = raw_gcode(tmp_path)
        complete(path, "prusalink", preview_png=preview)
        sizes = gcode_complete.gcode_thumbnails(Path(path).read_text(encoding="utf-8"))
        assert any(w >= 50 and h >= 50 for w, h in sizes), sizes


# ---------------------------------------------------------------------------
# The weight, from the file's own moves
# ---------------------------------------------------------------------------


class TestWeightFill:
    def test_the_weight_matches_what_the_usage_reader_computes(self, tmp_path):
        from kiln.printers.bambu_3mf import filament_usage_from_gcode

        path = raw_gcode(tmp_path)
        before = Path(path).read_text(encoding="utf-8")
        expected = filament_usage_from_gcode(before)
        assert expected.total_g > 0, "the fixture must extrude something"

        complete(path, "moonraker")
        text = Path(path).read_text(encoding="utf-8")
        total = float(re.search(r"; total filament used \[g\] = ([\d.]+)", text).group(1))
        assert total == pytest.approx(round(expected.total_g, 2), abs=0.01)

    def test_the_per_extruder_line_is_written_when_the_slicer_omitted_it(self, tmp_path):
        """PrusaSlicer writes ``filament used [g]`` only for multi-material,
        and PrusaLink reads exactly that key."""
        path = raw_gcode(tmp_path)
        assert "; filament used [g]" not in Path(path).read_text(encoding="utf-8")
        complete(path, "prusalink")
        text = Path(path).read_text(encoding="utf-8")
        grams = float(re.search(r"^; filament used \[g\] = ([\d.]+)$", text, re.M).group(1))
        assert grams > 0

    def test_the_length_the_slicer_knew_is_left_alone(self, tmp_path):
        path = raw_gcode(tmp_path)
        complete(path, "duet")
        text = Path(path).read_text(encoding="utf-8")
        assert "; filament used [mm] = 1493.99" in text

    def test_a_weight_the_slicer_worked_out_is_kept(self, tmp_path):
        path = tmp_path / "known.gcode"
        path.write_text(
            _HEADER + _moves()
            + _FOOTER.replace("used [g] = 0.00", "used [g] = 24.41"),
            encoding="utf-8",
        )
        complete(str(path), "moonraker")
        text = path.read_text(encoding="utf-8")
        assert "; total filament used [g] = 24.41" in text

    def test_a_file_that_extrudes_nothing_may_weigh_nothing(self, tmp_path):
        """A plate with no extrusion may honestly say 0.00 — the check is
        'it lays down filament and claims to weigh nothing', not 'it says
        zero'."""
        path = tmp_path / "empty.gcode"
        footer = _FOOTER.replace("; filament used [mm] = 1493.99\n", "")
        path.write_text(_HEADER + "G1 X10 Y10 F1800\n" + footer, encoding="utf-8")
        problems = gcode_complete.gcode_problems(str(path), "moonraker")
        assert not any("weight" in p for p in problems), problems


# ---------------------------------------------------------------------------
# A file nobody sliced through Kiln can still be completed
# ---------------------------------------------------------------------------


class TestThePictureCanComeFromTheFileItself:
    """Without this the refusal would name a remedy its owner could not
    reach: somebody's own Cura or Orca export has no mesh beside it, so
    there would be nothing to draw the preview from and the file would be
    stuck outside the door forever.  The toolpath in the file is the mesh."""

    def test_a_file_with_no_mesh_beside_it_still_completes(self, tmp_path):
        path = raw_gcode(tmp_path)
        gcode_complete.complete_gcode_for_printer(path, "moonraker")
        assert gcode_complete.gcode_problems(path, "moonraker") == []

    def test_the_picture_is_drawn_from_the_extrusion_moves(self, tmp_path):
        from PIL import Image

        text = Path(raw_gcode(tmp_path)).read_text(encoding="utf-8")
        png = gcode_complete._render_from_gcode(text, 400, 300)
        assert png is not None
        img = Image.open(io.BytesIO(png))
        assert img.size == (400, 300)
        inked = sum(1 for px in img.convert("RGBA").getdata() if px[3] > 0)
        assert inked > 50, "the toolpath drew nothing"

    def test_travel_only_moves_draw_nothing(self, tmp_path):
        text = _HEADER + "G1 X10 Y10 F1800\nG1 X50 Y50 F1800\n"
        assert gcode_complete._render_from_gcode(text, 400, 300) is None

    def test_a_file_that_prints_nothing_is_not_asked_for_a_picture(self, tmp_path):
        """A homing check or a levelling macro is not a print, and is not
        held to a print's standard."""
        path = tmp_path / "level.gcode"
        path.write_text("; generated by PrusaSlicer\nG28\nG29\n", encoding="utf-8")
        assert gcode_complete.gcode_problems(str(path), "moonraker") == []

    def test_a_file_that_cannot_be_read_is_the_adapters_own_error(self, tmp_path):
        assert gcode_complete.gcode_problems(str(tmp_path / "nope.gcode"), "duet") == []


# ---------------------------------------------------------------------------
# Only comments change, and completing twice changes nothing
# ---------------------------------------------------------------------------


class TestTheMovesAreUntouched:
    def test_every_non_comment_line_is_byte_identical(self, tmp_path, preview):
        path = raw_gcode(tmp_path)
        before = Path(path).read_text(encoding="utf-8")
        complete(path, "moonraker", preview_png=preview)
        after = Path(path).read_text(encoding="utf-8")
        assert _moves_of(after) == _moves_of(before)

    def test_completion_is_idempotent(self, tmp_path, preview):
        path = raw_gcode(tmp_path)
        complete(path, "moonraker", preview_png=preview)
        once = Path(path).read_bytes()
        complete(path, "moonraker", preview_png=preview)
        assert Path(path).read_bytes() == once

    def test_it_can_write_beside_the_original(self, tmp_path, preview):
        path = raw_gcode(tmp_path)
        out = tmp_path / "copy.gcode"
        complete(path, "moonraker", preview_png=preview, output_path=str(out))
        assert Path(path).read_text(encoding="utf-8") == _HEADER + _moves() + _FOOTER
        assert gcode_complete.gcode_problems(str(out), "moonraker") == []


# ---------------------------------------------------------------------------
# The check, family by family
# ---------------------------------------------------------------------------


class TestTheCheck:
    @pytest.mark.parametrize(
        "family", ["moonraker", "creality", "octoprint", "prusalink", "duet"],
    )
    def test_a_surface_that_draws_a_preview_names_the_missing_one(self, tmp_path, family):
        problems = gcode_complete.gcode_problems(raw_gcode(tmp_path), family)
        assert any("preview" in p or "thumbnail" in p for p in problems), problems
        surface = gcode_complete.SURFACES[family].surface
        assert any(surface in p for p in problems), (surface, problems)

    @pytest.mark.parametrize("family", ["elegoo", "serial"])
    def test_a_surface_kiln_cannot_see_is_never_refused_a_preview(self, tmp_path, family):
        problems = gcode_complete.gcode_problems(raw_gcode(tmp_path), family)
        assert not any("preview" in p or "thumbnail" in p for p in problems), problems

    def test_a_surface_kiln_cannot_see_says_so(self, tmp_path):
        assert gcode_complete.SURFACES["elegoo"].reads_thumbnail is False
        assert "could not" in gcode_complete.SURFACES["elegoo"].evidence.lower()

    def test_elegoo_gets_a_best_effort_preview_and_is_never_refused(self, tmp_path, preview):
        """What the Centauri's screen reads could not be cited, so the
        picture is written anyway — a comment block costs nothing — and
        its absence is never a refusal, before or after."""
        path = raw_gcode(tmp_path)
        assert gcode_complete.gcode_problems(path, "elegoo") == []
        complete(path, "elegoo", preview_png=preview)
        sizes = gcode_complete.gcode_thumbnails(Path(path).read_text(encoding="utf-8"))
        assert sizes == list(gcode_complete.THUMBNAIL_SIZES), sizes
        assert gcode_complete.gcode_problems(path, "elegoo") == []

    def test_serial_gets_no_preview_its_own_upload_would_strip(self, tmp_path, preview):
        path = raw_gcode(tmp_path)
        complete(path, "serial", preview_png=preview)
        assert "; thumbnail begin" not in Path(path).read_text(encoding="utf-8")

    def test_the_serial_surface_reads_neither(self, tmp_path):
        """Marlin's SD upload drops every comment line, so the check has
        nothing to hold a serial printer to."""
        assert gcode_complete.gcode_problems(raw_gcode(tmp_path), "serial") == []

    def test_completion_clears_the_check(self, tmp_path, preview):
        path = raw_gcode(tmp_path)
        assert gcode_complete.gcode_problems(path, "moonraker")
        complete(path, "moonraker", preview_png=preview)
        assert gcode_complete.gcode_problems(path, "moonraker") == []

    def test_a_3mf_is_the_bambu_checks_business_not_this_one(self, tmp_path):
        p = tmp_path / "plate.gcode.3mf"
        p.write_bytes(b"PK\x03\x04not a real archive")
        assert gcode_complete.gcode_problems(str(p), "moonraker") == []

    def test_a_binary_gcode_is_left_alone(self, tmp_path):
        p = tmp_path / "part.bgcode"
        p.write_bytes(b"GCDE\x00\x00\x00\x00")
        assert gcode_complete.gcode_problems(str(p), "prusalink") == []

    def test_a_weightless_plate_is_named_for_the_surfaces_that_show_weight(self, tmp_path):
        problems = gcode_complete.gcode_problems(raw_gcode(tmp_path), "moonraker")
        assert any("weight" in p for p in problems), problems

    def test_octoprint_is_not_refused_over_a_weight_it_computes_itself(self, tmp_path):
        problems = gcode_complete.gcode_problems(raw_gcode(tmp_path), "octoprint")
        assert not any("weight" in p for p in problems), problems

    def test_the_remedy_is_named(self, tmp_path):
        problems = gcode_complete.gcode_problems(raw_gcode(tmp_path), "moonraker")
        assert any("complete_gcode_for_printer" in p for p in problems), problems


# ---------------------------------------------------------------------------
# Chokepoint 1: the upload door every adapter shares
# ---------------------------------------------------------------------------


class _Fake(PrinterAdapter):
    """A stand-in for one backend.  It is a plain ``PrinterAdapter``
    subclass on purpose: the upload gate is installed by
    ``__init_subclass__``, so a ninth backend inherits it without knowing
    it exists — the same shape as the bed-fit wrap already there."""

    def __init__(self, family: str, *, printer_copy: bytes | None = None) -> None:
        self._family = family
        self.uploaded: list[str] = []
        self.started: list[str] = []
        self._printer_copy = printer_copy

    @property
    def name(self) -> str:
        return self._family

    @property
    def capabilities(self) -> PrinterCapabilities:
        return PrinterCapabilities()

    def upload_file(self, file_path: str) -> UploadResult:
        self.uploaded.append(file_path)
        return UploadResult(
            success=True, file_name=Path(file_path).name, message="ok",
        )

    def read_print_file(self, file_name: str) -> bytes | None:
        return self._printer_copy

    def _start_print_impl(self, file_name: str, **kwargs) -> PrintResult:
        self.started.append(file_name)
        return PrintResult(success=True, message="started")

    def get_state(self) -> PrinterState:
        return PrinterState()

    def get_job(self) -> JobProgress:
        return JobProgress()

    def list_files(self) -> list:
        return []

    def delete_file(self, file_name: str) -> bool:
        return True

    def cancel_print(self) -> PrintResult:
        return PrintResult(success=True, message="ok")

    def pause_print(self) -> PrintResult:
        return PrintResult(success=True, message="ok")

    def _resume_print_impl(self) -> PrintResult:
        return PrintResult(success=True, message="ok")

    def emergency_stop(self) -> PrintResult:
        return PrintResult(success=True, message="ok")

    def send_gcode(self, command: str) -> str:
        return "ok"

    def set_tool_temp(self, celsius: float, tool: int = 0) -> bool:
        return True

    def set_bed_temp(self, celsius: float) -> bool:
        return True

    def _load_filament_impl(self, plan):
        raise NotImplementedError

    def _unload_filament_impl(self, plan):
        raise NotImplementedError

    def _purge_filament_impl(self, plan):
        raise NotImplementedError


class TestUploadDoor:
    @pytest.mark.parametrize(
        "family", ["moonraker", "creality", "octoprint", "prusalink", "duet"],
    )
    def test_an_incomplete_file_never_leaves(self, tmp_path, family):
        adapter = _Fake(family)
        with pytest.raises(PrinterError) as exc:
            adapter.upload_file(raw_gcode(tmp_path))
        assert gcode_complete.SURFACES[family].surface in str(exc.value)
        assert adapter.uploaded == []

    @pytest.mark.parametrize(
        "family", ["moonraker", "creality", "octoprint", "prusalink", "duet"],
    )
    def test_a_completed_file_leaves(self, tmp_path, family, preview):
        path = raw_gcode(tmp_path)
        complete(path, family, preview_png=preview)
        adapter = _Fake(family)
        assert adapter.upload_file(path).success
        assert adapter.uploaded == [path]

    @pytest.mark.parametrize("family", ["elegoo", "serial"])
    def test_a_family_whose_surface_reads_nothing_is_not_refused(self, tmp_path, family):
        adapter = _Fake(family)
        assert adapter.upload_file(raw_gcode(tmp_path)).success

    def test_an_unknown_backend_is_not_refused(self, tmp_path):
        """A backend with no established surface soft-passes, the way the
        rest of the pre-upload gate does."""
        adapter = _Fake("some-new-printer")
        assert adapter.upload_file(raw_gcode(tmp_path)).success

    def test_a_model_upload_is_not_this_doors_business(self, tmp_path):
        stl = tmp_path / "part.stl"
        stl.write_text("solid x\nendsolid x\n", encoding="utf-8")
        assert _Fake("moonraker").upload_file(str(stl)).success


# ---------------------------------------------------------------------------
# Chokepoint 2: a start by name reads the printer's own copy
# ---------------------------------------------------------------------------


class TestStartByNameDoor:
    @pytest.fixture(autouse=True)
    def _no_signoff(self, monkeypatch):
        monkeypatch.setenv("KILN_SKIP_PREVIEW_GATE", "1")

    def test_a_printer_copy_without_its_preview_is_refused(self, tmp_path):
        raw = Path(raw_gcode(tmp_path)).read_bytes()
        adapter = _Fake("moonraker", printer_copy=raw)
        result = adapter.start_print("part.gcode")
        assert result.success is False, result.message
        assert gcode_complete.SURFACES["moonraker"].surface in result.message
        assert adapter.started == []

    def test_a_completed_printer_copy_starts(self, tmp_path, preview):
        path = raw_gcode(tmp_path)
        complete(path, "moonraker", preview_png=preview)
        adapter = _Fake("moonraker", printer_copy=Path(path).read_bytes())
        assert adapter.start_print("part.gcode").success is True

    def test_a_family_whose_surface_reads_nothing_starts(self, tmp_path):
        raw = Path(raw_gcode(tmp_path)).read_bytes()
        adapter = _Fake("elegoo", printer_copy=raw)
        assert adapter.start_print("part.gcode").success is True


# ---------------------------------------------------------------------------
# Chokepoint 3: the file slice_model recommends is already complete
# ---------------------------------------------------------------------------


def test_the_slice_steer_completes_the_gcode_it_recommends(tmp_path, preview):
    from kiln.plugins import slicer_tools

    path = raw_gcode(tmp_path)
    response: dict = {"output_path": path}
    with mock.patch.object(
        gcode_complete, "_render_preview", return_value=preview,
    ):
        slicer_tools._steer_to_complete_gcode(response, path, "prusa_mk4", None)
    assert response["recommended_upload_path"] == path
    assert gcode_complete.gcode_problems(path, "prusalink") == []
    assert gcode_complete.gcode_problems(path, "moonraker") == []


def test_the_slice_steer_survives_a_renderer_that_cannot_draw(tmp_path):
    """A missing picture must never fail a slice — the upload door still
    refuses the file, and the weight is filled either way."""
    from kiln.plugins import slicer_tools

    path = raw_gcode(tmp_path)
    response: dict = {"output_path": path}
    with mock.patch.object(gcode_complete, "_render_preview", return_value=None):
        slicer_tools._steer_to_complete_gcode(response, path, "prusa_mk4", None)
    text = Path(path).read_text(encoding="utf-8")
    assert "; thumbnail begin" not in text
    assert "; total filament used [g] = 0.00" not in text


# ---------------------------------------------------------------------------
# Every door, not just the ones this change remembered
# ---------------------------------------------------------------------------


def _shipped_adapters() -> list[type]:
    import importlib

    for module_name in (
        "bambu", "moonraker", "octoprint", "prusalink",
        "elegoo", "creality", "duet", "serial_adapter",
    ):
        importlib.import_module(f"kiln.printers.{module_name}")

    seen: list[type] = []

    def walk(cls: type) -> None:
        for sub in cls.__subclasses__():
            if sub.__module__.startswith("kiln.printers.") and sub not in seen:
                seen.append(sub)
            walk(sub)

    walk(PrinterAdapter)
    return seen


def test_every_shipped_backend_maps_to_a_surface():
    """A backend Kiln ships must say what its surface reads — including
    'nothing I can cite'.  An adapter that maps to nothing would upload
    whatever it was handed without anybody noticing."""
    adapters = _shipped_adapters()
    assert len(adapters) >= 8, adapters
    unmapped = [
        cls.__name__ for cls in adapters
        if gcode_complete.family_for_adapter_class(cls) is None
    ]
    assert unmapped == [], unmapped


def test_the_bambu_family_is_left_to_its_own_check(tmp_path):
    """Bambu files are archives judged by ``bambu_archive_problems``; this
    check must not second-guess them, and the completion must not touch
    a byte of that path."""
    path = raw_gcode(tmp_path)
    before = Path(path).read_bytes()
    assert gcode_complete.gcode_problems(path, "bambu") == []
    gcode_complete.complete_gcode_for_printer(path, "bambu")
    assert Path(path).read_bytes() == before


class TestTheThreePrintDoors:
    """``slice_and_print``, ``reslice_and_print`` and ``quick_print`` all
    hand their file to ``prepare_upload_for_adapter``.  A Bambu gets a
    wrapped archive there; everybody else used to get the raw G-code
    untouched and meet the upload refusal one step later, with nothing in
    between that could fix it."""

    def test_a_raw_gcode_printer_gets_a_complete_file(self, tmp_path):
        from kiln.printers.upload_prep import prepare_upload_for_adapter

        adapter = _Fake("moonraker")
        path = raw_gcode(tmp_path)
        upload_path, wrapped = prepare_upload_for_adapter(adapter, path)
        assert (upload_path, wrapped) == (path, False)
        assert gcode_complete.gcode_problems(path, "moonraker") == []
        assert adapter.upload_file(upload_path).success

    def test_the_bambu_wrap_path_is_untouched(self, tmp_path):
        """An adapter that wraps still wraps, and nothing writes into the
        G-code on its way there."""
        from kiln.printers.upload_prep import prepare_upload_for_adapter

        path = raw_gcode(tmp_path)
        before = Path(path).read_bytes()

        class _Wrapping(_Fake):
            def wrap_gcode_as_3mf(self, gcode_path, **kwargs):
                return gcode_path + ".3mf"

        upload_path, wrapped = prepare_upload_for_adapter(_Wrapping("bambu"), path)
        assert wrapped is True and upload_path.endswith(".3mf")
        assert Path(path).read_bytes() == before
