"""Tests for kiln.file_metadata — the filament figures a file's header carries."""

from __future__ import annotations

import pytest

from kiln.file_metadata import _extract_gcode_metadata_from_lines


class TestFilamentUsedFromHeader:
    def test_two_filaments_are_summed_in_mm(self):
        # OrcaSlicer lists one value per extruder; the plate uses the sum.
        meta = _extract_gcode_metadata_from_lines(
            ["; generated by OrcaSlicer 2.3.2", "; filament used [mm] = 11040.26, 584.30", "G28"]
        )
        assert meta.extra["filament_used"] == pytest.approx(11624.56)
        assert meta.extra["filament_used_unit"] == "mm"

    def test_cura_metres_become_mm(self):
        meta = _extract_gcode_metadata_from_lines([";Filament used: 4.523m"])
        assert meta.extra["filament_used"] == pytest.approx(4523.0)
        assert meta.extra["filament_used_unit"] == "mm"

    def test_grams_alone_are_kept_as_grams(self):
        meta = _extract_gcode_metadata_from_lines(["; total filament weight [g] : 3.66"])
        assert meta.extra["filament_used"] == pytest.approx(3.66)
        assert meta.extra["filament_used_unit"] == "g"

    def test_no_header_means_no_key(self):
        meta = _extract_gcode_metadata_from_lines(["G28", "G1 X10 Y10 E.5"])
        assert "filament_used" not in meta.extra
