"""``route_print_job`` on an install without kiln-pro asks Kiln's servers, with what it read here.

The router and the plate survey are kiln-pro's.  A plain install used to
answer ``ROUTING_UNAVAILABLE`` at every tier (sold-reachable gate,
2026-10-06: the Business card sold fleet routing and no buyer with a plain
install could run it).  Now the door reads what only this machine can read
-- its printers as the registry sees them, each plate as it stands, the
job's own file -- and asks the served route (``plan_fleet_route``) for the
plan.  These tests pin the door's side of that wire with the server stood
in (public tests cannot import kiln-pro):

* every eligible printer is sent as a candidate, with one plate reading
  each, in the reading's shape, and never an address or an access code;
* the job's sliced file travels once, beside the readings, not once per
  machine;
* the server's plan, and its own rulings (``NO_ROOM`` with each machine's
  sentence, the tier gate), are relayed as they are;
* a call that got no answer is worded in the shared voice, says why, and
  routes nothing;
* ``plate_reading`` reads a clear plate, says when it cannot read one, and
  tells a contract for another machine apart from one for this machine
  without putting the identity on the wire;
* ``hosted_form`` carries each plate occupant's own file the way it carries
  the job's.
"""

from __future__ import annotations

import base64
import gzip
import json
import struct
import sys
import urllib.error
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import pytest

from kiln import _pro_placement_bridge as bridge

HOST, ACCESS_CODE = "192.168.7.42", "s3cret-access-code"


def _cube(path: Path, size: float = 20.0) -> str:
    v = [(0, 0, 0), (size, 0, 0), (size, size, 0), (0, size, 0), (0, 0, size), (size, 0, size), (size, size, size), (0, size, size)]
    faces = [(0, 3, 2), (0, 2, 1), (4, 5, 6), (4, 6, 7), (0, 1, 5), (0, 5, 4), (1, 2, 6), (1, 6, 5), (2, 3, 7), (2, 7, 6), (3, 0, 4), (3, 4, 7)]
    with open(path, "wb") as fh:
        fh.write(b"\0" * 80)
        fh.write(struct.pack("<I", len(faces)))
        for a, b, c in faces:
            fh.write(struct.pack("<3f", 0, 0, 0))
            for i in (a, b, c):
                fh.write(struct.pack("<3f", *v[i]))
            fh.write(struct.pack("<H", 0))
    return str(path)


def _gcode(path: Path) -> str:
    path.write_text("; generated by OrcaSlicer 2.3.2\nG90\n;LAYER_CHANGE\n;Z:0.2\nG1 X20 Y20 Z0.2\nG1 X40 Y20 E0.5\nG1 X40 Y40 E0.5\nG1 X20 Y40 E0.5\nG1 X20 Y20 E0.5\n")
    return str(path)


def _machine(name: str) -> SimpleNamespace:
    return SimpleNamespace(
        name=name, serial=f"01P00A0000000{name}", host=HOST, access_code=ACCESS_CODE, _printer_model="bambu_a1",
        get_state=lambda: SimpleNamespace(state=SimpleNamespace(value="idle")),
    )


class _FakeMCP:
    def __init__(self) -> None:
        self.tools: dict[str, Any] = {}

    def tool(self, *a, **k):
        def deco(fn):
            self.tools[fn.__name__] = fn
            return fn
        return deco


class _Registry:
    def __init__(self, machines):
        self.adapters = machines

    def list_names(self):
        return list(self.adapters)

    def get(self, name):
        return self.adapters[name]


@pytest.fixture
def plain_install(monkeypatch, tmp_path):
    """The real door with kiln-pro absent and the served call stood in."""
    monkeypatch.setenv("KILN_HOME", str(tmp_path / "kiln-home"))
    import kiln.server as srv
    from kiln.plugins import fleet_tools
    from kiln.queue import PrintQueue

    monkeypatch.setattr(srv, "_check_auth", lambda scope: None)
    monkeypatch.setattr(srv, "requires_tier", lambda tier: (lambda fn: fn), raising=False)
    monkeypatch.setattr(srv, "_get_queue", lambda: PrintQueue())
    monkeypatch.setitem(sys.modules, "kiln.job_router", None)
    monkeypatch.setitem(sys.modules, "kiln.placement_fleet", None)

    def make(machines: dict[str, Any], answer: Any):
        registry = _Registry(machines)
        monkeypatch.setattr(srv, "_get_registry", lambda: registry)
        monkeypatch.setattr(srv, "_registry", registry, raising=False)
        sent: list[dict] = []

        def served(tool, _timeout=None, _asked_by_user=True, **kw):
            sent.append({"tool": tool, **kw})
            if isinstance(answer, BaseException):
                raise answer
            return answer

        monkeypatch.setattr(srv, "_pro_api_call", served)
        mcp = _FakeMCP()
        fleet_tools._FleetToolsPlugin().register(mcp)
        return mcp.tools["route_print_job"], sent

    return make


PLAN = {"success": True, "routing": {"recommended_printer": {"printer_id": "a", "plate": {"status": "clear"}}, "alternatives": [], "excluded": []}}


class TestWhatIsSent:
    def test_every_eligible_printer_with_one_reading_each_and_no_address_or_access_code(self, plain_install, tmp_path):
        from kiln.plate_state import mark_clear

        a, b = _machine("a"), _machine("b")
        mark_clear(a, "human")
        door, sent = plain_install({"a": a, "b": b}, PLAN)
        assert door(_cube(tmp_path / "cube.stl"), material="PLA", quality="fine", priority="high") == PLAN
        body = sent[0]
        assert body["tool"] == "plan_fleet_route" and body["material"] == "PLA"
        assert body["quality_priority"] == 5 and body["speed_priority"] == 5
        assert [c["printer_id"] for c in body["candidates"]] == ["a", "b"]
        assert set(body["plates"]) == {"a", "b"}
        for reading in body["plates"].values():
            assert reading["schema"] == bridge.READING_SCHEMA and reading["request"]["schema"] == bridge.REQUEST_SCHEMA
        assert body["plates"]["a"]["request"]["plate"]["status"] == "clear"
        assert body["plates"]["b"]["request"]["plate"]["status"] == "unknown"
        assert body["sliced_gcode"] is None
        wire = json.dumps(body)
        assert HOST not in wire and ACCESS_CODE not in wire

    def test_a_sliced_file_travels_once_beside_the_readings(self, plain_install, tmp_path):
        a, b = _machine("a"), _machine("b")
        door, sent = plain_install({"a": a, "b": b}, PLAN)
        path = _gcode(tmp_path / "part.gcode")
        door(path, material="PLA")
        body = sent[0]
        assert body["sliced_gcode"]["name"] == "part.gcode"
        assert gzip.decompress(base64.b64decode(body["sliced_gcode"]["gz_b64"])) == Path(path).read_bytes()
        assert all(r["request"]["sliced_gcode"] is None for r in body["plates"].values())
        assert json.dumps(body).count("gz_b64") == 1

    def test_a_plate_this_machine_cannot_read_is_sent_as_such(self, plain_install, tmp_path, monkeypatch):
        a = _machine("a")
        monkeypatch.setattr(bridge, "request_for", lambda *x, **k: (_ for _ in ()).throw(RuntimeError("no plate store")))
        door, sent = plain_install({"a": a}, PLAN)
        door(_cube(tmp_path / "cube.stl"), material="PLA")
        reading = sent[0]["plates"]["a"]
        assert reading["request"] is None and reading["unknowns"] == ["plate record"]
        assert reading["unreadable"] == "Kiln could not read a's plate, so it will not route this print there"


class TestWhatComesBack:
    def test_the_servers_own_rulings_are_relayed_as_they_are(self, plain_install, tmp_path):
        no_room = {"success": False, "error": {"code": "NO_ROOM", "message": "No printer ... Nothing was routed."},
                   "per_machine": {"a": ["no room for this part on the plate as it stands"]}, "plates": {"a": {"has_room": False}}}
        door, _ = plain_install({"a": _machine("a")}, no_room)
        assert door(_cube(tmp_path / "cube.stl"), material="PLA") == no_room
        gate = {"status": "error", "error": "Fleet routing needs Kiln Business.", "code": "TIER_REQUIRED", "required_tier": "business"}
        door, _ = plain_install({"a": _machine("a")}, gate)
        assert door(_cube(tmp_path / "cube.stl"), material="PLA") == gate

    @pytest.mark.parametrize("answer, why", [
        (urllib.error.URLError(OSError(101, "Network is unreachable")), "offline"),
        ({"status": "error", "code": "KILN_ACCOUNT_NOT_PAIRED", "error": "pair first", "why": "signed_out"}, "signed_out"),
        ({"status": "error", "code": "SERVER_UNREACHABLE", "error": "timed out"}, "unanswered"),
        ({"detail": "Not Found"}, "refused"),
        ("not even a dict", "unanswered"),
    ])
    def test_no_answer_is_worded_in_the_shared_voice_and_nothing_is_routed(self, plain_install, tmp_path, answer, why):
        door, _ = plain_install({"a": _machine("a")}, answer)
        result = door(_cube(tmp_path / "cube.stl"), material="PLA")
        assert result["success"] is False and result["error"]["code"] == "ROUTING_UNAVAILABLE"
        assert result["why"] == why
        text = result["error"]["message"]
        assert text.startswith("Routing picks which of your printers takes this print.")
        assert "won't route it anywhere" in text and "start_print or fleet_submit_job" in text
        assert result["error"]["retryable"] is (why != "refused")


class TestThePlateReading:
    def test_an_unregistered_name_is_a_reading_that_says_so(self):
        reading = bridge.plate_reading("ghost", None, {"file": "cube.stl", "part": None, "sliced_gcode_path": None})
        assert reading["request"] is None and reading["unknowns"] == ["printer"]
        assert reading["unreadable"] == "ghost is not a registered printer, so Kiln cannot see its plate"

    def test_a_machine_is_read_as_kiln_asking_itself(self, monkeypatch, tmp_path):
        from kiln.printers import engagement

        monkeypatch.setenv("KILN_HOME", str(tmp_path / "kiln-home"))
        seen: list[bool] = []
        real = bridge.request_for

        def spy(adapter, printer_id, **kw):
            seen.append(engagement._in_internal_read())
            return real(adapter, printer_id, **kw)

        monkeypatch.setattr(bridge, "request_for", spy)
        reading = bridge.plate_reading("a", _machine("a"), {"file": "cube.stl", "part": {"size_mm": [30.0, 30.0, 5.0]}, "sliced_gcode_path": None})
        assert seen == [True] and engagement._in_internal_read() is False
        assert reading["request"]["printer_id"] == "bambu_a1" and reading["request"]["placement"] == "auto"
        assert reading["file_name"] == "cube.stl" and reading["contract"] is None and reading["machine_matches"] is True

    def test_a_contract_for_another_machine_is_told_apart_without_the_identity_on_the_wire(self, monkeypatch, tmp_path):
        from kiln import plate_state
        from kiln.printers import print_gate

        monkeypatch.setenv("KILN_HOME", str(tmp_path / "kiln-home"))
        path = _gcode(tmp_path / "part.gcode")
        a = _machine("a")
        mine = print_gate.same_bed_machine_id(a)
        assert mine
        for planned, matches in ((mine, True), ("someone-else", False)):
            monkeypatch.setattr(plate_state, "quiet_start_contract_for",
                                lambda *x, **k: {"planned_for_machine": planned, "planned_for_plate": "fp-1"})
            reading = bridge.plate_reading("a", a, {"file": "part.gcode", "part": None, "sliced_gcode_path": path})
            assert reading["machine_matches"] is matches
            assert reading["contract"] == {"planned_for_plate": "fp-1"}
            assert mine not in json.dumps(reading) and "someone-else" not in json.dumps(reading)

    def test_fleet_readings_in_wire_form_leave_the_jobs_file_out_of_every_request(self, tmp_path):
        a, b = _machine("a"), _machine("b")
        path = _gcode(tmp_path / "part.gcode")
        job = {"file": "part.gcode", "part": None, "sliced_gcode_path": path}
        local = bridge.fleet_readings(job, ["a", "b", "ghost"], {"a": a, "b": b})
        assert list(local) == ["a", "b", "ghost"]
        assert local["a"]["request"]["sliced_gcode"] == {"path": path}
        wire = bridge.fleet_readings(job, ["a", "b"], {"a": a, "b": b}, wire=True)
        assert all(r["request"]["sliced_gcode"] is None for r in wire.values())


class TestTheHostedForm:
    def test_each_plate_occupants_file_travels_like_the_jobs(self, tmp_path):
        path = _gcode(tmp_path / "jar.gcode")
        request = {"schema": bridge.REQUEST_SCHEMA, "occupant_gcode": {"path": path}, "sliced_gcode": None,
                   "plate": {"status": "occupied", "jobs": [{"file": "jar.gcode", "gcode": {"path": path}}, {"file": "x", "gcode": None}]}}
        wire = bridge.hosted_form(request)
        assert wire["occupant_gcode"]["name"] == "jar.gcode" and "gz_b64" in wire["occupant_gcode"]
        assert wire["plate"]["jobs"][0]["gcode"]["name"] == "jar.gcode" and "path" not in wire["plate"]["jobs"][0]["gcode"]
        assert wire["plate"]["jobs"][1]["gcode"] is None
        assert request["plate"]["jobs"][0]["gcode"] == {"path": path}, "the request itself is not modified"
        assert "path" not in json.dumps(wire)
