"""Tests for kiln.printers.bambu_3mf — Bambu Lab 3MF packaging.

Covers:
- BambuPrintSettings dataclass defaults and custom values
- Bambu3MFResult dataclass and to_dict
- Template loading (lazy singletons with mocked file reads)
- _resolve_start_gcode() — parametric temp substitution vs fixed temps
- _resolve_end_gcode() — safe Z-height regex substitution
- _count_layers() — LAYER_CHANGE marker counting
- _find_max_z() — Z-height extraction from PrusaSlicer comments
- _postprocess_prusa_body() — init stripping + layer tracking injection
- _build_gcode_header() — header block generation
- _build_slice_info() — XML metadata generation
- _build_plate_json() — JSON plate metadata
- build_bambu_3mf() — end-to-end 3MF packaging
- Edge cases: empty body, no layers, missing templates, source 3MF extraction
- _reset_cache() — singleton cache clearing
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import re
import zipfile
from pathlib import Path
from unittest.mock import patch

import pytest

from kiln.printers.bambu_3mf import (
    Bambu3MFResult,
    BambuPrintSettings,
    _build_gcode_header,
    _build_plate_json,
    _build_slice_info,
    _count_layers,
    _find_max_z,
    _postprocess_prusa_body,
    _reset_cache,
    _resolve_end_gcode,
    _resolve_start_gcode,
    build_bambu_3mf,
    repackage_gcode_as_bambu_3mf,
    thumbnail_inputs_for_model,
)

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(autouse=True)
def _clear_singleton_cache():
    """Reset lazy-loaded template singletons between tests."""
    _reset_cache()
    yield
    _reset_cache()


# Minimal PrusaSlicer-like gcode body with two layers.
MINIMAL_GCODE_BODY = """\
; generated by PrusaSlicer
M83
G28
M104 S200
M140 S60

;BEFORE_LAYER_CHANGE
;Z:0.2
;LAYER_CHANGE
G1 Z0.2 F600
G1 X10 Y10 E0.5

;BEFORE_LAYER_CHANGE
;Z:0.4
;LAYER_CHANGE
G1 Z0.4 F600
G1 X20 Y20 E0.5
"""

FAKE_START_GCODE = """\
; BambuStudio A1 start gcode
M104 S220
M140 S65
M109 S220
M190 S65
M104 S140
M104 S170
M104 S250
G1 Z25 F600
; set_filament_type:PLA
; set_filament_type:UNKNOWN
"""

FAKE_END_GCODE = """\
; End gcode
G1 Z65.0 F900
M104 S0
M140 S0
"""

# A real, parseable solid — four facets with actual volume, so the
# thumbnail renderer has something to paint and the result can be looked
# at rather than merely counted.
TETRAHEDRON_STL = """\
solid wedge
facet normal 0 0 -1
  outer loop
    vertex 0 0 0
    vertex 20 0 0
    vertex 10 18 0
  endloop
endfacet
facet normal 0 -1 0
  outer loop
    vertex 0 0 0
    vertex 10 9 16
    vertex 20 0 0
  endloop
endfacet
facet normal 1 1 0
  outer loop
    vertex 20 0 0
    vertex 10 9 16
    vertex 10 18 0
  endloop
endfacet
facet normal -1 1 0
  outer loop
    vertex 10 18 0
    vertex 10 9 16
    vertex 0 0 0
  endloop
endfacet
endsolid wedge
"""


# ---------------------------------------------------------------------------
# BambuPrintSettings tests
# ---------------------------------------------------------------------------

class TestBambuPrintSettingsDefaults:
    """BambuPrintSettings dataclass default values and to_dict."""

    def test_default_values(self):
        s = BambuPrintSettings()
        assert s.hotend_temp == 220
        assert s.bed_temp == 65
        assert s.filament_type == "PLA"
        assert s.filament_color == "#FFFFFF"
        assert s.nozzle_diameter == 0.4
        assert s.layer_height == 0.2
        assert s.bed_type == "textured_plate"
        assert s.model_name == "model"

    def test_custom_values(self):
        s = BambuPrintSettings(
            hotend_temp=250,
            bed_temp=90,
            filament_type="ABS",
            filament_color="#FF0000",
            nozzle_diameter=0.6,
            layer_height=0.3,
            bed_type="cool_plate",
            model_name="my_model",
        )
        assert s.hotend_temp == 250
        assert s.bed_temp == 90
        assert s.filament_type == "ABS"
        assert s.filament_color == "#FF0000"
        assert s.nozzle_diameter == 0.6
        assert s.layer_height == 0.3
        assert s.bed_type == "cool_plate"
        assert s.model_name == "my_model"

    def test_to_dict_keys(self):
        d = BambuPrintSettings().to_dict()
        expected_keys = {
            "hotend_temp", "bed_temp", "filament_type", "filament_color",
            "nozzle_diameter", "layer_height", "bed_type", "model_name",
        }
        assert set(d.keys()) == expected_keys

    def test_to_dict_values_match_fields(self):
        s = BambuPrintSettings(hotend_temp=240, filament_type="PETG")
        d = s.to_dict()
        assert d["hotend_temp"] == 240
        assert d["filament_type"] == "PETG"
        assert d["bed_temp"] == 65  # default


# ---------------------------------------------------------------------------
# Bambu3MFResult tests
# ---------------------------------------------------------------------------

class TestBambu3MFResult:
    """Bambu3MFResult dataclass and to_dict."""

    def test_to_dict_all_fields(self):
        r = Bambu3MFResult(
            output_path="/tmp/test.3mf",
            total_layers=10,
            max_z=2.0,
            file_size=1234,
            md5="abc123",
            est_print_time_sec=300,
        )
        d = r.to_dict()
        assert d["output_path"] == "/tmp/test.3mf"
        assert d["total_layers"] == 10
        assert d["max_z"] == 2.0
        assert d["file_size"] == 1234
        assert d["md5"] == "abc123"
        assert d["est_print_time_sec"] == 300


# ---------------------------------------------------------------------------
# Template loading tests
# ---------------------------------------------------------------------------

class TestTemplateLoading:
    """_load_a1_start_gcode / _load_a1_end_gcode with mocked filesystem."""

    def test_load_start_gcode_reads_file(self):
        from kiln.printers.bambu_3mf import _load_a1_start_gcode
        with patch("kiln.printers.bambu_3mf._A1_START_GCODE_PATH") as mock_path:
            mock_path.is_file.return_value = True
            mock_path.read_text.return_value = "G28\nM104 S220\n"
            result = _load_a1_start_gcode()
            assert result == "G28\nM104 S220\n"
            mock_path.read_text.assert_called_once_with(encoding="utf-8")

    def test_load_start_gcode_caches(self):
        from kiln.printers.bambu_3mf import _load_a1_start_gcode
        with patch("kiln.printers.bambu_3mf._A1_START_GCODE_PATH") as mock_path:
            mock_path.is_file.return_value = True
            mock_path.read_text.return_value = "cached content"
            result1 = _load_a1_start_gcode()
            result2 = _load_a1_start_gcode()
            assert result1 == result2
            # Should only read once due to singleton caching.
            mock_path.read_text.assert_called_once()

    def test_load_start_gcode_missing_file_raises(self):
        from kiln.printers.bambu_3mf import _load_a1_start_gcode
        with patch("kiln.printers.bambu_3mf._A1_START_GCODE_PATH") as mock_path:
            mock_path.is_file.return_value = False
            mock_path.__str__ = lambda self: "/fake/path/start.gcode"
            with pytest.raises(FileNotFoundError, match="start gcode not found"):
                _load_a1_start_gcode()

    def test_load_end_gcode_reads_file(self):
        from kiln.printers.bambu_3mf import _load_a1_end_gcode
        with patch("kiln.printers.bambu_3mf._A1_END_GCODE_PATH") as mock_path:
            mock_path.is_file.return_value = True
            mock_path.read_text.return_value = "M104 S0\n"
            result = _load_a1_end_gcode()
            assert result == "M104 S0\n"

    def test_load_end_gcode_missing_file_raises(self):
        from kiln.printers.bambu_3mf import _load_a1_end_gcode
        with patch("kiln.printers.bambu_3mf._A1_END_GCODE_PATH") as mock_path:
            mock_path.is_file.return_value = False
            mock_path.__str__ = lambda self: "/fake/path/end.gcode"
            with pytest.raises(FileNotFoundError, match="end gcode not found"):
                _load_a1_end_gcode()


# ---------------------------------------------------------------------------
# _resolve_start_gcode tests
# ---------------------------------------------------------------------------

class TestResolveStartGcode:
    """Temperature substitution in start gcode templates.

    220°C and 65°C are parametric (PLA defaults).
    140°C, 170°C, 250°C, 25°C are fixed init temps that must NOT change.
    """

    def test_default_temps_unchanged(self):
        result = _resolve_start_gcode(
            FAKE_START_GCODE, hotend_temp=220, bed_temp=65
        )
        assert "M104 S220" in result
        assert "M140 S65" in result

    def test_custom_hotend_temp_replaces_220(self):
        result = _resolve_start_gcode(
            FAKE_START_GCODE, hotend_temp=250, bed_temp=65
        )
        assert "M104 S250" in result
        assert "M109 S250" in result

    def test_custom_bed_temp_replaces_65(self):
        result = _resolve_start_gcode(
            FAKE_START_GCODE, hotend_temp=220, bed_temp=90
        )
        assert "M140 S90" in result
        assert "M190 S90" in result

    def test_fixed_temp_140_preserved(self):
        result = _resolve_start_gcode(
            FAKE_START_GCODE, hotend_temp=250, bed_temp=90
        )
        assert "M104 S140" in result

    def test_fixed_temp_170_preserved(self):
        result = _resolve_start_gcode(
            FAKE_START_GCODE, hotend_temp=250, bed_temp=90
        )
        assert "M104 S170" in result

    def test_fixed_temp_250_preserved_when_hotend_not_250(self):
        # When hotend IS 250, the M104 S250 line should be left alone
        # (it's a fixed init line, not a parametric one).  But since
        # M104 S250 only gets replaced when hotend_temp != 220 and the
        # line starts with M104 S220, the fixed 250 line is never matched.
        result = _resolve_start_gcode(
            FAKE_START_GCODE, hotend_temp=230, bed_temp=65
        )
        assert "M104 S250" in result

    def test_filament_type_replacement(self):
        result = _resolve_start_gcode(
            FAKE_START_GCODE, filament_type="PETG"
        )
        assert "set_filament_type:PETG" in result
        assert "set_filament_type:UNKNOWN" in result  # UNKNOWN preserved

    def test_filament_type_pla_unchanged(self):
        result = _resolve_start_gcode(
            FAKE_START_GCODE, filament_type="PLA"
        )
        assert "set_filament_type:PLA" in result

    def test_empty_template(self):
        result = _resolve_start_gcode("", hotend_temp=250, bed_temp=90)
        assert result == ""

    def test_both_temps_changed(self):
        result = _resolve_start_gcode(
            FAKE_START_GCODE, hotend_temp=240, bed_temp=80
        )
        assert "M104 S240" in result
        assert "M109 S240" in result
        assert "M140 S80" in result
        assert "M190 S80" in result
        # Fixed temps still present.
        assert "M104 S140" in result
        assert "M104 S170" in result
        assert "M104 S250" in result


# ---------------------------------------------------------------------------
# _resolve_end_gcode tests
# ---------------------------------------------------------------------------

class TestResolveEndGcode:
    """Z-height substitution in end gcode template."""

    def test_default_z_adjustment(self):
        result = _resolve_end_gcode(FAKE_END_GCODE, max_z=65.0)
        # safe_z = 65.0 + 5.0 = 70.0
        assert "G1 Z70.0 F900" in result

    def test_custom_z_height(self):
        result = _resolve_end_gcode(FAKE_END_GCODE, max_z=20.0)
        # safe_z = 20.0 + 5.0 = 25.0
        assert "G1 Z25.0 F900" in result

    def test_only_first_z_f900_replaced(self):
        template = "G1 Z65.0 F900\nG1 Z10.0 F900\n"
        result = _resolve_end_gcode(template, max_z=30.0)
        # Only the first match replaced.
        assert "G1 Z35.0 F900" in result
        assert "G1 Z10.0 F900" in result

    def test_non_matching_lines_preserved(self):
        result = _resolve_end_gcode(FAKE_END_GCODE, max_z=10.0)
        assert "M104 S0" in result
        assert "M140 S0" in result

    def test_z_with_integer_in_template(self):
        template = "G1 Z50 F900\n"
        result = _resolve_end_gcode(template, max_z=40.0)
        assert "G1 Z45.0 F900" in result


# ---------------------------------------------------------------------------
# _count_layers / _find_max_z tests
# ---------------------------------------------------------------------------

class TestCountLayers:
    """Layer counting from ;LAYER_CHANGE markers."""

    def test_two_layers(self):
        assert _count_layers(MINIMAL_GCODE_BODY) == 2

    def test_no_layers(self):
        assert _count_layers("G28\nG1 X10\n") == 0

    def test_empty_body(self):
        assert _count_layers("") == 0

    def test_inline_layer_change_not_counted(self):
        # ;LAYER_CHANGE must be at start of line
        body = "some text ;LAYER_CHANGE\n"
        assert _count_layers(body) == 0

    def test_many_layers(self):
        body = "\n".join(f";LAYER_CHANGE\nG1 Z{i * 0.2}" for i in range(100))
        assert _count_layers(body) == 100


class TestFindMaxZ:
    """Z-height extraction from ;Z: comments."""

    def test_finds_max_z(self):
        assert _find_max_z(MINIMAL_GCODE_BODY) == 0.4

    def test_no_z_comments_returns_default(self):
        assert _find_max_z("G28\nG1 X10\n") == 10.0

    def test_empty_body_returns_default(self):
        assert _find_max_z("") == 10.0

    def test_multiple_z_values(self):
        body = ";Z:0.2\n;Z:5.0\n;Z:3.0\n;Z:10.5\n"
        assert _find_max_z(body) == 10.5

    def test_integer_z_value(self):
        body = ";Z:10\n"
        assert _find_max_z(body) == 10.0


# ---------------------------------------------------------------------------
# _postprocess_prusa_body tests
# ---------------------------------------------------------------------------

class TestPostprocessPrusaBody:
    """PrusaSlicer gcode post-processing: init stripping + layer tracking."""

    def test_strips_prusa_init_commands(self):
        result = _postprocess_prusa_body(
            MINIMAL_GCODE_BODY, total_layers=2, est_time_sec=60
        )
        lines = result.split("\n")
        # M83, G28, M104, M140 from the header should be stripped.
        stripped_commands = [line.strip() for line in lines]
        assert "M83" not in stripped_commands
        assert "G28" not in stripped_commands

    def test_preserves_comments_in_header(self):
        result = _postprocess_prusa_body(
            MINIMAL_GCODE_BODY, total_layers=2, est_time_sec=60
        )
        assert "; generated by PrusaSlicer" in result

    def test_injects_m73_layer_tracking(self):
        result = _postprocess_prusa_body(
            MINIMAL_GCODE_BODY, total_layers=2, est_time_sec=60
        )
        assert "M73 L1" in result
        assert "M73 L2" in result

    def test_injects_m991_layer_notification(self):
        result = _postprocess_prusa_body(
            MINIMAL_GCODE_BODY, total_layers=2, est_time_sec=60
        )
        assert "M991 S0 P0" in result

    def test_injects_progress_percentage(self):
        result = _postprocess_prusa_body(
            MINIMAL_GCODE_BODY, total_layers=2, est_time_sec=120
        )
        # Layer 1 of 2 = 50%, layer 2 of 2 = 99% (capped)
        assert "M73 P50" in result
        assert "M73 P99" in result

    def test_progress_never_exceeds_99(self):
        # Single layer — 1/1*100 = 100, but capped at 99
        body = ";LAYER_CHANGE\nG1 Z0.2\n"
        result = _postprocess_prusa_body(
            body, total_layers=1, est_time_sec=60
        )
        assert "M73 P99" in result
        assert "M73 P100" not in result

    def test_remaining_time_in_minutes(self):
        result = _postprocess_prusa_body(
            MINIMAL_GCODE_BODY, total_layers=2, est_time_sec=600
        )
        # At layer 1: remaining = (2-1)*600/2 = 300 sec = 5 min
        assert "R5" in result

    def test_remaining_time_minimum_one_minute(self):
        result = _postprocess_prusa_body(
            MINIMAL_GCODE_BODY, total_layers=2, est_time_sec=60
        )
        # At layer 2: remaining sec = max(60, (2-2)*60/2) = max(60,0) = 60 → 1 min
        lines = result.split("\n")
        # Last progress line for layer 2 should have R1
        r_values = [line for line in lines if line.startswith("M73 P") and "R" in line]
        assert any("R1" in v for v in r_values)

    def test_preserves_gcode_after_header(self):
        result = _postprocess_prusa_body(
            MINIMAL_GCODE_BODY, total_layers=2, est_time_sec=60
        )
        assert "G1 X10 Y10 E0.5" in result
        assert "G1 X20 Y20 E0.5" in result

    def test_layer_comment_format(self):
        result = _postprocess_prusa_body(
            MINIMAL_GCODE_BODY, total_layers=2, est_time_sec=60
        )
        assert "; layer num/total_layer_count: 1/2" in result
        assert "; layer num/total_layer_count: 2/2" in result
        assert "; update layer progress" in result

    def test_no_layer_change_markers(self):
        body = "; just comments\nG1 X10\n"
        result = _postprocess_prusa_body(
            body, total_layers=0, est_time_sec=0
        )
        # No injection, body passes through.
        assert "M73 L" not in result
        assert "G1 X10" in result

    def test_strips_prusaslicer_m73_commands(self):
        """PrusaSlicer M73 P{pct} R{min} lines must be stripped.

        PrusaSlicer emits M73 progress lines throughout the gcode body.
        These lack the L parameter and override our injected layer tracking,
        causing the Bambu printer display to show stale progress.
        """
        body_with_m73 = (
            "; generated by PrusaSlicer\n"
            "M83\n"
            "M73 P0 R30\n"   # PrusaSlicer progress — should be stripped
            ";BEFORE_LAYER_CHANGE\n"
            ";Z:0.2\n"
            ";LAYER_CHANGE\n"
            "G1 Z0.2 F600\n"
            "M73 P10 R27\n"  # PrusaSlicer mid-layer progress — stripped
            "G1 X10 Y10 E0.5\n"
            "M73 P20 R24\n"  # Another PrusaSlicer M73 — stripped
            ";BEFORE_LAYER_CHANGE\n"
            ";Z:0.4\n"
            ";LAYER_CHANGE\n"
            "G1 Z0.4 F600\n"
            "M73 P50 R15\n"  # Stripped
            "G1 X20 Y20 E0.5\n"
        )
        result = _postprocess_prusa_body(
            body_with_m73, total_layers=2, est_time_sec=120
        )
        lines = result.split("\n")

        # Our injected M73 lines (with L and with correct P/R) should be present.
        assert "M73 L1" in result
        assert "M73 L2" in result

        # PrusaSlicer's native M73 lines should all be gone.
        prusa_m73_lines = [
            l for l in lines
            if l.strip().startswith("M73 ")
            and "L" not in l  # our injected lines have L
        ]
        # The only M73 P lines should be our injected ones (which are at
        # layer boundaries, right after M73 L lines).
        for m73_line in prusa_m73_lines:
            # Our injected M73 P lines are in the format "M73 P{pct} R{min}"
            # and appear right after "; update layer progress" — they should
            # only exist at positions following M73 L lines.
            pass
        # More directly: the specific PrusaSlicer values should be gone.
        assert "M73 P10 R27" not in result
        assert "M73 P20 R24" not in result
        assert "M73 P50 R15" not in result
        assert "M73 P0 R30" not in result

    def test_empty_body(self):
        result = _postprocess_prusa_body(
            "", total_layers=0, est_time_sec=0
        )
        assert result == ""

    def test_non_init_gcode_before_first_layer_preserved(self):
        """Non-init commands before the first LAYER_CHANGE should be kept."""
        body = "G92 E0\nG1 F1800\n;LAYER_CHANGE\nG1 Z0.2\n"
        result = _postprocess_prusa_body(
            body, total_layers=1, est_time_sec=30
        )
        # G92 is in _skip_prefixes so it IS stripped.
        # G1 F1800 is NOT in _skip_prefixes, so it should be kept.
        assert "G1 F1800" in result


# ---------------------------------------------------------------------------
# _build_gcode_header tests
# ---------------------------------------------------------------------------

class TestBuildGcodeHeader:
    """Gcode header block generation."""

    def test_contains_header_markers(self):
        h = _build_gcode_header(
            total_layers=10, max_z=2.0, est_print_time_sec=300
        )
        assert "; HEADER_BLOCK_START" in h
        assert "; HEADER_BLOCK_END" in h
        assert "; CONFIG_BLOCK_START" in h
        assert "; CONFIG_BLOCK_END" in h

    def test_contains_layer_count(self):
        h = _build_gcode_header(
            total_layers=42, max_z=8.4, est_print_time_sec=600
        )
        assert "; total layer number: 42" in h

    def test_contains_max_z(self):
        h = _build_gcode_header(
            total_layers=10, max_z=15.50, est_print_time_sec=300
        )
        assert "; max_z_height: 15.50" in h

    def test_contains_filament_type(self):
        h = _build_gcode_header(
            total_layers=10, max_z=2.0, est_print_time_sec=300,
            filament_type="PETG",
        )
        assert "; filament_type = PETG" in h

    def test_contains_temperatures(self):
        h = _build_gcode_header(
            total_layers=10, max_z=2.0, est_print_time_sec=300,
            hotend_temp=245, bed_temp=85,
        )
        assert "; temperature = 245" in h
        assert "; bed_temperature = 85" in h

    def test_time_formatting(self):
        # 3723 seconds = 1h 2m 3s
        h = _build_gcode_header(
            total_layers=10, max_z=2.0, est_print_time_sec=3723
        )
        assert "1h 2m 3s" in h

    def test_nozzle_diameter(self):
        h = _build_gcode_header(
            total_layers=10, max_z=2.0, est_print_time_sec=300,
            nozzle_diameter=0.6,
        )
        assert "; nozzle_diameter = 0.6" in h

    def test_bambu_studio_version(self):
        h = _build_gcode_header(
            total_layers=10, max_z=2.0, est_print_time_sec=300
        )
        assert "BambuStudio 02.05.00.66" in h


# ---------------------------------------------------------------------------
# _build_slice_info tests
# ---------------------------------------------------------------------------

class TestBuildSliceInfo:
    """XML slice_info.config generation."""

    def test_valid_xml_structure(self):
        xml = _build_slice_info(
            total_layers=10, est_print_time_sec=300
        )
        assert xml.startswith('<?xml version="1.0"')
        assert "<config>" in xml
        assert "</config>" in xml
        assert "<plate>" in xml

    def test_contains_prediction(self):
        xml = _build_slice_info(
            total_layers=10, est_print_time_sec=600
        )
        assert 'key="prediction" value="600"' in xml

    def test_contains_filament_type(self):
        xml = _build_slice_info(
            total_layers=10, est_print_time_sec=300,
            filament_type="ABS",
        )
        assert 'type="ABS"' in xml

    def test_contains_filament_color(self):
        xml = _build_slice_info(
            total_layers=10, est_print_time_sec=300,
            filament_color="#FF0000",
        )
        assert 'color="#FF0000"' in xml

    def test_contains_model_name(self):
        xml = _build_slice_info(
            total_layers=10, est_print_time_sec=300,
            model_name="benchy",
        )
        assert 'name="benchy"' in xml

    def test_layer_range_uses_total_layers(self):
        xml = _build_slice_info(
            total_layers=50, est_print_time_sec=1500
        )
        assert 'layer_ranges="0 49"' in xml

    def test_nozzle_diameter_in_filament(self):
        xml = _build_slice_info(
            total_layers=10, est_print_time_sec=300,
            nozzle_diameter=0.6,
        )
        assert 'nozzle_diameter="0.60"' in xml

    def test_printer_model_id(self):
        xml = _build_slice_info(
            total_layers=10, est_print_time_sec=300
        )
        assert 'printer_model_id" value="N2S"' in xml


# ---------------------------------------------------------------------------
# _build_plate_json tests
# ---------------------------------------------------------------------------

class TestBuildPlateJson:
    """JSON plate metadata generation."""

    def test_valid_json(self):
        raw = _build_plate_json()
        data = json.loads(raw)
        assert isinstance(data, dict)

    def test_default_values(self):
        data = json.loads(_build_plate_json())
        assert data["bed_type"] == "textured_plate"
        assert data["nozzle_diameter"] == 0.4
        assert data["filament_colors"] == ["#FFFFFF"]
        assert data["version"] == 2
        assert data["is_seq_print"] is False

    def test_custom_values(self):
        data = json.loads(_build_plate_json(
            filament_color="#00FF00",
            nozzle_diameter=0.6,
            bed_type="cool_plate",
            first_layer_time=120.0,
        ))
        assert data["filament_colors"] == ["#00FF00"]
        assert data["nozzle_diameter"] == 0.6
        assert data["bed_type"] == "cool_plate"
        assert data["first_layer_time"] == 120.0

    def test_bbox_all_present(self):
        data = json.loads(_build_plate_json())
        assert "bbox_all" in data
        assert len(data["bbox_all"]) == 4

    def test_filament_ids(self):
        data = json.loads(_build_plate_json())
        assert data["filament_ids"] == [0]
        assert data["first_extruder"] == 0


# ---------------------------------------------------------------------------
# build_bambu_3mf — end-to-end tests
# ---------------------------------------------------------------------------

class TestBuildBambu3mf:
    """End-to-end 3MF building with mocked template loading."""

    def _mock_templates(self):
        """Return patches for start and end gcode loading."""
        return (
            patch(
                "kiln.printers.bambu_3mf._load_a1_start_gcode",
                return_value=FAKE_START_GCODE,
            ),
            patch(
                "kiln.printers.bambu_3mf._load_a1_end_gcode",
                return_value=FAKE_END_GCODE,
            ),
        )

    def test_produces_valid_zip(self, tmp_path):
        out = str(tmp_path / "test.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            build_bambu_3mf(MINIMAL_GCODE_BODY, out)
        assert zipfile.is_zipfile(out)

    def test_contains_required_files(self, tmp_path):
        out = str(tmp_path / "test.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            build_bambu_3mf(MINIMAL_GCODE_BODY, out)
        with zipfile.ZipFile(out) as zf:
            names = zf.namelist()
            assert "[Content_Types].xml" in names
            assert "_rels/.rels" in names
            assert "3D/3dmodel.model" in names
            assert "Metadata/plate_1.gcode" in names
            assert "Metadata/plate_1.gcode.md5" in names
            assert "Metadata/slice_info.config" in names
            assert "Metadata/plate_1.json" in names
            assert "Metadata/model_settings.config" in names
            assert "Metadata/cut_information.xml" in names
            assert "Metadata/filament_sequence.json" in names
            assert "Metadata/project_settings.config" in names

    def test_gcode_md5_matches_content(self, tmp_path):
        out = str(tmp_path / "test.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            build_bambu_3mf(MINIMAL_GCODE_BODY, out)
        with zipfile.ZipFile(out) as zf:
            gcode = zf.read("Metadata/plate_1.gcode")
            stored_md5 = zf.read("Metadata/plate_1.gcode.md5").decode("utf-8")
            assert hashlib.md5(gcode).hexdigest() == stored_md5

    def test_result_metadata(self, tmp_path):
        out = str(tmp_path / "test.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            result = build_bambu_3mf(MINIMAL_GCODE_BODY, out)
        assert result.output_path == out
        assert result.total_layers == 2
        assert result.max_z == 0.4
        assert result.file_size > 0
        assert len(result.md5) == 32  # MD5 hex digest
        assert result.est_print_time_sec == 480  # 2 layers * 6s + 420s startup overhead

    def test_result_file_md5_matches(self, tmp_path):
        out = str(tmp_path / "test.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            result = build_bambu_3mf(MINIMAL_GCODE_BODY, out)
        actual_md5 = hashlib.md5(Path(out).read_bytes()).hexdigest()
        assert result.md5 == actual_md5

    def test_custom_settings_applied(self, tmp_path):
        out = str(tmp_path / "test.3mf")
        settings = BambuPrintSettings(
            hotend_temp=250,
            bed_temp=90,
            filament_type="ABS",
            filament_color="#FF0000",
            model_name="benchy",
        )
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            build_bambu_3mf(MINIMAL_GCODE_BODY, out, settings=settings)
        with zipfile.ZipFile(out) as zf:
            gcode = zf.read("Metadata/plate_1.gcode").decode("utf-8")
            assert "; filament_type = ABS" in gcode
            assert "; temperature = 250" in gcode
            assert "; bed_temperature = 90" in gcode

            slice_info = zf.read("Metadata/slice_info.config").decode("utf-8")
            assert 'type="ABS"' in slice_info
            assert 'color="#FF0000"' in slice_info
            assert 'name="benchy"' in slice_info

    def test_no_layer_change_raises_valueerror(self, tmp_path):
        out = str(tmp_path / "test.3mf")
        body = "; just comments\nG28\n"
        p_start, p_end = self._mock_templates()
        with p_start, p_end, pytest.raises(ValueError, match="no ;LAYER_CHANGE markers"):
            build_bambu_3mf(body, out)

    def test_empty_body_raises_valueerror(self, tmp_path):
        out = str(tmp_path / "test.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end, pytest.raises(ValueError, match="no ;LAYER_CHANGE markers"):
            build_bambu_3mf("", out)

    def test_creates_output_directory(self, tmp_path):
        out = str(tmp_path / "subdir" / "deep" / "test.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            build_bambu_3mf(MINIMAL_GCODE_BODY, out)
        assert os.path.isfile(out)

    def test_default_settings_used_when_none(self, tmp_path):
        out = str(tmp_path / "test.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            build_bambu_3mf(MINIMAL_GCODE_BODY, out, settings=None)
        with zipfile.ZipFile(out) as zf:
            gcode = zf.read("Metadata/plate_1.gcode").decode("utf-8")
            assert "; filament_type = PLA" in gcode
            assert "; temperature = 220" in gcode

    def test_gcode_contains_start_and_end(self, tmp_path):
        out = str(tmp_path / "test.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            build_bambu_3mf(MINIMAL_GCODE_BODY, out)
        with zipfile.ZipFile(out) as zf:
            gcode = zf.read("Metadata/plate_1.gcode").decode("utf-8")
            # Start gcode content should be present.
            assert "BambuStudio A1 start gcode" in gcode
            # End gcode content should be present.
            assert "; End gcode" in gcode

    def test_gcode_contains_layer_tracking(self, tmp_path):
        out = str(tmp_path / "test.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            build_bambu_3mf(MINIMAL_GCODE_BODY, out)
        with zipfile.ZipFile(out) as zf:
            gcode = zf.read("Metadata/plate_1.gcode").decode("utf-8")
            assert "M73 L1" in gcode
            assert "M73 L2" in gcode
            assert "M991 S0 P0" in gcode

    def test_gcode_starts_with_initial_m73(self, tmp_path):
        """Initial M73 at very start so firmware shows correct time immediately."""
        out = str(tmp_path / "test.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            build_bambu_3mf(MINIMAL_GCODE_BODY, out)
        with zipfile.ZipFile(out) as zf:
            gcode = zf.read("Metadata/plate_1.gcode").decode("utf-8")
            # The very first line should be M73 P0 R{minutes_with_startup}
            first_line = gcode.split("\n")[0]
            assert first_line.startswith("M73 P0 R")
            # Minutes should include startup overhead (420s = 7min)
            # 2 layers * 6s = 12s printing + 420s startup = 480s = 8min
            assert first_line == "M73 P0 R8"

    def test_slice_info_prediction_includes_startup_overhead(self, tmp_path):
        """slice_info prediction should include Bambu startup overhead."""
        out = str(tmp_path / "test.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            build_bambu_3mf(MINIMAL_GCODE_BODY, out)
        with zipfile.ZipFile(out) as zf:
            slice_info = zf.read("Metadata/slice_info.config").decode("utf-8")
            # 12s printing + 420s startup = 480s
            assert 'key="prediction" value="480"' in slice_info


# ---------------------------------------------------------------------------
# Source 3MF extraction tests
# ---------------------------------------------------------------------------

class TestBuildBambu3mfSourceExtraction:
    """Thumbnail and geometry extraction from a source 3MF."""

    def _mock_templates(self):
        return (
            patch(
                "kiln.printers.bambu_3mf._load_a1_start_gcode",
                return_value=FAKE_START_GCODE,
            ),
            patch(
                "kiln.printers.bambu_3mf._load_a1_end_gcode",
                return_value=FAKE_END_GCODE,
            ),
        )

    def test_extracts_thumbnails_from_source(self, tmp_path):
        # Create a fake source 3MF with a thumbnail.
        source = str(tmp_path / "source.3mf")
        with zipfile.ZipFile(source, "w") as zf:
            zf.writestr("Metadata/thumbnail.png", b"fake_png_data")
            zf.writestr("3D/3dmodel.model", "<model>custom geometry</model>")

        out = str(tmp_path / "output.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            build_bambu_3mf(
                MINIMAL_GCODE_BODY, out, source_3mf_path=source
            )
        with zipfile.ZipFile(out) as zf:
            assert "Metadata/thumbnail.png" in zf.namelist()
            assert zf.read("Metadata/thumbnail.png") == b"fake_png_data"

    def test_extracts_3d_model_from_source(self, tmp_path):
        source = str(tmp_path / "source.3mf")
        with zipfile.ZipFile(source, "w") as zf:
            zf.writestr("3D/3dmodel.model", "<model>custom geometry</model>")

        out = str(tmp_path / "output.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            build_bambu_3mf(
                MINIMAL_GCODE_BODY, out, source_3mf_path=source
            )
        with zipfile.ZipFile(out) as zf:
            model = zf.read("3D/3dmodel.model").decode("utf-8")
            assert "custom geometry" in model

    def test_bad_source_3mf_uses_minimal_model(self, tmp_path):
        # Create a corrupt source file.
        source = str(tmp_path / "corrupt.3mf")
        Path(source).write_text("not a zip")

        out = str(tmp_path / "output.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            build_bambu_3mf(
                MINIMAL_GCODE_BODY, out, source_3mf_path=source
            )
        # Should still produce a valid 3MF with the minimal model.
        assert zipfile.is_zipfile(out)
        with zipfile.ZipFile(out) as zf:
            model = zf.read("3D/3dmodel.model").decode("utf-8")
            assert "vertex" in model  # minimal cube model

    def test_nonexistent_source_3mf_uses_minimal_model(self, tmp_path):
        out = str(tmp_path / "output.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            build_bambu_3mf(
                MINIMAL_GCODE_BODY, out,
                source_3mf_path="/nonexistent/source.3mf",
            )
        assert zipfile.is_zipfile(out)

    def test_no_source_3mf_uses_minimal_model(self, tmp_path):
        out = str(tmp_path / "output.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            build_bambu_3mf(MINIMAL_GCODE_BODY, out, source_3mf_path=None)
        with zipfile.ZipFile(out) as zf:
            model = zf.read("3D/3dmodel.model").decode("utf-8")
            assert "vertex" in model


# ---------------------------------------------------------------------------
# repackage_gcode_as_bambu_3mf — stl_paths thumbnail fallback
# ---------------------------------------------------------------------------

class TestRepackageStlThumbnailFallback:
    """When no source_3mf_path thumbnails are available, stl_paths must
    trigger thumbnail generation so the Bambu LCD shows the actual part
    (not a blank preview)."""

    def test_stl_paths_triggers_thumbnail_generation(self, tmp_path):
        """A REAL mesh through the REAL renderer, asserted on the archive.

        The version of this test that mocked ``_generate_thumbnail`` was
        green for the entire life of the bug it was written to catch: the
        wraps passed a list of file PATHS to a function that takes parsed
        geometry, every call raised, and the mock stood in for the call
        that never worked.  A thumbnail test that never renders anything
        tests the mock.
        """
        gcode = tmp_path / "test.gcode"
        gcode.write_text("; test gcode\nG1 X0 Y0 Z0\n")
        stl = tmp_path / "wedge.stl"
        stl.write_text(TETRAHEDRON_STL)
        out = str(tmp_path / "output.3mf")

        repackage_gcode_as_bambu_3mf(str(gcode), out, stl_paths=[str(stl)])

        with zipfile.ZipFile(out) as zf:
            names = zf.namelist()
            assert "Metadata/plate_1.png" in names
            assert "Auxiliaries/.thumbnails/thumbnail_3mf.png" in names
            plate = zf.read("Metadata/plate_1.png")
        # Non-trivial bytes: a real render, not a placeholder or an empty
        # entry the archive would happily hold.
        assert plate.startswith(b"\x89PNG\r\n\x1a\n")
        assert len(plate) > 1000

    def test_source_3mf_thumbnails_win_over_stl_fallback(self, tmp_path):
        gcode = tmp_path / "test.gcode"
        gcode.write_text("; test gcode\n")
        source = tmp_path / "source.3mf"
        with zipfile.ZipFile(source, "w") as zf:
            zf.writestr("Metadata/plate_1.png", b"source_thumb_bytes")
        stl = tmp_path / "wedge.stl"
        stl.write_text(TETRAHEDRON_STL)
        out = str(tmp_path / "output.3mf")

        # The renderer should NOT run when the source 3MF already has
        # thumbnails — its own preview is truer than anything we'd make.
        with patch(
            "kiln.multicolor_3mf.render_plate_thumbnail",
            return_value=b"stl_fallback_bytes",
        ) as gen:
            repackage_gcode_as_bambu_3mf(
                str(gcode), out,
                source_3mf_path=str(source),
                stl_paths=[str(stl)],
            )
            gen.assert_not_called()

        with zipfile.ZipFile(out) as zf:
            assert zf.read("Metadata/plate_1.png") == b"source_thumb_bytes"

    def test_no_stl_no_thumbnails_still_succeeds(self, tmp_path):
        gcode = tmp_path / "test.gcode"
        gcode.write_text("; test gcode\n")
        out = str(tmp_path / "output.3mf")

        repackage_gcode_as_bambu_3mf(str(gcode), out)

        assert zipfile.is_zipfile(out)


# ---------------------------------------------------------------------------
# Thumbnails actually land in the archive — both doors, declared colors
# ---------------------------------------------------------------------------

def _part_pixels(png_bytes: bytes) -> list[tuple[int, int, int]]:
    """The lit pixels of the part, background aside.

    The renderer paints on a near-black field, so anything appreciably
    brighter than it belongs to the model.
    """
    from io import BytesIO

    from PIL import Image

    with Image.open(BytesIO(png_bytes)) as img:
        raw = img.convert("RGB").tobytes()
    pixels = [tuple(raw[i:i + 3]) for i in range(0, len(raw), 3)]
    return [p for p in pixels if sum(p) / 3 > 60]


def _cast_pixels(png_bytes: bytes) -> list[tuple[int, int, int]]:
    """Part pixels carrying a real color cast, shading and grey aside."""
    return [p for p in _part_pixels(png_bytes) if max(p) - min(p) > 40]


class TestThumbnailsReachTheArchive:
    """Every Bambu 3MF must carry a real preview for the printer screen.

    Both wraps passed bare file paths to a renderer that takes parsed
    geometry.  Every call raised ``ValueError`` inside a bare
    ``except Exception: pass``, so every 3MF Kiln uploaded had zero
    thumbnail entries and nothing anywhere went red.  These tests assert
    on the bytes in the emitted archive, which is the only place the
    defect was visible.
    """

    #: path -> the exact pixel size BambuStudio expects there.
    EXPECTED = {
        "Metadata/plate_1.png": (512, 512),
        "Metadata/plate_1_small.png": (128, 128),
        "Metadata/top_1.png": (512, 512),
        "Metadata/pick_1.png": (512, 512),
        "Auxiliaries/.thumbnails/thumbnail_3mf.png": (240, 180),
        "Auxiliaries/.thumbnails/thumbnail_middle.png": (680, 510),
        "Auxiliaries/.thumbnails/thumbnail_small.png": (251, 188),
    }

    def _mock_templates(self):
        return (
            patch(
                "kiln.printers.bambu_3mf._load_a1_start_gcode",
                return_value=FAKE_START_GCODE,
            ),
            patch(
                "kiln.printers.bambu_3mf._load_a1_end_gcode",
                return_value=FAKE_END_GCODE,
            ),
        )

    def _stl(self, tmp_path):
        stl = tmp_path / "wedge.stl"
        stl.write_text(TETRAHEDRON_STL)
        return str(stl)

    def _source_declaring(self, tmp_path, colors):
        """A source 3MF that declares *colors* and carries NO thumbnail."""
        source = tmp_path / "source.3mf"
        with zipfile.ZipFile(source, "w") as zf:
            zf.writestr(
                "Metadata/plate_1.json", json.dumps({"filament_colors": colors}),
            )
        return str(source)

    def test_build_bambu_3mf_embeds_the_full_thumbnail_set(self, tmp_path):
        out = str(tmp_path / "built.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            build_bambu_3mf(
                MINIMAL_GCODE_BODY, out, stl_paths=[self._stl(tmp_path)],
            )

        from io import BytesIO

        from PIL import Image

        with zipfile.ZipFile(out) as zf:
            names = zf.namelist()
            for path, size in self.EXPECTED.items():
                assert path in names, f"{path} missing from the 3MF"
                data = zf.read(path)
                assert len(data) > 500, f"{path} is a stub, {len(data)} bytes"
                with Image.open(BytesIO(data)) as img:
                    assert img.size == size, f"{path} is {img.size}, want {size}"

    def test_repackage_embeds_the_full_thumbnail_set(self, tmp_path):
        gcode = tmp_path / "ready.gcode"
        gcode.write_text("; already-bambu gcode\nG1 X0 Y0 Z0\n")
        out = str(tmp_path / "repacked.3mf")

        repackage_gcode_as_bambu_3mf(
            str(gcode), out, stl_paths=[self._stl(tmp_path)],
        )

        from io import BytesIO

        from PIL import Image

        with zipfile.ZipFile(out) as zf:
            names = zf.namelist()
            for path, size in self.EXPECTED.items():
                assert path in names, f"{path} missing from the 3MF"
                with Image.open(BytesIO(zf.read(path))) as img:
                    assert img.size == size, f"{path} is {img.size}, want {size}"

    def test_pixels_match_the_colour_the_SAME_archive_declares(self, tmp_path):
        """The file's own claim and its own preview must agree.

        Read wholly from the emitted 3MF: the color out of
        ``Metadata/plate_1.json``, the pixels out of
        ``Metadata/plate_1.png``.  Nothing the test supplies is trusted,
        so this cannot pass by agreeing with an input that the archive
        does not actually carry.
        """
        out = str(tmp_path / "red.3mf")
        settings = BambuPrintSettings(filament_color="#FF0000")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            build_bambu_3mf(
                MINIMAL_GCODE_BODY, out,
                settings=settings,
                stl_paths=[self._stl(tmp_path)],
            )

        with zipfile.ZipFile(out) as zf:
            declared = json.loads(zf.read("Metadata/plate_1.json"))["filament_colors"]
            lit = _cast_pixels(zf.read("Metadata/plate_1.png"))

        assert declared == ["#FF0000"]
        assert len(lit) > 1000, f"only {len(lit)} coloured pixels — grey preview?"
        mean_r = sum(p[0] for p in lit) / len(lit)
        mean_g = sum(p[1] for p in lit) / len(lit)
        mean_b = sum(p[2] for p in lit) / len(lit)
        assert mean_r > 2 * mean_g and mean_r > 2 * mean_b, (
            f"archive declares {declared} but the preview averages "
            f"({mean_r:.0f}, {mean_g:.0f}, {mean_b:.0f})"
        )

    def test_repackage_paints_the_colour_the_source_declared(self, tmp_path):
        """The copied declaration drives the copied-metadata door too.

        This door has no colors of its own — it inherits the plate
        metadata from the source 3MF.  A colour parameter here would have
        gone unpassed by its real caller and silently defaulted, so the
        colour is read back out of that copied JSON instead.
        """
        gcode = tmp_path / "ready.gcode"
        gcode.write_text("; already-bambu gcode\n")
        out = str(tmp_path / "blue.3mf")

        repackage_gcode_as_bambu_3mf(
            str(gcode), out,
            source_3mf_path=self._source_declaring(tmp_path, ["#0000FF"]),
            stl_paths=[self._stl(tmp_path)],
        )

        with zipfile.ZipFile(out) as zf:
            lit = _cast_pixels(zf.read("Metadata/plate_1.png"))

        assert len(lit) > 1000, f"only {len(lit)} coloured pixels — grey preview?"
        mean_r = sum(p[0] for p in lit) / len(lit)
        mean_b = sum(p[2] for p in lit) / len(lit)
        assert mean_b > 2 * mean_r, (
            "the source declared #0000FF but the preview did not render blue"
        )

    def test_a_white_declaration_renders_white_not_a_house_colour(self, tmp_path):
        """White means white — the preview may not brand the print.

        An earlier fix rendered this exact case (a plate declaring
        ``#FFFFFF``) in a warm house colour.  It looked like a working
        thumbnail and was a lie about what comes off the printer, which
        is worse than no thumbnail at all: the preview is how a
        non-technical user checks that the machine understood them.
        """
        out = str(tmp_path / "white.3mf")
        p_start, p_end = self._mock_templates()
        with p_start, p_end:
            # Default settings — the everyday slice-and-print case.
            build_bambu_3mf(
                MINIMAL_GCODE_BODY, out, stl_paths=[self._stl(tmp_path)],
            )

        with zipfile.ZipFile(out) as zf:
            declared = json.loads(zf.read("Metadata/plate_1.json"))["filament_colors"]
            plate = zf.read("Metadata/plate_1.png")

        assert declared == ["#FFFFFF"]
        part = _part_pixels(plate)
        assert len(part) > 1000, "the part did not render at all"
        # No colour cast: the failure mode this exists for is a preview
        # that paints a hue the file never declared.
        cast = _cast_pixels(plate)
        assert len(cast) < 0.02 * len(part), (
            f"declared {declared} but {len(cast)} of {len(part)} part pixels "
            "carry a colour cast — the preview invented a colour"
        )
        # ...and actually white, not a neutral grey standing in for it.
        bright = [p for p in part if sum(p) / 3 > 180]
        assert len(bright) > 1000, (
            f"a white part rendered only {len(bright)} bright pixels — "
            "the preview is too dark to be the declared white"
        )

    def test_an_undeclared_colour_renders_neutral_never_invented(self, tmp_path):
        """No declaration, no colour — render neutral rather than guess.

        Repackaging without a source 3MF writes no ``plate_1.json`` at
        all, so the archive claims nothing about filament.  A preview
        must not fill that silence with a colour of its own choosing.
        """
        gcode = tmp_path / "ready.gcode"
        gcode.write_text("; already-bambu gcode\n")
        out = str(tmp_path / "undeclared.3mf")

        repackage_gcode_as_bambu_3mf(
            str(gcode), out, stl_paths=[self._stl(tmp_path)],
        )

        with zipfile.ZipFile(out) as zf:
            assert "Metadata/plate_1.json" not in zf.namelist()
            plate = zf.read("Metadata/plate_1.png")

        part = _part_pixels(plate)
        assert len(part) > 1000, "the part did not render at all"
        cast = _cast_pixels(plate)
        assert len(cast) < 0.02 * len(part), (
            f"{len(cast)} of {len(part)} part pixels carry a colour cast, but "
            "the archive declares no filament colour — a colour was invented"
        )

    def test_thumbnail_failure_is_logged_not_swallowed(self, tmp_path, caplog):
        """A broken render still ships the print — and still says so.

        The bug survived because its exception was discarded by a bare
        ``except Exception: pass``.  Best-effort must never mean silent.
        """
        gcode = tmp_path / "ready.gcode"
        gcode.write_text("; already-bambu gcode\n")
        out = str(tmp_path / "out.3mf")

        with caplog.at_level(logging.WARNING), patch(
            "kiln.printers.bambu_3mf._render_plate_preview",
            side_effect=RuntimeError("renderer exploded"),
        ):
            repackage_gcode_as_bambu_3mf(
                str(gcode), out, stl_paths=[self._stl(tmp_path)],
            )

        # The print still shipped.
        assert zipfile.is_zipfile(out)
        with zipfile.ZipFile(out) as zf:
            assert not [n for n in zf.namelist() if n.endswith(".png")]
        # And the failure is on the record, with the traceback.
        assert "renderer exploded" in caplog.text
        assert "RuntimeError" in caplog.text

    def test_a_dead_primary_renderer_falls_back_instead_of_giving_up(
        self, tmp_path, caplog
    ):
        """Losing the good renderer costs quality, never the preview.

        Previews come from ``visualize_model`` so the printer's screen
        shows the same picture of the part as everywhere else in Kiln.
        When that cannot run, a plainer render still beats the blank tile
        this whole area exists to prevent — so the fallback is load-
        bearing, and it says out loud that it was used.
        """
        gcode = tmp_path / "ready.gcode"
        gcode.write_text("; already-bambu gcode\n")
        out = str(tmp_path / "fallback.3mf")

        with caplog.at_level(logging.WARNING), patch(
            "kiln.model_visualizer.visualize_model",
            side_effect=RuntimeError("no openscad here"),
        ):
            repackage_gcode_as_bambu_3mf(
                str(gcode), out, stl_paths=[self._stl(tmp_path)],
            )

        with zipfile.ZipFile(out) as zf:
            plate = zf.read("Metadata/plate_1.png")
        assert plate.startswith(b"\x89PNG\r\n\x1a\n")
        assert len(plate) > 1000
        assert "no openscad here" in caplog.text


class TestThumbnailInputsForModel:
    """One router, so every wrap door previews the same formats.

    Each door used to decide for itself which of the wrap's two thumbnail
    inputs a model file belongs in — and one of them never decided at
    all, wrapping gcode with no geometry and shipping a blank preview.
    """

    def test_a_mesh_goes_to_the_renderer(self, tmp_path):
        for name in ("part.stl", "part.obj", "part.glb"):
            mesh = tmp_path / name
            mesh.write_text("solid s\nendsolid s\n")
            assert thumbnail_inputs_for_model(str(mesh)) == ([str(mesh)], None)

    def test_a_3mf_goes_to_the_thumbnail_copier(self, tmp_path):
        project = tmp_path / "part.3mf"
        project.write_bytes(b"PK\x03\x04")
        assert thumbnail_inputs_for_model(str(project)) == (None, str(project))

    def test_an_unpreviewable_file_costs_the_preview_not_the_print(self, tmp_path):
        other = tmp_path / "part.gcode"
        other.write_text("G1 X0\n")
        assert thumbnail_inputs_for_model(str(other)) == (None, None)

    def test_nothing_to_route_is_not_an_error(self, tmp_path):
        assert thumbnail_inputs_for_model(None) == (None, None)
        assert thumbnail_inputs_for_model(str(tmp_path / "gone.stl")) == (None, None)

    def test_a_step_is_converted_only_to_draw_the_preview(self, tmp_path):
        """CAD-first users get a preview; the conversion stays unrecorded."""
        step = tmp_path / "part.step"
        step.write_text("ISO-10303-21;\n")
        mesh = tmp_path / "converted.stl"
        mesh.write_text("solid s\nendsolid s\n")

        with patch(
            "kiln.step_import.ensure_mesh_path",
            return_value=(str(mesh), None, None),
        ) as convert:
            assert thumbnail_inputs_for_model(str(step)) == ([str(mesh)], None)

        # No with_record= — see test_the_thumbnail_path_deliberately_keeps_no_record.
        assert convert.call_args.kwargs == {}

    def test_a_missing_step_converter_costs_only_the_preview(self, tmp_path):
        step = tmp_path / "part.step"
        step.write_text("ISO-10303-21;\n")

        with patch(
            "kiln.step_import.ensure_mesh_path",
            side_effect=RuntimeError("no backend installed"),
        ):
            assert thumbnail_inputs_for_model(str(step)) == (None, None)


# ---------------------------------------------------------------------------
# _reset_cache tests
# ---------------------------------------------------------------------------

class TestResetCache:
    """Singleton cache clearing."""

    def test_reset_allows_reload(self):
        import kiln.printers.bambu_3mf as mod
        mod._a1_start_gcode = "cached"
        mod._a1_end_gcode = "cached"
        _reset_cache()
        assert mod._a1_start_gcode is None
        assert mod._a1_end_gcode is None


# ---------------------------------------------------------------------------
# Production-extension sub-parts must travel with the root model
# ---------------------------------------------------------------------------


class TestProductionExtensionSubParts:
    """A copied root model part is only valid if its references resolve.

    Under the 3MF production extension the root part holds
    ``<component objectid=".." p:path="/3D/Objects/object_N.model"/>`` and the
    geometry lives in those sub-parts.  This writer copied the root part
    verbatim while reading only ``3D/3dmodel.model``, so the output referenced
    parts it never wrote — a dangling reference we manufactured.  Bambu Studio,
    OrcaSlicer and PrusaSlicer all emit that layout.
    """

    _SUB_PART = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<model unit="millimeter" xmlns='
        '"http://schemas.microsoft.com/3dmanufacturing/core/2015/02">\n'
        "  <resources>\n"
        '    <object id="2" type="model">\n'
        "      <mesh>\n"
        "        <vertices>\n"
        '          <vertex x="0" y="0" z="0"/>\n'
        '          <vertex x="1" y="0" z="0"/>\n'
        '          <vertex x="0" y="1" z="0"/>\n'
        '          <vertex x="0" y="0" z="1"/>\n'
        "        </vertices>\n"
        "        <triangles>\n"
        '          <triangle v1="0" v2="1" v3="2"/>\n'
        '          <triangle v1="0" v2="1" v3="3"/>\n'
        '          <triangle v1="0" v2="2" v3="3"/>\n'
        '          <triangle v1="1" v2="2" v3="3"/>\n'
        "        </triangles>\n"
        "      </mesh>\n"
        "    </object>\n"
        "  </resources>\n"
        "  <build/>\n"
        "</model>"
    )

    _ROOT_PART = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<model unit="millimeter" xmlns='
        '"http://schemas.microsoft.com/3dmanufacturing/core/2015/02" '
        'xmlns:p='
        '"http://schemas.microsoft.com/3dmanufacturing/production/2015/06">\n'
        "  <resources>\n"
        '    <object id="1" type="model">\n'
        "      <components>\n"
        '        <component objectid="2" '
        'p:path="/3D/Objects/object_2.model"/>\n'
        "      </components>\n"
        "    </object>\n"
        "  </resources>\n"
        '  <build><item objectid="1"/></build>\n'
        "</model>"
    )

    def _source(self, tmp_path: Path) -> str:
        """A source 3MF in the layout every real slicer writes."""
        src = tmp_path / "source.3mf"
        with zipfile.ZipFile(src, "w") as zf:
            zf.writestr("[Content_Types].xml", "<Types/>")
            zf.writestr("_rels/.rels", "<Relationships/>")
            zf.writestr("3D/3dmodel.model", self._ROOT_PART)
            zf.writestr("3D/Objects/object_2.model", self._SUB_PART)
        return str(src)

    @staticmethod
    def _dangling_refs(archive: str) -> list[str]:
        """Every p:path the archive references but does not contain."""
        with zipfile.ZipFile(archive) as zf:
            names = set(zf.namelist())
            root = zf.read("3D/3dmodel.model").decode("utf-8")
        referenced = set(re.findall(r'p:path="([^"]+)"', root))
        return sorted(
            ref for ref in referenced if ref.lstrip("/") not in names
        )

    def test_sub_part_is_carried_into_the_output(self, tmp_path: Path) -> None:
        out = str(tmp_path / "out.3mf")
        build_bambu_3mf(
            MINIMAL_GCODE_BODY, out, source_3mf_path=self._source(tmp_path),
        )
        with zipfile.ZipFile(out) as zf:
            assert "3D/Objects/object_2.model" in zf.namelist()

    def test_no_dangling_references_in_the_output(self, tmp_path: Path) -> None:
        """The invariant, not the fixture.

        This is the assertion that generalises: whatever the source layout,
        nothing we emit may reference a part the archive does not contain.
        """
        out = str(tmp_path / "out.3mf")
        build_bambu_3mf(
            MINIMAL_GCODE_BODY, out, source_3mf_path=self._source(tmp_path),
        )
        assert self._dangling_refs(out) == []

    def test_sub_part_bytes_are_unaltered(self, tmp_path: Path) -> None:
        """Geometry is copied, not re-serialised."""
        out = str(tmp_path / "out.3mf")
        build_bambu_3mf(
            MINIMAL_GCODE_BODY, out, source_3mf_path=self._source(tmp_path),
        )
        with zipfile.ZipFile(out) as zf:
            carried = zf.read("3D/Objects/object_2.model").decode("utf-8")
        assert carried == self._SUB_PART

    def test_single_part_source_gains_nothing(self, tmp_path: Path) -> None:
        """A source with no sub-parts must not grow spurious entries."""
        src = tmp_path / "flat.3mf"
        with zipfile.ZipFile(src, "w") as zf:
            zf.writestr("3D/3dmodel.model", self._SUB_PART)
        out = str(tmp_path / "out.3mf")
        build_bambu_3mf(MINIMAL_GCODE_BODY, out, source_3mf_path=str(src))
        with zipfile.ZipFile(out) as zf:
            extra = [
                n for n in zf.namelist()
                if n.startswith("3D/") and n != "3D/3dmodel.model"
            ]
        assert extra == []
# Per-model template selection
# ---------------------------------------------------------------------------

BUNDLE_MACHINE_DIR = Path(
    "/Applications/BambuStudio.app/Contents/Resources/profiles/BBL/machine"
)


class TestPerModelTemplateSelection:
    """The DECLARED model picks the template; anything else keeps the A1 files.

    The identity rule is load-bearing here and not a style preference: a model
    table that guessed wrong in five of six rows once named the wrong printer
    confidently, so only a declaration may drive this.
    """

    def test_declared_model_gets_its_own_end_gcode(self):
        from kiln.printers.bambu_3mf import _MODEL_END_GCODE_FILES, _select_end_gcode

        for model in _MODEL_END_GCODE_FILES:
            template, source = _select_end_gcode(model)
            assert source == model, f"{model} was served {source}'s end gcode"
            assert template, f"{model} end template is empty"

    def test_every_registered_model_names_a_real_data_file(self):
        from kiln.printers.bambu_3mf import (
            _DATA_DIR,
            _MODEL_END_GCODE_FILES,
            _MODEL_START_GCODE_FILES,
        )

        for registry in (_MODEL_START_GCODE_FILES, _MODEL_END_GCODE_FILES):
            for key, filename in registry.items():
                assert (_DATA_DIR / filename).is_file(), f"{key} -> {filename} missing"

    def test_p2s_no_longer_gets_a1_end_gcode(self):
        """The defect this change exists for, from the end-gcode side."""
        from kiln.printers.bambu_3mf import _select_end_gcode

        p2s, _ = _select_end_gcode("bambu_p2s")
        a1, _ = _select_end_gcode("bambu_a1")
        assert p2s != a1
        assert "P2S" in p2s

    def test_model_id_is_normalized(self):
        from kiln.printers.bambu_3mf import _select_end_gcode

        assert _select_end_gcode("  BAMBU_P2S ")[1] == "bambu_p2s"

    @pytest.mark.parametrize(
        "declared", [None, "", "   ", "bambu_a2l", "bambu_never_heard_of_it"],
    )
    def test_undeclared_or_unknown_model_keeps_todays_behaviour(self, declared):
        """Rule: an unknown model is never an error — people print on this path."""
        from kiln.printers.bambu_3mf import (
            _load_a1_end_gcode,
            _load_a1_start_gcode,
            _select_end_gcode,
            _select_start_gcode,
        )

        start, start_source = _select_start_gcode(declared)
        end, end_source = _select_end_gcode(declared)
        assert start == _load_a1_start_gcode()
        assert end == _load_a1_end_gcode()
        assert start_source == end_source == "bambu_a1"

    def test_a1_start_gcode_is_untouched(self):
        """The A1 sequence is the artifact proven on real hardware."""
        from kiln.printers.bambu_3mf import _load_a1_start_gcode, _select_start_gcode

        assert _select_start_gcode("bambu_a1", 0.4)[0] == _load_a1_start_gcode()

    def test_each_model_gets_its_own_start_sequence(self):
        """The defect this change exists for, from the start-gcode side."""
        from kiln.printers.bambu_3mf import _load_a1_start_gcode, _select_start_gcode

        a1 = _load_a1_start_gcode()
        for model in ("bambu_p2s", "bambu_p1s", "bambu_p1p", "bambu_x1c",
                      "bambu_x1e", "bambu_h2s", "bambu_a1_mini"):
            gcode, source = _select_start_gcode(model, 0.4)
            assert source == model, f"{model} was served {source}'s start gcode"
            assert gcode != a1, f"{model} still gets the A1 sequence"

    def test_enclosed_models_make_no_negative_x_move(self):
        """The hazard the A1 substitution created, pinned.

        The A1 and A1 mini are bed-slingers whose startup drives X negative
        with the soft endstops disabled first.  Wrapping an enclosed CoreXY
        print in that sequence aimed it off the front of its own bed.
        """
        from kiln.printers.bambu_3mf import _select_start_gcode

        for model in ("bambu_p2s", "bambu_p1s", "bambu_p1p",
                      "bambu_x1c", "bambu_x1e", "bambu_h2s"):
            gcode, _ = _select_start_gcode(model, 0.4)
            assert not re.search(r"X-\d", gcode), f"{model} drives X negative"

    def test_an_uncaptured_nozzle_falls_back_rather_than_borrowing(self):
        """A 0.6 owner must never be handed the 0.4 sequence silently."""
        from kiln.printers.bambu_3mf import _load_a1_start_gcode, _select_start_gcode

        gcode, source = _select_start_gcode("bambu_p2s", 0.6)
        assert source == "bambu_a1"
        assert gcode == _load_a1_start_gcode()

    def test_start_and_end_fallback_warnings_do_not_silence_each_other(self):
        """One shared warned-set made the start gap invisible once end had warned."""
        from kiln.printers.bambu_3mf import _select_end_gcode, _select_start_gcode

        with patch("kiln.printers.bambu_3mf.logger") as mock_logger:
            _select_end_gcode("bambu_a2l")
            _select_start_gcode("bambu_a2l")
            messages = [c.args[0] for c in mock_logger.warning.call_args_list]
        assert any("start gcode" in m for m in messages)
        assert any("end gcode" in m for m in messages)

    def test_fallback_warning_fires_once_per_model(self):
        from kiln.printers.bambu_3mf import _select_start_gcode

        with patch("kiln.printers.bambu_3mf.logger") as mock_logger:
            for _ in range(5):
                _select_start_gcode("bambu_h2d")
            assert mock_logger.warning.call_count == 1

    def test_a1_never_warns(self):
        from kiln.printers.bambu_3mf import _select_end_gcode, _select_start_gcode

        with patch("kiln.printers.bambu_3mf.logger") as mock_logger:
            _select_start_gcode("bambu_a1")
            _select_end_gcode("bambu_a1")
            assert mock_logger.warning.call_count == 0


# ---------------------------------------------------------------------------
# Shipped-template safety: nothing reaches a printer with a placeholder in it
# ---------------------------------------------------------------------------

class TestNoUnresolvedPlaceholderEverShips:
    """A surviving placeholder would be sent to the printer verbatim.

    This is the test that protects real hardware, so it sweeps every shipped
    data file rather than the ones a fixture happens to name.
    """

    @staticmethod
    def _shipped_gcode_files():
        from kiln.printers.bambu_3mf import _DATA_DIR

        return sorted(_DATA_DIR.glob("bambu_*_gcode.gcode"))

    def test_there_are_shipped_files_to_check(self):
        # A glob that silently matches nothing is a test that always passes.
        assert len(self._shipped_gcode_files()) >= 9

    def test_every_shipped_end_template_resolves_completely(self):
        from kiln.printers.bambu_3mf import (
            _MODEL_END_GCODE_FILES,
            _assert_fully_resolved,
            _resolve_end_gcode,
            _select_end_gcode,
        )

        # Z values spanning a first layer to the tallest bed Kiln knows.
        for model in _MODEL_END_GCODE_FILES:
            template, _ = _select_end_gcode(model)
            for max_z in (0.2, 12.0, 65.0, 150.0, 249.0, 255.0, 339.0):
                resolved = _resolve_end_gcode(
                    template, max_z=max_z, printer_model=model,
                )
                _assert_fully_resolved(resolved, source=f"{model} @ {max_z}")

    def test_every_shipped_start_template_resolves_completely(self):
        from kiln.printers.bambu_3mf import (
            _MODEL_START_GCODE_FILES,
            _assert_fully_resolved,
            _resolve_start_gcode,
            _select_start_gcode,
        )

        for model, nozzle in _MODEL_START_GCODE_FILES:
            template, _ = _select_start_gcode(model, nozzle)
            for temps in ((220, 65, "PLA"), (255, 100, "ABS")):
                resolved = _resolve_start_gcode(
                    template,
                    hotend_temp=temps[0], bed_temp=temps[1], filament_type=temps[2],
                )
                _assert_fully_resolved(resolved, source=f"{model} @ {nozzle}")

    def test_built_3mf_gcode_carries_no_placeholder(self, tmp_path):
        """End to end: the bytes actually written into the 3MF."""
        from kiln.printers.bambu_3mf import _MODEL_END_GCODE_FILES

        for model in _MODEL_END_GCODE_FILES:
            out = str(tmp_path / f"{model}.3mf")
            build_bambu_3mf(MINIMAL_GCODE_BODY, out, printer_model=model)
            with zipfile.ZipFile(out) as zf:
                name = next(n for n in zf.namelist() if n.endswith(".gcode"))
                gcode = zf.read(name).decode("utf-8")
            assert "{" not in gcode, f"{model} 3MF gcode has a brace placeholder"

    @pytest.mark.parametrize(
        "leaked",
        [
            "M140 S[bed_temperature_initial_layer_single]",
            "G1 Z{max_layer_z + 0.5} F900",
            "M104 S{nozzle_temperature_initial_layer[initial_extruder]}",
        ],
    )
    def test_guard_refuses_a_leaked_placeholder(self, leaked):
        from kiln.printers.bambu_3mf import _assert_fully_resolved

        with pytest.raises(ValueError, match="Unresolved gcode placeholder"):
            _assert_fully_resolved(f"G28\n{leaked}\nM400\n", source="test")

    def test_guard_reports_the_line_number(self):
        from kiln.printers.bambu_3mf import _assert_fully_resolved

        with pytest.raises(ValueError, match="line 3"):
            _assert_fully_resolved("G28\nM400\nM140 S[bed_temp]\n", source="test")

    def test_guard_passes_real_bambu_gcode(self):
        """No false positive on the proven files' own syntax."""
        from kiln.printers.bambu_3mf import _assert_fully_resolved, _load_a1_start_gcode

        _assert_fully_resolved(_load_a1_start_gcode(), source="a1 start")

    def test_build_refuses_an_unresolvable_template(self, tmp_path, monkeypatch):
        """The guard is wired into build_bambu_3mf, not just available to it."""
        import kiln.printers.bambu_3mf as mod

        monkeypatch.setattr(
            mod, "_select_end_gcode",
            lambda model: ("M104 S[nozzle_temperature_initial_layer]\n", "bambu_fake"),
        )
        with pytest.raises(ValueError, match="Unresolved gcode placeholder"):
            build_bambu_3mf(
                MINIMAL_GCODE_BODY, str(tmp_path / "o.3mf"), printer_model="bambu_fake",
            )


# ---------------------------------------------------------------------------
# End-template expansion, validated against the hardware-proven A1 capture
# ---------------------------------------------------------------------------

class TestEndTemplateExpansion:
    """The expander's ground truth is the A1 file proven on real hardware."""

    def test_pre_expanded_template_passes_through_untouched(self):
        from kiln.printers.bambu_3mf import _expand_end_template, _load_a1_end_gcode

        proven = _load_a1_end_gcode()
        assert _expand_end_template(proven, {"max_layer_z": 65.0}) == proven

    @pytest.mark.skipif(
        not BUNDLE_MACHINE_DIR.is_dir(),
        reason="BambuStudio not installed — the ground-truth template is unavailable",
    )
    def test_bundle_a1_template_expands_to_the_proven_capture(self):
        """Expanding the vendor A1 end template must reproduce our proven file.

        This is the only check available without hardware that the expander
        agrees with BambuStudio itself: same conditionals taken, same numbers,
        same blank lines where the guards were.  ``max_layer_z=65`` and bed
        centre 128 are read back out of the capture's own resolved values.
        """
        from kiln.printers.bambu_3mf import _expand_end_template, _load_a1_end_gcode

        source = BUNDLE_MACHINE_DIR / (
            "Bambu Lab A1 0.4 nozzle template machine_end_gcode.json"
        )
        template = json.loads(source.read_text(encoding="utf-8"))["machine_end_gcode"]
        expanded = _expand_end_template(
            template,
            {
                "max_layer_z": 65.0,
                "spiral_mode": False,
                "print_sequence": "by layer",
                "first_layer_center_no_wipe_tower": [128.0, 128.0],
            },
        )

        # The capture also holds the slicer's own preamble and postamble,
        # which are not part of the template.
        proven = _load_a1_end_gcode()
        middle = proven[
            proven.index(";===== date: 20231229") : proven.index("M73 P100 R0")
        ]
        assert expanded.rstrip("\n") == middle.rstrip("\n")

    def test_taller_print_takes_the_other_branch(self):
        """A print near the Z ceiling must clamp, not lift through the lid."""
        from kiln.printers.bambu_3mf import _expand_end_template, _select_end_gcode

        template, _ = _select_end_gcode("bambu_p1s")
        variables = {"max_layer_z": 20.0}
        short = _expand_end_template(template, variables)
        tall = _expand_end_template(template, {"max_layer_z": 240.0})
        assert "G1 Z120 F600" in short          # 20 + 100, under the 250 limit
        assert "G1 Z250 F600" in tall           # clamped by the {else} branch
        assert "G1 Z340 F600" not in tall

    def test_integral_results_lose_their_decimal_point(self):
        from kiln.printers.bambu_3mf import _format_template_number

        assert _format_template_number(165.0) == "165"
        assert _format_template_number(65.5) == "65.5"
        assert _format_template_number(163.0) == "163"

    def test_unbalanced_conditionals_raise(self):
        from kiln.printers.bambu_3mf import _expand_end_template

        with pytest.raises(ValueError, match="unclosed"):
            _expand_end_template("{if max_layer_z > 1}\nG28\n", {"max_layer_z": 5.0})
        with pytest.raises(ValueError, match=r"\{endif\} with no"):
            _expand_end_template("{endif}\n", {})

    def test_an_unknown_variable_raises_instead_of_guessing(self):
        from kiln.printers.bambu_3mf import _eval_template_expr

        with pytest.raises(ValueError, match="no value for"):
            _eval_template_expr("flush_temperatures + 1", {"max_layer_z": 1.0})

    def test_integer_division_is_refused_rather_than_guessed(self):
        """BambuStudio truncates `24/20` to 1; Python would say 1.2."""
        from kiln.printers.bambu_3mf import _eval_template_expr

        with pytest.raises(ValueError, match="Integer division"):
            _eval_template_expr("24/20", {})

    def test_unsupported_syntax_is_refused(self):
        from kiln.printers.bambu_3mf import _eval_template_expr

        with pytest.raises(ValueError, match="Unsupported syntax"):
            _eval_template_expr("min(1, 2)", {})

    def test_negation_does_not_mangle_not_equal(self):
        from kiln.printers.bambu_3mf import _eval_template_expr

        expr = '!spiral_mode && print_sequence != "by object"'
        variables = {"spiral_mode": False, "print_sequence": "by layer"}
        assert _eval_template_expr(expr, variables) is True
        variables["print_sequence"] = "by object"
        assert _eval_template_expr(expr, variables) is False


class TestBedCentreIsRead:
    """The bed centre is read from the spec sheet, never copied into a table."""

    def test_known_models_resolve_from_printer_intelligence(self):
        from kiln.printers.bambu_3mf import _bed_center

        assert _bed_center("bambu_a1") == (128.0, 128.0)
        assert _bed_center("bambu_a1_mini") == (90.0, 90.0)

    def test_unknown_model_gets_none_not_a_default_bed(self):
        """A wrong bed centre is a travel move to the wrong place."""
        from kiln.printers.bambu_3mf import _bed_center

        assert _bed_center("bambu_never_heard_of_it") is None
        assert _bed_center("") is None


# ---------------------------------------------------------------------------
# The doors that reach the builder
# ---------------------------------------------------------------------------

class TestDeclaredModelReachesTheBuilder:
    """Both public doors must pass the declaration through, not just one."""

    def test_adapter_passes_its_declared_model(self, tmp_path):
        from kiln.printers.bambu import BambuAdapter

        gcode = tmp_path / "part.gcode"
        gcode.write_text(MINIMAL_GCODE_BODY, encoding="utf-8")
        adapter = BambuAdapter(
            host="127.0.0.1", access_code="00000000", serial="0000",
            printer_model="bambu_p2s",
        )
        with patch("kiln.printers.bambu_3mf.build_bambu_3mf") as mock_build:
            mock_build.return_value.output_path = str(tmp_path / "part.3mf")
            adapter.wrap_gcode_as_3mf(str(gcode))
        assert mock_build.call_args.kwargs["printer_model"] == "bambu_p2s"

    def test_slicer_autowrap_passes_the_effective_printer(self, tmp_path):
        from kiln.plugins.slicer_tools import _auto_wrap_bambu_3mf

        gcode = tmp_path / "part.gcode"
        gcode.write_text(MINIMAL_GCODE_BODY, encoding="utf-8")
        with patch("kiln.printers.bambu_3mf.build_bambu_3mf") as mock_build:
            _auto_wrap_bambu_3mf(str(gcode), "bambu_h2s", None)
        assert mock_build.call_args.kwargs["printer_model"] == "bambu_h2s"
