"""The A1's tile shows the print's filament weight, from every Kiln door.

The printer's screen reads ``Metadata/slice_info.config``: the plate's
``<metadata key="weight">`` (grams, two decimals) and each
``<filament ... used_m="…" used_g="…">`` (metres and grams, two decimals).
Reference: the Bambu Studio 02.05.00.66 plate on Adam's own A1 (the
chopstick holder) carries ``weight="24.41"`` with filaments
``used_m="5.13" used_g="16.28"`` and ``used_m="2.70" used_g="8.13"`` —
the weight is the sum of the per-filament grams, and ``used_m`` is the
G-code header's ``total filament length [mm] : 5127.93,2704.70`` in
metres.  Kiln wrote ``0.00`` in all three places, so every Kiln print
showed no weight.

What each slicer writes, measured 2026-09-18:

* PrusaSlicer 2.9.4 with a filament density: ``; filament used [mm] =
  427.39``, ``; filament used [cm3] = 1.03``, ``; filament used [g] =
  1.27``, ``; total filament used [g] = 1.27``.  Without one (Kiln's
  printer-only profiles) the ``[g]`` line is omitted and the total reads
  ``0.00``.
* OrcaSlicer 2.3.2 (the painted jar): ``; filament used [mm] = 11035.45,
  584.76``, ``; filament used [cm3] = 26.54, 1.41``, ``; total filament
  used [g] = 0.00``, ``; filament_density = 0`` — one value per USED
  extruder, comma separated.
* Bambu Studio: header lines only — ``; total filament length [mm] :
  5127.93,2704.70`` and ``; total filament weight [g] : 16.28,8.13``.

So grams come from the slicer when it knew them, else from its length
times the filament cross-section times the material's density, and when
no slicer comment exists at all from the E moves themselves.
"""

from __future__ import annotations

import json
import math
import re
import zipfile
from pathlib import Path

import pytest

from kiln.printers import bambu_3mf

_AREA_MM2 = math.pi * (1.75 / 2) ** 2  # 2.405 mm^2 of 1.75 mm filament
_PLA = 1.24


@pytest.fixture(autouse=True)
def _clear_singleton_cache():
    bambu_3mf._reset_cache()
    yield
    bambu_3mf._reset_cache()


def _grams(mm: float, density: float = _PLA) -> float:
    return mm * _AREA_MM2 * density / 1000.0


def _layers(n: int = 2, tools: list[int] | None = None, e: float | None = 0.5) -> str:
    """A PrusaSlicer-shaped body: relative E, one layer change per layer."""
    out = ["; generated by PrusaSlicer 2.9.4", "M83 ; use relative distances for extrusion", "G28", "M104 S200"]
    for i in range(n):
        out += [
            ";BEFORE_LAYER_CHANGE",
            f";Z:{0.2 * (i + 1):.1f}",
            ";LAYER_CHANGE",
            f"G1 Z{0.2 * (i + 1):.1f} F600",
        ]
        if tools:
            out.append(f"T{tools[i % len(tools)]}")
        move = f"G1 X{10 * (i + 1)} Y10"
        if e is not None:
            move += f" E{e}"
        out.append(move)
    return "\n".join(out) + "\n"


_PRUSA_FOOTER = (
    "; filament used [mm] = 427.39\n"
    "; filament used [cm3] = 1.03\n"
    "; filament used [g] = 1.27\n"
    "; total filament used [g] = 1.27\n"
    "; total filament cost = 0.00\n"
    "; filament_density = 1.24\n"
    "; filament_diameter = 1.75\n"
)

# The painted jar, as OrcaSlicer 2.3.2 wrote it through Kiln's density-less profile.
_ORCA_JAR_FOOTER = (
    "; filament used [mm] = 11035.45, 584.76\n"
    "; filament used [cm3] = 26.54, 1.41\n"
    "; total filament used [g] = 0.00\n"
    "; total filament cost = 0.00\n"
    "; total filament change = 8\n"
    "; filament_colour = #FFFFFF;#F72323\n"
    "; filament_density = 0\n"
    "; filament_diameter = 1.75,1.75\n"
    "; filament_type = PLA;PLA\n"
)

_STUDIO_HEADER = (
    "; HEADER_BLOCK_START\n"
    "; BambuStudio 02.05.00.66\n"
    "; total filament length [mm] : 5127.93,2704.70\n"
    "; total filament volume [cm^3] : 12334.13,6505.56\n"
    "; total filament weight [g] : 16.28,8.13\n"
    "; filament_density: 1.32,1.25,1.25,1.24,1.24\n"
    "; filament_diameter: 1.75,1.75,1.75,1.75,1.75\n"
    "; HEADER_BLOCK_END\n"
)


def _slice_info(path: str) -> str:
    with zipfile.ZipFile(path) as zf:
        return zf.read("Metadata/slice_info.config").decode("utf-8")


def _weight(xml: str) -> str:
    return re.search(r'<metadata key="weight" value="([^"]*)"', xml).group(1)


def _filaments(xml: str) -> list[tuple[str, str]]:
    return re.findall(r'<filament id="\d+"[^>]*used_m="([^"]*)" used_g="([^"]*)"', xml)


# ---------------------------------------------------------------------------
# The one reader
# ---------------------------------------------------------------------------


class TestGramsFromSlicerComments:
    def test_prusaslicer_grams_are_taken_as_written(self):
        usage = bambu_3mf.filament_usage_from_gcode(_layers(2) + _PRUSA_FOOTER)
        assert usage.mm == pytest.approx((427.39,))
        assert usage.grams == pytest.approx((1.27,))
        assert usage.total_g == pytest.approx(1.27)
        assert usage.source == "slicer_grams"

    def test_orca_without_a_density_gets_grams_from_its_length(self):
        usage = bambu_3mf.filament_usage_from_gcode(_layers(4, tools=[0, 1, 0, 1]) + _ORCA_JAR_FOOTER)
        assert usage.mm == pytest.approx((11035.45, 584.76))
        assert usage.grams == pytest.approx((_grams(11035.45), _grams(584.76)), abs=0.005)
        assert usage.grams == pytest.approx((32.91, 1.74), abs=0.005)
        assert usage.total_g == pytest.approx(34.66, abs=0.005)
        assert usage.source == "slicer_length"

    def test_bambu_studio_header_totals_are_read(self):
        usage = bambu_3mf.filament_usage_from_gcode(_STUDIO_HEADER + _layers(2, tools=[0, 1]))
        assert usage.mm == pytest.approx((5127.93, 2704.70))
        assert usage.grams == pytest.approx((16.28, 8.13))
        assert usage.total_g == pytest.approx(24.41)

    def test_the_material_picks_the_density(self):
        body = _layers(2) + "; filament used [mm] = 1000\n; filament_density = 0\n; filament_type = PETG\n"
        usage = bambu_3mf.filament_usage_from_gcode(body)
        assert usage.grams == pytest.approx((_grams(1000, 1.27),), abs=0.005)

    def test_the_callers_material_outranks_the_profiles_default(self):
        body = _layers(2) + "; filament used [mm] = 1000\n; filament_type = PLA\n"
        usage = bambu_3mf.filament_usage_from_gcode(body, filament_types=["ABS"])
        assert usage.grams == pytest.approx((_grams(1000, 1.04),), abs=0.005)

    def test_the_slicers_own_density_outranks_the_table(self):
        body = _layers(2) + "; filament used [mm] = 1000\n; filament_density = 1.32\n; filament_type = PLA\n"
        usage = bambu_3mf.filament_usage_from_gcode(body)
        assert usage.grams == pytest.approx((_grams(1000, 1.32),), abs=0.005)

    def test_values_land_on_the_extruders_the_print_used(self):
        # Orca and Prusa list one value per USED extruder: a print on T0 and
        # T2 writes two numbers, and the second belongs to tray 3, not tray 2.
        body = _layers(4, tools=[0, 2, 0, 2]) + "; filament used [mm] = 100, 50\n"
        usage = bambu_3mf.filament_usage_from_gcode(body)
        assert usage.mm == pytest.approx((100.0, 0.0, 50.0))


class TestGramsFromEMoves:
    def test_relative_e_is_summed_when_no_comment_exists(self):
        body = "M83\nG1 X1 Y1 E400\nG1 E-0.8\nG1 E0.8\nG1 X2 Y2 E600 ; comment E999\n"
        usage = bambu_3mf.filament_usage_from_gcode(body)
        assert usage.mm == pytest.approx((1000.0,))
        assert usage.grams == pytest.approx((_grams(1000),), abs=0.005)
        assert usage.grams[0] == pytest.approx(2.98, abs=0.005)
        assert usage.source == "e_moves"

    def test_absolute_e_and_g92_resets_are_honoured(self):
        body = "M82\nG1 X1 E5\nG1 X2 E12\nG92 E0\nG1 X3 E3\n"
        usage = bambu_3mf.filament_usage_from_gcode(body)
        assert usage.mm == pytest.approx((15.0,))

    def test_multi_filament_split_follows_the_tool_changes(self):
        body = "M83\nT0\nG1 X1 E100\nT1\nG1 X2 E50\nT0\nG1 X3 E25\nT1000\nG1 E7\nT255\n"
        usage = bambu_3mf.filament_usage_from_gcode(body)
        # Bambu's T255 / T1000 are pseudo-tools of the start sequence, not trays.
        assert usage.mm == pytest.approx((125.0, 50.0))
        assert usage.grams == pytest.approx((_grams(125), _grams(50)), abs=0.005)

    def test_no_extrusion_is_zero_and_says_so(self):
        usage = bambu_3mf.filament_usage_from_gcode("G28\nG1 X10 Y10\nG1 Z5\n")
        assert usage.total_g == 0.0
        assert usage.total_mm == 0.0
        assert usage.source == "none"


# ---------------------------------------------------------------------------
# The builder writes them where the A1 reads
# ---------------------------------------------------------------------------


class TestBuilderWritesTheWeight:
    def test_single_filament(self, tmp_path):
        out = str(tmp_path / "one.gcode.3mf")
        bambu_3mf.build_bambu_3mf(_layers(3) + _PRUSA_FOOTER, out)
        xml = _slice_info(out)
        assert _weight(xml) == "1.27"
        assert _filaments(xml) == [("0.43", "1.27")]

    def test_multi_filament_split(self, tmp_path):
        body = (
            _layers(4, tools=[0, 1, 2, 0])
            + "; filament_colour = #F2F2F2;#D32F2F;#1A1A1A\n"
            + "; filament_type = PLA;PETG;PLA\n"
            + "; filament used [mm] = 100.0, 50.0, 25.0\n"
        )
        out = str(tmp_path / "three.gcode.3mf")
        bambu_3mf.build_bambu_3mf(body, out)
        xml = _slice_info(out)
        expected = [_grams(100), _grams(50, 1.27), _grams(25)]
        assert _filaments(xml) == [
            ("0.10", f"{expected[0]:.2f}"),
            ("0.05", f"{expected[1]:.2f}"),
            ("0.03", f"{expected[2]:.2f}"),
        ]
        assert _weight(xml) == f"{sum(expected):.2f}"

    def test_the_declared_material_is_the_density_source(self, tmp_path):
        out = str(tmp_path / "petg.gcode.3mf")
        body = _layers(3) + "; filament used [mm] = 1000\n; filament_density = 0\n"
        bambu_3mf.build_bambu_3mf(body, out, settings=bambu_3mf.BambuPrintSettings(filament_type="PETG"))
        assert _weight(_slice_info(out)) == f"{_grams(1000, 1.27):.2f}"

    def test_no_extrusion_writes_zero_honestly(self, tmp_path):
        out = str(tmp_path / "empty.gcode.3mf")
        bambu_3mf.build_bambu_3mf(_layers(3, e=None), out)
        xml = _slice_info(out)
        assert _weight(xml) == "0.00"
        assert _filaments(xml) == [("0.00", "0.00")]


# ---------------------------------------------------------------------------
# Completion fills a slicer's own plate, G-code untouched
# ---------------------------------------------------------------------------

_MODEL = """\
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <resources>
    <basematerials id="1">
      <base name="White" displaycolor="#FFFFFF" />
      <base name="Red" displaycolor="#F72323" />
    </basematerials>
    <object id="2" type="model" pid="1" pindex="0">
      <mesh>
        <vertices>
          <vertex x="0" y="0" z="0" /><vertex x="20" y="0" z="0" /><vertex x="0" y="20" z="0" />
          <vertex x="20" y="20" z="0" /><vertex x="10" y="10" z="15" />
        </vertices>
        <triangles>
          <triangle v1="0" v2="1" v3="4" />
          <triangle v1="1" v2="3" v3="4" pid="1" p1="1" />
          <triangle v1="3" v2="2" v3="4" />
          <triangle v1="2" v2="0" v3="4" pid="1" p1="1" />
          <triangle v1="0" v2="2" v3="1" /><triangle v1="1" v2="2" v3="3" />
        </triangles>
      </mesh>
    </object>
  </resources>
  <build><item objectid="2" /></build>
</model>"""

_FILAMENT = (
    '    <filament id="{id}" tray_info_idx="GFL99" type="PLA" color="{color}" used_m="{m}" used_g="{g}" '
    'used_for_object="true" used_for_support="false" group_id="0" nozzle_diameter="0.40" volume_type="Standard"/>\n'
)


def _slice_info_xml(weight: str, filaments: list[tuple[str, str, str]]) -> str:
    rows = "".join(_FILAMENT.format(id=i + 1, color=c, m=m, g=g) for i, (c, m, g) in enumerate(filaments))
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n<config>\n  <plate>\n'
        '    <metadata key="index" value="1"/>\n    <metadata key="prediction" value="6382"/>\n'
        f'    <metadata key="weight" value="{weight}"/>\n'
        '    <metadata key="filament_maps" value="0;1"/>\n'
        + rows
        + "  </plate>\n</config>\n"
    )


def _orca_jar_archive(tmp_path: Path, *, weight: str = "0.00", grams=("0.00", "0.00")) -> str:
    """The painted jar as Orca wrapped it: plate G-code with indented tool
    changes inside the AMS blocks, its own slice_info with 0.00 everywhere."""
    gcode = (
        "; generated by OrcaSlicer 2.3.2\nM83\nG28\nM620 S0A\n    T0\nM621 S0A\n"
        "G1 X10 Y10 Z0.2 E1\nM620 S1A\n    T1\nM621 S1A\nG1 X12 Y10 E1\n" + _ORCA_JAR_FOOTER
    )
    p = tmp_path / "jar.gcode.3mf"
    with zipfile.ZipFile(p, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("3D/3dmodel.model", _MODEL)
        zf.writestr("Metadata/plate_1.gcode", gcode)
        zf.writestr(
            "Metadata/slice_info.config",
            _slice_info_xml(weight, [("#FFFFFF", "0.00", grams[0]), ("#F72323", "0.00", grams[1])]),
        )
        zf.writestr("Metadata/plate_1.json", json.dumps({"filament_colors": ["#FFFFFF", "#F72323"], "version": 2}))
    return str(p)


def _members(path: str) -> dict[str, bytes]:
    with zipfile.ZipFile(path) as zf:
        return {n: zf.read(n) for n in zf.namelist()}


class TestCompletionFillsTheWeight:
    def test_orcas_zero_becomes_the_jars_real_weight(self, tmp_path):
        path = _orca_jar_archive(tmp_path)
        before = _members(path)
        bambu_3mf.complete_bambu_archive(path)
        after = _members(path)
        assert after["Metadata/plate_1.gcode"] == before["Metadata/plate_1.gcode"]
        assert after["3D/3dmodel.model"] == before["3D/3dmodel.model"]
        xml = after["Metadata/slice_info.config"].decode("utf-8")
        assert _weight(xml) == "34.66"
        assert _filaments(xml) == [("11.04", "32.91"), ("0.58", "1.74")]
        # Everything else in the file is exactly what it was.
        assert 'key="prediction" value="6382"' in xml
        assert 'key="filament_maps" value="0;1"' in xml

    def test_a_weight_the_slicer_knew_is_left_alone(self, tmp_path):
        path = _orca_jar_archive(tmp_path, weight="24.41", grams=("16.28", "8.13"))
        bambu_3mf.complete_bambu_archive(path)
        xml = _members(path)["Metadata/slice_info.config"].decode("utf-8")
        assert _weight(xml) == "24.41"
        assert [g for _, g in _filaments(xml)] == ["16.28", "8.13"]

    def test_completion_is_idempotent_on_the_weight(self, tmp_path):
        path = _orca_jar_archive(tmp_path)
        bambu_3mf.complete_bambu_archive(path)
        first = _members(path)["Metadata/slice_info.config"]
        bambu_3mf.complete_bambu_archive(path)
        assert _members(path)["Metadata/slice_info.config"] == first


class TestRepackageDoorFillsTheWeight:
    """The third door: a plate object's gcode wrapped with the source
    archive's own slice_info, which used to carry the slicer's 0.00 verbatim."""

    def _repackage(self, tmp_path: Path) -> str:
        source = _orca_jar_archive(tmp_path)
        gcode = tmp_path / "object.gcode"
        gcode.write_text("M83\nG28\nG1 X10 Y10 Z0.2 E1\n" + _ORCA_JAR_FOOTER, encoding="utf-8")
        out = str(tmp_path / "object.gcode.3mf")
        bambu_3mf.repackage_gcode_as_bambu_3mf(str(gcode), out, source_3mf_path=source)
        return out

    def test_the_copied_zero_becomes_the_gcodes_weight(self, tmp_path):
        xml = _slice_info(self._repackage(tmp_path))
        assert _weight(xml) == "34.66"
        assert _filaments(xml) == [("11.04", "32.91"), ("0.58", "1.74")]

    def test_without_the_fill_the_zero_would_have_been_copied(self, tmp_path, monkeypatch):
        # The pin: with the fill switched off the door copies 0.00 through,
        # which is exactly what it did before.
        monkeypatch.setattr(bambu_3mf, "_slice_info_knows_its_weight", lambda _xml: True)
        assert _weight(_slice_info(self._repackage(tmp_path))) == "0.00"


class TestEMovesCountLikeTheSlicer:
    """The printer-screen fallback counts the way the slicer's own total is
    counted, so a file with no slicer totals weighs what it would have."""

    def test_a_bambu_studio_start_sequence_keeps_the_filament_through_t1000(self):
        # Bambu Studio's nozzle-load line runs under T1000; everything
        # printed after it used to be dropped as belonging to no tray.
        body = (
            "M83\nT0\nG1 X1 Y1 E100\n"
            "T1000\nG1 X18 Y1 Z0.8 F18000\nG0 E2 F300\nG0 X240 E15 F4800\n"
            "G1 X10 Y10 E200\nG1 X20 Y20 E300\n"
        )
        usage = bambu_3mf.filament_usage_from_gcode(body)
        assert usage.source == "e_moves"
        assert usage.mm == (pytest.approx(615.0),)

    def test_a_wipe_retract_and_its_prime_are_not_plastic(self):
        # OrcaSlicer retracts part-way while wiping (E-.32 on a travel),
        # finishes the retract, then primes E.8 before the next wall.
        # Signed sums netted +0.48 of that as filament.
        body = "M83\nG1 X10 Y10 E5\nG1 X11 Y10 E-.32\nG1 E-.48 F1800\nG1 E.8 F1800\nG1 X20 Y10 E5\n"
        usage = bambu_3mf.filament_usage_from_gcode(body)
        assert usage.mm == (pytest.approx(10.0),)

    def test_a_filament_change_unload_is_not_subtracted(self):
        body = "M83\nT0\nG1 X1 Y1 E100\nG1 E-15 F6000\nG1 E-55.3 F5400\nT1\nG1 E30\nG1 X2 Y2 E40\n"
        usage = bambu_3mf.filament_usage_from_gcode(body)
        assert usage.mm == (pytest.approx(100.0), pytest.approx(40.0))
