#!/usr/bin/env python3
"""Generate the public "supported printers" marketing surface from the
source of truth.

The source of truth for *which printers Kiln supports* is
``kiln/src/kiln/data/printer_intelligence.json`` (one entry per model) plus
the canonical brand map (kept in sync with
``kiln.design_intelligence._MANUFACTURER_PREFIXES`` by
``tests/test_supported_printers.py``). This script reads that data, groups
models by brand, drops any model that is missing a required sibling profile
(so we never advertise a half-finished printer), and writes
``docs/site/src/data/supported_printers.json`` — which the website's
``/printers`` page renders.

This is the auto-maintain hook: add a model to ``printer_intelligence.json``
(with its safety, slicer, and material-compatibility profiles) and rerun this
script — the marketing surface names the new model with zero hand-editing.

Usage::

    python3 scripts/generate_supported_printers.py          # write the surface
    python3 scripts/generate_supported_printers.py --check  # CI gate: exit 1 if stale

Wire ``--check`` into pre-commit / CI so the committed surface can never drift
from the data (the same guarantee ``check_doc_counts.py`` gives the README).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "kiln" / "src" / "kiln" / "data"
INTEL = DATA / "printer_intelligence.json"
OUT = ROOT / "docs" / "site" / "src" / "data" / "supported_printers.json"
README = ROOT / "README.md"
RM_BEGIN = "<!-- BEGIN SUPPORTED PRINTERS (auto-generated by scripts/generate_supported_printers.py) -->"
RM_END = "<!-- END SUPPORTED PRINTERS -->"

# Required sibling surfaces. A model present in printer_intelligence.json but
# missing any of these is *incomplete* — we refuse to advertise it until its
# support is full-fledged. (kiln-pro's check_doc_counts.py is the hard parity
# gate across all five surfaces; this is the marketing-side safety net.)
REQUIRED_SURFACES = {
    "safety": DATA / "safety_profiles.json",
    "slicer": DATA / "slicer_profiles.json",
    "material-compat": DATA / "design_knowledge" / "printer_material_compatibility.json",
}

# Generic fallback profiles, not real purchasable models — never advertised.
EXCLUDED_IDS = {"default", "klipper_generic"}

# Canonical printer_id-prefix -> manufacturer map. MUST stay identical to
# kiln.design_intelligence._MANUFACTURER_PREFIXES; that invariant is pinned by
# tests/test_supported_printers.py so the two can never silently drift. Order
# matters: more specific prefixes first.
MANUFACTURER_PREFIXES: list[tuple[str, str]] = [
    ("bambu_", "Bambu Lab"),
    ("elegoo_", "Elegoo"),
    ("prusa_", "Prusa Research"),
    ("voron_", "Voron"),
    ("anker", "AnkerMake"),
    ("artillery", "Artillery"),
    ("flashforge", "FlashForge"),
    ("qidi", "QIDI"),
    ("ratrig", "RatRig"),
    ("sovol", "Sovol"),
    ("creality_hi", "Creality"),
    ("cr10", "Creality"),
    ("ender", "Creality"),
    ("k1", "Creality"),
    ("k2", "Creality"),
    ("sparkx", "SparkX"),
    ("klipper_generic", "Generic"),
]


def derive_manufacturer(printer_id: str, display_name: str) -> str:
    pid = printer_id.lower()
    for prefix, mfr in MANUFACTURER_PREFIXES:
        if pid.startswith(prefix):
            return mfr
    return display_name.split()[0] if display_name.strip() else "Unknown"


def _load(path: Path) -> dict:
    return json.loads(path.read_text())


def build_surface() -> tuple[dict, list[tuple[str, list[str]]]]:
    intel = _load(INTEL)
    siblings = {name: _load(path) for name, path in REQUIRED_SURFACES.items()}

    incomplete: list[tuple[str, list[str]]] = []
    by_brand: dict[str, list[dict]] = {}

    for pid, entry in intel.items():
        if pid.startswith("_") or pid in EXCLUDED_IDS:
            continue
        name = entry.get("display_name", pid)
        missing = [s for s, data in siblings.items() if pid not in data]
        if missing:
            incomplete.append((pid, missing))
            continue
        brand = derive_manufacturer(pid, name)
        by_brand.setdefault(brand, []).append(
            {"id": pid, "name": name, "build_volume_mm": entry.get("build_volume_mm")}
        )

    # Brands ordered by breadth (most models first), then alphabetically;
    # models alphabetically. Fully deterministic so --check is stable.
    brands = []
    for brand in sorted(by_brand, key=lambda b: (-len(by_brand[b]), b)):
        models = sorted(by_brand[brand], key=lambda m: m["name"])
        brands.append(
            {
                "brand": brand,
                "slug": brand.lower().replace(" ", "-"),
                "model_count": len(models),
                "models": models,
            }
        )

    payload = {
        "_comment": (
            "AUTO-GENERATED by scripts/generate_supported_printers.py — DO NOT EDIT BY HAND. "
            "Add a model to kiln/src/kiln/data/printer_intelligence.json (plus its safety, "
            "slicer, and material-compatibility profiles) and rerun the generator."
        ),
        "total_brands": len(brands),
        "total_models": sum(b["model_count"] for b in brands),
        "brands": brands,
    }
    return payload, incomplete


def render_readme_block(payload: dict) -> str:
    """One-line, auto-maintained breadth summary for the README, between markers."""
    brands = ", ".join(b["brand"] for b in payload["brands"])
    return (
        f"{RM_BEGIN}\n"
        f"Kiln ships **tuned profiles for {payload['total_models']} models across "
        f"{payload['total_brands']} brands** — {brands}. "
        f"[See the full searchable list →](https://kiln3d.com/printers)\n"
        f"{RM_END}"
    )


def sync_readme(block: str, *, check: bool):
    """Replace the marked block in the README. Returns True if up to date, False
    if stale (check mode), or None if the README has no markers (not wired)."""
    import re

    if not README.exists():
        return None
    text = README.read_text()
    if RM_BEGIN not in text or RM_END not in text:
        return None
    new_text = re.sub(
        re.escape(RM_BEGIN) + ".*?" + re.escape(RM_END),
        lambda _m: block,
        text,
        flags=re.DOTALL,
    )
    if check:
        return new_text == text
    if new_text != text:
        README.write_text(new_text)
    return True


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed surface is stale (CI/pre-commit drift gate)",
    )
    args = parser.parse_args()

    payload, incomplete = build_surface()
    rendered = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"

    for pid, missing in incomplete:
        print(
            f"warning: '{pid}' is in printer_intelligence.json but missing "
            f"{', '.join(missing)} — not advertised until complete.",
            file=sys.stderr,
        )

    readme_block = render_readme_block(payload)

    if args.check:
        stale = []
        if (OUT.read_text() if OUT.exists() else "") != rendered:
            stale.append(str(OUT.relative_to(ROOT)))
        if sync_readme(readme_block, check=True) is False:
            stale.append(str(README.relative_to(ROOT)) + " (printer block)")
        if stale:
            print(
                f"DRIFT: {', '.join(stale)} stale. "
                f"Run: python3 scripts/generate_supported_printers.py",
                file=sys.stderr,
            )
            sys.exit(1)
        print(
            f"OK: supported-printers surfaces match the data "
            f"({payload['total_models']} models across {payload['total_brands']} brands)."
        )
        return

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered)
    readme_synced = sync_readme(readme_block, check=False)
    print(
        f"Wrote {OUT.relative_to(ROOT)}"
        + (" + README printer block" if readme_synced is not None else "")
        + f": {payload['total_models']} models across {payload['total_brands']} brands."
    )


if __name__ == "__main__":
    main()
