"""Slicer integration for Kiln — headless slicing via PrusaSlicer / OrcaSlicer CLI.

Wraps the command-line interface of PrusaSlicer and OrcaSlicer so that STL
(or 3MF/STEP) files can be sliced to G-code without opening the GUI.  The
slicer binary is auto-detected on PATH or can be specified explicitly.

Two command lines, not one — they share no flags:

    * PrusaSlicer (``prusa-slicer`` / ``PrusaSlicer``) and other Slic3r
      derivatives: ``--export-gcode --output FILE --load profile.ini``.
    * OrcaSlicer and BambuStudio: ``--slice 0 --outputdir DIR
      --load-settings machine.json;process.json``, with JSON presets that
      :mod:`kiln.slicer_orca` emits from the same bundled settings.

:func:`slicer_cli_family` tells them apart and :func:`slice_file` runs the
right one, so callers name a model and a profile and never a dialect.

Example::

    from kiln.slicer import slice_file, find_slicer

    slicer = find_slicer()                # auto-detect
    result = slice_file("model.stl")      # -> SliceResult
    print(result.output_path)             # <tempdir>/kiln_sliced/model.gcode
"""

from __future__ import annotations

import contextlib
import logging
import os
import re
import shutil
import signal
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from kiln.slicer_orca import ini_to_settings, write_orca_presets

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Kiln attribution header for generated gcode files.
_KILN_GCODE_HEADER = (
    "; Generated by Kiln — 3D printing infrastructure for AI agents\n"
    "; https://kiln3d.com\n"
    ";\n"
)

# Names to probe on PATH, in preference order.
_SLICER_NAMES: list[str] = [
    "prusa-slicer",
    "PrusaSlicer",
    "prusaslicer",
    "orca-slicer",
    "OrcaSlicer",
    "orcaslicer",
]

# Common install locations on macOS (app bundles).
# Only populated on macOS to avoid useless stat() calls on Linux/WSL.
_MACOS_PATHS: list[str] = (
    [
        "/Applications/PrusaSlicer.app/Contents/MacOS/PrusaSlicer",
        "/Applications/Original Prusa Drivers/PrusaSlicer.app/Contents/MacOS/PrusaSlicer",
        "/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer",
    ]
    if sys.platform == "darwin"
    else []
)

# One place to say how to get a slicer Kiln can drive, so the advice cannot
# drift from the capability.  It has now been wrong in both directions: it
# offered "PrusaSlicer or OrcaSlicer" while every command Kiln built was
# PrusaSlicer-only, and then named PrusaSlicer alone once that was fixed by
# refusing Orca.  Both are drivable now, so it says so — and this stays the
# only copy of the sentence.
_INSTALL_SLICER = (
    "Kiln slices with PrusaSlicer, OrcaSlicer or BambuStudio:\n"
    "  Windows: install OrcaSlicer or PrusaSlicer from orcaslicer.com / prusaslicer.org\n"
    "  macOS: brew install --cask prusaslicer  (or orcaslicer)\n"
    "  Linux/WSL: apt install prusa-slicer  (or download from prusaslicer.org)\n"
    "Or set KILN_SLICER_PATH to any of their binaries."
)

# CLI dialects.  OrcaSlicer and BambuStudio are forks of the same non-Slic3r
# command line: verified 2026-08-11 that OrcaSlicer 2.3.2 and BambuStudio
# 02.06.00.51 both reject --export-gcode / --output / --load and expose
# --slice / --outputdir / --load-settings instead.  They also load JSON
# presets rather than the PrusaSlicer .ini Kiln generates, so driving them is
# a new backend and not a flag rename.
_CLI_PRUSA = "prusa"
_CLI_BAMBU = "bambu"

# Extensions the slicer can accept as input.
_INPUT_EXTENSIONS = {".stl", ".3mf", ".step", ".stp", ".obj", ".amf"}

# Default output directory.
_DEFAULT_OUTPUT_DIR = os.path.join(tempfile.gettempdir(), "kiln_sliced")


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------


class SlicerError(Exception):
    """Raised when slicing fails."""


class SlicerNotFoundError(SlicerError):
    """Raised when no slicer binary is found on the system."""


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------


@dataclass
class SlicerInfo:
    """Information about a discovered slicer binary."""

    path: str
    name: str
    version: str | None = None

    def to_dict(self) -> dict:
        return {
            "path": self.path,
            "name": self.name,
            "version": self.version,
        }


@dataclass
class SliceResult:
    """Outcome of a slicing operation."""

    success: bool
    output_path: str | None = None
    slicer: str | None = None
    message: str = ""
    stdout: str = ""
    stderr: str = ""

    def to_dict(self) -> dict:
        d = {
            "success": self.success,
            "output_path": self.output_path,
            "slicer": self.slicer,
            "message": self.message,
        }
        if self.stderr:
            d["stderr"] = self.stderr[:500]
        return d


# ---------------------------------------------------------------------------
# Slicer discovery
# ---------------------------------------------------------------------------


def find_slicer(slicer_path: str | None = None) -> SlicerInfo:
    """Locate a slicer binary on the system.

    Args:
        slicer_path: Explicit path to a slicer binary.  If provided,
            this is used directly (validated for existence).  If ``None``,
            auto-detection is performed.

    Returns:
        A :class:`SlicerInfo` with the resolved path and name.

    Raises:
        SlicerNotFoundError: If no slicer binary can be found.
    """
    if slicer_path:
        if os.path.isfile(slicer_path) and os.access(slicer_path, os.X_OK):
            name = Path(slicer_path).stem.lower()
            version = _get_version(slicer_path)
            return SlicerInfo(path=slicer_path, name=name, version=version)
        raise SlicerNotFoundError(f"Slicer binary not found or not executable: {slicer_path}")

    # Check PATH
    for name in _SLICER_NAMES:
        found = shutil.which(name)
        if found:
            version = _get_version(found)
            return SlicerInfo(path=found, name=name.lower(), version=version)

    # Check macOS app bundles
    for path in _MACOS_PATHS:
        if os.path.isfile(path) and os.access(path, os.X_OK):
            name = Path(path).stem.lower()
            version = _get_version(path)
            return SlicerInfo(path=path, name=name, version=version)

    # Check env var
    env_path = os.environ.get("KILN_SLICER_PATH")
    if env_path and os.path.isfile(env_path) and os.access(env_path, os.X_OK):
        name = Path(env_path).stem.lower()
        version = _get_version(env_path)
        return SlicerInfo(path=env_path, name=name, version=version)

    raise SlicerNotFoundError(f"No slicer found. {_INSTALL_SLICER}")


def slicer_cli_family(info: SlicerInfo) -> str:
    """Which command-line dialect *info* speaks.

    ``find_slicer`` has always known which binary it resolved and then thrown
    that away: :func:`slice_file` built one Slic3r-dialect argv for everything.
    An OrcaSlicer-only user therefore got ``Invalid option --export-gcode``
    and exit 254 from a tool that had just reported finding their slicer.

    The ``--version`` banner is preferred over the file name, because a binary
    called ``orca-slicer`` that reports ``PrusaSlicer-2.9.4`` is a PrusaSlicer.
    Measured on this machine: PrusaSlicer answers
    ``"PrusaSlicer-2.9.4 based on Slic3r (with GUI support)"`` and OrcaSlicer
    answers ``"OrcaSlicer-2.3.2:"``, but BambuStudio's ``--version`` is itself
    an invalid option and its banner is a log line, so BambuStudio is
    recognised by file name alone.  Orca and Bambu are checked before Prusa
    because Orca is a Slic3r derivative and a build whose banner mentions
    Slic3r must not read as PrusaSlicer.

    Anything unrecognised is treated as PrusaSlicer — the behaviour before
    this function existed, so a binary Kiln cannot place keeps its old path
    instead of gaining a new refusal.
    """
    banner = (info.version or "").lower()
    if "orca" in banner or "bambu" in banner:
        return _CLI_BAMBU
    if "prusaslicer" in banner or "slic3r" in banner:
        return _CLI_PRUSA
    haystack = f"{info.name or ''} {os.path.basename(info.path or '')}".lower()
    if "orca" in haystack or "bambu" in haystack:
        return _CLI_BAMBU
    return _CLI_PRUSA


def supports_duplicate_flag(info: SlicerInfo) -> bool:
    """Whether *info*'s binary can lay out copies itself, via ``--duplicate``.

    The real question a multi-copy caller has, asked once.  Both callers used
    to ask it as ``"prusa" in slicer.name``, which is the FILE NAME: a
    PrusaSlicer installed under any other name fell back to duplicating the
    mesh, and a binary merely named like one would have been handed a flag the
    other command line does not have.  :func:`slicer_cli_family` reads the
    binary's own ``--version`` banner first and the name only as a fallback,
    so it answers what the program IS rather than what it is called.

    Named for the capability rather than the vendor because that is what the
    callers branch on — and because the answer stops being "is it PrusaSlicer"
    the moment a third dialect appears.
    """
    return slicer_cli_family(info) == _CLI_PRUSA


def _get_version(slicer_path: str) -> str | None:
    """Try to get the slicer version string."""
    try:
        result = subprocess.run(
            [slicer_path, "--version"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        output = (result.stdout or result.stderr or "").strip()
        # PrusaSlicer outputs "PrusaSlicer-2.7.1+linux-..."
        # OrcaSlicer outputs "OrcaSlicer 2.0.0"
        if output:
            return output.split("\n")[0].rstrip("\r")[:100]
    except Exception as exc:
        logger.debug("Failed to get slicer version from %s: %s", slicer_path, exc)
    return None


# ---------------------------------------------------------------------------
# Slicing
# ---------------------------------------------------------------------------


def _gcode_output_is_complete(out_file: str) -> bool:
    """Whether *out_file* looks like a finished slice, not a truncated one.

    Slicers write their summary footer (the ``filament used`` statistics
    block) only after the last toolpath is out, so a process killed
    mid-write never gets there.  Distinguishes "crashed AFTER finishing"
    from "crashed while writing" when the slicer dies on a signal:
    PrusaSlicer 2.9.4's CLI segfaults in its object-conflict bookkeeping
    (Print::export_gcode → ConflictResult assignment) on some multi-object
    files — stacked parts meeting at an exactly-coincident plane, the
    shape Kiln's banded multicolor compose produces — after exporting a
    complete, correct file.
    """
    try:
        with open(out_file, "rb") as fh:
            fh.seek(0, os.SEEK_END)
            size = fh.tell()
            fh.seek(max(0, size - 65536))
            tail = fh.read()
    except OSError:
        return False
    return b"filament used" in tail


def _record_slice(
    profile: str | None,
    input_abs: str | None = None,
    out_file: str | None = None,
) -> None:
    """Count one successful slice, and note the pair for the monitor twin.

    Recorded at the two runners rather than in a tool body, because the count
    used to live in the ``slice_model`` tool alone and every other path — the
    pipelines, estimates, CLI, kiln-pro batch flows — reported zero.  Detail is
    the profile filename stem; profiles are named for printers, never for
    users' models.

    The twin note rides the same chokepoint for the same reason: the web
    Monitor's layer viewer needs the sliced toolpath of whatever ends up
    printing, and only the slice runner reliably knows the (mesh, gcode)
    pair — a per-tool note would cover one door and miss the pipelines.
    """
    try:
        from kiln.daily_stats import record_event

        record_event("slices", detail=Path(profile).stem[:64] if profile else "unknown")
    except Exception:  # noqa: BLE001 — stats must never fail a slice
        logger.debug("slice telemetry recording failed", exc_info=True)
    if input_abs and out_file:
        try:
            from kiln.monitor_twin import note_sliced

            note_sliced(input_abs, out_file)
        except Exception:  # noqa: BLE001 — the twin ledger must never fail a slice
            logger.debug("monitor-twin slice note failed", exc_info=True)


# The crash any Bambu Lab machine preset provokes in both forks, and the one
# thing Kiln cannot serialize its way around.  Measured 2026-08-11 against
# OrcaSlicer 2.3.2 and BambuStudio 02.06.00.51: both die in
# Slic3r::DynamicPrintConfig::update_values_to_printer_extruders_for_multiple_filaments
# (null deref, EXC_BAD_ACCESS) on their OWN bundled Bambu presets as readily as
# on Kiln's, while a Creality preset through the identical code path slices
# fine.  So it is upstream and profile-specific, not a Kiln argv or preset bug.
_ORCA_SIGSEGV_RETURNCODES = frozenset({-11, 139})

# The macOS locale-race startup crash, slicer spelling.  The same libc race
# kiln.openscad_runner retries for OpenSCAD kills PrusaSlicer too: seven
# crash reports on one machine 2026-08-11..2026-08-17, every one SIGTRAP
# with libc's "loc->decimal_point is NULL" guard, every one 0.06-0.13s
# after launch -- dead before the model mattered.  Same shape, same
# remedy, same honesty about the bounds: the crash is upstream
# (macOS 26.5 libc + a multithreaded process touching the locale during
# startup), a retry is a lottery re-draw, and a crash that lands OUTSIDE
# the startup window is a real answer about real geometry and is not
# retried.  SIGSEGV/SIGBUS ride along because the OpenSCAD twin showed
# one underlying race spelling itself as either a libc guard trap or a
# wild read, depending on where the torn pointer lands.
_SLIC3R_STARTUP_CRASH_RETURNCODES = frozenset({
    -int(signal.SIGTRAP), -int(signal.SIGSEGV), -int(signal.SIGBUS),
})

# The Orca dialect keeps SIGSEGV out of its retry set on purpose: -11 on
# that path is the deterministic Bambu-preset crash above, a real verdict
# with a real message, and retrying it would crash the same way twice
# more just to say the same thing later (the openscad_runner rule about
# not retrying real answers).  The locale race has not been captured on
# an Orca binary; TRAP/BUS are covered so that if it ever is, the user
# gets the re-draw instead of the failure.
_ORCA_STARTUP_CRASH_RETURNCODES = frozenset({
    -int(signal.SIGTRAP), -int(signal.SIGBUS),
})

#: A crash later than this is blamed on the model, not on startup.  The
#: observed crashes die in the first ~0.1s; ten seconds is far past any
#: plausible startup and far short of real slicing work on a big model.
_STARTUP_CRASH_WINDOW_S = 10.0

#: Total launches, so two re-draws after a first startup crash.
_SLICE_ATTEMPTS = 3


def _bed_xy_bounds_from_profile(
    profile: str | None,
) -> tuple[float, float, float, float] | None:
    """The bed's XY rectangle from a profile ini, or None.

    Parses ``bed_shape = 0x0,256x0,256x256,0x256`` into
    ``(x_min, y_min, x_max, y_max)``.  Corner-origin beds give
    ``(0, 0, w, d)``; center-origin (delta) beds keep their negative
    corners, so the fit check below works for both.
    """
    if not profile or not os.path.isfile(profile):
        return None
    try:
        shape = ini_to_settings(profile).get("bed_shape", "")
    except OSError:
        return None
    xs: list[float] = []
    ys: list[float] = []
    for corner in shape.split(","):
        x, sep, y = corner.strip().partition("x")
        if not sep:
            continue
        try:
            xs.append(float(x))
            ys.append(float(y))
        except ValueError:
            continue
    if len(xs) < 3:
        return None
    return (min(xs), min(ys), max(xs), max(ys))


# Matches kiln.printers.bed_fit._FIT_EPSILON_MM — floating-point noise on
# the bed edge must not reject a model that fits.
_BED_FIT_EPSILON_MM = 0.5


def _check_3mf_on_bed(input_abs: str, profile: str | None) -> None:
    """Refuse to slice a 3MF whose placed geometry misses the profile's bed.

    3MF only: a 3MF carries explicit build transforms that slicers honour
    literally, while loose STL geometry is auto-centred by PrusaSlicer.
    Without this gate the failure is invisible — PrusaSlicer prints "All
    objects are outside of the print volume." and exits 0 with no output
    file, which used to surface as a generic "output file was not
    created".  Skips silently when the bed shape or the geometry cannot
    be determined: this is a diagnosis gate, not a new way to fail good
    files.
    """
    bed = _bed_xy_bounds_from_profile(profile)
    if bed is None:
        return
    from kiln.printers.bed_fit import compute_3mf_geometry_bbox

    bbox = compute_3mf_geometry_bbox(input_abs)
    if bbox is None:
        return
    bed_x_min, bed_y_min, bed_x_max, bed_y_max = bed
    eps = _BED_FIT_EPSILON_MM
    if (
        bbox["x_min"] >= bed_x_min - eps
        and bbox["x_max"] <= bed_x_max + eps
        and bbox["y_min"] >= bed_y_min - eps
        and bbox["y_max"] <= bed_y_max + eps
    ):
        return
    raise SlicerError(
        f"Model geometry (with its 3MF build transform applied) spans "
        f"X[{bbox['x_min']:.1f}..{bbox['x_max']:.1f}] "
        f"Y[{bbox['y_min']:.1f}..{bbox['y_max']:.1f}] mm, outside the "
        f"profile's bed X[{bed_x_min:g}..{bed_x_max:g}] "
        f"Y[{bed_y_min:g}..{bed_y_max:g}] mm. Slicers honour a 3MF's "
        f"placement literally (no auto-centre), so this would slice to "
        f"nothing. Re-export the 3MF centred on the bed, or translate "
        f"the model so its footprint fits."
    )


def _run_slicer_with_startup_retry(
    cmd: list[str],
    *,
    timeout: int,
    retryable_returncodes: frozenset[int],
    remove_partial_output,
    output_is_complete,
) -> subprocess.CompletedProcess:
    """Launch a slicer, re-drawing the startup-crash lottery when it hits.

    One loop for both CLI dialects so the retry rule cannot drift between
    them.  A retry fires only when ALL of these hold: the death was one of
    *retryable_returncodes*, it happened inside the startup window, the
    output is NOT already complete (a signal death after a complete write
    is the salvage case, owned by the caller), and an attempt remains.
    *remove_partial_output* runs between attempts so a half-written file
    from a crashed run can never pose as the next run's result.
    """
    result: subprocess.CompletedProcess | None = None
    for attempt in range(1, _SLICE_ATTEMPTS + 1):
        started = time.monotonic()
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        except subprocess.TimeoutExpired:
            remove_partial_output()
            raise SlicerError(
                f"Slicing timed out after {timeout}s. The model may be too complex "
                f"or the slicer is hanging."
            ) from None
        except OSError as exc:
            raise SlicerError(f"Failed to run slicer: {exc}") from exc
        elapsed = time.monotonic() - started
        if (
            attempt < _SLICE_ATTEMPTS
            and result.returncode in retryable_returncodes
            and elapsed < _STARTUP_CRASH_WINDOW_S
            and not output_is_complete()
        ):
            logger.warning(
                "Slicer died of signal %d %.2fs after launch (the startup "
                "crash lottery) -- relaunching, attempt %d of %d",
                -result.returncode, elapsed, attempt + 1, _SLICE_ATTEMPTS,
            )
            remove_partial_output()
            continue
        break
    assert result is not None
    return result


def _slice_with_orca(
    slicer: SlicerInfo,
    input_abs: str,
    out_file: str,
    *,
    profile: str | None,
    extra_args: list[str] | None,
    timeout: int,
) -> SliceResult:
    """Slice through the BambuStudio/OrcaSlicer command line.

    A different argv and a different preset format from
    :func:`slice_file`'s Slic3r path: ``--slice 0 --outputdir DIR
    --load-settings "machine.json;process.json" --load-filaments "f.json"``,
    where the presets are the JSON that :mod:`kiln.slicer_orca` writes out of
    the same bundled settings the ``.ini`` is built from.

    Orca names its own output (``plate_1.gcode``) inside ``--outputdir``
    rather than taking an output path, so it writes to a private directory
    and the result is moved to where the caller asked for it.
    """
    with tempfile.TemporaryDirectory(prefix="kiln_orca_") as work_dir:
        cmd: list[str] = [slicer.path, "--slice", "0", "--outputdir", work_dir]

        if profile and not os.path.isfile(profile):
            raise SlicerError(f"Profile file not found: {os.path.basename(profile)}")

        if not profile:
            # "No profile" cannot mean "no preset" here the way it does for
            # PrusaSlicer, which slices happily on its own defaults.  Orca's
            # defaults use relative extrusion with no per-layer reset, so a
            # bare slice_file("model.stl") — the documented form — fails
            # validation before it starts.  Kiln's own generic profile is a
            # real answer to "you didn't say", and it keeps the bare call
            # working on both backends.
            #
            # Resolved through the ordinary door rather than read straight
            # off the profile, so it passes the same invariants every other
            # profile does — the per-layer E reset among them.
            from kiln.slicer_profiles import resolve_slicer_profile

            profile = resolve_slicer_profile("default")

        settings = ini_to_settings(profile)
        preset_name = Path(profile).stem[:48] or "kiln"

        presets = write_orca_presets(settings, work_dir, name=preset_name)
        cmd += ["--load-settings", f"{presets.machine_path};{presets.process_path}"]
        cmd += ["--load-filaments", str(presets.filament_path)]

        if extra_args:
            cmd.extend(extra_args)
        cmd.append(input_abs)

        logger.info("Slicing (Orca dialect): %s", " ".join(cmd))

        def _latest_gcode_complete() -> bool:
            done = sorted(Path(work_dir).glob("*.gcode"), key=lambda p: p.stat().st_mtime)
            return bool(done) and _gcode_output_is_complete(str(done[-1]))

        def _drop_partial_gcode() -> None:
            for stale in Path(work_dir).glob("*.gcode"):
                with contextlib.suppress(OSError):
                    stale.unlink()

        result = _run_slicer_with_startup_retry(
            cmd,
            timeout=timeout,
            retryable_returncodes=_ORCA_STARTUP_CRASH_RETURNCODES,
            remove_partial_output=_drop_partial_gcode,
            output_is_complete=_latest_gcode_complete,
        )

        produced = sorted(Path(work_dir).glob("*.gcode"), key=lambda p: p.stat().st_mtime)

        # A death by signal AFTER a complete write is salvageable, exactly as
        # it is on the Slic3r path — see _gcode_output_is_complete, which
        # exists because PrusaSlicer does this on some multi-object files.
        # Orca is a Slic3r derivative, so it inherits the possibility; without
        # this the two paths would disagree about the same event, and a good
        # slice would be thrown away with a message about a Bambu crash.
        crashed_after_finishing = bool(
            result.returncode != 0
            and produced
            and _gcode_output_is_complete(str(produced[-1]))
        )

        if result.returncode in _ORCA_SIGSEGV_RETURNCODES and not crashed_after_finishing:
            raise SlicerError(
                f"{os.path.basename(slicer.path)} crashed while slicing. This is a "
                f"known crash in BambuStudio and OrcaSlicer themselves, on Bambu Lab "
                f"printer profiles specifically — their own bundled Bambu presets "
                f"crash the same way, and the same Kiln code slices other printers "
                f"fine. Slice this printer with PrusaSlicer instead; Kiln wraps the "
                f"result as a Bambu 3MF itself, so nothing about the print is lost.\n"
                f"{_INSTALL_SLICER}"
            )

        if result.returncode != 0 and not crashed_after_finishing:
            # This CLI reports the reason on stdout and leaves stderr empty.
            stderr_snippet = (result.stderr or "").strip() or (result.stdout or "").strip()
            raise SlicerError(f"Slicer exited with code {result.returncode}. stderr: {stderr_snippet[:500]}")

        if not produced:
            # This CLI reports on stdout, but surface both streams — the
            # Slic3r-family lesson: the reason for a silent exit-0 no-write
            # lives on whichever stream the message omitted.
            reason = (result.stdout or "").strip() or (result.stderr or "").strip()
            raise SlicerError(
                f"Slicer completed but wrote no G-code. "
                f"Slicer said: {reason[:500] if reason else '(no output)'}"
            )

        # One plate, because slice_file promises exactly one file.  The model
        # did not fit on a single plate, and quietly handing back the first
        # one is how a user prints half a job and finds out at the printer.
        if len(produced) > 1:
            raise SlicerError(
                f"This model needed {len(produced)} build plates, and a slice "
                f"returns a single G-code file. Split it into separate models, "
                f"or scale it down so it fits one plate."
            )

        shutil.move(str(produced[0]), out_file)

    _record_slice(profile, input_abs, out_file)
    message = f"Sliced {Path(input_abs).name} -> {Path(out_file).name}"
    if crashed_after_finishing:
        message += (
            f" (the slicer crashed on exit AFTER writing complete G-code — "
            f"signal {-result.returncode}; the output was verified complete "
            f"and kept)"
        )
    return SliceResult(
        success=True,
        output_path=out_file,
        slicer=slicer.name,
        message=message,
        stdout=(result.stdout or "").strip(),
        stderr=(result.stderr or "").strip(),
    )


def slice_file(
    input_path: str,
    *,
    output_dir: str | None = None,
    output_name: str | None = None,
    profile: str | None = None,
    slicer_path: str | None = None,
    extra_args: list[str] | None = None,
    timeout: int = 300,
) -> SliceResult:
    """Slice a 3D model file to G-code.

    Args:
        input_path: Path to the input file (STL, 3MF, STEP, OBJ, AMF).
        output_dir: Directory for the output G-code file.  Defaults to
            the system temp directory.
        output_name: Override the output file name.  Defaults to the
            input file's stem with ``.gcode`` extension.
        profile: Path to a slicer profile/config file (.ini or .json).
        slicer_path: Explicit slicer binary path.  Auto-detected if omitted.
        extra_args: Additional CLI arguments to pass to the slicer.
        timeout: Maximum slicing time in seconds (default 300).

    Returns:
        A :class:`SliceResult` with the path to the generated G-code.

    Raises:
        SlicerError: If slicing fails.
        SlicerNotFoundError: If no slicer binary is found.
        FileNotFoundError: If the input file does not exist.
    """
    # Validate input
    input_abs = os.path.abspath(input_path)
    if not os.path.isfile(input_abs):
        raise FileNotFoundError(f"Input file not found: {os.path.basename(input_abs)}")

    ext = Path(input_abs).suffix.lower()
    if ext not in _INPUT_EXTENSIONS:
        raise SlicerError(f"Unsupported input format '{ext}'. Supported: {', '.join(sorted(_INPUT_EXTENSIONS))}")

    if ext == ".3mf":
        _check_3mf_on_bed(input_abs, profile)

    # Find slicer
    slicer = find_slicer(slicer_path)

    # Prepare output
    out_dir = output_dir or _DEFAULT_OUTPUT_DIR
    os.makedirs(out_dir, mode=0o700, exist_ok=True)

    if output_name:
        # Strict filename sanitisation: basename, null bytes, length, reserveds
        safe_name = output_name.replace("\x00", "")
        safe_name = os.path.basename(safe_name)
        if not safe_name or safe_name != output_name.replace("\x00", "") or safe_name in {".", ".."}:
            raise ValueError(
                f"output_name must be a plain filename without path separators "
                f"or traversal sequences, got: {output_name!r}"
            )
        if len(safe_name) > 255:
            raise ValueError(f"output_name too long ({len(safe_name)} chars, max 255)")
        out_file = os.path.join(out_dir, safe_name)
    else:
        stem = Path(input_abs).stem
        out_file = os.path.join(out_dir, f"{stem}.gcode")

    # Anything at out_file after the run must have been written BY the run.
    # The path is deterministic (input stem into a shared output dir), so a
    # previous slice of the same model leaves a complete-looking file here —
    # and without this unlink the crash-salvage check below would read that
    # STALE file and certify a slicer that died before writing anything as a
    # fresh success: the previous model's toolpath, headed for start_print.
    with contextlib.suppress(OSError):
        os.unlink(out_file)

    # Two command lines, one function.  Everything below this point is the
    # Slic3r dialect; an Orca/BambuStudio binary needs a different argv AND a
    # different preset format, so it gets its own runner rather than a flag
    # swap.  The branch is here — at the one place all twelve slicing doors
    # funnel through — so none of them has to know which slicer is installed.
    if slicer_cli_family(slicer) == _CLI_BAMBU:
        return _slice_with_orca(
            slicer,
            input_abs,
            out_file,
            profile=profile,
            extra_args=extra_args,
            timeout=timeout,
        )

    # Build command
    cmd: list[str] = [
        slicer.path,
        "--export-gcode",
        input_abs,
        "--output",
        out_file,
    ]

    if profile:
        if not os.path.isfile(profile):
            raise SlicerError(f"Profile file not found: {os.path.basename(profile)}")
        cmd.extend(["--load", profile])

    if extra_args:
        cmd.extend(extra_args)

    logger.info("Slicing: %s", " ".join(cmd))

    def _drop_partial_out_file() -> None:
        with contextlib.suppress(OSError):
            os.unlink(out_file)

    result = _run_slicer_with_startup_retry(
        cmd,
        timeout=timeout,
        retryable_returncodes=_SLIC3R_STARTUP_CRASH_RETURNCODES,
        remove_partial_output=_drop_partial_out_file,
        output_is_complete=lambda: _gcode_output_is_complete(out_file),
    )

    crashed_after_finishing = (
        result.returncode != 0
        and result.returncode < 0  # killed by a signal, not a reported error
        and _gcode_output_is_complete(out_file)
    )
    if result.returncode != 0 and not crashed_after_finishing:
        stderr_snippet = (result.stderr or "").strip()[:500]
        raise SlicerError(f"Slicer exited with code {result.returncode}. stderr: {stderr_snippet}")

    # Verify output exists.  PrusaSlicer can exit 0 without writing — e.g.
    # "All objects are outside of the print volume." — and it says why on
    # STDERR; a message that omitted stderr turned that specific reason
    # into a generic mystery.
    if not os.path.isfile(out_file):
        reason = (result.stderr or "").strip() or (result.stdout or "").strip()
        raise SlicerError(
            f"Slicer completed but output file was not created. "
            f"Slicer said: {reason[:500] if reason else '(no output)'}"
        )

    _record_slice(profile, input_abs, out_file)

    message = f"Sliced {Path(input_abs).name} -> {Path(out_file).name}"
    if crashed_after_finishing:
        message += (
            f" (the slicer crashed on exit AFTER writing complete G-code — "
            f"signal {-result.returncode}; the output was verified complete "
            f"and kept)"
        )
    return SliceResult(
        success=True,
        output_path=out_file,
        slicer=slicer.name,
        message=message,
        stdout=(result.stdout or "").strip(),
        stderr=(result.stderr or "").strip(),
    )


def derive_filament_weight(estimates: dict[str, Any], material: str | None) -> None:
    """Fill in a filament weight the slicer could not work out, in place.

    A slicer gets weight by multiplying extruded volume by the filament's
    density, and density lives on a FILAMENT profile.  Kiln's bundled profiles
    describe a printer — bed, speeds, temperatures — and name no filament, so
    the slicer has no density and reports ``0``.  The volume is right there in
    the same G-code, so the missing half is only the material.

    Weight is physics and is computed here when the caller names a material.
    Cost is not: the table's price is a generic figure, not what anyone paid,
    and a made-up price is the kind of confident wrong number this is meant to
    stop.  ``estimate_material_cost`` takes a real ``cost_per_kg`` for that.

    Recorded as *generic*, because a table density is the family's nominal
    value and not a measurement of the spool on the shelf.
    """
    if not material or estimates.get("filament_weight_g"):
        return
    volume_cm3 = estimates.get("filament_volume_cm3")
    if not volume_cm3:
        return
    try:
        from kiln.cost_estimator import BUILTIN_MATERIALS
    except ImportError:  # pragma: no cover — cost table always ships
        return

    profile = BUILTIN_MATERIALS.get(str(material).strip().upper())
    if profile is None:
        return
    estimates["filament_weight_g"] = round(volume_cm3 * profile.density_g_per_cm3, 2)
    estimates["filament_weight_basis"] = (
        f"computed from extruded volume x generic {profile.name} density "
        f"({profile.density_g_per_cm3} g/cm3)"
    )


def estimate_print(
    file_path: str,
    *,
    profile: str | None = None,
    slicer_path: str | None = None,
    material: str | None = None,
) -> dict[str, Any]:
    """Estimate print time and filament usage by slicing to a temp file.

    Slices the model and parses the G-code comments for estimated
    print time, filament length, and filament weight.

    Args:
        file_path: Path to STL/3MF/OBJ file.
        profile: Optional slicer profile path.
        slicer_path: Optional explicit slicer binary path.
        material: Optional filament family (``"PLA"``, ``"PETG"``, …).  Only
            a density source: without it a weight the slicer could not work
            out is reported as absent rather than guessed.

    Returns:
        Dict with ``estimated_time_seconds``, ``filament_length_mm``,
        ``filament_weight_g``, ``layer_count``, and ``gcode_path``.  Keys the
        slicer could not answer are ABSENT, never zero.

    Raises:
        SlicerError: If slicing fails.
    """
    result = slice_file(file_path, profile=profile, slicer_path=slicer_path)
    if not result.success or not result.output_path:
        raise SlicerError("Slicing failed — cannot estimate print.")

    estimates = _parse_gcode_estimates(result.output_path)
    derive_filament_weight(estimates, material)
    return estimates


def _parse_gcode_estimates(gcode_path: str) -> dict[str, Any]:
    """Parse G-code file for slicer-generated estimates.

    Every estimate a slicer writes is a COMMENT, so the whole file is read
    and only comment lines are matched.  Toolpath lines are the overwhelming
    majority and are rejected on their first character, which is what makes
    reading all of them cheap.

    This used to search a window — the first 200 lines and the last 500 —
    and the window kept being the bug.  It was widened once already when
    PrusaSlicer's estimates turned out to sit ~350 lines from EOF, behind its
    trailing config block.  OrcaSlicer's block is longer still: measured at
    584-589 lines from EOF, just outside the 500, so every estimate came back
    empty for an Orca slice while the values sat in the file.  A window tuned
    to today's slicers is a bug waiting for the next one to add a setting.
    """
    import re as _re

    estimates: dict[str, Any] = {"gcode_path": gcode_path}

    try:
        with open(gcode_path, errors="replace") as fh:
            search_lines = [line for line in fh if line.startswith(";")]
    except OSError:
        return estimates

    for line in search_lines:
        line = line.strip()

        # PrusaSlicer: ; estimated printing time (normal mode) = 1h 23m 45s
        time_match = _re.search(
            r"estimated printing time.*?=\s*(?:(\d+)d\s*)?(?:(\d+)h\s*)?(?:(\d+)m\s*)?(?:(\d+)s)?",
            line,
            _re.IGNORECASE,
        )
        if time_match:
            d = int(time_match.group(1) or 0)
            h = int(time_match.group(2) or 0)
            m = int(time_match.group(3) or 0)
            s = int(time_match.group(4) or 0)
            estimates["estimated_time_seconds"] = d * 86400 + h * 3600 + m * 60 + s
            estimates["estimated_time_human"] = line.split("=", 1)[-1].strip()

        # ; filament used [mm] = 1234.56
        fil_mm = _re.search(r"filament used \[mm\]\s*=\s*([\d.]+)", line, _re.IGNORECASE)
        if fil_mm:
            estimates["filament_length_mm"] = float(fil_mm.group(1))

        # ; filament used [g] = 12.34 or total filament used [g] = 12.34
        #
        # A zero here is the slicer saying it could not work the weight out —
        # it needs a filament density, and Kiln's profiles describe a printer,
        # not a filament.  Nothing that gets extruded weighs nothing, so the
        # key is left ABSENT rather than recorded as 0: "I don't know" is a
        # true statement about every print, "0 g" is a false one.  See
        # derive_filament_weight, which fills it in when a material is named.
        fil_g = _re.search(r"filament used \[g\]\s*=\s*([\d.]+)", line, _re.IGNORECASE)
        if fil_g and float(fil_g.group(1)) > 0:
            estimates["filament_weight_g"] = float(fil_g.group(1))

        # ; filament used [cm3] = 12.34
        fil_cm3 = _re.search(r"filament used \[cm3\]\s*=\s*([\d.]+)", line, _re.IGNORECASE)
        if fil_cm3:
            estimates["filament_volume_cm3"] = float(fil_cm3.group(1))

        # ; total layers count = 123
        layers = _re.search(r"total layers count\s*=\s*(\d+)", line, _re.IGNORECASE)
        if layers:
            estimates["layer_count"] = int(layers.group(1))

        # ; filament cost = 1.23
        #
        # Zero for the same reason, and left absent for the same reason: a
        # price comes off a filament profile Kiln's printer profiles do not
        # carry.  Unlike weight this one is NOT derived downstream — the
        # material table's price is a generic figure rather than what anyone
        # paid, and estimate_material_cost takes a real cost_per_kg.
        cost = _re.search(r"filament cost\s*=\s*([\d.]+)", line, _re.IGNORECASE)
        if cost and float(cost.group(1)) > 0:
            estimates["filament_cost"] = float(cost.group(1))

    return estimates


# ---------------------------------------------------------------------------
# Multi-color multi-copy slicing
# ---------------------------------------------------------------------------


def slice_multicolor_copies(
    input_path: str,
    count: int,
    *,
    spacing_mm: float = 10.0,
    bed_width_mm: float = 256.0,
    bed_depth_mm: float = 256.0,
    printer_id: str | None = None,
    slicer_path: str | None = None,
    profile: str | None = None,
    extra_args: list[str] | None = None,
    output_dir: str | None = None,
    timeout: int = 300,
) -> SliceResult:
    """Slice an STL into *count* copies, each assigned a different tool (T0, T1, ...).

    The approach: position each copy on a grid, slice each individually, then
    merge the gcode bodies with ``T`` commands between copies.  This avoids
    the need for a multi-extruder PrusaSlicer printer profile.

    The merged gcode will contain ``T0`` before copy 1's layers, ``T1`` before
    copy 2's layers, etc.  Downstream Bambu 3MF wrapping will convert these
    to M620/M621 AMS load sequences.

    :param input_path: Path to the source STL file.
    :param count: Number of copies (each gets a different tool).
    :param spacing_mm: Gap between copies in mm.
    :param bed_width_mm: Build plate width (X) in mm.
    :param bed_depth_mm: Build plate depth (Y) in mm.
    :param printer_id: Optional supported printer model id.  When provided,
        the bundled printer-intelligence build volume overrides the generic
        bed dimensions.
    :param slicer_path: Explicit slicer binary path.
    :param profile: Path to a slicer profile/config file.
    :param extra_args: Additional CLI arguments for the slicer.
    :param output_dir: Directory for output files.
    :param timeout: Slicing timeout per copy in seconds.
    :returns: A :class:`SliceResult` with the merged gcode path.
    :raises SlicerError: If slicing any copy fails.
    :raises ValueError: If copies don't fit on the bed.
    """
    import math
    import tempfile as _tempfile

    from kiln.auto_orient import _parse_mesh, _translate_to_bed, _write_binary_stl

    if count < 2:
        raise ValueError(f"count must be >= 2, got {count}")
    if printer_id:
        from kiln.printers.bed_fit import resolve_build_volume

        resolved = resolve_build_volume(printer_id)
        if resolved is None:
            raise ValueError(
                f"Unknown printer_id {printer_id!r}; omit printer_id and "
                "pass bed_width_mm/bed_depth_mm explicitly, or use a "
                "supported printer model id."
            )
        _model_id, build_volume = resolved
        bed_width_mm, bed_depth_mm = build_volume[0], build_volume[1]

    # Parse mesh and compute bounding box
    triangles, _vertices = _parse_mesh(input_path)
    triangles = _translate_to_bed(triangles)

    all_verts = [v for tri in triangles for v in tri]
    xs = [v[0] for v in all_verts]
    ys = [v[1] for v in all_verts]
    x_min, x_max = min(xs), max(xs)
    y_min, y_max = min(ys), max(ys)
    model_width = x_max - x_min
    model_depth = y_max - y_min

    if model_width <= 0 or model_depth <= 0:
        raise ValueError("Model has zero width or depth.")

    # Center mesh at origin
    center_x = (x_min + x_max) / 2.0
    center_y = (y_min + y_max) / 2.0
    centered = []
    for tri in triangles:
        tv = tuple((v[0] - center_x, v[1] - center_y, v[2]) for v in tri)
        centered.append(tv)

    # Grid layout
    cell_w = model_width + spacing_mm
    cell_d = model_depth + spacing_mm
    cols = int(bed_width_mm // cell_w)
    rows = int(bed_depth_mm // cell_d)

    if cols < 1 or rows < 1:
        raise ValueError(
            f"Model ({model_width:.1f} x {model_depth:.1f} mm) is too large "
            f"for the build plate ({bed_width_mm} x {bed_depth_mm} mm)."
        )
    if count > cols * rows:
        raise ValueError(
            f"Cannot fit {count} copies on {bed_width_mm}x{bed_depth_mm} mm bed."
        )

    actual_cols = min(count, cols)
    actual_rows = math.ceil(count / actual_cols)
    grid_width = actual_cols * cell_w - spacing_mm
    grid_depth = actual_rows * cell_d - spacing_mm
    start_x = (bed_width_mm - grid_width) / 2.0 + model_width / 2.0
    start_y = (bed_depth_mm - grid_depth) / 2.0 + model_depth / 2.0

    # Create positioned STL copies and slice each
    work_dir = _tempfile.mkdtemp(prefix="kiln_multicolor_")
    gcode_bodies: list[str] = []
    slicer_name: str | None = None

    placed = 0
    for row in range(actual_rows):
        for col in range(actual_cols):
            if placed >= count:
                break
            offset_x = start_x + col * cell_w
            offset_y = start_y + row * cell_d

            # Translate centered mesh to this grid position
            positioned = []
            for tri in centered:
                tv = tuple((v[0] + offset_x, v[1] + offset_y, v[2]) for v in tri)
                positioned.append(tv)

            # Write positioned copy as STL
            copy_stl = os.path.join(work_dir, f"copy_{placed}.stl")
            _write_binary_stl(positioned, copy_stl)

            # Slice it
            copy_out_dir = os.path.join(work_dir, f"slice_{placed}")
            os.makedirs(copy_out_dir, exist_ok=True)

            result = slice_file(
                copy_stl,
                output_dir=copy_out_dir,
                profile=profile,
                slicer_path=slicer_path,
                extra_args=list(extra_args) if extra_args else None,
                timeout=timeout,
            )
            if not result.success or not result.output_path:
                raise SlicerError(f"Slicing copy {placed} failed: {result.message}")

            slicer_name = result.slicer

            # Read the gcode body
            with open(result.output_path, errors="replace") as fh:
                gcode_bodies.append(fh.read())

            placed += 1

    # Merge gcode bodies with T commands between copies
    merged = _merge_multicolor_gcode(gcode_bodies)

    # Write merged gcode
    out_dir = output_dir or _DEFAULT_OUTPUT_DIR
    os.makedirs(out_dir, mode=0o700, exist_ok=True)
    stem = Path(input_path).stem
    merged_path = os.path.join(out_dir, f"{stem}_multicolor.gcode")
    with open(merged_path, "w") as fh:
        fh.write(_KILN_GCODE_HEADER + merged)

    return SliceResult(
        success=True,
        output_path=merged_path,
        slicer=slicer_name,
        message=f"Sliced {count} multi-color copies of {Path(input_path).name}",
    )


def _merge_multicolor_gcode(gcode_bodies: list[str]) -> str:
    """Merge multiple single-filament gcode bodies into one with T commands.

    Takes the first copy's gcode as the base (with headers/comments intact),
    then for subsequent copies, extracts only the layer gcode (stripping
    slicer headers and init commands) and inserts T commands before each.

    The merged gcode uses the first copy's header, all layer bodies merged
    sequentially, with tool changes at the transition between copies.
    """
    if not gcode_bodies:
        raise ValueError("No gcode bodies to merge")
    if len(gcode_bodies) == 1:
        return gcode_bodies[0]

    def _extract_body(gcode: str) -> str:
        """Extract gcode body starting from the first layer change marker."""
        lines = gcode.split("\n")
        body_start = 0
        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped.startswith((";BEFORE_LAYER_CHANGE", ";LAYER_CHANGE")):
                body_start = i
                break
        return "\n".join(lines[body_start:])

    def _extract_header(gcode: str) -> str:
        """Extract gcode header before the first layer change."""
        lines = gcode.split("\n")
        header_lines = []
        for line in lines:
            stripped = line.strip()
            if stripped.startswith((";BEFORE_LAYER_CHANGE", ";LAYER_CHANGE")):
                break
            header_lines.append(line)
        return "\n".join(header_lines)

    # Build merged gcode:
    # 1. Header from copy 0
    # 2. T0 + body from copy 0
    # 3. T1 + body from copy 1
    # ...
    parts: list[str] = []

    # Header from first copy
    parts.append(_extract_header(gcode_bodies[0]))
    parts.append("")

    for i, gcode in enumerate(gcode_bodies):
        body = _extract_body(gcode)
        # Insert tool change command before each copy's layers
        parts.append(f"; --- Copy {i + 1} (Tool {i}) ---")
        parts.append(f"T{i}")
        parts.append(body)
        parts.append("")

    return "\n".join(parts)


def merge_multipart_gcode(
    parts: list[dict[str, Any]],
    *,
    output_path: str | None = None,
) -> dict[str, Any]:
    """Merge separately-sliced gcode files into one multi-tool gcode.

    Uses a **batched** strategy that minimises tool changes: parts are
    grouped by Z-height overlap so the printer completes all layers of
    one tool in the overlap zone before switching, then continues with
    whichever tool has layers remaining.

    .. note::

        Parts **must be XY-disjoint** — their printed footprints must not
        overlap on the build plate.  The batched merge prints each tool's
        layers independently in the overlap zone; if parts share XY space,
        the later tool will collide with the earlier tool's deposited
        material.

    Each entry in *parts* must have:

    - ``gcode_path``: Path to the ``.gcode`` file.
    - ``tool_index``: Tool number (T0, T1, ...) for AMS mapping.
    - ``name``: Human-readable name (e.g. ``"body_grey"``).

    :param parts: List of part dicts.
    :param output_path: Output file path.  Defaults to a temp file.
    :returns: Dict with ``output_path``, ``total_layers``, ``phases``,
        and ``estimated_time_sec``.
    :raises ValueError: If parts list is empty or files not found.
    """
    if not parts:
        raise ValueError("No parts to merge.")

    # Parse each gcode into header + [(z, block), ...]
    parsed: list[tuple[str, list[tuple[float, str]], dict[str, Any]]] = []
    for p in parts:
        gcode_path = p["gcode_path"]
        if not os.path.isfile(gcode_path):
            raise ValueError(f"Gcode file not found: {gcode_path}")

        with open(gcode_path) as f:
            lines = f.readlines()

        header_lines: list[str] = []
        layers: list[tuple[float, str]] = []
        current_block: list[str] = []
        current_z: float | None = None
        found_first = False

        for line in lines:
            if ";LAYER_CHANGE" in line and not found_first:
                found_first = True
            if not found_first:
                header_lines.append(line)
                continue
            if ";LAYER_CHANGE" in line and current_block and current_z is not None:
                layers.append((current_z, "".join(current_block)))
                current_block = []
                current_z = None
            current_block.append(line)
            m = re.match(r"^;Z:([\d.]+)", line)
            if m:
                current_z = float(m.group(1))

        if current_block and current_z is not None:
            layers.append((current_z, "".join(current_block)))

        if not layers:
            raise ValueError(
                f"Part {p['name']!r} ({gcode_path}) has zero parsed layers. "
                "Ensure the gcode contains ;LAYER_CHANGE markers."
            )

        parsed.append(("".join(header_lines), layers, p))

    # Find the Z overlap range — the max Z of the shortest part
    # layers is guaranteed non-empty per the zero-layer check above.
    z_maxes = [max(z for z, _ in layers) for _, layers, _ in parsed]
    overlap_ceiling = min(z_maxes)

    # Use the first part's header as the merged header
    merged_header = parsed[0][0]

    # Build tool names for the merge comment
    tool_names = ", ".join(
        f"T{p['tool_index']}={p['name']}" for p in parts
    )
    total_layers = max(len(layers) for _, layers, _ in parsed)

    # Build merged output using batched strategy:
    # Phase 1: For each part (in tool_index order), emit its overlap layers
    # Phase 2: For each part with layers above the overlap, emit those
    sorted_parts = sorted(enumerate(parsed), key=lambda x: x[1][2]["tool_index"])
    phases: list[dict[str, Any]] = []
    merged_blocks: list[str] = []

    merged_blocks.append(merged_header)
    merged_blocks.append(
        f"; Kiln multi-color merge: {len(parts)} parts, "
        f"{total_layers} layers, tools: {tool_names}\n"
    )

    for _idx, (_header, layers, part_info) in sorted_parts:
        tool = part_info["tool_index"]
        name = part_info["name"]
        overlap = [(z, blk) for z, blk in layers if z <= overlap_ceiling]
        above = [(z, blk) for z, blk in layers if z > overlap_ceiling]

        if overlap:
            merged_blocks.append(f"; --- Tool change: T{tool} ({name}) ---\n")
            merged_blocks.append(f"T{tool}\n")
            merged_blocks.append("G92 E0\n")
            for _z, blk in overlap:
                merged_blocks.append(blk)
            phases.append({
                "tool": tool,
                "name": name,
                "zone": "overlap",
                "layers": len(overlap),
                "z_range": f"{overlap[0][0]}-{overlap[-1][0]}mm",
            })

    for _idx, (_header, layers, part_info) in sorted_parts:
        tool = part_info["tool_index"]
        name = part_info["name"]
        above = [(z, blk) for z, blk in layers if z > overlap_ceiling]

        if above:
            merged_blocks.append(f"; --- Tool change: T{tool} ({name}) ---\n")
            merged_blocks.append(f"T{tool}\n")
            merged_blocks.append("G92 E0\n")
            for _z, blk in above:
                merged_blocks.append(blk)
            phases.append({
                "tool": tool,
                "name": name,
                "zone": "upper",
                "layers": len(above),
                "z_range": f"{above[0][0]}-{above[-1][0]}mm",
            })

    merged_body = "".join(merged_blocks)

    # Sum slicer time estimates from each part's original gcode file.
    # PrusaSlicer puts estimates at the END of the file (after all layers),
    # so we scan the full file, not just the pre-layer header.
    _TIME_RE = re.compile(
        r"estimated printing time \(normal mode\).*?=\s*"
        r"(?:(\d+)d\s*)?(?:(\d+)h\s*)?(?:(\d+)m\s*)?(?:(\d+)s)?",
        re.IGNORECASE,
    )
    total_time = 0
    for _header, _layers, part_info in parsed:
        gcode_path = part_info.get("gcode_path", "")
        if gcode_path and os.path.isfile(gcode_path):
            with open(gcode_path, errors="replace") as _f:
                for _line in _f:
                    m = _TIME_RE.search(_line)
                    if m:
                        total_time += (
                            int(m.group(1) or 0) * 86400
                            + int(m.group(2) or 0) * 3600
                            + int(m.group(3) or 0) * 60
                            + int(m.group(4) or 0)
                        )
                        break  # one estimate per file

    if not output_path:
        output_path = os.path.join(
            tempfile.mkdtemp(prefix="kiln_merge_"),
            "merged_multicolor.gcode",
        )

    with open(output_path, "w") as f:
        f.write(_KILN_GCODE_HEADER + merged_body)

    return {
        "output_path": output_path,
        "total_layers": total_layers,
        "phases": phases,
        "estimated_time_sec": total_time,
        "parts_merged": len(parts),
    }
